module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section6DerivedSupport
public import SubdiffusiveProcess.Section5.HomogenizedCoefficientReciprocalLower

@[expose] public section

/-!
# The literal coefficient sigma-field for the rescaled cutoff

The Dirichlet theorem requires its random factor to be measurable for the
sigma-field generated by the *rescaled coefficient itself*.  This file gives
that definition a small working API and identifies it with the sigma-
field generated by the unscaled cutoff.  In particular, no shell coordinate is
retained in this comparison.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab

open MeasureTheory

noncomputable section

variable {d : ℕ} {Ω : Type*}

/-- Every point evaluation is measurable for the sigma-field generated by the
coefficient. -/
theorem measurable_eval_coefficientSigma (A : Ω → Vec d → ℝ) (x : Vec d) :
    @Measurable Ω ℝ (coefficientSigma A) (borel ℝ) (fun omega => A omega x) := by
  refine Measurable.of_comap_le ?_
  exact le_iSup
    (fun y : Vec d => MeasurableSpace.comap (fun omega => A omega y) (borel ℝ)) x

/-- Comparison principle for coefficient-generated sigma-fields. -/
theorem coefficientSigma_le_of_measurable_eval
    (A B : Ω → Vec d → ℝ)
    (h : ∀ x, @Measurable Ω ℝ (coefficientSigma B) (borel ℝ)
      (fun omega => A omega x)) :
    coefficientSigma A ≤ coefficientSigma B := by
  refine iSup_le fun x => ?_
  have hx := (h x).comap_le
  exact hx

/-- Multiplying every coefficient evaluation by a fixed nonzero scalar does
not change its generated sigma-field. -/
theorem coefficientSigma_const_mul (A : Ω → Vec d → ℝ) {c : ℝ} (hc : c ≠ 0) :
    coefficientSigma (fun omega x => c * A omega x) = coefficientSigma A := by
  apply le_antisymm
  · apply coefficientSigma_le_of_measurable_eval
    intro x
    exact measurable_const.mul (measurable_eval_coefficientSigma A x)
  · apply coefficientSigma_le_of_measurable_eval
    intro x
    have h := measurable_eval_coefficientSigma
      (fun omega x => c * A omega x) x
    have heq : (fun omega => A omega x) =
        fun omega => c⁻¹ * (c * A omega x) := by
      funext omega
      field_simp
    rw [heq]
    exact measurable_const.mul h

/-- Precomposing the spatial variable by a bijection does not change the
coefficient-generated sigma-field. -/
theorem coefficientSigma_comp_bijective (A : Ω → Vec d → ℝ)
    (f : Vec d → Vec d) (hf : Function.Bijective f) :
    coefficientSigma (fun omega x => A omega (f x)) = coefficientSigma A := by
  apply le_antisymm
  · apply coefficientSigma_le_of_measurable_eval
    intro x
    exact measurable_eval_coefficientSigma A (f x)
  · apply coefficientSigma_le_of_measurable_eval
    intro y
    obtain ⟨x, rfl⟩ := hf.surjective y
    exact measurable_eval_coefficientSigma (fun omega x => A omega (f x)) x

/-- The literal rescaled coefficient and the raw finite cutoff carry exactly
the same information. -/
theorem coefficientSigma_rescaledCutoffCoefficient_eq_aCutoff
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (L N : ℕ) :
    coefficientSigma (fun omega => rescaledCutoffCoefficient M L N omega) =
      coefficientSigma (fun omega => _root_.SubdiffusiveProcess.Model.aCutoff M L omega) := by
  let c : ℝ := (3 : ℝ) ^ N
  have hc : c ≠ 0 := by positivity
  have hf : Function.Bijective (fun x : Vec d => c • x) := by
    refine ⟨?_, ?_⟩
    · intro x y hxy
      exact smul_right_injective (Vec d) hc hxy
    · intro y
      refine ⟨c⁻¹ • y, ?_⟩
      simp [hc]
  have hahom : (ahom M L)⁻¹ ≠ 0 := inv_ne_zero (ne_of_gt (by
    exact (Real.exp_pos _).trans_le
      (_root_.SubdiffusiveProcess.Section5.homogenized_coefficient_reciprocal_lower M L)))
  unfold rescaledCutoffCoefficient
  change coefficientSigma
      (fun omega x => (ahom M L)⁻¹ *
        _root_.SubdiffusiveProcess.Model.aCutoff M L omega (c • x)) = _
  rw [coefficientSigma_const_mul _ hahom]
  exact coefficientSigma_comp_bijective
    (fun omega => _root_.SubdiffusiveProcess.Model.aCutoff M L omega) _ hf

end

end SubdiffusiveProcess.CoarseGrainingVocab
