import SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet.AlmostSureBalancedPrebalance
import SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet.BalancedFinalReadout

/-!
# The final universal random factor for cutoff Dirichlet homogenization
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet

open MeasureTheory Homogenization
open SubdiffusiveProcess.CoarseGrainingVocab
open scoped ENNReal

noncomputable section

private abbrev Sample (d : ℕ) :=
  SubdiffusiveProcess.Frozen.Assumptions.PotentialSample d

/-- The random factor after paying the deterministic `L²` and `H⁻¹`
readouts. -/
def cutoffDirichletRandomFactor
    {d : ℕ} [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ)
    (C vartheta : ℝ) (hvartheta : vartheta ∈ Set.Ioo (0 : ℝ) 1)
    (omega : Sample d) : ℝ :=
  dirichletReadoutRandomFactor (dirichletSOrder vartheta hvartheta) d
    (dirichletUniversalRandomFactor M L N C M.delta vartheta
      (dirichletS1 vartheta) (dirichletS2 vartheta)
      (dirichletBalanceScale vartheta M.delta) omega)

/-- Ambient measurability of the concrete universal prebalance factor. -/
theorem measurable_dirichletUniversalRandomFactor
    {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ)
    (C vartheta : ℝ) :
    Measurable (dirichletUniversalRandomFactor M L N C M.delta vartheta
      (dirichletS1 vartheta) (dirichletS2 vartheta)
      (dirichletBalanceScale vartheta M.delta)) := by
  let E1 := dirichletFullResponseOne M L N (dirichletS1 vartheta)
  let E2 := dirichletFullResponseTwo M L N (dirichletS1 vartheta)
  let Y := dirichletEllipticityEnvelope M L N (dirichletS1 vartheta)
  have hE1 : Measurable E1 :=
    measurable_dirichletFullResponseOne M L N (dirichletS1 vartheta)
  have hE2 : Measurable E2 :=
    measurable_dirichletFullResponseTwo M L N (dirichletS1 vartheta)
  have hY : Measurable Y := by
    dsimp only [Y, dirichletEllipticityEnvelope]
    exact measurable_const.add (measurable_const.mul hE2)
  change Measurable (dirichletRandomFactor C M.delta vartheta
    (dirichletS1 vartheta) (dirichletS2 vartheta)
    (dirichletBalanceScale vartheta M.delta) E1 E2 Y)
  unfold dirichletRandomFactor
  have hFirst : Measurable fun omega =>
      Real.rpow 3 (dirichletS1 vartheta *
          (dirichletBalanceScale vartheta M.delta : ℝ)) *
        E1 omega * Y omega := (measurable_const.mul hE1).mul hY
  have hSecond : Measurable fun omega =>
      Real.rpow 3 (-dirichletS2 vartheta *
          (dirichletBalanceScale vartheta M.delta : ℝ)) *
        (1 + Real.rpow 3 (dirichletS1 vartheta *
          (dirichletBalanceScale vartheta M.delta : ℝ)) * E2 omega ^ 2) :=
    measurable_const.mul
      (measurable_const.add (measurable_const.mul (hE2.pow_const 2)))
  exact (measurable_const.add
    ((measurable_const.mul measurable_const).mul (hFirst.add hSecond))).add
      (((measurable_const.mul measurable_const).mul hE1).mul hY)

/-- The final factor is measurable in the sigma-field generated by the
literal rescaled coefficient. -/
theorem coefficientMeasurable_cutoffDirichletRandomFactor
    {d : ℕ} [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ)
    (C vartheta : ℝ) (hvartheta : vartheta ∈ Set.Ioo (0 : ℝ) 1) :
    CoefficientMeasurable
      (fun omega ↦ rescaledCutoffCoefficient M L N omega)
      (cutoffDirichletRandomFactor M L N C vartheta hvartheta) := by
  letI : MeasurableSpace (Sample d) :=
    coefficientSigma (fun omega ↦ rescaledCutoffCoefficient M L N omega)
  change Measurable (cutoffDirichletRandomFactor M L N C vartheta hvartheta)
  unfold cutoffDirichletRandomFactor dirichletReadoutRandomFactor
  exact measurable_const.add (measurable_const.mul
    (coefficientMeasurable_dirichletUniversalRandomFactor M L N C M.delta
      vartheta (dirichletS1 vartheta) (dirichletS2 vartheta)
      (dirichletBalanceScale vartheta M.delta)))

/-- The final factor satisfies the frozen pointwise lower bound. -/
theorem one_le_cutoffDirichletRandomFactor
    {d : ℕ} [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ)
    {C vartheta : ℝ} (hC : 0 ≤ C)
    (hvartheta : vartheta ∈ Set.Ioo (0 : ℝ) 1)
    (omega : Sample d) :
    1 ≤ cutoffDirichletRandomFactor M L N C vartheta hvartheta omega := by
  apply one_le_dirichletReadoutRandomFactor
  exact zero_le_one.trans (one_le_dirichletUniversalRandomFactor M L N
    hC M.shellPrefix.delta_pos.le vartheta (dirichletS1 vartheta)
    (dirichletS2 vartheta) (dirichletBalanceScale vartheta M.delta) omega)

/-- Uniform `L^q` control survives the finite deterministic final-readout
price. -/
theorem exists_cutoffDirichletRandomFactor_moment_bound
    (d : ℕ) [NeZero d] {vartheta q C : ℝ}
    (hvartheta : vartheta ∈ Set.Ioo (0 : ℝ) 1)
    (hq : 1 ≤ q) (hC : 0 ≤ C) :
    ∃ delta0 B : ℝ, 0 < delta0 ∧ 0 < B ∧
      ∀ (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d), M.delta ≤ delta0 →
        ∀ L N : ℕ, L ≤ N →
          eLpNorm (cutoffDirichletRandomFactor M L N C vartheta hvartheta)
              (ENNReal.ofReal q) M.P.toMeasure ≤ ENNReal.ofReal B := by
  obtain ⟨delta0, B0, hdelta0, hB0, hmoment⟩ :=
    exists_dirichletRandomFactor_moment_bound d hvartheta.1 hvartheta.2
      hq hC
  let A := (dirichletFinalReadoutConstant
    (dirichletSOrder vartheta hvartheta) d).toReal
  let B := 1 + A * B0
  have hA : 0 ≤ A := ENNReal.toReal_nonneg
  have hB : 0 < B := by dsimp only [B]; positivity
  refine ⟨delta0, B, hdelta0, hB, ?_⟩
  intro M hM L N hLN
  let U : Sample d → ℝ :=
    dirichletUniversalRandomFactor M L N C M.delta vartheta
      (dirichletS1 vartheta) (dirichletS2 vartheta)
      (dirichletBalanceScale vartheta M.delta)
  have hUMeas : AEStronglyMeasurable U M.P.toMeasure :=
    (measurable_dirichletUniversalRandomFactor M L N C vartheta).aestronglyMeasurable
  have hq0 : 0 < q := zero_lt_one.trans_le hq
  have hqENN : (1 : ENNReal) ≤ ENNReal.ofReal q := by
    simpa only [ENNReal.ofReal_one] using ENNReal.ofReal_le_ofReal hq
  have honeMeas : AEStronglyMeasurable
      (fun _ : Sample d ↦ (1 : ℝ)) M.P.toMeasure :=
    aestronglyMeasurable_const
  have hscaledMeas : AEStronglyMeasurable
      (fun omega ↦ A * U omega) M.P.toMeasure := hUMeas.const_mul A
  have htriangle := eLpNorm_add_le honeMeas hscaledMeas hqENN
  have honeNorm : eLpNorm (fun _ : Sample d ↦ (1 : ℝ))
      (ENNReal.ofReal q) M.P.toMeasure = 1 := by
    rw [eLpNorm_const 1 (ENNReal.ofReal_pos.mpr hq0).ne'
      (NeZero.ne M.P.toMeasure)]
    simp
  have hscaledNorm : eLpNorm (fun omega ↦ A * U omega)
      (ENNReal.ofReal q) M.P.toMeasure =
        ENNReal.ofReal A * eLpNorm U (ENNReal.ofReal q) M.P.toMeasure := by
    change eLpNorm (A • U) (ENNReal.ofReal q) M.P.toMeasure = _
    rw [eLpNorm_const_smul, Real.enorm_eq_ofReal hA]
  have hUNorm : eLpNorm U (ENNReal.ofReal q) M.P.toMeasure ≤
      ENNReal.ofReal B0 := hmoment M hM L N hLN
  change eLpNorm (fun omega ↦ 1 + A * U omega)
      (ENNReal.ofReal q) M.P.toMeasure ≤ ENNReal.ofReal B
  calc
    _ ≤ eLpNorm (fun _ : Sample d ↦ (1 : ℝ))
          (ENNReal.ofReal q) M.P.toMeasure +
        eLpNorm (fun omega ↦ A * U omega)
          (ENNReal.ofReal q) M.P.toMeasure := htriangle
    _ = 1 + ENNReal.ofReal A *
        eLpNorm U (ENNReal.ofReal q) M.P.toMeasure := by
      rw [honeNorm, hscaledNorm]
    _ ≤ 1 + ENNReal.ofReal A * ENNReal.ofReal B0 := by gcongr
    _ = ENNReal.ofReal B := by
      dsimp only [B]
      rw [← ENNReal.ofReal_mul hA]
      calc
        1 + ENNReal.ofReal (A * B0) =
            ENNReal.ofReal 1 + ENNReal.ofReal (A * B0) := by simp
        _ = ENNReal.ofReal (1 + A * B0) :=
          (ENNReal.ofReal_add zero_le_one (mul_nonneg hA hB0.le)).symm

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet
