import SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet.CoefficientSigma
import SubdiffusiveProcess.CoarseGrainingVocab.PrefixSuffixMeasurability

/-!
# Coefficient measurability of the cutoff response errors

The ambient response measurability API is stated for the potential sample's
full Borel sigma-field.  The Dirichlet theorem needs the sharper fact that the
response errors are measurable from the coefficient alone.  We replay the
existing countable variational reduction with the source sigma-field replaced
by `coefficientSigma (aCutoff M L)`, and then assemble the countable sphere,
descendant, and scale aggregations of the manuscript error.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab

open Filter MeasureTheory Homogenization Homogenization.Book
open scoped BigOperators ENNReal

noncomputable section

private abbrev Sample (d : ℕ) :=
  SubdiffusiveProcess.Frozen.Assumptions.PotentialSample d

variable {d : ℕ}

/-- Joint measurability of the cutoff when the sample carries precisely the
sigma-field generated by its point evaluations. -/
theorem measurable_aCutoff_uncurry_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) :
    @Measurable (Sample d × Vec d) ℝ
      ((coefficientSigma (fun omega =>
        SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)).prod inferInstance)
      inferInstance
      (fun z => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2) := by
  letI : MeasurableSpace (Sample d) :=
    coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)
  have hEvalSwap : Measurable
      (Function.uncurry fun x : Vec d =>
        fun omega : Sample d => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega x) := by
    exact measurable_uncurry_of_continuous_of_measurable
      (ι := Vec d) (α := Sample d) (β := ℝ)
      (SubdiffusiveProcess.Frozen.Assumptions.continuous_aCutoff M L)
      (fun x => measurable_eval_coefficientSigma
        (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega) x)
  exact hEvalSwap.comp measurable_swap

private theorem blockEnergyDensity_scalarCoeffField {d : ℕ}
    (a : Vec d → ℝ) (ha : ∀ x, 0 < a x) (X : BlockState d) (x : Vec d) :
    blockEnergyDensity (scalarCoeffField a) X x =
      (1 / 2 : ℝ) *
        (a x * vecDot (X.potential x) (X.potential x) +
          (a x)⁻¹ * vecDot (X.flux x) (X.flux x)) := by
  have hInv : ((Homogenization.scalarMatrix (d := d) (a x))⁻¹ : Mat d) =
      Homogenization.scalarMatrix (d := d) (a x)⁻¹ := by
    rw [Homogenization.scalarMatrix,
      Homogenization.nonsing_inv_smul (a x) (ha x).ne' (by simp)]
    simp [Homogenization.scalarMatrix]
  simp [blockEnergyDensity, blockCoeffField, blockMatrixOfCoeff,
    scalarCoeffField, Homogenization.Book.Ch02.symmPart_scalarMatrix,
    Homogenization.Book.Ch02.skewPart_scalarMatrix, hInv,
    BlockState.eval, blockMatVecMul, Homogenization.matVecMul_scalarMatrix,
    Homogenization.blockVecDot, Homogenization.matVecMul,
    Homogenization.vecDot, Homogenization.matTranspose, Finset.mul_sum,
    mul_left_comm]

/-- A fixed admissible competitor has coefficient-measurable cutoff energy. -/
theorem measurable_cutoff_fixed_blockEnergyAverage_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d)
    (P : BlockVec d) (X : BlockState d)
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) P X) :
    @Measurable (Sample d) ℝ
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) X) := by
  letI : MeasurableSpace (Sample d) :=
    coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)
  have hJoint := measurable_aCutoff_uncurry_coefficientSigma M L
  have hXL2 : MemBlockL2 (U : Set (Vec d)) X.eval := hX.memBlockL2_eval
  have hPotentialL2 : MemVectorL2 (U : Set (Vec d)) X.potential := by
    simpa [BlockState.eval] using
      memVectorL2_fst_of_memBlockL2 (U := (U : Set (Vec d))) hXL2
  have hFluxL2 : MemVectorL2 (U : Set (Vec d)) X.flux := by
    simpa [BlockState.eval] using
      memVectorL2_snd_of_memBlockL2 (U := (U : Set (Vec d))) hXL2
  let f : Vec d → Vec d := hPotentialL2.aestronglyMeasurable.mk X.potential
  let g : Vec d → Vec d := hFluxL2.aestronglyMeasurable.mk X.flux
  have hf : Measurable f := hPotentialL2.aestronglyMeasurable.measurable_mk
  have hg : Measurable g := hFluxL2.aestronglyMeasurable.measurable_mk
  have measurable_vecDot_self {v : Sample d × Vec d → Vec d}
      (hv : Measurable v) : Measurable (fun z => vecDot (v z) (v z)) := by
    simp only [vecDot]
    exact Finset.measurable_sum _ fun i _ =>
      ((measurable_pi_apply i).comp hv).mul ((measurable_pi_apply i).comp hv)
  have hPotential : Measurable (fun z : Sample d × Vec d =>
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2 *
        vecDot (f z.2) (f z.2)) :=
    hJoint.mul (measurable_vecDot_self (hf.comp measurable_snd))
  have hFlux : Measurable (fun z : Sample d × Vec d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2)⁻¹ *
        vecDot (g z.2) (g z.2)) :=
    hJoint.inv.mul (measurable_vecDot_self (hg.comp measurable_snd))
  have hIntegral : StronglyMeasurable (fun omega : Sample d =>
      ∫ x, (1 / 2 : ℝ) *
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega x * vecDot (f x) (f x) +
          (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega x)⁻¹ * vecDot (g x) (g x))
        ∂volumeMeasureOn (U : Set (Vec d))) :=
    (measurable_const.mul (hPotential.add hFlux)).stronglyMeasurable.integral_prod_right'
  have hEq : (fun omega : Sample d =>
      blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) X) =
      fun omega => (volume (U : Set (Vec d))).toReal⁻¹ *
        ∫ x, (1 / 2 : ℝ) *
          (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega x * vecDot (f x) (f x) +
            (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega x)⁻¹ * vecDot (g x) (g x))
          ∂volumeMeasureOn (U : Set (Vec d)) := by
    funext omega
    rw [blockEnergyAverage, volumeAverage]
    congr 1
    apply integral_congr_ae
    filter_upwards [hPotentialL2.aestronglyMeasurable.ae_eq_mk,
      hFluxL2.aestronglyMeasurable.ae_eq_mk] with x hfx hgx
    simpa [f, g, hfx, hgx] using
      blockEnergyDensity_scalarCoeffField
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L omega) X x
  rw [hEq]
  exact measurable_const.mul hIntegral.measurable

/-- Every deterministic loading has coefficient-measurable cutoff `Mu`. -/
theorem measurable_cutoff_Mu_coefficientSigma [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d)
    (P : BlockVec d) :
    @Measurable (Sample d) ℝ
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => Mu (U : Set (Vec d)) P
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))) := by
  letI : MeasurableSpace (Sample d) :=
    coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)
  obtain ⟨X, hX, hMu⟩ := cutoffMu_countableReduction M L U P
  have hEq : (fun omega : Sample d => Mu (U : Set (Vec d)) P
      (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))) =
      fun omega => ⨅ n : ℕ, blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) (X n) := by
    funext omega
    exact hMu omega
  rw [hEq]
  exact Measurable.iInf fun n =>
    measurable_cutoff_fixed_blockEnergyAverage_coefficientSigma
      M L U P (X n) (hX n)

/-- Every fixed response probe is measurable from the cutoff coefficient
alone. -/
theorem measurable_cutoff_responseJ_coefficientSigma [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d)
    (p q : Vec d) :
    @Measurable (Sample d) ℝ
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => J U (aCutoffCoeffOnData M L omega U).toCoeffOn p q) := by
  have hMu := measurable_cutoff_Mu_coefficientSigma M L U (-p, q)
  have hEq : (fun omega : Sample d =>
      J U (aCutoffCoeffOnData M L omega U).toCoeffOn p q) =
      fun omega => Mu (U : Set (Vec d)) (-p, q)
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) - vecDot p q := by
    funext omega
    let aomega := (aCutoffCoeffOnData M L omega U).toCoeffOn
    calc
      J U aomega p q = Ch02.doubledMu U aomega (-p, q) - vecDot p q :=
        Ch02.responseJ_eq_doubledMu_neg_left_sub_vecDot U aomega p q
      _ = Mu (U : Set (Vec d)) (-p, q) aomega.toCoeffField - vecDot p q := by
        rw [Ch02.doubledMu_eq_Mu]
      _ = Mu (U : Set (Vec d)) (-p, q)
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) -
            vecDot p q := rfl
  rw [hEq]
  exact hMu.sub measurable_const

/-- The literal unit-sphere cutoff response maximum is coefficient-measurable. -/
theorem measurable_normalizedDefect_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance (normalizedDefect M L U) := by
  by_cases hd : d = 0
  · subst d
    have heq : normalizedDefect M L U = fun _ => 0 := by
      funext omega
      unfold normalizedDefect paperScalarProbeMaxOn
      apply le_antisymm
      · refine iSup_le fun e => ?_
        have hfalse : False := by
          have he := e.2
          simp [vecNormSq, vecDot] at he
        exact hfalse.elim
      · exact bot_le
    rw [heq]
    exact measurable_const
  letI : NeZero d := ⟨hd⟩
  have hrep : @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance (normalizedDefectCountableRepresentative M L U) := by
    unfold normalizedDefectCountableRepresentative
    exact Measurable.iSup fun i =>
      (measurable_cutoff_responseJ_coefficientSigma M L U
        ((Real.sqrt (ahom M L))⁻¹ •
          (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))
        (Real.sqrt (ahom M L) •
          (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))).ennreal_ofReal
  have heq : normalizedDefect M L U =
      normalizedDefectCountableRepresentative M L U := by
    funext omega
    exact normalizedDefect_eq_countableRepresentative M L U omega
  rwa [heq]

/-- A one-cube paper probe maximum is coefficient-measurable. -/
theorem measurable_paperScalarProbeMax_aCutoffFamily_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (Q : TriadicCube d) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => paperScalarProbeMax Q (aCutoffFamily M L omega) (ahom M L)) := by
  simpa [paperScalarProbeMax, paperScalarProbe, normalizedDefect,
    paperScalarProbeMaxOn, aCutoffFamily, aCutoffTriadicData,
    ScalarTriadicCoeffData.toTriadicCoeffFamily] using
    measurable_normalizedDefect_coefficientSigma M L (Ch02.cubeDomain Q)

/-- The maximum over descendants at a fixed scale is coefficient-measurable. -/
theorem measurable_paperMaxDescendantProbeAtScale_aCutoffFamily_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (Q : TriadicCube d) (k : ℤ) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => paperMaxDescendantProbeAtScale Q k
        (aCutoffFamily M L omega) (ahom M L)) := by
  unfold paperMaxDescendantProbeAtScale
  exact Measurable.iSup fun R =>
    measurable_paperScalarProbeMax_aCutoffFamily_coefficientSigma M L R.1

/-- The `p = infinity` response aggregation at one scale is
coefficient-measurable. -/
theorem measurable_paperScaleResponseAtScale_infinity_aCutoffFamily_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (Q : TriadicCube d) (k : ℤ) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => paperScaleResponseAtScale Q k .infinity
        (aCutoffFamily M L omega) (ahom M L)) := by
  change @Measurable (Sample d) ℝ≥0∞
    (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
    inferInstance
    (fun omega => (paperMaxDescendantProbeAtScale Q k
      (aCutoffFamily M L omega) (ahom M L)) ^ (1 / 2 : ℝ))
  exact ENNReal.continuous_rpow_const.measurable.comp
    (measurable_paperMaxDescendantProbeAtScale_aCutoffFamily_coefficientSigma
      M L Q k)

/-- The full finite-`q` manuscript response error with spatial exponent
`infinity` is measurable from the raw cutoff coefficient alone. -/
theorem measurable_paperHomogenizationError_infinity_finite_aCutoffFamily_coefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (Q : TriadicCube d) (n : ℤ) (s q : ℝ) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
      inferInstance
      (fun omega => paperHomogenizationError Q n s .infinity (.finite q)
        (aCutoffFamily M L omega) (ahom M L)) := by
  change @Measurable (Sample d) ℝ≥0∞
    (coefficientSigma (fun omega => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
    inferInstance
    (fun omega => (∑' l : ℕ,
      ENNReal.ofReal (Ch02.geometricWeight s q l) *
        (paperScaleResponseAtScale Q (n - (l : ℤ)) .infinity
          (aCutoffFamily M L omega) (ahom M L)) ^ q) ^ (1 / q))
  apply ENNReal.continuous_rpow_const.measurable.comp
  apply Measurable.ennreal_tsum
  intro l
  exact measurable_const.mul
    (ENNReal.continuous_rpow_const.measurable.comp
      (measurable_paperScaleResponseAtScale_infinity_aCutoffFamily_coefficientSigma
        M L Q (n - (l : ℤ))))

/-- The same full response error is measurable for the literal rescaled-
coefficient sigma-field used by the Dirichlet theorem. -/
theorem measurable_paperHomogenizationError_infinity_finite_rescaledCoefficientSigma
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ)
    (Q : TriadicCube d) (n : ℤ) (s q : ℝ) :
    @Measurable (Sample d) ℝ≥0∞
      (coefficientSigma (fun omega => rescaledCutoffCoefficient M L N omega))
      inferInstance
      (fun omega => paperHomogenizationError Q n s .infinity (.finite q)
        (aCutoffFamily M L omega) (ahom M L)) := by
  rw [coefficientSigma_rescaledCutoffCoefficient_eq_aCutoff M L N]
  exact
    measurable_paperHomogenizationError_infinity_finite_aCutoffFamily_coefficientSigma
      M L Q n s q

/-- Real-valued first full response error from
`e.Dirichlet.full.response.moments`. -/
noncomputable def dirichletFullResponseOne
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ)
    (omega : Sample d) : ℝ :=
  (paperHomogenizationError (originCube d (N : ℤ)) (N : ℤ)
    s .infinity (.finite 1) (aCutoffFamily M L omega) (ahom M L)).toReal

/-- Real-valued second full response error from
`e.Dirichlet.full.response.moments`. -/
noncomputable def dirichletFullResponseTwo
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ)
    (omega : Sample d) : ℝ :=
  (paperHomogenizationError (originCube d (N : ℤ)) (N : ℤ)
    (s / 2) .infinity (.finite 2) (aCutoffFamily M L omega) (ahom M L)).toReal

/-- The first full response error is nonnegative. -/
theorem dirichletFullResponseOne_nonneg
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ)
    (omega : Sample d) :
    0 ≤ dirichletFullResponseOne M L N s omega :=
  ENNReal.toReal_nonneg

/-- The second full response error is nonnegative. -/
theorem dirichletFullResponseTwo_nonneg
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ)
    (omega : Sample d) :
    0 ≤ dirichletFullResponseTwo M L N s omega :=
  ENNReal.toReal_nonneg

/-- Real readout of the first full response error in
`e.Dirichlet.full.response.moments`. -/
theorem coefficientMeasurable_dirichletFullResponseOne
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ) :
    CoefficientMeasurable
      (fun omega => rescaledCutoffCoefficient M L N omega)
      (dirichletFullResponseOne M L N s) := by
  exact (measurable_paperHomogenizationError_infinity_finite_rescaledCoefficientSigma
    M L N (originCube d (N : ℤ)) (N : ℤ) s 1).ennreal_toReal

/-- Real readout of the second full response error in
`e.Dirichlet.full.response.moments`. -/
theorem coefficientMeasurable_dirichletFullResponseTwo
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L N : ℕ) (s : ℝ) :
    CoefficientMeasurable
      (fun omega => rescaledCutoffCoefficient M L N omega)
      (dirichletFullResponseTwo M L N s) := by
  exact (measurable_paperHomogenizationError_infinity_finite_rescaledCoefficientSigma
    M L N (originCube d (N : ℤ)) (N : ℤ) (s / 2) 2).ennreal_toReal

end

end SubdiffusiveProcess.CoarseGrainingVocab
