module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ChemicalDRSConditions

@[expose] public section

/-!
# Finite-scale truncation of local event sigma-algebras

 An event generated by a
multiscale field on a set of sites has a finite-scale measurable replacement
which agrees with it whenever no discarded event occurs on those sites.
The replacement is constructed by closure under complements and countable
unions. Its error is controlled by the discarded events themselves.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section9Support

open MeasureTheory Set
open SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation
open scoped ENNReal

noncomputable section

/-- Agreement off an exceptional set extends from generators to their sigma-algebra. -/
theorem exists_measurable_agree_off {Ω : Type*} (m : MeasurableSpace Ω)
    (G : Set (Set Ω)) (H : Set Ω)
    (hG : ∀ A ∈ G, ∃ B, MeasurableSet[m] B ∧ ∀ ω, ω ∉ H → (ω ∈ A ↔ ω ∈ B))
    {A : Set Ω} (hA : MeasurableSet[MeasurableSpace.generateFrom G] A) :
    ∃ B, MeasurableSet[m] B ∧ ∀ ω, ω ∉ H → (ω ∈ A ↔ ω ∈ B) := by
  classical
  let P : Set Ω → Prop := fun A => ∃ B, MeasurableSet[m] B ∧ ∀ ω, ω ∉ H → (ω ∈ A ↔ ω ∈ B)
  have hempty : P ∅ :=
    ⟨∅, MeasurableSet.empty, fun ω _ =>
      ⟨fun h => absurd h (Set.notMem_empty ω), fun h => absurd h (Set.notMem_empty ω)⟩⟩
  have hcompl : ∀ A, P A → P Aᶜ := by
    intro A hA
    obtain ⟨B, hB, hAB⟩ := hA
    refine ⟨Bᶜ, hB.compl, fun ω hω => ?_⟩
    simp only [Set.mem_compl_iff, hAB ω hω]
  have hiUnion : ∀ t : ℕ → Set Ω, (∀ i, P (t i)) → P (⋃ i, t i) := by
    intro t ht
    choose B hB hBt using ht
    refine ⟨⋃ i, B i, MeasurableSet.iUnion hB, fun ω hω => ?_⟩
    constructor
    · intro h
      obtain ⟨i, hi⟩ := Set.mem_iUnion.1 h
      exact Set.mem_iUnion.2 ⟨i, (hBt i ω hω).1 hi⟩
    · intro h
      obtain ⟨i, hi⟩ := Set.mem_iUnion.1 h
      exact Set.mem_iUnion.2 ⟨i, (hBt i ω hω).2 hi⟩
  let m' : MeasurableSpace Ω := ⟨P, hempty, hcompl, hiUnion⟩
  exact (MeasurableSpace.generateFrom_le (fun s hs => hG s hs)) A hA

theorem sdiff_union_subset_of_agree_off {Ω : Type*} {A B H : Set Ω}
    (h : ∀ ω, ω ∉ H → (ω ∈ A ↔ ω ∈ B)) :
    (A \ B) ∪ (B \ A) ⊆ H := by
  intro ω hω
  rcases hω with hω | hω
  · by_contra hωH
    have := h ω hωH
    exact hω.2 (this.1 hω.1)
  · by_contra hωH
    have := h ω hωH
    exact hω.2 (this.2 hω.1)

theorem measure_differences_le {Ω : Type*} [MeasurableSpace Ω] (mu : Measure Ω)
    {A B H : Set Ω} (hA : MeasurableSet A) (hB : MeasurableSet B)
    (h : (A \ B) ∪ (B \ A) ⊆ H) :
    mu (A \ B) + mu (B \ A) ≤ mu H := by
  have hd : Disjoint (A \ B) (B \ A) :=
    Set.disjoint_left.mpr fun x hx hx' => hx.2 hx'.1
  have hmeas2 : MeasurableSet (B \ A) := hB.diff hA
  calc mu (A \ B) + mu (B \ A)
      = mu ((A \ B) ∪ (B \ A)) := (measure_union hd hmeas2).symm
    _ ≤ mu H := measure_mono h

theorem latticeDist_separated_balls {d r R : ℕ} {x y u v : Lattice d}
    (hsep : 2 * r + R < latticeDist x y) (hu : latticeDist x u ≤ r)
    (hv : latticeDist y v ≤ r) : R < latticeDist u v := by
  have h1 := latticeDist_triangle x u v
  have h2 := latticeDist_triangle x v y
  have h3 : latticeDist v y = latticeDist y v := latticeDist_comm v y
  omega

theorem truncation_cutoff_requires_large_distance {Cdep j0 N : ℕ}
    (h : 100 * (Cdep * 3 ^ j0) ≤ N) : 100 * Cdep ≤ N := by
  have h1 : 1 ≤ 3 ^ j0 := Nat.one_le_pow j0 3 (by positivity)
  have h2 : Cdep * 1 ≤ Cdep * 3 ^ j0 := Nat.mul_le_mul_left Cdep h1
  have h3 : 100 * (Cdep * 1) ≤ 100 * (Cdep * 3 ^ j0) := Nat.mul_le_mul_left 100 h2
  nlinarith [h, h3]

theorem prefactor_absorption {K a q : ℝ} (hK : 0 < K) (habs : 2 * Real.log K ≤ a*q) :
    K * Real.exp (-(a*q)) ≤ Real.exp (-(a/2*q)) := by
  have h1 : K = Real.exp (Real.log K) := (Real.exp_log hK).symm
  rw [h1, ← Real.exp_add]
  apply Real.exp_le_exp.mpr
  have h3 : a*q = 2*(a/2*q) := by ring
  linarith

theorem mem_truncation_tail_iff {Ω ι : Type*} (E : ℕ → ι → Set Ω) (S : Set ι) (j0 : ℕ) (ω : Ω) :
    (ω ∈ ⋃ j : ℕ, ⋃ (_ : j0 < j), ⋃ z ∈ S, E j z) ↔ ∃ j, j0 < j ∧ ∃ z ∈ S, ω ∈ E j z := by
  constructor
  · intro h
    simp only [Set.mem_iUnion] at h
    obtain ⟨j, hj, z, hz, hω⟩ := h
    exact ⟨j, hj, z, hz, hω⟩
  · rintro ⟨j, hj, z, hz, hω⟩
    simp only [Set.mem_iUnion]
    exact ⟨j, hj, z, hz, hω⟩

theorem measure_event_le_truncation_error {Ω : Type*} [MeasurableSpace Ω]
    (mu : Measure Ω) {A B H : Set Ω}
    (h : ∀ ω, ω ∉ H → (ω ∈ A ↔ ω ∈ B)) : mu A ≤ mu B + mu H := by
  have hsub : A ⊆ B ∪ H := by
    intro ω hω
    by_cases hH : ω ∈ H
    · exact Or.inr hH
    · exact Or.inl ((h ω hH).mp hω)
  calc mu A ≤ mu (B ∪ H) := measure_mono hsub
    _ ≤ mu B + mu H := measure_union_le B H

theorem exists_triadic_cutoff {N D : ℕ} (hD : 0 < D) (h : D ≤ N) :
    ∃ j : ℕ, D * 3^j ≤ N ∧ N < D * 3^(j+1) := by
  -- The set {k | N < D * 3^k} is nonempty: 3^(log 3 N + 1) > N and D ≥ 1.
  have hex : ∃ k, N < D * 3^k := by
    refine ⟨Nat.log 3 N + 1, ?_⟩
    have h1 : N < 3^(Nat.log 3 N + 1) := Nat.lt_pow_succ_log_self (by norm_num : (1:ℕ) < 3) N
    have hle : 3^(Nat.log 3 N + 1) ≤ D * 3^(Nat.log 3 N + 1) := by
      rw [Nat.mul_comm]
      exact Nat.le_mul_of_pos_right _ hD
    exact lt_of_lt_of_le h1 hle
  -- Let k₀ be the least index with N < D * 3^k₀; witness is k₀ - 1.
  refine ⟨Nat.find hex - 1, ?_, ?_⟩
  · -- Lower bound: if D * 3^(k₀-1) > N then k₀ - 1 would be a smaller witness.
    have hk0 : Nat.find hex ≠ 0 := by
      intro h0
      have hs := Nat.find_spec hex
      rw [h0, pow_zero, mul_one] at hs
      exact absurd hs (not_lt.2 h)
    have h1 : 1 ≤ Nat.find hex := by omega
    by_contra hcon
    have hlt : N < D * 3^(Nat.find hex - 1) := not_le.1 hcon
    have hmin := Nat.find_min' hex hlt
    omega
  · -- Upper bound: k₀ - 1 + 1 = k₀.
    have hk0 : Nat.find hex ≠ 0 := by
      intro h0
      have hs := Nat.find_spec hex
      rw [h0, pow_zero, mul_one] at hs
      exact absurd hs (not_lt.2 h)
    have hk := Nat.find_spec hex
    have hadd : Nat.find hex - 1 + 1 = Nat.find hex := by omega
    rw [hadd]
    exact hk

/-- Every local event admits a finite-scale replacement; the two events agree
whenever no discarded generator occurs. -/
theorem exists_event_truncation {d : ℕ} {Ω : Type*} (E : ℕ → Lattice d → Set Ω)
    (S : Set (Lattice d)) (j0 : ℕ) {A : Set Ω}
    (hA : MeasurableSet[⨆ j, eventFieldSigma (E j) S] A) :
    ∃ B, MeasurableSet[⨆ j ∈ Finset.range (j0 + 1), eventFieldSigma (E j) S] B ∧
      ∀ ω, (ω ∉ ⋃ j : ℕ, ⋃ (_ : j0 < j), ⋃ z ∈ S, E j z) → (ω ∈ A ↔ ω ∈ B) := by
  change MeasurableSet[⨆ j, MeasurableSpace.generateFrom
    {T | ∃ z ∈ S, T = E j z}] A at hA
  rw [MeasurableSpace.iSup_generateFrom] at hA
  refine exists_measurable_agree_off _ _ _ ?_ hA
  rintro T hT
  obtain ⟨j, z, hz, rfl⟩ := Set.mem_iUnion.mp hT
  by_cases hj : j ≤ j0
  · have hm : eventFieldSigma (E j) S ≤
        ⨆ j ∈ Finset.range (j0 + 1), eventFieldSigma (E j) S :=
      le_iSup_of_le j (le_iSup_of_le (Finset.mem_range.mpr (by omega)) le_rfl)
    exact ⟨E j z, hm _ (measurableSet_event_of_mem hz), fun _ _ => Iff.rfl⟩
  · refine ⟨∅, @MeasurableSet.empty Ω (⨆ j ∈ Finset.range (j0 + 1), eventFieldSigma (E j) S), fun ω hω => ?_⟩
    have hnot : ω ∉ E j z := fun h => hω (Set.mem_iUnion.mpr ⟨j,
      Set.mem_iUnion.mpr ⟨by omega, Set.mem_iUnion.mpr ⟨z,
        Set.mem_iUnion.mpr ⟨hz, h⟩⟩⟩⟩)
    simp only [Set.mem_empty_iff_false, iff_false]
    exact hnot

/-- The replacement error is bounded by the sum of the discarded event probabilities.
-/
theorem exists_event_truncation_measure {d : ℕ} {Ω : Type*} [mΩ : MeasurableSpace Ω]
    (mu : Measure Ω) (E : ℕ → Lattice d → Set Ω) (F : Finset (Lattice d)) (j0 : ℕ)
    (hE : ∀ j z, MeasurableSet (E j z)) {A : Set Ω}
    (hA : MeasurableSet[⨆ j, eventFieldSigma (E j) (F : Set _)] A) :
    ∃ B, MeasurableSet[⨆ j ∈ Finset.range (j0 + 1), eventFieldSigma (E j) (F : Set _)] B ∧
      mu (A \ B) + mu (B \ A) ≤ ∑' j : ℕ, ∑ z ∈ F, mu (E (j + j0 + 1) z) := by
  obtain ⟨B, hB, hagree⟩ := exists_event_truncation E (F : Set _) j0 hA
  have hm (j : ℕ) : eventFieldSigma (E j) (F : Set _) ≤ mΩ :=
    MeasurableSpace.generateFrom_le (fun _ ⟨z, _, hz⟩ => hz ▸ hE j z)
  have hAm : MeasurableSet A := (iSup_le hm) A hA
  have hBm : MeasurableSet B := (iSup_le (fun j => iSup_le (fun _ => hm j))) B hB
  refine ⟨B, hB, (measure_differences_le mu hAm hBm
    (sdiff_union_subset_of_agree_off hagree)).trans ?_⟩
  have hsub : (⋃ j : ℕ, ⋃ (_ : j0 < j), ⋃ z ∈ (F : Set _), E j z) ⊆
      ⋃ n : ℕ, ⋃ z ∈ F, E (n + j0 + 1) z := by
    intro ω hω
    obtain ⟨j, hj, hω⟩ := Set.mem_iUnion₂.mp hω
    obtain ⟨z, hz, hmem⟩ := Set.mem_iUnion₂.mp hω
    have heq : j - (j0 + 1) + j0 + 1 = j := by omega
    exact Set.mem_iUnion.mpr ⟨j - (j0 + 1), Set.mem_iUnion₂.mpr
      ⟨z, hz, by simpa only [heq] using hmem⟩⟩
  exact (measure_mono hsub).trans ((measure_iUnion_le _).trans
    (ENNReal.tsum_le_tsum (fun n => measure_biUnion_finset_le F (fun z => E (n + j0 + 1) z))))

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section9Support
