import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ChemicalTimarCycleCells

/-!
# The cycle space of the `1`-step graph of `ℤ^d` is generated by its unit cells

This file proves the topological input of `[Timár, Lemma 2]`, in the exact form the boundary
argument consumes: **every `ZMod 2`-valued labelling of the `1`-step edges of `ℤ^d` that is a
cocycle on each unit cube cell is a coboundary**
(`exists_potential_of_isCellCocycle`).  Equivalently: `H^1` of the `1`-step graph of `ℤ^d`
relative to its unit-cube cells vanishes — "every `1`-step cycle is generated by unit squares".

## The statement

`IsCellCocycle ω` asks that `ω x y + ω y z + ω z x = 0` whenever `x, y, z` are pairwise `1`-step
adjacent.  By `exists_unitCubeCell_of_triple` such a triple is exactly a triple inside one unit
cube cell, so this is the *cellwise* cocycle condition and nothing more.

## The proof: the geodesic ladder

Let `γˣ k = latticeGeodesic 0 x k` be the `ℓ^∞` geodesic from the origin to `x`, and put
`g x = ∑_{k < d(0,x)} ω (γˣ k) (γˣ (k+1))`, the `ω`-sum along it.

The point is that geodesics from the origin to `1`-step adjacent endpoints stay `1`-step
adjacent at every time, and one time apart as well: clamping to `[-k, k]` is nonexpansive and
moves by at most one when `k` moves by one (`latticeDist_latticeGeodesic_zero_le`).  So the two
geodesics form a **ladder** whose rungs `(γˣ k, γˣ (k+1), γʸ (k+1), γʸ k)` are quadruples of
pairwise adjacent sites — hence quadruples inside one unit cube cell — and the cocycle condition
makes each rung close up (`ladder_step`).  Summing the rungs telescopes
(`sum_range_add_succ`): the sums along the two geodesics differ by
`ω (γˣ 0) (γʸ 0) + ω (γˣ N) (γʸ N) = ω 0 0 + ω x y = ω x y`.

No simple-connectivity machinery, no chain complexes: the contraction of `ℤ^d` to the origin is
carried by the geodesic itself, and the cocycle condition is applied only to the `O(1)` sites of
a single rung.

## Source

`[TimarBoundary, Lemma 2]` (Timár, *Boundary-connectivity via graph theory*, Proc. AMS 141
(2013), 475-480), the cycle-space input of its proof.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section9Support

open Set
open SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation

noncomputable section

variable {d : ℕ}

/-! ## Cell cocycles -/

/-- A `ZMod 2` labelling of the `1`-step edges of `ℤ^d` is a **cell cocycle** if it sums to zero
around every triangle of pairwise adjacent sites — equivalently (`exists_unitCubeCell_of_triple`)
around every triangle inside a unit cube cell. -/
def IsCellCocycle (ω : Lattice d → Lattice d → ZMod 2) : Prop :=
  ∀ x y z : Lattice d, latticeDist x y ≤ 1 → latticeDist y z ≤ 1 → latticeDist x z ≤ 1 →
    ω x y + ω y z + ω z x = 0

/-- Any three pairwise `1`-step adjacent sites lie in a common unit cube cell, so the triangle
condition of `IsCellCocycle` is exactly the cellwise one. -/
theorem exists_unitCubeCell_of_triple {p q r : Lattice d}
    (hpq : latticeDist p q ≤ 1) (hqr : latticeDist q r ≤ 1) (hpr : latticeDist p r ≤ 1) :
    ∃ a : Lattice d, p ∈ unitCubeCell a ∧ q ∈ unitCubeCell a ∧ r ∈ unitCubeCell a := by
  refine ⟨fun i => min (p i) (min (q i) (r i)), fun i => ?_, fun i => ?_, fun i => ?_⟩
  · have h1 := latticeDist_le_iff.mp hpq i
    have h2 := latticeDist_le_iff.mp hqr i
    have h3 := latticeDist_le_iff.mp hpr i
    show p i = min (p i) (min (q i) (r i)) ∨ p i = min (p i) (min (q i) (r i)) + 1
    omega
  · have h1 := latticeDist_le_iff.mp hpq i
    have h2 := latticeDist_le_iff.mp hqr i
    have h3 := latticeDist_le_iff.mp hpr i
    show q i = min (p i) (min (q i) (r i)) ∨ q i = min (p i) (min (q i) (r i)) + 1
    omega
  · have h1 := latticeDist_le_iff.mp hpq i
    have h2 := latticeDist_le_iff.mp hqr i
    have h3 := latticeDist_le_iff.mp hpr i
    show r i = min (p i) (min (q i) (r i)) ∨ r i = min (p i) (min (q i) (r i)) + 1
    omega

variable {ω : Lattice d → Lattice d → ZMod 2}

/-- A cell cocycle vanishes on the diagonal. -/
theorem isCellCocycle_self (hω : IsCellCocycle ω) (x : Lattice d) : ω x x = 0 := by
  have h := hω x x x (by simp) (by simp) (by simp)
  have k : ∀ a : ZMod 2, a + a + a = a := by decide
  rwa [k] at h

/-- A cell cocycle is symmetric on `1`-step edges. -/
theorem isCellCocycle_symm (hω : IsCellCocycle ω) {x y : Lattice d} (hxy : latticeDist x y ≤ 1) :
    ω y x = ω x y := by
  have h := hω x y x hxy (by rwa [latticeDist_comm]) (by simp)
  rw [isCellCocycle_self hω x, add_zero] at h
  have k : ∀ a b : ZMod 2, a + b = 0 → b = a := by decide
  exact k _ _ h

/-! ## The geodesic ladder -/

/-- Geodesics from the origin to `1`-step adjacent endpoints stay `1`-step adjacent, at equal
times and at times one apart: clamping to `[-k, k]` is nonexpansive in the endpoint and moves by
at most one in `k`. -/
theorem latticeDist_latticeGeodesic_zero_le {x y : Lattice d} (h : latticeDist x y ≤ 1)
    {k l : ℕ} (hkl : l ≤ k + 1) (hlk : k ≤ l + 1) :
    latticeDist (latticeGeodesic 0 x k) (latticeGeodesic 0 y l) ≤ 1 := by
  refine latticeDist_le_iff.mpr fun i => ?_
  have hi := latticeDist_le_iff.mp h i
  simp only [latticeGeodesic, Pi.zero_apply, sub_zero, zero_add]
  omega

/-- **The ladder rung closes up.**  For `1`-step adjacent `x` and `y`, the quadrilateral formed
by the two geodesics between times `k` and `k + 1` lies in a single unit cube cell, so the
cocycle condition turns the two "vertical" steps into the two "horizontal" ones. -/
theorem ladder_step (hω : IsCellCocycle ω) {x y : Lattice d} (hxy : latticeDist x y ≤ 1)
    (k : ℕ) :
    ω (latticeGeodesic 0 x k) (latticeGeodesic 0 x (k + 1))
      + ω (latticeGeodesic 0 y k) (latticeGeodesic 0 y (k + 1))
    = ω (latticeGeodesic 0 x k) (latticeGeodesic 0 y k)
      + ω (latticeGeodesic 0 x (k + 1)) (latticeGeodesic 0 y (k + 1)) := by
  have hxx : latticeDist x x ≤ 1 := by simp
  have hyy : latticeDist y y ≤ 1 := by simp
  have hpq : latticeDist (latticeGeodesic 0 x k) (latticeGeodesic 0 x (k + 1)) ≤ 1 :=
    latticeDist_latticeGeodesic_zero_le hxx (by omega) (by omega)
  have hqr : latticeDist (latticeGeodesic 0 x (k + 1)) (latticeGeodesic 0 y (k + 1)) ≤ 1 :=
    latticeDist_latticeGeodesic_zero_le hxy (by omega) (by omega)
  have hpr : latticeDist (latticeGeodesic 0 x k) (latticeGeodesic 0 y (k + 1)) ≤ 1 :=
    latticeDist_latticeGeodesic_zero_le hxy (by omega) (by omega)
  have hrs : latticeDist (latticeGeodesic 0 y (k + 1)) (latticeGeodesic 0 y k) ≤ 1 :=
    latticeDist_latticeGeodesic_zero_le hyy (by omega) (by omega)
  have hps : latticeDist (latticeGeodesic 0 x k) (latticeGeodesic 0 y k) ≤ 1 :=
    latticeDist_latticeGeodesic_zero_le hxy (by omega) (by omega)
  have t1 := hω (latticeGeodesic 0 x k) (latticeGeodesic 0 x (k + 1))
    (latticeGeodesic 0 y (k + 1)) hpq hqr hpr
  have t2 := hω (latticeGeodesic 0 x k) (latticeGeodesic 0 y (k + 1)) (latticeGeodesic 0 y k)
    hpr hrs hps
  rw [isCellCocycle_symm hω hpr] at t1
  rw [← isCellCocycle_symm hω hrs, isCellCocycle_symm hω hps] at t2
  have hchar : ∀ a b c e f : ZMod 2, a + b + c = 0 → c + e + f = 0 → a + e = f + b := by decide
  exact hchar _ _ _ _ _ t1 t2

/-! ## The potential -/

/-- The `ω`-sum along the first `N` steps of the geodesic from the origin to `x`. -/
def geodesicSum (ω : Lattice d → Lattice d → ZMod 2) (x : Lattice d) (N : ℕ) : ZMod 2 :=
  ∑ k ∈ Finset.range N, ω (latticeGeodesic 0 x k) (latticeGeodesic 0 x (k + 1))

/-- Past the length of the geodesic the sum no longer changes. -/
theorem geodesicSum_of_le (hω : IsCellCocycle ω) (x : Lattice d) {N : ℕ}
    (hN : latticeDist 0 x ≤ N) : geodesicSum ω x N = geodesicSum ω x (latticeDist 0 x) := by
  induction N, hN using Nat.le_induction with
  | base => rfl
  | succ N hN ih =>
    have h1 : latticeGeodesic 0 x N = x := latticeGeodesic_of_latticeDist_le hN
    have h2 : latticeGeodesic 0 x (N + 1) = x :=
      latticeGeodesic_of_latticeDist_le (by omega)
    rw [geodesicSum, Finset.sum_range_succ, ← geodesicSum, ih, h1, h2,
      isCellCocycle_self hω x, add_zero]

/-- A telescoping sum in characteristic two. -/
theorem sum_range_add_succ (h : ℕ → ZMod 2) (N : ℕ) :
    ∑ k ∈ Finset.range N, (h k + h (k + 1)) = h 0 + h N := by
  have hself : ∀ a : ZMod 2, a + a = 0 := by decide
  induction N with
  | zero => simp [hself]
  | succ N ih =>
    rw [Finset.sum_range_succ, ih]
    have : h 0 + h N + (h N + h (N + 1)) = h 0 + (h N + h N) + h (N + 1) := by ring
    rw [this, hself, add_zero]

/-- **The cycle space of the `1`-step graph of `ℤ^d` is generated by its unit cube cells.**
Every cell cocycle is a coboundary: there is a `ZMod 2` potential `g` with `ω x y = g x + g y`
on every `1`-step edge.

This is the topological input of `[Timár, Lemma 2]`, and the reason the boundary argument is a
theorem about `ℤ^d` rather than about a general graph. -/
theorem exists_potential_of_isCellCocycle (hω : IsCellCocycle ω) :
    ∃ g : Lattice d → ZMod 2, ∀ x y : Lattice d, latticeDist x y ≤ 1 → ω x y = g x + g y := by
  refine ⟨fun x => geodesicSum ω x (latticeDist 0 x), fun x y hxy => ?_⟩
  set N := max (latticeDist 0 x) (latticeDist 0 y) with hNdef
  have hxN : latticeDist 0 x ≤ N := le_max_left _ _
  have hyN : latticeDist 0 y ≤ N := le_max_right _ _
  have hladder : ∑ k ∈ Finset.range N,
      (ω (latticeGeodesic 0 x k) (latticeGeodesic 0 x (k + 1))
        + ω (latticeGeodesic 0 y k) (latticeGeodesic 0 y (k + 1)))
      = ∑ k ∈ Finset.range N,
        (ω (latticeGeodesic 0 x k) (latticeGeodesic 0 y k)
          + ω (latticeGeodesic 0 x (k + 1)) (latticeGeodesic 0 y (k + 1))) :=
    Finset.sum_congr rfl fun k _ => ladder_step hω hxy k
  rw [Finset.sum_add_distrib, ← geodesicSum, ← geodesicSum, geodesicSum_of_le hω x hxN,
    geodesicSum_of_le hω y hyN] at hladder
  rw [sum_range_add_succ (fun k => ω (latticeGeodesic 0 x k) (latticeGeodesic 0 y k)) N] at hladder
  have h0x : latticeGeodesic 0 x 0 = (0 : Lattice d) := latticeGeodesic_zero 0 x
  have h0y : latticeGeodesic 0 y 0 = (0 : Lattice d) := latticeGeodesic_zero 0 y
  have hNx : latticeGeodesic 0 x N = x := latticeGeodesic_of_latticeDist_le hxN
  have hNy : latticeGeodesic 0 y N = y := latticeGeodesic_of_latticeDist_le hyN
  simp only [h0x, h0y, hNx, hNy, isCellCocycle_self hω, zero_add] at hladder
  exact hladder.symm

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section9Support
