module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ChemicalLocalCarrier
public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ChemicalLocalIndependence
public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ChemicalP346ASDDiameterTwo

@[expose] public section

/-!
# The `[ASD]` site family of a Section 9 event field

The abstract percolation layer of `Section9ChemicalP346ASDDiameterTwo` consumes a
family `B : ℕ → ℤ^d → Set Ω` with two hypotheses: independence of the
`σ`-algebras generated by the levels `≤ l` over two site sets separated by more
than `3 ^ l`, and a per-level tail `μ (B L w) ≤ exp (-(T² 3^{a L}))`.

This file constructs that family from the multiscale-percolation field `E` and **proves both
hypotheses** from the
field's own hypotheses.  The construction is the reindexing

```text
asdSiteEvent E Cbox Cdep L z = ∅                                      (L < s₀)
                             = influenceFailure (E (L - s₀)) (Cbox 3^(L-s₀)) z
```

with the shift `s₀ = asdShift Cbox Cdep = 2 Cbox + Cdep`, chosen so that
`2 Cbox + Cdep < 3 ^ s₀`: level `L` reads the field at scale `L - s₀` inside a
ball of radius `Cbox 3^(L - s₀)`, so two site sets separated by more than `3 ^ L`
carry field supports separated by more than `Cdep 3 ^ (L - s₀)`, which is the
field's own finite-range radius at that scale.  The union over `L` is unchanged
(`iUnion_asdSiteEvent`), because `L ↦ L - s₀` is onto `ℕ` above `s₀`.

## Main results

* `iUnion_asdSiteEvent` — the family's union is the bad-site event.
* `indep_siteSigma_asdSiteEvent` — the abstract layer's independence hypothesis.
* `measure_asdSiteEvent_le_exp` — the abstract layer's tail hypothesis at
  `a = 3/2` and rate `asdRate`.
* `measure_crossingEvent₂At_asdSiteEvent_le` — `[ASD]`'s crossing bound for the
  concrete field, with no hypothesis beyond the field's own.

## Source
ABK26
`l.percolation.bound.general` (3) as ported in
`Section9ChemicalP346ASDDiameterTwo`.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section9Support

open MeasureTheory Set ProbabilityTheory
open SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation
open scoped ENNReal

noncomputable section

variable {d : ℕ} {Ω : Type*}

/-! ## The reindexing shift -/

/-- The level shift of the `[ASD]` site family: level `L` of the family reads
scale `L - asdShift Cbox Cdep` of the event field. -/
def asdShift (Cbox Cdep : ℕ) : ℕ := 2 * Cbox + Cdep

theorem asdShift_lt_three_pow (Cbox Cdep : ℕ) :
    asdShift Cbox Cdep < 3 ^ asdShift Cbox Cdep := by
  have h := ASD.succ_le_three_pow (asdShift Cbox Cdep)
  omega

/-- The `[ASD]` site family of a Section 9 multiscale event field. -/
def asdSiteEvent (E : ℕ → Lattice d → Set Ω) (Cbox Cdep : ℕ) (L : ℕ)
    (z : Lattice d) : Set Ω :=
  if L < asdShift Cbox Cdep then (∅ : Set Ω)
  else influenceFailure (E (L - asdShift Cbox Cdep))
    (Cbox * 3 ^ (L - asdShift Cbox Cdep)) z

theorem asdSiteEvent_of_lt {E : ℕ → Lattice d → Set Ω} {Cbox Cdep L : ℕ}
    (h : L < asdShift Cbox Cdep) (z : Lattice d) :
    asdSiteEvent E Cbox Cdep L z = (∅ : Set Ω) := by
  simp [asdSiteEvent, h]

theorem asdSiteEvent_of_le {E : ℕ → Lattice d → Set Ω} {Cbox Cdep L : ℕ}
    (h : asdShift Cbox Cdep ≤ L) (z : Lattice d) :
    asdSiteEvent E Cbox Cdep L z =
      influenceFailure (E (L - asdShift Cbox Cdep))
        (Cbox * 3 ^ (L - asdShift Cbox Cdep)) z := by
  simp [asdSiteEvent, Nat.not_lt.mpr h]

/-- The family's union over the levels is exactly the bad-site event. -/
theorem iUnion_asdSiteEvent (E : ℕ → Lattice d → Set Ω) (Cbox Cdep : ℕ)
    (z : Lattice d) :
    (⋃ L : ℕ, asdSiteEvent E Cbox Cdep L z) = percolationBadSite E Cbox z := by
  rw [percolationBadSite_eq_iUnion]
  apply Set.Subset.antisymm
  · refine Set.iUnion_subset fun L => ?_
    by_cases h : L < asdShift Cbox Cdep
    · rw [asdSiteEvent_of_lt h]
      exact Set.empty_subset _
    · rw [asdSiteEvent_of_le (Nat.not_lt.mp h)]
      exact Set.subset_iUnion (fun j => influenceFailure (E j) (Cbox * 3 ^ j) z) _
  · refine Set.iUnion_subset fun j => ?_
    refine le_trans ?_ (Set.subset_iUnion _ (j + asdShift Cbox Cdep))
    rw [asdSiteEvent_of_le (Nat.le_add_left _ _), Nat.add_sub_cancel]

theorem measurableSet_asdSiteEvent [MeasurableSpace Ω]
    {E : ℕ → Lattice d → Set Ω} (hE : ∀ j z, MeasurableSet (E j z))
    (Cbox Cdep L : ℕ) (z : Lattice d) :
    MeasurableSet (asdSiteEvent E Cbox Cdep L z) := by
  by_cases h : L < asdShift Cbox Cdep
  · rw [asdSiteEvent_of_lt h]; exact MeasurableSet.empty
  · rw [asdSiteEvent_of_le (Nat.not_lt.mp h)]
    exact MeasurableSet.biUnion (Finset.countable_toSet _) fun u _ => hE _ u

/-! ## The independence hypothesis of the abstract layer -/

theorem asdShift_def (Cbox Cdep : ℕ) : asdShift Cbox Cdep = 2 * Cbox + Cdep := rfl

/-- The level-`≤ l` `σ`-algebra of the site family over `U` is carried by the
field scales `≤ l - s₀` over the `Cbox 3^(l-s₀)`-thickening of `U`. -/
theorem siteSigma_asdSiteEvent_le [MeasurableSpace Ω]
    (E : ℕ → Lattice d → Set Ω) (Cbox Cdep l : ℕ) (U : Set (Lattice d)) :
    ASD.siteSigma (asdSiteEvent E Cbox Cdep) U l ≤
      ⨆ j ∈ Finset.range ((l - asdShift Cbox Cdep) + 1), eventFieldSigma (E j)
        (⋃ x ∈ U, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
          Set (Lattice d))) := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro A ⟨L, hL, y, hy, rfl⟩
  by_cases hLs : L < asdShift Cbox Cdep
  · rw [asdSiteEvent_of_lt hLs]
    exact MeasurableSpace.measurableSet_empty _
  · rw [asdSiteEvent_of_le (Nat.not_lt.mp hLs)]
    have hj : L - asdShift Cbox Cdep ∈ Finset.range ((l - asdShift Cbox Cdep) + 1) := by
      simp only [Finset.mem_range]
      omega
    have hmono : eventFieldSigma (E (L - asdShift Cbox Cdep))
        (⋃ x ∈ U, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
          Set (Lattice d))) ≤
        ⨆ j ∈ Finset.range ((l - asdShift Cbox Cdep) + 1), eventFieldSigma (E j)
          (⋃ x ∈ U, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
            Set (Lattice d))) :=
      le_iSup_of_le (L - asdShift Cbox Cdep) (le_iSup_of_le hj le_rfl)
    have hmeas : MeasurableSet[eventFieldSigma (E (L - asdShift Cbox Cdep))
        (⋃ x ∈ U, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
          Set (Lattice d)))]
        (influenceFailure (E (L - asdShift Cbox Cdep))
          (Cbox * 3 ^ (L - asdShift Cbox Cdep)) y) := by
      refine MeasurableSet.biUnion (Finset.countable_toSet _) fun u hu => ?_
      have hrad : Cbox * 3 ^ (L - asdShift Cbox Cdep) ≤
          Cbox * 3 ^ (l - asdShift Cbox Cdep) :=
        Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (by omega) (by omega))
      exact measurableSet_event_of_mem (Set.mem_biUnion hy
        (mem_latticeBallFinset_iff.mpr ((mem_latticeBallFinset_iff.mp hu).trans hrad)))
    exact hmono _ hmeas

/-- **The abstract layer's independence hypothesis, discharged for the concrete
field.**  Nothing beyond `IndependentEventScales` and the field's own
finite-range hypothesis is used. -/
theorem indep_siteSigma_asdSiteEvent [MeasurableSpace Ω] (mu : Measure Ω)
    [IsProbabilityMeasure mu] (E : ℕ → Lattice d → Set Ω) (Cbox Cdep : ℕ)
    (hE : ∀ j z, MeasurableSet (E j z))
    (hsc : IndependentEventScales mu E)
    (hr : MultiscaleFiniteRangeIndependentEvents mu (fun j => Cdep * 3 ^ j) E)
    (l : ℕ) (S T : Set (Lattice d))
    (hsep : ∀ u ∈ S, ∀ v ∈ T, 3 ^ l < latticeDist u v) :
    Indep (ASD.siteSigma (asdSiteEvent E Cbox Cdep) S l)
      (ASD.siteSigma (asdSiteEvent E Cbox Cdep) T l) mu := by
  classical
  by_cases hl : l < asdShift Cbox Cdep
  · have hbot : ∀ U : Set (Lattice d),
        ASD.siteSigma (asdSiteEvent E Cbox Cdep) U l ≤ ⊥ := by
      intro U
      refine MeasurableSpace.generateFrom_le ?_
      rintro A ⟨L, hL, y, hy, rfl⟩
      rw [asdSiteEvent_of_lt (by omega)]
      exact MeasurableSpace.measurableSet_empty _
    exact indep_of_subsigmas mu
      (indep_bot_left (_mΩ := inferInstance) (μ := mu) (⊥ : MeasurableSpace Ω))
      (hbot S) (hbot T)
  · have hl' : asdShift Cbox Cdep ≤ l := Nat.not_lt.mp hl
    have hkey : ∀ j : ℕ, j ≤ l - asdShift Cbox Cdep →
        2 * (Cbox * 3 ^ (l - asdShift Cbox Cdep)) + Cdep * 3 ^ j ≤ 3 ^ l := by
      intro j hj
      have hpow : (3 : ℕ) ^ j ≤ 3 ^ (l - asdShift Cbox Cdep) :=
        Nat.pow_le_pow_right (by norm_num) hj
      have h1 : 2 * (Cbox * 3 ^ (l - asdShift Cbox Cdep)) + Cdep * 3 ^ j ≤
          asdShift Cbox Cdep * 3 ^ (l - asdShift Cbox Cdep) := by
        have hcd : Cdep * 3 ^ j ≤ Cdep * 3 ^ (l - asdShift Cbox Cdep) :=
          Nat.mul_le_mul_left _ hpow
        have hP : asdShift Cbox Cdep * 3 ^ (l - asdShift Cbox Cdep) =
            2 * (Cbox * 3 ^ (l - asdShift Cbox Cdep)) +
              Cdep * 3 ^ (l - asdShift Cbox Cdep) := by
          rw [asdShift_def]; ring
        rw [hP]
        exact Nat.add_le_add_left hcd _
      have h2 : asdShift Cbox Cdep * 3 ^ (l - asdShift Cbox Cdep) ≤
          3 ^ asdShift Cbox Cdep * 3 ^ (l - asdShift Cbox Cdep) :=
        Nat.mul_le_mul_right _ (le_of_lt (asdShift_lt_three_pow Cbox Cdep))
      have h3 : (3 : ℕ) ^ asdShift Cbox Cdep * 3 ^ (l - asdShift Cbox Cdep) = 3 ^ l := by
        rw [← pow_add]
        congr 1
        omega
      exact le_trans h1 (h3 ▸ h2)
    have hsp : ∀ j < (l - asdShift Cbox Cdep) + 1,
        Indep (eventFieldSigma (E j)
            (⋃ x ∈ S, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
              Set (Lattice d))))
          (eventFieldSigma (E j)
            (⋃ x ∈ T, (latticeBallFinset x (Cbox * 3 ^ (l - asdShift Cbox Cdep)) :
              Set (Lattice d)))) mu := by
      intro j hj
      refine hr j _ _ (latticeThickening_separated ?_)
      intro x hx y hy
      show 2 * (Cbox * 3 ^ (l - asdShift Cbox Cdep)) + Cdep * 3 ^ j < latticeDist x y
      exact lt_of_le_of_lt (hkey j (by omega)) (hsep x hx y hy)
    have hi := indep_event_truncations mu E _ _ ((l - asdShift Cbox Cdep) + 1) hE hsc hsp
    exact indep_of_subsigmas mu hi
      (siteSigma_asdSiteEvent_le E Cbox Cdep l S)
      (siteSigma_asdSiteEvent_le E Cbox Cdep l T)

/-! ## The tail hypothesis of the abstract layer -/

/-- The rate of the `[ASD]` site family at exponent `a = 3/2`: the field's own
rate `cprob q`, halved (the other half absorbs the influence-box entropy) and
rescaled by the level shift. -/
def asdRate (Cbox Cdep : ℕ) (cprob q : ℝ) : ℝ :=
  cprob * q / 2 * (3 : ℝ) ^ (-((3 : ℝ) * (asdShift Cbox Cdep : ℝ) / 2))

theorem asdRate_pos (Cbox Cdep : ℕ) {cprob q : ℝ} (h : 0 < cprob * q) :
    0 < asdRate Cbox Cdep cprob q :=
  mul_pos (by linarith) (Real.rpow_pos_of_pos (by norm_num) _)

theorem asdRate_mul_rpow {Cbox Cdep L : ℕ} (hL : asdShift Cbox Cdep ≤ L)
    (cprob q : ℝ) :
    asdRate Cbox Cdep cprob q * (3 : ℝ) ^ ((3 : ℝ) * (L : ℝ) / 2) =
      cprob * q / 2 *
        (3 : ℝ) ^ ((3 : ℝ) * ((L - asdShift Cbox Cdep : ℕ) : ℝ) / 2) := by
  have hcast : ((L - asdShift Cbox Cdep : ℕ) : ℝ) = (L : ℝ) - (asdShift Cbox Cdep : ℝ) := by
    rw [Nat.cast_sub hL]
  rw [asdRate, hcast, mul_assoc, ← Real.rpow_add (by norm_num : (0:ℝ) < 3)]
  ring_nf

/-- **The abstract layer's tail hypothesis, discharged for the concrete field.**
The influence-box entropy `(2 Cbox 3^j + 1)^d` and the field prefactor `Cprob`
are absorbed by half the field rate, under two explicit thresholds on `q` that
do not depend on the field. -/
theorem measure_asdSiteEvent_le_exp [MeasurableSpace Ω] (mu : Measure Ω)
    {E : ℕ → Lattice d → Set Ω} {Cbox Cdep : ℕ} (hCbox : 1 ≤ Cbox)
    {Cprob cprob q : ℝ} (hCprob : 0 < Cprob) (hA : 0 ≤ cprob * q)
    (hth1 : Real.log ((((3 * Cbox) ^ d : ℕ) : ℝ) * Cprob) ≤ cprob * q / 2)
    (hth2 : (d : ℝ) * Real.log 3 ≤ cprob * q / 2)
    (hE : ∀ j u, mu (E j u) ≤
      ENNReal.ofReal (Cprob * Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2))))
    (L : ℕ) (z : Lattice d) :
    mu (asdSiteEvent E Cbox Cdep L z) ≤
      ENNReal.ofReal (Real.exp
        (-(asdRate Cbox Cdep cprob q * (3 : ℝ) ^ ((3 : ℝ) * (L : ℝ) / 2)))) := by
  by_cases hL : L < asdShift Cbox Cdep
  · rw [asdSiteEvent_of_lt hL]
    simp
  · have hL' : asdShift Cbox Cdep ≤ L := Nat.not_lt.mp hL
    set j : ℕ := L - asdShift Cbox Cdep with hjdef
    rw [asdSiteEvent_of_le hL', asdRate_mul_rpow hL' cprob q]
    set K : ℝ := (((3 * Cbox) ^ d : ℕ) : ℝ) * Cprob with hKdef
    have hKpos : 0 < K := by
      have : (0 : ℝ) < (((3 * Cbox) ^ d : ℕ) : ℝ) := by
        have : 0 < (3 * Cbox) ^ d := Nat.pow_pos (by omega)
        exact_mod_cast this
      exact mul_pos this hCprob
    -- the union bound over the influence box
    have hstep := measure_influenceFailure_le (μ := mu) (E j) (Cbox * 3 ^ j) z
      (ENNReal.ofReal (Cprob * Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2))))
      (hE j)
    rw [nsmul_eq_mul] at hstep
    refine hstep.trans ?_
    -- the entropy count
    have hcard : (((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) ≤
        (((3 * Cbox) ^ d : ℕ) : ℝ) * (((3 ^ d : ℕ) : ℝ) ^ j) := by
      have h := card_influenceBox_le hCbox d j
      have hc : (((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) ≤
          (((3 * Cbox) ^ d * (3 ^ d) ^ j : ℕ) : ℝ) := by exact_mod_cast h
      simpa using hc
    have hexp : 0 ≤ Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2)) := (Real.exp_pos _).le
    have hmain : (((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) *
        (Cprob * Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2))) ≤
        Real.exp (-(cprob * q / 2 * (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2))) := by
      have hgrow : K * (((3 ^ d : ℕ) : ℝ) ^ j) ≤
          Real.exp (cprob * q / 2 * (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2)) := by
        have hpowpos : (0 : ℝ) < (((3 ^ d : ℕ) : ℝ) ^ j) := by positivity
        have hlog : Real.log (K * (((3 ^ d : ℕ) : ℝ) ^ j)) ≤
            cprob * q / 2 * (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2) := by
          rw [Real.log_mul (ne_of_gt hKpos) (ne_of_gt hpowpos), Real.log_pow]
          have hlog3d : Real.log (((3 ^ d : ℕ) : ℝ)) = (d : ℝ) * Real.log 3 := by
            push_cast
            rw [Real.log_pow]
          rw [hlog3d]
          have hlin : Real.log K + (j : ℝ) * ((d : ℝ) * Real.log 3) ≤
              cprob * q / 2 * ((j : ℝ) + 1) := by
            have hj0 : (0 : ℝ) ≤ (j : ℝ) := Nat.cast_nonneg j
            nlinarith
          refine hlin.trans ?_
          have hgeom : ((j : ℝ) + 1) ≤ (3 : ℝ) ^ ((3 : ℝ) * j / 2) :=
            three_rpow_three_halves_mul_ge j
          have : (0 : ℝ) ≤ cprob * q / 2 := by linarith
          have heq : (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2) = (3 : ℝ) ^ ((3 : ℝ) * j / 2) := rfl
          rw [heq]
          exact mul_le_mul_of_nonneg_left hgeom this
        have := Real.exp_le_exp.mpr hlog
        rwa [Real.exp_log (by positivity)] at this
      have hfinal : (((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) * Cprob ≤
          K * (((3 ^ d : ℕ) : ℝ) ^ j) := by
        rw [hKdef]
        have := mul_le_mul_of_nonneg_right hcard hCprob.le
        nlinarith [this]
      calc (((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) *
            (Cprob * Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2)))
          = ((((2 * (Cbox * 3 ^ j) + 1) ^ d : ℕ) : ℝ) * Cprob) *
              Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2)) := by ring
        _ ≤ (K * (((3 ^ d : ℕ) : ℝ) ^ j)) *
              Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2)) :=
              mul_le_mul_of_nonneg_right hfinal hexp
        _ ≤ Real.exp (cprob * q / 2 * (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2)) *
              Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2)) :=
              mul_le_mul_of_nonneg_right hgrow hexp
        _ = Real.exp (-(cprob * q / 2 * (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2))) := by
              rw [← Real.exp_add]
              congr 1
              have heq : (3 : ℝ) ^ ((3 : ℝ) * (j : ℝ) / 2) = (3 : ℝ) ^ ((3 : ℝ) * j / 2) := rfl
              rw [heq]
              ring
    rw [← ENNReal.ofReal_natCast, ← ENNReal.ofReal_mul (by positivity)]
    exact ENNReal.ofReal_le_ofReal hmain

/-! ## The crossing bound for the concrete field -/

/-- **`[ASD, Lemma B.1(3)]`'s crossing bound for a Section 9 event field.**

For every field satisfying the multiscale-percolation hypotheses and every `q`
above three explicit thresholds, the probability that a distance-two bad path
crosses the annulus `□_{k+1}(w) ∖ □_k(w)` is at most
`exp (-(e^{-80} asdRate 3^{k/2} / 2))`.  All hypotheses of the abstract layer are
discharged; nothing external enters. -/
theorem measure_crossingEvent₂At_asdSiteEvent_le [MeasurableSpace Ω]
    (mu : Measure Ω) [IsProbabilityMeasure mu] {E : ℕ → Lattice d → Set Ω}
    {Cbox Cdep : ℕ} (hd : 1 ≤ d) (hCbox : 1 ≤ Cbox)
    {Cprob cprob q : ℝ} (hCprob : 0 < Cprob) (hApos : 0 < cprob * q)
    (hth1 : Real.log ((((3 * Cbox) ^ d : ℕ) : ℝ) * Cprob) ≤ cprob * q / 2)
    (hth2 : (d : ℝ) * Real.log 3 ≤ cprob * q / 2)
    (hgate : 16 * (d : ℝ) * Real.exp 80 ≤ asdRate Cbox Cdep cprob q / 2)
    (hE : ∀ j z, MeasurableSet (E j z))
    (hsc : IndependentEventScales mu E)
    (hr : MultiscaleFiniteRangeIndependentEvents mu (fun j => Cdep * 3 ^ j) E)
    (hprob : ∀ j u, mu (E j u) ≤
      ENNReal.ofReal (Cprob * Real.exp (-cprob * q * 3 ^ ((3 : ℝ) * j / 2))))
    (k : ℕ) (w : Lattice d) :
    mu (ASD.crossingEvent₂At (asdSiteEvent E Cbox Cdep) k w) ≤
      ENNReal.ofReal (Real.exp (-(Real.exp (-(80 : ℝ)) *
        asdRate Cbox Cdep cprob q * (3 : ℝ) ^ ((1 : ℝ) / 2 * (k : ℝ)) / 2))) := by
  have hRpos : 0 < asdRate Cbox Cdep cprob q := asdRate_pos Cbox Cdep hApos
  have hT2 : Real.sqrt (asdRate Cbox Cdep cprob q) ^ 2 = asdRate Cbox Cdep cprob q :=
    Real.sq_sqrt hRpos.le
  have hBtail : ∀ (L : ℕ) (v : Lattice d),
      mu (asdSiteEvent E Cbox Cdep L v) ≤
        ENNReal.ofReal (Real.exp
          (-(Real.sqrt (asdRate Cbox Cdep cprob q) ^ 2 *
            (3 : ℝ) ^ ((3 : ℝ) / 2 * (L : ℝ))))) := by
    intro L v
    have h := measure_asdSiteEvent_le_exp mu (E := E) (Cbox := Cbox) (Cdep := Cdep)
      hCbox hCprob hApos.le hth1 hth2 hprob L v
    have hex : (3 : ℝ) ^ ((3 : ℝ) / 2 * (L : ℝ)) = (3 : ℝ) ^ ((3 : ℝ) * (L : ℝ) / 2) := by
      congr 1
      ring
    rw [hT2, hex]
    exact h
  have hgate' : 16 * (d : ℝ) * Real.exp (40 / (1 - (1 : ℝ) / 2)) ≤
      Real.sqrt (asdRate Cbox Cdep cprob q) ^ 2 * ((1 : ℝ) / 2) := by
    rw [hT2]
    have h80 : (40 : ℝ) / (1 - (1 : ℝ) / 2) = 80 := by norm_num
    rw [h80]
    linarith
  have hmain := ASD.measure_crossingEvent₂At_le_exp (μ := mu)
    (B := asdSiteEvent E Cbox Cdep) (a := (3 : ℝ) / 2) (b := (1 : ℝ) / 2)
    (T := Real.sqrt (asdRate Cbox Cdep cprob q))
    hd (by norm_num) (by norm_num) (by norm_num) hgate'
    (fun l S S' hsep =>
      indep_siteSigma_asdSiteEvent mu E Cbox Cdep hE hsc hr l S S' hsep)
    hBtail k w
  rw [hT2] at hmain
  have h80 : (40 : ℝ) / (1 - (1 : ℝ) / 2) = 80 := by norm_num
  rw [h80] at hmain
  exact hmain

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section9Support
