

import Mathlib.Analysis.MeanInequalities
import SubdiffusiveProcess.Section9.BesovPowerAlgebra
import SubdiffusiveProcess.Section9.BesovScaleHolder
import SubdiffusiveProcess.Section9.BesovGeometricEmbedding
import SubdiffusiveProcess.CoarseGrainingVocab.Norms
import Homogenization.Besov.Negative.ExactFiniteBridge
import Homogenization.Besov.Poincare.Projection

/-!
# Exact circ restriction to triadic descendants

Canonical tree and finite-family Hölder infrastructure for the finite-exponent
branch of the local negative Besov restriction estimate in Section 9.
-/

namespace SubdiffusiveProcess.Section9

open scoped BigOperators ENNReal
open Homogenization

/-- Canonical diagonal finite parameters for the source quantity
`B^{-s}_{p,p}` in the strict fractional range. -/
noncomputable def exactCircDiagonalParameters (s p : ℝ) (hs : 0 < s)
    (hs1 : s < 1) (hp : 1 ≤ p) : ExactCircFiniteParameters where
  s := s
  p := p
  q := p
  admissible := ⟨hs, hs1.le, hp, hp, fun h => False.elim (hs1.ne h)⟩

@[simp] theorem exactCircDiagonalParameters_s (s p : ℝ) (hs : 0 < s)
    (hs1 : s < 1) (hp : 1 ≤ p) :
    (exactCircDiagonalParameters s p hs hs1 hp).s = s := rfl

@[simp] theorem exactCircDiagonalParameters_p (s p : ℝ) (hs : 0 < s)
    (hs1 : s < 1) (hp : 1 ≤ p) :
    (exactCircDiagonalParameters s p hs hs1 hp).p = p := rfl

@[simp] theorem exactCircDiagonalParameters_q (s p : ℝ) (hs : 0 < s)
    (hs1 : s < 1) (hp : 1 ≤ p) :
    (exactCircDiagonalParameters s p hs hs1 hp).q = p := rfl

/-- The geometric ratio generated by a strict smoothness gap lies strictly
between zero and one and is finite. -/
theorem besovRestrictionGeometricRatio_mem_Ioo {s σ : ℝ} (hσs : σ < s) :
    (3 : ℝ≥0∞) ^ (-(s - σ)) ∈ Set.Ioo 0 1 := by
  constructor
  · exact ENNReal.rpow_pos (by norm_num) (by norm_num)
  · exact ENNReal.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)

/-- Exact-circ block integrability restricts to a genuine triadic descendant. -/
def ExactCircIntegrable.descendant {d : ℕ} {H Q : TriadicCube d} {a : ℕ}
    {f : Vec d → ℝ} (hf : ExactCircIntegrable H f)
    (hQ : Q ∈ descendantsAtDepth H a) : ExactCircIntegrable Q f where
  block j R hR := hf.block (a + j) R (mem_descendantsAtDepth_add hQ hR)

/-- The certified block mean on a descendant is literally the corresponding
parent block mean at the shifted depth. -/
theorem exactCircBlockMean_descendant {d : ℕ} {H Q : TriadicCube d} {a j : ℕ}
    {f : Vec d → ℝ} (hf : ExactCircIntegrable H f)
    (hQ : Q ∈ descendantsAtDepth H a) {R : TriadicCube d}
    (hR : R ∈ descendantsAtDepth Q j) :
    exactCircBlockMean R f ((ExactCircIntegrable.descendant hf hQ).block j R hR) =
      exactCircBlockMean R f (hf.block (a + j) R (mem_descendantsAtDepth_add hQ hR)) := by
  rfl

/-- Finite-family Hölder in the form used by spatial restriction.  The
cardinality exponent is exact; no overlap multiplicity is inserted. -/
theorem sum_rpow_le_card_rpow_mul_sum_rpow {ι : Type*} (S : Finset ι)
    (x : ι → ℝ≥0∞) {p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    ∑ i ∈ S, x i ^ p ≤
      (S.card : ℝ≥0∞) ^ (1 - p / P) *
        (∑ i ∈ S, x i ^ P) ^ (p / P) := by
  let r : ℝ := P / p
  let t : ℝ := P / (P - p)
  have hP : 0 < P := hp.trans hpP
  have hr : 1 < r := by
    dsimp [r]
    exact (lt_div_iff₀ hp).2 (by simpa using hpP)
  have hrt : r.HolderConjugate t := by
    rw [Real.holderConjugate_iff]
    refine ⟨hr, ?_⟩
    dsimp [r, t]
    field_simp
    ring
  have hholder := ENNReal.inner_le_Lp_mul_Lq S (fun i => x i ^ p)
    (fun _ => (1 : ℝ≥0∞)) hrt
  simpa only [mul_one, ENNReal.one_rpow, Finset.sum_const, nsmul_eq_mul, mul_one,
    ← ENNReal.rpow_mul, one_div, show r⁻¹ = p / P by simp [r, div_eq_mul_inv],
    show p * r = P by
      dsimp [r]
      field_simp,
    show t⁻¹ = 1 - p / P by
      dsimp [t]
      field_simp,
    mul_comm] using hholder

/-- Spatial Hölder on the actual descendant family of `Q`, compared with the
shifted descendant family of `H`.  This is the exact finite-family core of the
Besov restriction argument. -/
theorem sum_blockMean_rpow_descendant_le {d : ℕ} {H Q : TriadicCube d}
    {a j : ℕ} (f : Vec d → ℝ) (hQ : Q ∈ descendantsAtDepth H a)
    {p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    ∑ R ∈ descendantsAtDepth Q j, (ENNReal.ofReal |cubeAverage R f|) ^ p ≤
      ((descendantsAtDepth Q j).card : ℝ≥0∞) ^ (1 - p / P) *
        (∑ R ∈ descendantsAtDepth H (a + j),
          (ENNReal.ofReal |cubeAverage R f|) ^ P) ^ (p / P) := by
  have hsubset : descendantsAtDepth Q j ⊆ descendantsAtDepth H (a + j) := by
    intro R hR
    exact mem_descendantsAtDepth_add hQ hR
  refine (sum_rpow_le_card_rpow_mul_sum_rpow (descendantsAtDepth Q j)
    (fun R => ENNReal.ofReal |cubeAverage R f|) hp hpP).trans ?_
  apply mul_le_mul_right
  apply ENNReal.rpow_le_rpow
  · exact Finset.sum_le_sum_of_subset_of_nonneg
      (f := fun R => (ENNReal.ofReal |cubeAverage R f|) ^ P)
      hsubset (fun _ _ _ => zero_le _)
  · exact div_nonneg hp.le (hp.trans hpP).le

/-- The normalized exact-circ depth average on a descendant has precisely the
cardinality-ratio loss against the shifted parent depth. -/
theorem exactCircDepthAverage_descendant_rpow_le {d : ℕ}
    {H Q : TriadicCube d} {a j : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    (exactCircDepthAverage Q p f (ExactCircIntegrable.descendant hf hQ) j) ^ p⁻¹ ≤
      (((descendantsAtDepth H (a + j)).card : ℝ≥0∞) /
        ((descendantsAtDepth Q j).card : ℝ≥0∞)) ^ P⁻¹ *
      (exactCircDepthAverage H P f hf (a + j)) ^ P⁻¹ := by
  let n : ℝ≥0∞ := (descendantsAtDepth Q j).card
  let N : ℝ≥0∞ := (descendantsAtDepth H (a + j)).card
  let A : ℝ≥0∞ := ∑ R ∈ descendantsAtDepth H (a + j),
    (ENNReal.ofReal |cubeAverage R f|) ^ P
  have hn : n ≠ 0 := by
    dsimp [n]
    exact_mod_cast Finset.card_ne_zero.mpr (descendantsAtDepth_nonempty Q j)
  have hN : N ≠ 0 := by
    dsimp [N]
    exact_mod_cast Finset.card_ne_zero.mpr (descendantsAtDepth_nonempty H (a + j))
  have hnTop : n ≠ ∞ := by
    dsimp [n]
    exact ENNReal.natCast_ne_top _
  have hNTop : N ≠ ∞ := by
    dsimp [N]
    exact ENNReal.natCast_ne_top _
  have hraw := sum_blockMean_rpow_descendant_le (j := j) f hQ hp hpP
  rw [exactCircDepthAverage_eq_cubeAverage, exactCircDepthAverage_eq_cubeAverage]
  have hmul :
      n⁻¹ * (∑ R ∈ descendantsAtDepth Q j,
        (ENNReal.ofReal |cubeAverage R f|) ^ p) ≤
        n⁻¹ * (n ^ (1 - p / P) * A ^ (p / P)) :=
    mul_le_mul_right hraw n⁻¹
  have hpow := ENNReal.rpow_le_rpow hmul (inv_nonneg.mpr hp.le)
  rw [normalized_holder_power_eq_parent n N A p P hn hnTop hN hNTop hp
    (hp.trans hpP)] at hpow
  have hchildSum :
      (descendantsAtDepth Q j).attach.sum (fun R =>
        (ENNReal.ofReal |cubeAverage R.1 f|) ^ p) =
      ∑ R ∈ descendantsAtDepth Q j, (ENNReal.ofReal |cubeAverage R f|) ^ p :=
    Finset.sum_attach (descendantsAtDepth Q j)
      (fun R => (ENNReal.ofReal |cubeAverage R f|) ^ p)
  have hparentSum :
      (descendantsAtDepth H (a + j)).attach.sum (fun R =>
        (ENNReal.ofReal |cubeAverage R.1 f|) ^ P) = A := by
    exact Finset.sum_attach (descendantsAtDepth H (a + j))
      (fun R => (ENNReal.ofReal |cubeAverage R f|) ^ P)
  rw [hchildSum, hparentSum]
  simpa only [n, N, A] using hpow

/-- The shifted-parent/child descendant-card ratio is the exact triadic
volume ratio; it is independent of the fine depth `j`. -/
theorem descendantsAtDepth_card_ratio {d : ℕ} (H Q : TriadicCube d)
    (a j : ℕ) :
    ((descendantsAtDepth H (a + j)).card : ℝ≥0∞) /
        ((descendantsAtDepth Q j).card : ℝ≥0∞) =
      (3 : ℝ≥0∞) ^ (d * a : ℕ) := by
  rw [descendantsAtDepth_card, descendantsAtDepth_card]
  push_cast
  rw [pow_add, ENNReal.mul_div_cancel_right]
  · rw [← pow_mul]
  · positivity
  · exact ENNReal.pow_ne_top (by norm_num)

/-- Exact spatial Hölder at one depth, with the manuscript's precise
`3^(d*a/P)` loss. -/
theorem exactCircDepthAverage_descendant_rpow_le_three {d : ℕ}
    {H Q : TriadicCube d} {a j : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    (exactCircDepthAverage Q p f (ExactCircIntegrable.descendant hf hQ) j) ^ p⁻¹ ≤
      (3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
        (exactCircDepthAverage H P f hf (a + j)) ^ P⁻¹ := by
  have h := exactCircDepthAverage_descendant_rpow_le (j := j) hf hQ hp hpP
  rw [descendantsAtDepth_card_ratio H Q a j] at h
  convert h using 1
  rw [← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]
  congr 1
  norm_cast

/-- Exact shift of the source depth weight along a descendant chain. -/
theorem exactCircDepthWeight_descendant_shift {d : ℕ} {H Q : TriadicCube d}
    {a j : ℕ} (hQ : Q ∈ descendantsAtDepth H a) (s σ : ℝ) :
    exactCircDepthWeight Q s j =
      (3 : ℝ≥0∞) ^
          (((exactCircSourceDepth Q j : ℤ) : ℝ) * (s - σ)) *
        exactCircDepthWeight H σ (a + j) := by
  unfold exactCircDepthWeight
  rw [← ENNReal.rpow_add]
  · congr 1
    have hscale := scale_eq_sub_of_mem_descendantsAtDepth hQ
    unfold exactCircSourceDepth
    push_cast
    rw [hscale]
    push_cast
    ring
  · norm_num
  · norm_num

/-- The exterior source-scale normalization turns the weight shift into a
literal geometric factor in the fine depth. -/
theorem exactCircDepthWeight_normalized_descendant_shift {d : ℕ}
    {H Q : TriadicCube d} {a j : ℕ}
    (hQ : Q ∈ descendantsAtDepth H a) (s σ : ℝ) :
    (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) * exactCircDepthWeight Q s j =
      ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
        ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
          exactCircDepthWeight H σ (a + j)) := by
  rw [exactCircDepthWeight_descendant_shift hQ]
  have hcoeff :
      (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) *
          (3 : ℝ≥0∞) ^ (((exactCircSourceDepth Q j : ℤ) : ℝ) * (s - σ)) =
        ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
          (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) := by
    simp only [← ENNReal.rpow_natCast, ← ENNReal.rpow_mul]
    rw [← ENNReal.rpow_add, ← ENNReal.rpow_add]
    · congr 1
      unfold exactCircSourceDepth
      push_cast
      ring
    all_goals norm_num
  rw [← mul_assoc, hcoeff]
  ac_rfl

/-- Pointwise normalized exact-circ depth-term restriction. -/
theorem exactCircDepthTerm_normalized_descendant_le {d : ℕ}
    {H Q : TriadicCube d} {a j : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {s σ p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) *
        exactCircDepthTerm Q s p f (ExactCircIntegrable.descendant hf hQ) j ≤
      (3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
        ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
        ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
          exactCircDepthTerm H σ P f hf (a + j)) := by
  rw [exactCircDepthTerm_eq, exactCircDepthTerm_eq]
  rw [← mul_assoc, exactCircDepthWeight_normalized_descendant_shift hQ]
  calc
    ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
          ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
            exactCircDepthWeight H σ (a + j)) *
        (exactCircDepthAverage Q p f (ExactCircIntegrable.descendant hf hQ) j) ^ p⁻¹ ≤
      ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
          ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
            exactCircDepthWeight H σ (a + j)) *
        ((3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
          (exactCircDepthAverage H P f hf (a + j)) ^ P⁻¹) := by
      gcongr
      exact exactCircDepthAverage_descendant_rpow_le_three (j := j) hf hQ hp hpP
    _ = _ := by ac_rfl

/-- The `p`-power sum of normalized child depth terms is bounded by the
geometrically weighted shifted parent sequence, with the exact spatial loss. -/
theorem tsum_exactCircDepthTerm_normalized_descendant_rpow_le {d : ℕ}
    {H Q : TriadicCube d} {a : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {s σ p P : ℝ} (hp : 0 < p) (hpP : p < P) :
    ∑' j : ℕ, ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) *
      exactCircDepthTerm Q s p f (ExactCircIntegrable.descendant hf hQ) j) ^ p ≤
      ∑' j : ℕ, ((3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
        ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ j *
        ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
          exactCircDepthTerm H σ P f hf (a + j))) ^ p := by
  apply ENNReal.tsum_le_tsum
  intro j
  exact ENNReal.rpow_le_rpow
    (exactCircDepthTerm_normalized_descendant_le (j := j) hf hQ hp hpP) hp.le

/-- Exact identification of the normalized depth sequence with the paper
finite circ norm on the diagonal `q=p`. -/
theorem normalized_depth_tsum_eq_negativeBesovCircFinite {d : ℕ}
    (P : ExactCircFiniteParameters) (Q : TriadicCube d) (f : Vec d → ℝ)
    (hf : ExactCircIntegrable Q f) (hdiag : P.q = P.p) :
    (ENNReal.ofReal P.s) ^ P.p⁻¹ *
        (∑' j : ℕ, ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * P.s)) *
          exactCircDepthTerm Q P.s P.p f hf j) ^ P.p) ^ P.p⁻¹ =
      (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * P.s)) *
        SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite P Q f hf := by
  rw [ennrealTsum_const_mul_rpow _ _ _
    (lt_of_lt_of_le zero_lt_one P.p_one_le)]
  unfold SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
  change _ = (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * P.s)) *
    ((ENNReal.ofReal P.s) ^ P.q⁻¹ * exactCircFiniteSeminorm P Q f hf)
  rw [exactCircFiniteSeminorm_eq, hdiag]
  ac_rfl

/-- Finite-exponent local Besov restriction, in the equivalent child-scale
form.  The displayed constant is dimension-free and remains meaningful for
infinite norm values. -/
theorem negativeBesovCircFinite_descendant_le {d : ℕ}
    {H Q : TriadicCube d} {a : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {s σ p P : ℝ} (hs : 0 < s) (hs1 : s < 1) (hσ : 0 < σ)
    (hσs : σ < s) (hp1 : 1 ≤ p) (hpP : p < P) :
    (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) *
        SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
          (exactCircDiagonalParameters s p hs hs1 hp1) Q f
          (ExactCircIntegrable.descendant hf hQ) ≤
      (ENNReal.ofReal s) ^ p⁻¹ * (ENNReal.ofReal σ) ^ (-P⁻¹) *
        ((1 - ((3 : ℝ≥0∞) ^ (-(s - σ))) ^
          (p * P / (P - p)))⁻¹) ^ ((P - p) / (p * P)) *
        (3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
        ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
          SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
            (exactCircDiagonalParameters σ P hσ (hσs.trans hs1)
              (hp1.trans hpP.le)) H f hf) := by
  let Pc := exactCircDiagonalParameters s p hs hs1 hp1
  let Pg := exactCircDiagonalParameters σ P hσ (hσs.trans hs1) (hp1.trans hpP.le)
  let cS : ℝ≥0∞ := (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s))
  let cG : ℝ≥0∞ := (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ))
  let K : ℝ≥0∞ := (3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P)
  let ρ : ℝ≥0∞ := (3 : ℝ≥0∞) ^ (-(s - σ))
  let G : ℝ≥0∞ := ((1 - ρ ^ (p * P / (P - p)))⁻¹) ^
    ((P - p) / (p * P))
  have hp : 0 < p := lt_of_lt_of_le zero_lt_one hp1
  have hsum := tsum_exactCircDepthTerm_normalized_descendant_rpow_le
    (s := s) (σ := σ) (p := p) (P := P) hf hQ hp hpP
  have hroot := ENNReal.rpow_le_rpow hsum (inv_nonneg.mpr hp.le)
  simp only [mul_assoc] at hroot
  rw [ennrealTsum_const_mul_rpow K
    (fun j => ρ ^ (j : ℕ) *
      (cG * exactCircDepthTerm H σ P f hf (a + j))) p hp] at hroot
  have hgeom := ennreal_geometric_weighted_lp_le_larger ρ
    (fun j => cG * exactCircDepthTerm H σ P f hf (a + j)) hp hpP
  have htail :
      (∑' j : ℕ, (cG * exactCircDepthTerm H σ P f hf (a + j)) ^ P) ^ P⁻¹ ≤
        cG * (∑' j : ℕ, (exactCircDepthTerm H σ P f hf j) ^ P) ^ P⁻¹ := by
    rw [ennrealTsum_const_mul_rpow cG
      (fun j => exactCircDepthTerm H σ P f hf (a + j)) P (hp.trans hpP)]
    apply mul_le_mul_right
    apply ENNReal.rpow_le_rpow
    · exact ennrealTsum_nat_add_le a
        (fun j => (exactCircDepthTerm H σ P f hf j) ^ P)
    · exact inv_nonneg.mpr (hp.trans hpP).le
  have hcore :
      (∑' j : ℕ, (cS * exactCircDepthTerm Q s p f
        (ExactCircIntegrable.descendant hf hQ) j) ^ p) ^ p⁻¹ ≤
        K * G * cG *
          (∑' j : ℕ, (exactCircDepthTerm H σ P f hf j) ^ P) ^ P⁻¹ := by
    calc
      _ ≤ K * (∑' j : ℕ, (ρ ^ (j : ℕ) *
          (cG * exactCircDepthTerm H σ P f hf (a + j))) ^ p) ^ p⁻¹ := hroot
      _ ≤ K * (G * (∑' j : ℕ,
          (cG * exactCircDepthTerm H σ P f hf (a + j)) ^ P) ^ P⁻¹) :=
        mul_le_mul_right hgeom K
      _ ≤ K * (G * (cG * (∑' j : ℕ,
          (exactCircDepthTerm H σ P f hf j) ^ P) ^ P⁻¹)) := by gcongr
      _ = _ := by ac_rfl
  have hscaled := mul_le_mul_right hcore ((ENNReal.ofReal s) ^ p⁻¹)
  have hchild := normalized_depth_tsum_eq_negativeBesovCircFinite
    Pc Q f (ExactCircIntegrable.descendant hf hQ) rfl
  have hσ0 : (ENNReal.ofReal σ) ^ P⁻¹ ≠ 0 := by positivity
  have hσtop : (ENNReal.ofReal σ) ^ P⁻¹ ≠ ∞ := by
    exact ENNReal.rpow_ne_top_of_nonneg (inv_nonneg.mpr (hp.trans hpP).le)
      ENNReal.ofReal_ne_top
  dsimp [Pc, Pg, cS, cG, K, ρ, G] at hchild hscaled ⊢
  rw [← hchild]
  calc
    _ ≤ (ENNReal.ofReal s) ^ p⁻¹ *
        ((3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
          (((1 - ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ (p * P / (P - p)))⁻¹) ^
            ((P - p) / (p * P)) *
          ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
            (∑' j : ℕ, (exactCircDepthTerm H σ P f hf j) ^ P) ^ P⁻¹))) := by
        simpa only [mul_assoc] using hscaled
    _ = _ := by
      unfold SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
      simp only [exactCircDiagonalParameters_s, exactCircDiagonalParameters_q]
      rw [Homogenization.Book.Ch01.circNegativeBesovFiniteSeminorm_eq]
      have hcancel : (ENNReal.ofReal σ) ^ (-P⁻¹) *
          (ENNReal.ofReal σ) ^ P⁻¹ = 1 := by
        rw [← ENNReal.rpow_add _ _ (by positivity) ENNReal.ofReal_ne_top]
        ring_nf
        exact ENNReal.rpow_zero
      symm
      calc
        _ = ((ENNReal.ofReal σ) ^ (-P⁻¹) * (ENNReal.ofReal σ) ^ P⁻¹) *
            (ENNReal.ofReal s) ^ p⁻¹ *
              (((1 - ((3 : ℝ≥0∞) ^ (-(s - σ))) ^ (p * P / (P - p)))⁻¹) ^
                ((P - p) / (p * P)) *
              ((3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) *
                ((3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
                  (∑' j : ℕ, (exactCircDepthTerm H σ P f hf j) ^ P) ^ P⁻¹))) := by
              ac_rfl
        _ = _ := by rw [hcancel, one_mul]; ac_rfl

/-- Conversion of child-scale normalization to the manuscript's parent-scale
factor. -/
theorem three_rpow_childScale_eq_parentScale {d : ℕ} {H Q : TriadicCube d}
    {a : ℕ} (hQ : Q ∈ descendantsAtDepth H a) (σ : ℝ) :
    (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * σ)) =
      (3 : ℝ≥0∞) ^ ((a : ℝ) * σ) *
        (3 : ℝ≥0∞) ^ (-((H.scale : ℝ) * σ)) := by
  rw [← ENNReal.rpow_add]
  · congr 1
    rw [scale_eq_sub_of_mem_descendantsAtDepth hQ]
    push_cast
    ring
  · norm_num
  · norm_num

/-- Finite-exponent local Besov restriction in the source parent-scale form. -/
theorem negativeBesovCircFinite_descendant_le_source {d : ℕ}
    {H Q : TriadicCube d} {a : ℕ} {f : Vec d → ℝ}
    (hf : ExactCircIntegrable H f) (hQ : Q ∈ descendantsAtDepth H a)
    {s σ p P : ℝ} (hs : 0 < s) (hs1 : s < 1) (hσ : 0 < σ)
    (hσs : σ < s) (hp1 : 1 ≤ p) (hpP : p < P) :
    (3 : ℝ≥0∞) ^ (-((Q.scale : ℝ) * s)) *
        SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
          (exactCircDiagonalParameters s p hs hs1 hp1) Q f
          (ExactCircIntegrable.descendant hf hQ) ≤
      (ENNReal.ofReal s) ^ p⁻¹ * (ENNReal.ofReal σ) ^ (-P⁻¹) *
        ((1 - ((3 : ℝ≥0∞) ^ (-(s - σ))) ^
          (p * P / (P - p)))⁻¹) ^ ((P - p) / (p * P)) *
        (3 : ℝ≥0∞) ^ ((σ + (d : ℝ) / P) * (a : ℝ)) *
        ((3 : ℝ≥0∞) ^ (-((H.scale : ℝ) * σ)) *
          SubdiffusiveProcess.CoarseGrainingVocab.negativeBesovCircFinite
            (exactCircDiagonalParameters σ P hσ (hσs.trans hs1)
              (hp1.trans hpP.le)) H f hf) := by
  have h := negativeBesovCircFinite_descendant_le hf hQ hs hs1 hσ hσs hp1 hpP
  rw [three_rpow_childScale_eq_parentScale hQ σ] at h
  have hfac : (3 : ℝ≥0∞) ^ ((d : ℝ) * (a : ℝ) / P) *
      (3 : ℝ≥0∞) ^ ((a : ℝ) * σ) =
      (3 : ℝ≥0∞) ^ ((σ + (d : ℝ) / P) * (a : ℝ)) := by
    rw [← ENNReal.rpow_add]
    · congr 1
      ring
    · norm_num
    · norm_num
  calc
    _ ≤ _ := h
    _ = _ := by rw [← hfac]; ac_rfl

end SubdiffusiveProcess.Section9
