module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section6SmallContrast.Schauder

@[expose] public section

/-!
# A dimension-dependent admissible multiplier contrast

The theorem leaves `epsilonStar` to be chosen.  This file makes a
positive choice for which the combined cutoff/multiplier contrast lies below
the proved Schauder threshold at exponent `1/2`.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section6BoundedMultiplier

open SubdiffusiveProcess.CoarseGrainingVocab.Section6SmallContrast

noncomputable section

/-- Chosen multiplier contrast for the Moser-free local step. -/
def boundedMultiplierEpsilonStar (d : ℕ) : ℝ :=
  min (1 / 4) (Real.log (1 + smallContrastThreshold d (1 / 2)) / 2)

theorem smallContrastThreshold_half_pos (d : ℕ) :
    0 < smallContrastThreshold d (1 / 2) := by
  unfold smallContrastThreshold
  positivity

theorem boundedMultiplierEpsilonStar_pos (d : ℕ) :
    0 < boundedMultiplierEpsilonStar d := by
  apply lt_min (by norm_num)
  have ht := smallContrastThreshold_half_pos d
  have hlog : 0 < Real.log (1 + smallContrastThreshold d (1 / 2)) :=
    Real.log_pos (by linarith)
  positivity

theorem boundedMultiplierEpsilonStar_le_quarter (d : ℕ) :
    boundedMultiplierEpsilonStar d ≤ 1 / 4 :=
  min_le_left _ _

/-- The explicit scalar contrast generated by cutoff oscillation and the
multiplier perturbation is admissible for `smallContrastSchauder`. -/
theorem boundedMultiplier_combinedContrast_le_threshold (d : ℕ) :
    Real.exp (boundedMultiplierEpsilonStar d) *
          (1 + boundedMultiplierEpsilonStar d) - 1 ≤
      smallContrastThreshold d (1 / 2) := by
  let epsilon := boundedMultiplierEpsilonStar d
  let t := smallContrastThreshold d (1 / 2)
  have heps0 : 0 ≤ epsilon := (boundedMultiplierEpsilonStar_pos d).le
  have hepsLog : epsilon ≤ Real.log (1 + t) / 2 := min_le_right _ _
  have honeExp : 1 + epsilon ≤ Real.exp epsilon :=
    by simpa [add_comm] using Real.add_one_le_exp epsilon
  have hexp0 : 0 ≤ Real.exp epsilon := (Real.exp_pos _).le
  have hprod : Real.exp epsilon * (1 + epsilon) ≤
      Real.exp epsilon * Real.exp epsilon :=
    mul_le_mul_of_nonneg_left honeExp hexp0
  have htwo : 2 * epsilon ≤ Real.log (1 + t) := by linarith
  have ht : 0 < t := smallContrastThreshold_half_pos d
  have hexpLog : Real.exp (2 * epsilon) ≤ 1 + t := by
    calc
      Real.exp (2 * epsilon) ≤ Real.exp (Real.log (1 + t)) :=
        Real.exp_le_exp.mpr htwo
      _ = 1 + t := Real.exp_log (by linarith)
  have hexpMul : Real.exp epsilon * Real.exp epsilon =
      Real.exp (2 * epsilon) := by
    rw [← Real.exp_add]
    congr 1
    ring
  dsimp only [epsilon, t] at *
  rw [hexpMul] at hprod
  linarith

theorem boundedMultiplier_combinedContrast_nonneg (d : ℕ) :
    0 ≤ Real.exp (boundedMultiplierEpsilonStar d) *
          (1 + boundedMultiplierEpsilonStar d) - 1 := by
  have hExp := Real.add_one_le_exp (boundedMultiplierEpsilonStar d)
  have hpos := boundedMultiplierEpsilonStar_pos d
  have hexpOne : 1 ≤ Real.exp (boundedMultiplierEpsilonStar d) := by
    linarith
  nlinarith [Real.exp_pos (boundedMultiplierEpsilonStar d)]

theorem boundedMultiplier_combinedContrast_lt_one (d : ℕ) :
    Real.exp (boundedMultiplierEpsilonStar d) *
          (1 + boundedMultiplierEpsilonStar d) - 1 < 1 := by
  exact (boundedMultiplier_combinedContrast_le_threshold d).trans_lt
    ((smallContrastThreshold_lt_half d (by norm_num) (by norm_num)).trans
      (by norm_num))

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section6BoundedMultiplier
