module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation.BoundaryPhysicalCarrier
public import SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation.BoundaryCombinedSignedLocalizedStep
public import SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation.BoundaryAffineParentBudget

@[expose] public section

/-!
# Localized three-quarter step with the physical low-frequency carrier

This module performs the finite profile bookkeeping after the physical-carrier
replacement.  The canonical affine lift is kept outside the inverse-gap
budget.  The resulting coefficients are the literal ones obtained from the
signed weak-energy row and the correction estimate.

The affine-external radius step retains the scalar-cutoff energy rows explicitly for the GMC good event.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation

open SubdiffusiveProcess.CoarseGrainingVocab Homogenization Homogenization.Book
open Homogenization.Book.Ch03 MeasureTheory
open scoped ENNReal

noncomputable section

variable {d : ℕ} [NeZero d]

omit [NeZero d] in
/-- Subtracting a zero-force solution preserves the forcing in the weak
equation. -/
theorem isDivFormWeakSolutionOn_sub_zero
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
    (Q : TriadicCube d) (u v : H1Function (openCubeSet Q))
    (g : Vec d → Vec d)
    (hu : IsDivFormWeakSolutionOn
      (_root_.SubdiffusiveProcess.Model.aCutoff M L omega) (openCubeSet Q) u g)
    (hv : IsDivFormWeakSolutionOn
      (_root_.SubdiffusiveProcess.Model.aCutoff M L omega) (openCubeSet Q) v (fun _ ↦ 0)) :
    IsDivFormWeakSolutionOn
      (_root_.SubdiffusiveProcess.Model.aCutoff M L omega) (openCubeSet Q) (u - v) g := by
  intro phi
  let fu : Vec d → ℝ := fun x ↦
    vecDot ((_root_.SubdiffusiveProcess.Model.aCutoff M L omega x) • u.grad x)
      (phi.toH1Function.grad x)
  let fv : Vec d → ℝ := fun x ↦
    vecDot ((_root_.SubdiffusiveProcess.Model.aCutoff M L omega x) • v.grad x)
      (phi.toH1Function.grad x)
  have hfu : IntegrableOn fu (openCubeSet Q) :=
    integrableOn_vecDot_of_memVectorL2
      (memVectorL2_aCutoff_smul_grad M L omega Q u)
      phi.toH1Function.grad_memVectorL2
  have hfv : IntegrableOn fv (openCubeSet Q) :=
    integrableOn_vecDot_of_memVectorL2
      (memVectorL2_aCutoff_smul_grad M L omega Q v)
      phi.toH1Function.grad_memVectorL2
  have hleft : ∫ x in openCubeSet Q,
      vecDot ((_root_.SubdiffusiveProcess.Model.aCutoff M L omega x) • (u - v).grad x)
        (phi.toH1Function.grad x) ∂volume =
      ∫ x in openCubeSet Q, fu x - fv x ∂volume := by
    apply integral_congr_ae
    filter_upwards with x
    simp only [fu, fv, H1Function.sub_grad, smul_sub, vecDot, Pi.sub_apply]
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro i _
    ring
  rw [hleft, integral_sub hfu hfv, hu phi, hv phi]
  simp [vecDot]

omit [NeZero d] in
/-- Symmetric two-term square bound. -/
theorem vecNormSq_sub_le_two_add_two (x y : Vec d) :
    vecNormSq (x - y) ≤ 2 * vecNormSq x + 2 * vecNormSq y := by
  unfold vecNormSq vecDot
  rw [Finset.mul_sum, Finset.mul_sum]
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_le_sum
  intro i _
  have hs : 0 ≤ (x i + y i) ^ 2 := sq_nonneg _
  simp only [Pi.sub_apply]
  nlinarith only [hs]

omit [NeZero d] in
/-- Exact linearity for the energy combination generated by the physical
finite-height cap. -/
theorem boundaryCrossScaleEnergyProfile_physicalCombined_eq
    (Q R : TriadicCube d) (center : Vec d) (rho : ℝ)
    (Eu Ev Eh : Vec d → ℝ)
    (hu : IntegrableOn Eu (openCubeSet Q))
    (hv : IntegrableOn Ev (openCubeSet Q))
    (hh : IntegrableOn Eh (openCubeSet Q)) :
    boundaryCrossScaleEnergyProfile Q R center rho
        (fun x ↦ Eu x + (1 / 2 : ℝ) * Ev x + (1 / 2 : ℝ) * Eh x) =
      boundaryCrossScaleEnergyProfile Q R center rho Eu +
        (1 / 2 : ℝ) * boundaryCrossScaleEnergyProfile Q R center rho Ev +
        (1 / 2 : ℝ) * boundaryCrossScaleEnergyProfile Q R center rho Eh := by
  let P := coarseCaccioppoliLocalClosedCube R center rho
  have hPm : MeasurableSet P :=
    measurableSet_coarseCaccioppoliLocalClosedCube R center rho
  have huP : IntegrableOn (P.indicator Eu) (openCubeSet Q) := hu.indicator hPm
  have hvP : IntegrableOn (P.indicator Ev) (openCubeSet Q) := hv.indicator hPm
  have hhP : IntegrableOn (P.indicator Eh) (openCubeSet Q) := hh.indicator hPm
  have hfun : P.indicator
      (fun x ↦ Eu x + (1 / 2 : ℝ) * Ev x + (1 / 2 : ℝ) * Eh x) =
      fun x ↦ P.indicator Eu x + (1 / 2 : ℝ) * P.indicator Ev x +
        (1 / 2 : ℝ) * P.indicator Eh x := by
    funext x
    by_cases hx : x ∈ P <;>
      simp [Set.indicator_of_mem, Set.indicator_of_notMem, hx]
  unfold boundaryCrossScaleEnergyProfile
  rw [show coarseCaccioppoliLocalClosedCube R center rho = P by rfl, hfun]
  change volumeAverage (openCubeSet Q)
      (((P.indicator Eu) + (1 / 2 : ℝ) • (P.indicator Ev)) +
        (1 / 2 : ℝ) • (P.indicator Eh)) = _
  calc
    _ = volumeAverage (openCubeSet Q)
          ((P.indicator Eu) + (1 / 2 : ℝ) • (P.indicator Ev)) +
        volumeAverage (openCubeSet Q) ((1 / 2 : ℝ) • (P.indicator Eh)) :=
      volumeAverage_add (huP.add (by
        simpa only [Pi.smul_apply, smul_eq_mul] using!
          hvP.const_mul (1 / 2 : ℝ))) (by
        simpa only [Pi.smul_apply, smul_eq_mul] using!
          hhP.const_mul (1 / 2 : ℝ))
    _ = _ := by
      rw [volumeAverage_add huP (by
          simpa only [Pi.smul_apply, smul_eq_mul] using!
            hvP.const_mul (1 / 2 : ℝ)),
        volumeAverage_smul, volumeAverage_smul]

omit [NeZero d] in
/-- The scalar-cutoff profile of a difference is bounded by twice the two
individual profiles. -/
theorem boundaryCrossScaleEnergyProfile_aCutoff_sub_le_two_add_two
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
    (Q R : TriadicCube d) (center : Vec d) (rho : ℝ)
    (u v : H1Function (openCubeSet Q)) :
    boundaryCrossScaleEnergyProfile Q R center rho (fun x ↦
        _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq ((u - v).grad x)) ≤
      2 * boundaryCrossScaleEnergyProfile Q R center rho (fun x ↦
          _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (u.grad x)) +
        2 * boundaryCrossScaleEnergyProfile Q R center rho (fun x ↦
          _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (v.grad x)) := by
  let P := coarseCaccioppoliLocalClosedCube R center rho
  let er : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq ((u - v).grad x)
  let eu : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (u.grad x)
  let ev : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (v.grad x)
  have her : IntegrableOn er (openCubeSet Q) := by
    simpa only [er] using! integrableOn_aCutoff_energy M L omega Q (u - v)
  have heu : IntegrableOn eu (openCubeSet Q) := by
    simpa only [eu] using! integrableOn_aCutoff_energy M L omega Q u
  have hev : IntegrableOn ev (openCubeSet Q) := by
    simpa only [ev] using! integrableOn_aCutoff_energy M L omega Q v
  have hpoint : ∀ x ∈ openCubeSet Q,
      P.indicator er x ≤ 2 * P.indicator eu x + 2 * P.indicator ev x := by
    intro x _hx
    by_cases hx : x ∈ P
    · simp only [Set.indicator_of_mem hx, er, eu, ev]
      have h := mul_le_mul_of_nonneg_left (vecNormSq_sub_le_two_add_two
        (u.grad x) (v.grad x))
        (_root_.SubdiffusiveProcess.Model.aCutoff_pos M L omega x).le
      simp only [H1Function.sub_grad]
      nlinarith only [h]
    · simp [Set.indicator_of_notMem hx]
  have hmono := volumeAverage_le_volumeAverage_of_le_on
    (measurableSet_openCubeSet Q)
    (her.indicator (measurableSet_coarseCaccioppoliLocalClosedCube R center rho))
    (((heu.indicator
      (measurableSet_coarseCaccioppoliLocalClosedCube R center rho)).const_mul 2).add
      ((hev.indicator
        (measurableSet_coarseCaccioppoliLocalClosedCube R center rho)).const_mul 2))
    hpoint
  unfold boundaryCrossScaleEnergyProfile
  dsimp only [P, er, eu, ev] at hmono ⊢
  have heuP := heu.indicator
    (measurableSet_coarseCaccioppoliLocalClosedCube R center rho)
  have hevP := hev.indicator
    (measurableSet_coarseCaccioppoliLocalClosedCube R center rho)
  have hsplit : volumeAverage (openCubeSet Q) (fun x ↦
      2 * (coarseCaccioppoliLocalClosedCube R center rho).indicator
          (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
            vecNormSq (u.grad x)) x +
      2 * (coarseCaccioppoliLocalClosedCube R center rho).indicator
          (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
            vecNormSq (v.grad x)) x) =
      2 * volumeAverage (openCubeSet Q)
        ((coarseCaccioppoliLocalClosedCube R center rho).indicator
          (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
            vecNormSq (u.grad x))) +
      2 * volumeAverage (openCubeSet Q)
        ((coarseCaccioppoliLocalClosedCube R center rho).indicator
          (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
            vecNormSq (v.grad x))) := by
    change volumeAverage (openCubeSet Q)
        ((2 : ℝ) • (coarseCaccioppoliLocalClosedCube R center rho).indicator
            (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
              vecNormSq (u.grad x)) +
          (2 : ℝ) • (coarseCaccioppoliLocalClosedCube R center rho).indicator
            (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
              vecNormSq (v.grad x))) = _
    rw [volumeAverage_add (by
        simpa only [Pi.smul_apply, smul_eq_mul] using! heuP.const_mul 2) (by
        simpa only [Pi.smul_apply, smul_eq_mul] using! hevP.const_mul 2),
      volumeAverage_smul, volumeAverage_smul]
  exact hmono.trans_eq hsplit

omit [NeZero d] in
/-- A canonical cutoff main energy is bounded by the corresponding outer
cross-scale profile. -/
theorem volumeAverage_boundaryCoerciveMain_localCanonicalFun_le_outerProfile_aCutoff
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
    (Q : TriadicCube d) (center : Vec d) {rhoInner rhoOuter : ℝ}
    (u : H1Function (openCubeSet Q))
    (hinner : 0 < rhoInner) (hlt : rhoInner < rhoOuter) :
    volumeAverage (openCubeSet Q)
        (boundaryCoerciveMainDensity
          (_root_.SubdiffusiveProcess.Model.aCutoff M L omega)
          (coarseCaccioppoliLocalCanonicalFun Q center rhoInner
            (coarseCaccioppoliBufferedCutoffRadius rhoInner rhoOuter)) u.grad) ≤
      boundaryCrossScaleEnergyProfile Q Q center rhoOuter (fun x ↦
        _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (u.grad x)) := by
  have hbetween := coarseCaccioppoliBufferedCutoffRadius_between hlt
  have henergy := integrableOn_aCutoff_energy M L omega Q u
  have hmain : IntegrableOn (boundaryCoerciveMainDensity
      (_root_.SubdiffusiveProcess.Model.aCutoff M L omega)
      (coarseCaccioppoliLocalCanonicalFun Q center rhoInner
        (coarseCaccioppoliBufferedCutoffRadius rhoInner rhoOuter)) u.grad)
      (openCubeSet Q) := by
    simpa only [boundaryCoerciveMainDensity] using!
      integrableOn_aCutoff_sqCutoff_vecNormSq M L omega u.grad_memVectorL2
        (coarseCaccioppoliLocalCanonicalFun_smooth Q center hinner hbetween.1)
        (coarseCaccioppoliLocalCanonicalFun_hasCompactSupport
          Q center hinner hbetween.1)
  have houter := volumeAverage_boundaryCoerciveMain_localCanonicalFun_le_outerProfile
    hinner hbetween.1
    (fun x _ ↦ (_root_.SubdiffusiveProcess.Model.aCutoff_pos M L omega x).le)
    henergy hmain
  have hmono := boundaryCrossScaleEnergyProfile_mono
    (Q := Q) (R := Q) (center := center) hbetween.2.le
    (fun x _ ↦ mul_nonneg
      (_root_.SubdiffusiveProcess.Model.aCutoff_pos M L omega x).le (vecNormSq_nonneg _))
    henergy
  exact houter.trans hmono

/-- The exact one-step bookkeeping after the physical-carrier replacement.
The affine lift and affine function remain outside the inverse-gap term. -/
theorem exists_boundaryCrossScale_physicalCarrierLocalizedStep
    (d : ℕ) [NeZero d] :
    ∃ C : ℝ, 0 < C ∧
      ∀ (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
        (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
        {Q : TriadicCube d} {s sigma K BE Ag : ℝ} {g : Vec d → Vec d}
        (u h v ell : H1Function (openCubeSet Q)) (center : Vec d)
        {rhoInner rhoOuter : ℝ},
        IsDivFormWeakSolutionOn
          (_root_.SubdiffusiveProcess.Model.aCutoff M L omega) (openCubeSet Q) u g →
        IsDivFormWeakSolutionOn
          (_root_.SubdiffusiveProcess.Model.aCutoff M L omega) (openCubeSet Q) v
            (fun _ ↦ 0) →
        MemVectorL2 (openCubeSet Q) g →
        LocalizedZeroTraceFunctionOn (openCubeSet Q)
          (coarseCaccioppoliLocalOpenCube Q center 1)
          (fun x ↦ u.toFun x - h.toFun x) →
        LocalizedZeroTraceFunctionOn (openCubeSet Q)
          (Set.univ : Set (Vec d)) (fun x ↦ v.toFun x - ell.toFun x) →
        (1 / 3 : ℝ) ≤ rhoInner → rhoInner < rhoOuter → rhoOuter < 1 →
        0 < s → s ≤ 1 / 4 → 0 < sigma → 0 < K → 0 ≤ BE → 0 ≤ Ag →
        sigma⁻¹ * Ch02.LambdaSq Q (s / 6) (.finite 2)
            (aCutoffFamily M L omega) ≤ K →
        sigma * (Ch02.lambdaSq Q (s / 6) (.finite 2)
            (aCutoffFamily M L omega))⁻¹ ≤ K →
        ForceBesovRegularity Q (s / 3) (fun x ↦ -g x) →
        MemLp (u - h).toFun (2 : ℝ≥0∞) (normalizedCubeMeasure Q) →
        MemLp (fun x ↦ HilbertVec.ofVec (-g x)) (2 : ℝ≥0∞)
          (normalizedCubeMeasure Q) →
        (let Eh : TriadicCube d → ℝ := fun S ↦ cubeAverage S
          (coefficientEnergyDensity
            (publicCoeffField S (aCutoffFamily M L omega)) h.grad);
          ∀ k : ℕ, descendantsAverage Q (k + 1) Eh ≤ BE) →
        localizedCoeffEnergyValue (openCubeSet Q)
          ((aCutoffFamily M L omega).coeffOn Q) h ≤ BE →
        volumeAverage (openCubeSet Q)
            (boundaryCoerciveForceDensity
              (_root_.SubdiffusiveProcess.Model.aCutoff M L omega)
              (coarseCaccioppoliLocalCanonicalFun Q center rhoInner
                (coarseCaccioppoliBufferedCutoffRadius rhoInner rhoOuter)) g) ≤ Ag →
        boundaryCrossScaleEnergyProfile Q Q center rhoInner (fun x ↦
            _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (u.grad x)) ≤
          (3 / 4 : ℝ) * boundaryCrossScaleEnergyProfile Q Q center rhoOuter
              (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
                vecNormSq (u.grad x)) +
            (79 / 8 : ℝ) * localizedCoeffEnergyValue (openCubeSet Q)
              ((aCutoffFamily M L omega).coeffOn Q) v +
            (57 / 8 : ℝ) * BE +
            4 * (1 / 8 + (64 * C ^ 4 * K)⁻¹) * BE +
            13 * localizedCoeffEnergyValue (openCubeSet Q)
              ((aCutoffFamily M L omega).coeffOn Q) ell +
            3 * Ag +
            4 * boundaryCommonGapPowerBudget Q s sigma K C 0
              (u - h).toFun (fun x ↦ -g x) *
                Real.rpow (rhoOuter - rhoInner) (-8 : ℝ) := by
  obtain ⟨C, hC, hcap⟩ :=
    exists_abs_affineResidualCombinedPairing_physicalCarrier_triadicGap d
  refine ⟨C, hC, ?_⟩
  intro M L omega Q s sigma K BE Ag g u h v ell center rhoInner rhoOuter
    hweakU hweakV hg hphysical haffine hinner hlt houter hs hs4 hsigma hK hBE hAg
    hupper hlower hreg hphysicalL2 hgL2 hEh hBEfull hforce
  obtain ⟨k, hchoice⟩ :=
    exists_coarseCaccioppoliTriadicGapScaleChoice hinner hlt houter.le
  have hweakR := isDivFormWeakSolutionOn_sub_zero M L omega Q u v g hweakU hweakV
  have haffineLocal : LocalizedZeroTraceFunctionOn (openCubeSet Q)
      (coarseCaccioppoliLocalOpenCube Q center 1)
      (fun x ↦ v.toFun x - ell.toFun x) := by
    intro eta heta hetaCompact hetaSupport
    exact haffine eta heta hetaCompact (hetaSupport.trans (Set.subset_univ _))
  have hzeroRaw := Homogenization.localizedZeroTraceFunctionOn_sub
    hphysical haffineLocal
  have hzero : LocalizedZeroTraceFunctionOn (openCubeSet Q)
      (coarseCaccioppoliLocalOpenCube Q center 1)
      (fun x ↦ (u - v).toFun x - (h - ell).toFun x) := by
    intro eta heta hetaCompact hetaSupport
    have hz := hzeroRaw eta heta hetaCompact hetaSupport
    convert hz using 1
    funext x
    simp only [H1Function.sub_toFun]
    ring
  have hpair := hcap M L omega u h v ell center hweakU hweakV hg haffine
    (lt_of_lt_of_le (by norm_num) hinner) hlt hchoice hs hs4 hsigma hK.le
      hupper hlower hreg hphysicalL2 hgL2 (hEh k)
  have hres :=
    boundaryCrossScaleEnergyProfile_aCutoff_residual_le_threeHalves_physical_add_three_affine
      M L omega Q Q center rhoOuter u (u - v) v
        (fun x ↦ by simp only [H1Function.sub_grad])
  have hhres := boundaryCrossScaleEnergyProfile_aCutoff_sub_le_two_add_two
    M L omega Q Q center rhoOuter h ell
  have hprofV := boundaryCrossScaleEnergyProfile_aCutoff_le_localizedCoeffEnergyValue
    M L omega Q Q center rhoOuter v
  have hprofH0 := boundaryCrossScaleEnergyProfile_aCutoff_le_localizedCoeffEnergyValue
    M L omega Q Q center rhoOuter h
  have hprofH := hprofH0.trans hBEfull
  have hprofEll := boundaryCrossScaleEnergyProfile_aCutoff_le_localizedCoeffEnergyValue
    M L omega Q Q center rhoOuter ell
  have hmainU :=
    volumeAverage_boundaryCoerciveMain_localCanonicalFun_le_outerProfile_aCutoff
      M L omega Q center u (lt_of_lt_of_le (by norm_num) hinner) hlt
  have hmainV :=
    volumeAverage_boundaryCoerciveMain_localCanonicalFun_le_outerProfile_aCutoff
      M L omega Q center v (lt_of_lt_of_le (by norm_num) hinner) hlt
  have hmainEll :=
    volumeAverage_boundaryCoerciveMain_localCanonicalFun_le_outerProfile_aCutoff
      M L omega Q center ell (lt_of_lt_of_le (by norm_num) hinner) hlt
  have hcommonZero := boundaryCommonYoungParentBudgetWeighted_le_gapPowerBudget
    (Q := Q) (S := Classical.choose (descendantsAtDepth_nonempty Q (k + 1)))
    (k := k) (rhoInner := rhoInner) (rhoOuter := rhoOuter) (s := s)
    (sigma := sigma) (K := K) (C := C) (BE := (0 : ℝ))
    (u := (u - h).toFun) (F := fun x ↦ -g x)
    (Classical.choose_spec (descendantsAtDepth_nonempty Q (k + 1)))
    hinner hlt houter.le hchoice hs hs4 hsigma hK hC (by norm_num) hreg
  have hcommonSplit := boundaryCommonYoungParentBudgetWeighted_le_zero_add_fineDatum
    (Q := Q) (k := k) (rhoInner := rhoInner) (rhoOuter := rhoOuter)
    (s := s) (sigma := sigma) (K := K) (C := C) (BE := BE)
    (u := (u - h).toFun) (F := fun x ↦ -g x)
    (lt_of_lt_of_le (by norm_num) hinner) hlt hs hs4 hsigma hK hC hBE
  have hcommon : boundaryCommonYoungParentBudgetWeighted Q k rhoInner rhoOuter
      s sigma K C BE (u - h).toFun (fun x ↦ -g x) ≤
      boundaryCommonGapPowerBudget Q s sigma K C 0
          (u - h).toFun (fun x ↦ -g x) *
        Real.rpow (rhoOuter - rhoInner) (-8 : ℝ) +
      (1 / 8 + (64 * C ^ 4 * K)⁻¹) * BE := by
    linarith only [hcommonZero, hcommonSplit]
  let Eu : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (u.grad x)
  let Ev : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (v.grad x)
  let Eh0 : Vec d → ℝ := fun x ↦
    _root_.SubdiffusiveProcess.Model.aCutoff M L omega x * vecNormSq (h.grad x)
  have hcombined := boundaryCrossScaleEnergyProfile_physicalCombined_eq
    Q Q center rhoOuter Eu Ev Eh0
    (by simpa only [Eu] using! integrableOn_aCutoff_energy M L omega Q u)
    (by simpa only [Ev] using! integrableOn_aCutoff_energy M L omega Q v)
    (by simpa only [Eh0] using! integrableOn_aCutoff_energy M L omega Q h)
  dsimp only [Eu, Ev, Eh0] at hcombined
  dsimp only at hpair
  rw [hcombined] at hpair
  let pairBudget : ℝ :=
    (3 / 8 : ℝ) * boundaryCrossScaleEnergyProfile Q Q center rhoOuter
        (fun x ↦ _root_.SubdiffusiveProcess.Model.aCutoff M L omega x *
          vecNormSq (u.grad x)) +
      (57 / 8 : ℝ) * localizedCoeffEnergyValue (openCubeSet Q)
        ((aCutoffFamily M L omega).coeffOn Q) v +
      (1 / 8 : ℝ) * BE +
      4 * (1 / 8 + (64 * C ^ 4 * K)⁻¹) * BE +
      6 * localizedCoeffEnergyValue (openCubeSet Q)
        ((aCutoffFamily M L omega).coeffOn Q) ell +
      (1 / 2 : ℝ) * Ag +
      4 * boundaryCommonGapPowerBudget Q s sigma K C 0
        (u - h).toFun (fun x ↦ -g x) *
          Real.rpow (rhoOuter - rhoInner) (-8 : ℝ)
  have hpairSimple : |volumeAverage (openCubeSet Q)
      (boundaryCorrectedFluxCutoffPairingDensity
        (_root_.SubdiffusiveProcess.Model.aCutoff M L omega)
        (coarseCaccioppoliLocalCanonicalFun Q center rhoInner
          (coarseCaccioppoliBufferedCutoffRadius rhoInner rhoOuter))
        ((u - v) - (h - ell)).toFun ((u - v) + (2 : ℝ) • v).grad g)| ≤
      pairBudget := by
    dsimp only [pairBudget]
    nlinarith only [hpair, hprofV, hprofH, hmainU, hmainV, hmainEll,
      hprofEll, hforce, hcommon]
  have hsigned := boundaryCrossScale_physical_le_of_combinedSignedPairingBudget
    M L omega Q u (u - v) v (h - ell) g center
    (fun x ↦ by simp only [H1Function.sub_grad]; abel_nf)
    hweakR hweakV hg hzero
    (lt_of_lt_of_le (by norm_num) hinner) hlt houter hforce hpairSimple
  dsimp only [pairBudget] at hsigned
  nlinarith only [hsigned, hres, hhres, hprofV, hprofH, hprofEll,
    hmainU, hmainV, hmainEll, hcommon]

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation
