import SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation.BoundaryFiniteHeightQuantitative

/-!
# A finite-height choice from the actual boundary prefactor

The forced corrected-flux estimate is controlled first by finite-`2`
ellipticity factors.  Those factors dominate the `q = 1` contrast, in the
direction opposite to the one needed to reuse a height chosen from
`ThetaRatio`.  This module therefore makes the equivalent scalar choice
directly from the nonnegative prefactor which has to be absorbed.

This is the logarithmic height calculation used in the manuscript.  It is
kept separate from all PDE and coefficient inputs.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation

open Homogenization

noncomputable section

/-- Real height which makes `2 * P * 3^{-(1-2t)h}` at most `1/8`. -/
noncomputable def boundaryFiniteHeightOfPrefactor (t P : ℝ) : ℝ :=
  max 0
    (Real.log (max 1 (16 * P)) /
      ((1 - 2 * t) * Real.log 3))

theorem boundaryFiniteHeightOfPrefactor_nonneg (t P : ℝ) :
    0 ≤ boundaryFiniteHeightOfPrefactor t P := by
  exact le_max_left _ _

theorem boundaryFiniteHeightOfPrefactor_eq
    {t P : ℝ} (ht : t < 1 / 2) :
    boundaryFiniteHeightOfPrefactor t P =
      Real.log (max 1 (16 * P)) / ((1 - 2 * t) * Real.log 3) := by
  have hlog : 0 ≤ Real.log (max 1 (16 * P)) :=
    Real.log_nonneg (le_max_left _ _)
  have hden : 0 ≤ (1 - 2 * t) * Real.log 3 :=
    mul_nonneg (by linarith) (Real.log_nonneg (by norm_num))
  unfold boundaryFiniteHeightOfPrefactor
  rw [max_eq_right]
  exact div_nonneg hlog hden

/-- The head growth generated by the scalar height is the expected power of
the prefactor. -/
theorem rpow_head_boundaryFiniteHeightOfPrefactor_eq
    {t P : ℝ} (ht : t < 1 / 2) :
    Real.rpow 3 (2 * t * boundaryFiniteHeightOfPrefactor t P) =
      Real.rpow (max 1 (16 * P)) (2 * t / (1 - 2 * t)) := by
  have hA : 0 < max 1 (16 * P) :=
    lt_of_lt_of_le zero_lt_one (le_max_left _ _)
  have hsigma : 0 < 1 - 2 * t := by linarith
  have hlog3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  change (3 : ℝ) ^ (2 * t * boundaryFiniteHeightOfPrefactor t P) =
    (max 1 (16 * P)) ^ (2 * t / (1 - 2 * t))
  rw [boundaryFiniteHeightOfPrefactor_eq ht,
    Real.rpow_def_of_pos (by norm_num : (0 : ℝ) < 3),
    Real.rpow_def_of_pos hA]
  congr 1
  field_simp [hsigma.ne', hlog3.ne']

/-- Sharp finite-head estimate after substituting the prefactor-selected
height. -/
theorem boundaryFiniteHeightHead_heightOfPrefactor_sq_le
    {t P : ℝ} (ht : 0 < t) (ht4 : t ≤ 1 / 4) :
    boundaryFiniteHeightHeadGlobalCoeff t
        (Nat.ceil (boundaryFiniteHeightOfPrefactor t P)) ^ 2 ≤
      6 * t⁻¹ * Real.rpow (max 1 (16 * P)) (2 * t / (1 - 2 * t)) := by
  have htHalf : t < 1 / 2 := by linarith
  have hhead := boundaryFiniteHeightHeadGlobalCoeff_sq_natCeil_le_six_mul_inv
    ht ht4 (boundaryFiniteHeightOfPrefactor_nonneg t P)
  rw [rpow_head_boundaryFiniteHeightOfPrefactor_eq htHalf] at hhead
  exact hhead

/-- At the manuscript specialization `t = s/3`, the height exponent is no
larger than `s`. -/
theorem boundaryHeightExponent_oneThird_le
    {s : ℝ} (hs : 0 ≤ s) (hs4 : s ≤ 1 / 4) :
    2 * (s / 3) / (1 - 2 * (s / 3)) ≤ s := by
  have hden : 0 < 1 - 2 * (s / 3) := by linarith
  rw [div_le_iff₀ hden]
  nlinarith

/-- Printed one-third specialization of the finite head: the rational height
power collapses to a single `s`-power and the front factor becomes
`18 s⁻¹`. -/
theorem boundaryFiniteHeightHead_oneThird_heightOfPrefactor_sq_le
    {s P : ℝ} (hs : 0 < s) (hs4 : s ≤ 1 / 4) :
    boundaryFiniteHeightHeadGlobalCoeff (s / 3)
        (Nat.ceil (boundaryFiniteHeightOfPrefactor (s / 3) P)) ^ 2 ≤
      18 * s⁻¹ * Real.rpow (max 1 (16 * P)) s := by
  have ht : 0 < s / 3 := by positivity
  have ht4 : s / 3 ≤ 1 / 4 := by linarith
  have hbase := boundaryFiniteHeightHead_heightOfPrefactor_sq_le
    (P := P) ht ht4
  have hA : 1 ≤ max 1 (16 * P) := le_max_left _ _
  have hpow : Real.rpow (max 1 (16 * P))
      (2 * (s / 3) / (1 - 2 * (s / 3))) ≤
      Real.rpow (max 1 (16 * P)) s :=
    Real.rpow_le_rpow_of_exponent_le hA
      (boundaryHeightExponent_oneThird_le hs.le hs4)
  have hfront : 0 ≤ 6 * (s / 3)⁻¹ := by positivity
  calc
    boundaryFiniteHeightHeadGlobalCoeff (s / 3)
        (Nat.ceil (boundaryFiniteHeightOfPrefactor (s / 3) P)) ^ 2 ≤
        6 * (s / 3)⁻¹ * Real.rpow (max 1 (16 * P))
          (2 * (s / 3) / (1 - 2 * (s / 3))) := hbase
    _ ≤ 6 * (s / 3)⁻¹ * Real.rpow (max 1 (16 * P)) s :=
      mul_le_mul_of_nonneg_left hpow hfront
    _ = 18 * s⁻¹ * Real.rpow (max 1 (16 * P)) s := by
      field_simp [hs.ne']
      ring

private theorem boundaryFiniteHeightOfPrefactor_log_bound
    {t P : ℝ} (ht : t < 1 / 2) :
    Real.log (max 1 (16 * P)) ≤
      (1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P * Real.log 3 := by
  have hsigma : 0 < 1 - 2 * t := by linarith
  have hlog3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  have hden : 0 < (1 - 2 * t) * Real.log 3 := mul_pos hsigma hlog3
  have hmax :
      Real.log (max 1 (16 * P)) / ((1 - 2 * t) * Real.log 3) ≤
        boundaryFiniteHeightOfPrefactor t P := by
    exact le_max_right _ _
  have hmul := mul_le_mul_of_nonneg_right hmax hden.le
  rw [div_mul_cancel₀ _ hden.ne'] at hmul
  calc
    Real.log (max 1 (16 * P)) ≤
        boundaryFiniteHeightOfPrefactor t P *
          ((1 - 2 * t) * Real.log 3) := hmul
    _ = (1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P * Real.log 3 := by
      ring

private theorem boundaryFiniteHeightOfPrefactor_rpow_bound
    {t P : ℝ} (ht : t < 1 / 2) :
    max 1 (16 * P) ≤
      Real.rpow 3 ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) := by
  have hA : 0 < max 1 (16 * P) :=
    lt_of_lt_of_le zero_lt_one (le_max_left _ _)
  have hexp :
      Real.exp (Real.log (max 1 (16 * P))) ≤
        Real.exp
          ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P * Real.log 3) :=
    Real.exp_le_exp.mpr
      (boundaryFiniteHeightOfPrefactor_log_bound (t := t) (P := P) ht)
  rw [Real.exp_log hA] at hexp
  calc
    max 1 (16 * P) ≤
        Real.exp
          ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P * Real.log 3) :=
      hexp
    _ = Real.rpow 3
        ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) := by
      rw [show (1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P * Real.log 3 =
          Real.log 3 * ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) by
        ring]
      exact (Real.rpow_def_of_pos (by norm_num) _).symm

/-- The selected real height absorbs the bare geometric tail prefactor. -/
theorem mul_rpow_neg_boundaryFiniteHeightOfPrefactor_le_sixteenth
    {t P : ℝ} (ht : t < 1 / 2) :
    P * Real.rpow 3
        (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) ≤ 1 / 16 := by
  have hA := boundaryFiniteHeightOfPrefactor_rpow_bound (t := t) (P := P) ht
  have hP16 : 16 * P ≤ Real.rpow 3
      ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) :=
    (le_max_right (1 : ℝ) (16 * P)).trans hA
  have hpowNeg : 0 ≤ Real.rpow 3
      (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) :=
    Real.rpow_nonneg (by norm_num) _
  have hcancel :
      Real.rpow 3 ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) *
          Real.rpow 3 (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) = 1 := by
    calc
      Real.rpow 3 ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) *
          Real.rpow 3 (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) =
          Real.rpow 3
            ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P +
              (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P)) :=
        (Real.rpow_add (by norm_num : (0 : ℝ) < 3) _ _).symm
      _ = 1 := by ring_nf; simp
  calc
    P * Real.rpow 3
        (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) =
        (1 / 16 : ℝ) *
          ((16 * P) * Real.rpow 3
            (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P)) := by ring
    _ ≤ (1 / 16 : ℝ) *
        (Real.rpow 3 ((1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) *
          Real.rpow 3
            (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P)) := by
      exact mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_right hP16 hpowNeg) (by norm_num)
    _ = 1 / 16 := by rw [hcancel]; ring

/-- Integerizing the prefactor height absorbs the support-safe finite tail. -/
theorem mul_boundaryFiniteHeightTail_heightOfPrefactor_le_eighth
    {t P : ℝ} (hP : 0 ≤ P) (ht : 0 < t) (ht4 : t ≤ 1 / 4) :
    P * boundaryFiniteHeightTailBetweenGlobalCoeff t (1 - t)
        (Nat.ceil (boundaryFiniteHeightOfPrefactor t P)) ≤ 1 / 8 := by
  have htHalf : t < 1 / 2 := by linarith
  have htail := boundaryFiniteHeightTailOneSub_natCeil_le_two_mul
    (t := t) (h := boundaryFiniteHeightOfPrefactor t P) ht4
  have hpow0 : 0 ≤ Real.rpow 3
      (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P) :=
    Real.rpow_nonneg (by norm_num) _
  calc
    P * boundaryFiniteHeightTailBetweenGlobalCoeff t (1 - t)
        (Nat.ceil (boundaryFiniteHeightOfPrefactor t P)) ≤
        P * (2 * Real.rpow 3
          (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P)) :=
      mul_le_mul_of_nonneg_left htail hP
    _ = 2 * (P * Real.rpow 3
        (-(1 - 2 * t) * boundaryFiniteHeightOfPrefactor t P)) := by ring
    _ ≤ 2 * (1 / 16 : ℝ) := by
      exact mul_le_mul_of_nonneg_left
        (mul_rpow_neg_boundaryFiniteHeightOfPrefactor_le_sixteenth
          (P := P) htHalf)
        (by norm_num)
    _ = 1 / 8 := by norm_num

/-- Direct smallness premise required by the support-aware quarter-absorption
theorem.  The height is chosen from the entire coefficient multiplying the
finite tail, so no ellipticity comparison is used in the wrong direction. -/
theorem boundarySupportAware_tail_small_of_heightOfPrefactor
    {t C A xi Kfine : ℝ}
    (hC : 0 ≤ C) (hA : 0 ≤ A) (hxi : 0 ≤ xi) (hKfine : 0 ≤ Kfine)
    (ht : 0 < t) (ht4 : t ≤ 1 / 4) :
    let P := C * A * Real.sqrt 2 * (2 * xi * Kfine)
    let height := Nat.ceil (boundaryFiniteHeightOfPrefactor t P)
    C * A * (Real.sqrt 2 *
      (2 * xi * boundaryFiniteHeightTailBetweenGlobalCoeff t (1 - t) height *
        Kfine)) ≤ 1 / 8 := by
  dsimp only
  let P : ℝ := C * A * Real.sqrt 2 * (2 * xi * Kfine)
  have hP : 0 ≤ P := by
    dsimp [P]
    positivity
  have htail := mul_boundaryFiniteHeightTail_heightOfPrefactor_le_eighth
    hP ht ht4
  dsimp only [P] at htail ⊢
  convert htail using 1
  ring

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section6HarmonicApproximation
