import SubdiffusiveProcess.CoarseGrainingVocab.AnnealedMatrixVariational
import SubdiffusiveProcess.CoarseGrainingVocab.Section5Support.SimplexMeshInduction
import SubdiffusiveProcess.CoarseGrainingVocab.Section5Support.SparseLayerInductionBase




namespace SubdiffusiveProcess.CoarseGrainingVocab.Section5Support

open Homogenization Homogenization.Book Kuhn MeasureTheory ProbabilityTheory Set
open SubdiffusiveProcess.Frozen.Assumptions

noncomputable section

variable {d : ℕ}

/-! ## Coordinates and layer products -/

/-- Every layer whose index lies in `I` is measurable for the block
sigma-algebra `potentialIndexSigma I`. -/
theorem measurable_potentialCoordinate_potentialIndexSigma {I : Set ℕ} {k : ℕ}
    (hk : k ∈ I) :
    Measurable[potentialIndexSigma (d := d) I]
      fun omega : PotentialSample d => omega k := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le k (le_iSup_of_le hk le_rfl)

/-- A single shell factor is measurable for any block containing its layer. -/
theorem measurable_shellFactor_apply_potentialIndexSigma (M : GMCModel d)
    {I : Set ℕ} {k : ℕ} (hk : k ∈ I) (x : Vec d) :
    Measurable[potentialIndexSigma (d := d) I]
      fun omega : PotentialSample d => shellFactor M k omega x :=
  (((PotentialField.measurable_eval x).comp
    (measurable_potentialCoordinate_potentialIndexSigma hk)).sub
      measurable_const).exp

/-- A layer product is measurable for the block sigma-algebra of its own
layers. -/
theorem measurable_layerCoefficient_apply_potentialIndexSigma (M : GMCModel d)
    (S : Finset ℕ) (x : Vec d) :
    Measurable[potentialIndexSigma (d := d) (S : Set ℕ)]
      fun omega : PotentialSample d => layerCoefficient M S omega x :=
  Finset.measurable_prod _ fun k hk =>
    measurable_shellFactor_apply_potentialIndexSigma M (by exact_mod_cast hk) x

/-! ## The cellwise supremum and the continuum minimum of a layer block -/

/-- **The cell weights of a layer block are block measurable.**  This is (M1) of
`DirichletInfimumMeasurability.lean` read on the sub-sigma-algebra. -/
theorem measurable_cellSup_layerCoefficient_potentialIndexSigma (M : GMCModel d)
    (S : Finset ℕ) (T : KuhnCell d) :
    Measurable[potentialIndexSigma (d := d) (S : Set ℕ)]
      fun omega : PotentialSample d => cellSup (layerCoefficient M S omega) T :=
  @measurable_cellSup d (PotentialSample d) (potentialIndexSigma (S : Set ℕ))
    (fun omega => layerCoefficient M S omega) T
    (fun omega => continuous_layerCoefficient M S omega)
    (fun y => measurable_layerCoefficient_apply_potentialIndexSigma M S y)

/-- **The continuum Dirichlet minimum of a layer block is block measurable.**
The whole measurability chain -- countable dense cell samples, the countable
`eps`-optimal slope family, the countable infimum of discrete minima -- is
stated over a bare measurable space, so it applies verbatim to
`potentialIndexSigma`. -/
theorem measurable_dirichletInfOn_layerCoefficient_potentialIndexSigma
    (M : GMCModel d) (S : Finset ℕ) (T : KuhnCell d) (p : Vec d) :
    Measurable[potentialIndexSigma (d := d) (S : Set ℕ)]
      fun omega : PotentialSample d =>
        dirichletInfOn (layerCoefficient M S omega) T.openCarrier p := by
  obtain ⟨n, rfl⟩ : ∃ n : ℕ, d = n + 1 :=
    ⟨d - 1, by have := M.shellPrefix.dimension; omega⟩
  exact @measurable_dirichletInfOn (PotentialSample (n + 1))
    (potentialIndexSigma (S : Set ℕ)) n T.supportCube T.openCarrier
    (fun omega => layerCoefficient M S omega)
    (isOpenBoundedConvexDomain_openCarrier T) T.openCarrier_subset_openCubeSet
    (fun omega => continuous_layerCoefficient M S omega)
    (fun omega x => (layerCoefficient_pos M S omega x).le) p
    (fun V => measurable_cellSup_layerCoefficient_potentialIndexSigma M S V)

/-! ## The sparse block -/

/-- The sigma-algebra generated by the sparse layers `0, R, ..., NR`. -/
def sparseLayerSigma (R N : ℕ) : MeasurableSpace (PotentialSample d) :=
  potentialIndexSigma ((sparseLayerIndices R N : Finset ℕ) : Set ℕ)

/-- **The sub-sigma-algebra factorization of Step 3.**  The quadratic form of the
sparse finite-volume matrix on a triadic cell is measurable with respect to the
sigma-algebra generated by the sparse layer tuple `(g_0, g_R, ..., g_{NR})`
alone. -/
theorem measurable_vecDot_randomSparseMatrix_sparseLayerSigma (M : GMCModel d)
    {R : ℕ} (hR : 0 < R) (N : ℕ) (T : KuhnCell d) (q : Vec d) :
    Measurable[sparseLayerSigma (d := d) R N]
      fun omega : PotentialSample d =>
        vecDot q
          (matVecMul (randomSparseMatrix M R N (kuhnCellDomain T) omega) q) := by
  have hfun : (fun omega : PotentialSample d =>
      vecDot q (matVecMul (randomSparseMatrix M R N (kuhnCellDomain T) omega) q)) =
      fun omega : PotentialSample d =>
        (volume T.openCarrier).toReal⁻¹ *
          dirichletInfOn (layerCoefficient M (sparseLayerIndices R N) omega)
            T.openCarrier q := by
    funext omega
    have hB : sparseLayerCoefficient M R N omega =
        layerCoefficient M (sparseLayerIndices R N) omega :=
      funext fun x => sparseLayerCoefficient_eq_layerCoefficient M hR N omega x
    rw [vecDot_randomSparseMatrix_eq M R N (kuhnCellDomain T) omega q,
      kuhnCellDomain_coe, hB]
  rw [hfun]
  exact (measurable_dirichletInfOn_layerCoefficient_potentialIndexSigma M
    (sparseLayerIndices R N) T q).const_mul _

/-! ## Independence of disjoint blocks, transferred to derived scalars -/

/-- Disjoint layer blocks generate independent sigma-algebras. -/
theorem indep_potentialIndexSigma_of_disjoint' (M : GMCModel d) {I J : Set ℕ}
    (hIJ : Disjoint I J) :
    Indep (potentialIndexSigma (d := d) I) (potentialIndexSigma J)
      M.P.toMeasure :=
  indep_iSup_of_disjoint (fun k => (measurable_potentialCoordinate k).comap_le)
    M.shellPrefix.independent.iIndep hIJ



theorem indepFun_of_potentialIndexSigma_disjoint (M : GMCModel d) {I J : Set ℕ}
    (hIJ : Disjoint I J) {X Y : PotentialSample d → ℝ}
    (hX : Measurable[potentialIndexSigma (d := d) I] X)
    (hY : Measurable[potentialIndexSigma (d := d) J] Y) :
    IndepFun X Y M.P.toMeasure := by
  refine (IndepFun_iff_Indep X Y M.P.toMeasure).2 ?_
  refine indep_of_indep_of_le_right
    (indep_of_indep_of_le_left (indep_potentialIndexSigma_of_disjoint' M hIJ)
      ?_) ?_
  · exact hX.comap_le
  · exact hY.comap_le

/-- The sparse block `{0, R, ..., NR}` and the fresh layer `(N+1)R` are
disjoint. -/
theorem disjoint_sparseLayerIndices_succ {R : ℕ} (hR : 0 < R) (N : ℕ) :
    Disjoint ((sparseLayerIndices R N : Finset ℕ) : Set ℕ) ({(N + 1) * R} : Set ℕ) := by
  refine Set.disjoint_right.2 ?_
  rintro k hk hkS
  rw [Set.mem_singleton_iff] at hk
  subst hk
  simp only [Finset.coe_image, Finset.coe_range, Set.mem_image, Set.mem_Iio,
    sparseLayerIndices] at hkS
  obtain ⟨j, hj, hjk⟩ := hkS
  have : j < N + 1 := hj
  have hlt : j * R < (N + 1) * R := Nat.mul_lt_mul_of_lt_of_le this le_rfl hR
  omega

/-- The continuum minimum of a layer block on an arbitrary open bounded convex
domain inside a triadic cube is block measurable. -/
theorem measurable_dirichletInfOn_layerCoefficient_indexSigma {n0 : ℕ}
    (M : GMCModel (n0 + 1)) (S : Finset ℕ) {Q : TriadicCube (n0 + 1)}
    {U : Set (Vec (n0 + 1))} (hU : IsOpenBoundedConvexDomain U)
    (hUQ : U ⊆ openCubeSet Q) (p : Vec (n0 + 1)) :
    Measurable[potentialIndexSigma (d := n0 + 1) ((S : Finset ℕ) : Set ℕ)]
      fun omega : PotentialSample (n0 + 1) =>
        dirichletInfOn (layerCoefficient M S omega) U p :=
  @measurable_dirichletInfOn (PotentialSample (n0 + 1))
    (potentialIndexSigma (S : Set ℕ)) n0 Q U
    (fun omega => layerCoefficient M S omega) hU hUQ
    (fun omega => continuous_layerCoefficient M S omega)
    (fun omega x => (layerCoefficient_pos M S omega x).le) p
    (fun V => measurable_cellSup_layerCoefficient_potentialIndexSigma M S V)

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section5Support
