import SubdiffusiveProcess.CoarseGrainingVocab.Section6SupportBase

/-- The sigma-field generated by all point evaluations of a random coefficient. -/

def SubdiffusiveProcess.CoarseGrainingVocab.coefficientSigma {d : ℕ} {Ω : Type*}
    (A : Ω → SubdiffusiveProcess.CoarseGrainingVocab.Vec d → ℝ) : MeasurableSpace Ω :=
  ⨆ x : SubdiffusiveProcess.CoarseGrainingVocab.Vec d,
    MeasurableSpace.comap (fun ω ↦ A ω x) (borel ℝ)

