module

public import SubdiffusiveProcess.Probability.ProductLpContraction
public import Mathlib.Probability.Independence.InfinitePi

@[expose] public section

/-!
# Regrouping the integer-indexed layer environment

Source: `lem:band` (Lemma 31). Disjoint restrictions of an infinite product
are independent as whole random elements. Two measure-preserving splits
expose the coarse, retained, and fine blocks. The final theorem consumes the
finite-p product projection bound on the actual integer-indexed product.

The product sigma-field is used before completion, as required for the band
measurability argument. Passing the response construction through completion
and deriving quantitative fine/coarse influence estimates remain separate.
-/

open MeasureTheory ProbabilityTheory
open scoped MeasureTheory ENNReal

namespace SubdiffusiveProcess

variable {I : Type*} {X : I → Type*} [mX : ∀ i, MeasurableSpace (X i)]
    (μ : (i : I) → Measure (X i)) [∀ i, IsProbabilityMeasure (μ i)]

/-- The sigma-field of a restriction is generated by its coordinate evaluations. -/
theorem comap_restrict_eq_iSup (S : Set I) :
    (inferInstance : MeasurableSpace ((i : S) → X i)).comap S.domRestrict =
      ⨆ i ∈ S, (mX i).comap (fun x : (i : I) → X i => x i) := by
  simp only [MeasurableSpace.pi, MeasurableSpace.comap_iSup,
    MeasurableSpace.comap_comp, iSup_subtype]
  rfl

/-- Disjoint infinite coordinate restrictions are independent random elements. -/
theorem indepFun_restrict_infinitePi (S T : Set I) (hST : Disjoint S T) :
    IndepFun S.domRestrict T.domRestrict (Measure.infinitePi μ) := by
  rw [IndepFun_iff_Indep, comap_restrict_eq_iSup, comap_restrict_eq_iSup]
  have hi : iIndepFun (fun i (x : (i : I) → X i) => x i) (Measure.infinitePi μ) :=
    iIndepFun_infinitePi (X := fun _ x => x) (fun _ => measurable_id)
  exact indep_iSup_of_disjoint (fun i => (measurable_pi_apply i).comap_le)
    hi.iIndep hST

/-- Splitting an arbitrary index set into a predicate and its complement preserves product law. -/
theorem measurePreserving_infinitePi_split (p : I → Prop) [DecidablePred p] :
    MeasurePreserving (MeasurableEquiv.piEquivPiSubtypeProd X p) (Measure.infinitePi μ)
      ((Measure.infinitePi fun i : Subtype p => μ i).prod
        (Measure.infinitePi fun i : {i // ¬p i} => μ i)) := by
  refine ⟨(MeasurableEquiv.piEquivPiSubtypeProd X p).measurable, ?_⟩
  have hi := indepFun_restrict_infinitePi μ {i | p i} {i | ¬p i}
    (disjoint_compl_right)
  have hm := (indepFun_iff_map_prod_eq_prod_map_map
    (show AEMeasurable ({i | p i} : Set I).domRestrict (Measure.infinitePi μ) from
      (measurable_pi_iff.mpr (fun _ => measurable_pi_apply _)).aemeasurable)
    (show AEMeasurable ({i | ¬p i} : Set I).domRestrict (Measure.infinitePi μ) from
      (measurable_pi_iff.mpr (fun _ => measurable_pi_apply _)).aemeasurable)).mp hi
  simpa only [Set.domRestrict, Measure.infinitePi_map_restrict'] using! hm

/-- Split at an outer predicate, then split its retained part once more. -/
def threeBlockEquiv (p q : I → Prop) [DecidablePred p] [DecidablePred q] :
    ((i : I) → X i) ≃ᵐ
      (((i : {i : Subtype p // q i}) → X i.1.1) ×
        ((i : {i : Subtype p // ¬q i}) → X i.1.1)) ×
          ((i : {i // ¬p i}) → X i) :=
  (MeasurableEquiv.piEquivPiSubtypeProd X p).trans
    ((MeasurableEquiv.piEquivPiSubtypeProd (fun i : Subtype p => X i)
      (fun i => q i)).prodCongr (MeasurableEquiv.refl _))

/-- The two successive splits preserve the joint product law of the blocks. -/
theorem measurePreserving_infinitePi_threeBlock (p q : I → Prop)
    [DecidablePred p] [DecidablePred q] :
    MeasurePreserving (threeBlockEquiv (X := X) p q) (Measure.infinitePi μ)
      (((Measure.infinitePi fun i : {i : Subtype p // q i} => μ i.1.1).prod
        (Measure.infinitePi fun i : {i : Subtype p // ¬q i} => μ i.1.1)).prod
          (Measure.infinitePi fun i : {i // ¬p i} => μ i)) := by
  exact ((measurePreserving_infinitePi_split (fun i : Subtype p => μ i)
    (fun i => q i)).prod (MeasurePreserving.id _)).comp
      (measurePreserving_infinitePi_split μ p)

/-- At radius H, these are exactly the coarse, middle, and fine index conditions. -/
theorem integer_band_block_conditions (H : ℕ) (j : ℤ) :
    ((j ≤ (H : ℤ) ∧ j < -(H : ℤ)) ↔ j < -(H : ℤ)) ∧
      ((j ≤ (H : ℤ) ∧ ¬j < -(H : ℤ)) ↔ -(H : ℤ) ≤ j ∧ j ≤ (H : ℤ)) ∧
      (¬j ≤ (H : ℤ) ↔ (H : ℤ) < j) := by
  omega

/-- B1 on the actual integer-indexed product, before completion of its sigma-field. -/
theorem infinitePi_integer_band_error_le {Y : ℤ → Type*}
    [∀ j, MeasurableSpace (Y j)] (laws : (j : ℤ) → Measure (Y j))
    [∀ j, IsProbabilityMeasure (laws j)] (H : ℕ)
    {r : ℝ≥0∞} (hr : 1 ≤ r) (hr_top : r ≠ ∞)
    {f : ((j : ℤ) → Y j) → ℝ} (hf : Integrable f (Measure.infinitePi laws)) :
    let e := threeBlockEquiv (X := Y) (fun j : ℤ => j ≤ (H : ℤ))
      (fun j => j < -(H : ℤ))
    eLpNorm (f - (Measure.infinitePi laws)[f | middleSigma.comap e]) r
        (Measure.infinitePi laws) ≤
      eLpNorm (f - (Measure.infinitePi laws)[f | leftMiddleSigma.comap e]) r
        (Measure.infinitePi laws) +
      eLpNorm (f - (Measure.infinitePi laws)[f | middleRightSigma.comap e]) r
        (Measure.infinitePi laws) := by
  dsimp only
  exact product_condExp_error_eLpNorm_equiv_le _
    (measurePreserving_infinitePi_threeBlock laws _ _) hr hr_top hf

end SubdiffusiveProcess

namespace SubdiffusiveProcess

/-- Integer index reversal transports the entire product law and reverses each marginal.
No equality of different layer laws or stationarity under index shifts is assumed. -/
theorem measurePreserving_infinitePi_neg
    {X : Type*} [MeasurableSpace X]
    (laws : ℤ → Measure X) [∀ j, IsProbabilityMeasure (laws j)] :
    MeasurePreserving (fun ω : ℤ → X => fun j : ℤ => ω (-j))
      (Measure.infinitePi laws) (Measure.infinitePi (fun j : ℤ => laws (-j))) := by
  let e : ℤ ≃ ℤ := Equiv.neg ℤ
  have he : (MeasurableEquiv.piCongrLeft (fun _ : ℤ => X) e : (ℤ → X) → (ℤ → X)) =
      (fun ω : ℤ → X => fun j : ℤ => ω (-j)) := by
    funext ω j
    simp only [MeasurableEquiv.coe_piCongrLeft, Equiv.piCongrLeft_apply_eq_cast, e,
      Equiv.neg_symm, Equiv.neg_apply, cast_eq]
  have hmap := Measure.infinitePi_map_piCongrLeft
    (μ := fun j : ℤ => laws (-j)) e
  refine ⟨?_, ?_⟩
  · rw [← he]
    exact (MeasurableEquiv.piCongrLeft (fun _ : ℤ => X) e).measurable
  · rw [← he]
    simpa only [e, Equiv.neg_apply, neg_neg] using hmap

end SubdiffusiveProcess
