import SubdiffusiveProcess.Probability.RetainedResponseTransport
import SubdiffusiveProcess.Probability.LayerProductBlocks

/-! # Actual finite-band conditioning in an infinite layer product

The conditioning sigma field is generated by the whole retained coordinates.
The complement contains every other coordinate, with its original product law.
The finite-band map into potentials is arbitrary measurable here and is
instantiated by the literal layer sum in the Sobolev consumer.
-/

open MeasureTheory Filter Set
open scoped ENNReal MeasureTheory
noncomputable section
namespace SubdiffusiveProcess
variable {I : Type*} [DecidableEq I] {F : I → Type*}
    [∀ j, MeasurableSpace (F j)] (laws : (j : I) → Measure (F j))
    [∀ j, IsProbabilityMeasure (laws j)] (J : Finset I)

/-- Finite moments survive actual finite-band conditioning in the uncompleted layer product. -/
theorem memLp_condExp_layer_restrict {p : ℝ≥0∞} (hp : 1 ≤ p) (hpt : p ≠ ∞)
    {f : ((j : I) → F j) → ℝ} (hf : MemLp f p (Measure.infinitePi laws)) :
    MemLp ((Measure.infinitePi laws)[f |
      (inferInstance : MeasurableSpace ((j : J) → F j)).comap
        (fun (ω : (j : I) → F j) (j : J) => ω j)]) p (Measure.infinitePi laws) := by
  exact memLp_condExp_equiv_fst (MeasurableEquiv.piEquivPiSubtypeProd F (fun j => j ∈ J))
    (measurePreserving_infinitePi_split laws (fun j => j ∈ J)) hp hpt hf

/-- Conditioning is integration over all discarded coordinates, with the retained fields fixed. -/
theorem condExp_layer_restrict_integral
    {f : ((j : I) → F j) → ℝ} (hf : Integrable f (Measure.infinitePi laws)) :
    (Measure.infinitePi laws)[f |
      (inferInstance : MeasurableSpace ((j : J) → F j)).comap (fun (ω : (j : I) → F j) (j : J) => ω j)]
      =ᵐ[Measure.infinitePi laws]
      fun ω => ∫ y, f ((MeasurableEquiv.piEquivPiSubtypeProd F (fun j => j ∈ J)).symm
        ((fun j => ω j), y)) ∂(Measure.infinitePi fun j : {j : I // j ∉ J} => laws j) := by
  exact condExp_equiv_fst_integral (MeasurableEquiv.piEquivPiSubtypeProd F (fun j => j ∈ J))
    (measurePreserving_infinitePi_split laws (fun j => j ∈ J)) hf

/-- Strong compactness given a whole finite band, in the actual infinite-product environment Lp. -/
theorem layer_conditional_responses_isCompact_closure
    {X : Type*} [PseudoMetricSpace X] [TopologicalSpace.SeparableSpace X]
    [MeasurableSpace X] [BorelSpace X]
    {V : ((j : J) → F j) → X} (hV : Measurable V)
    {ι : Type*} {f : ι → X × ((j : {j : I // j ∉ J}) → F j) → ℝ}
    (hm : ∀ i, Measurable (f i)) (hn : ∀ i x y, 0 ≤ f i (x, y))
    {C : ℝ} (hC : 0 ≤ C)
    (hc : ∀ i x x' y, f i (x, y) ≤ Real.exp (C * dist x x') * f i (x', y))
    {p q : ℝ≥0∞} [hp : Fact (1 ≤ p)] (hpq : p < q) (hqt : q ≠ ∞)
    {B : ℝ≥0∞} (hB : B ≠ ∞)
    (hf : ∀ i, MemLp (fun ω => f i (V (fun j => ω j), (fun j => ω j)))
      q (Measure.infinitePi laws))
    (hb : ∀ i, eLpNorm (fun ω => f i (V (fun j => ω j), (fun j => ω j)))
      q (Measure.infinitePi laws) ≤ B) :
    IsCompact (closure (range (fun i =>
      (memLp_condExp_layer_restrict laws J hp.out (ne_top_of_lt hpq)
        ((hf i).mono_exponent hpq.le)).toLp
        ((Measure.infinitePi laws)[(fun ω => f i (V (fun j => ω j), (fun j => ω j))) |
          (inferInstance : MeasurableSpace ((j : J) → F j)).comap (fun (ω : (j : I) → F j) (j : J) => ω j)])))) := by
  exact retained_conditional_responses_equiv_isCompact_closure
    (MeasurableEquiv.piEquivPiSubtypeProd F (fun j => j ∈ J))
    (measurePreserving_infinitePi_split laws (fun j => j ∈ J))
    hV hm hn hC hc hpq hqt hB hf hb

end SubdiffusiveProcess
