module

public import SubdiffusiveProcess.Probability.LayerProductBlocks
public import SubdiffusiveProcess.Probability.CopyLayerBlock
public import Mathlib.Probability.Martingale.Convergence

@[expose] public section




open MeasureTheory Filter
open scoped ENNReal Topology

namespace SubdiffusiveProcess.Probability
noncomputable section

section Sigma

variable {I : Type*} (E : I → Type*) [∀ i, MeasurableSpace (E i)]

/-- The σ-field generated by the coordinates indexed by `S`. -/
def coordinateSigma (S : Set I) : MeasurableSpace ((i : I) → E i) :=
  MeasurableSpace.comap (fun (ω : (i : I) → E i) (j : S) => ω j) MeasurableSpace.pi

/-- The coordinate σ-field is contained in the product σ-field. -/
theorem coordinateSigma_le (S : Set I) : coordinateSigma E S ≤ MeasurableSpace.pi :=
  Measurable.comap_le (f := fun (ω : (i : I) → E i) (j : S) => ω j)
    (measurable_pi_iff.mpr fun j => measurable_pi_apply (j : I))

/-- The coordinate σ-field is the supremum of the σ-fields of its coordinates. -/
theorem coordinateSigma_eq_iSup (S : Set I) :
    coordinateSigma E S = ⨆ i ∈ S, (inferInstance : MeasurableSpace (E i)).comap
      (fun x : (i : I) → E i => x i) :=
  SubdiffusiveProcess.comap_restrict_eq_iSup (X := E) S

/-- The coordinate σ-field is monotone in the index set. -/
theorem coordinateSigma_mono {S T : Set I} (h : S ⊆ T) :
    coordinateSigma E S ≤ coordinateSigma E T := by
  rw [coordinateSigma_eq_iSup, coordinateSigma_eq_iSup]
  exact iSup₂_le fun i hi => le_iSup₂ (f := fun i (_ : i ∈ T) =>
    (inferInstance : MeasurableSpace (E i)).comap (fun x : (i : I) → E i => x i)) i (h hi)

end Sigma

section Resample

variable {I : Type*} {E : I → Type*} [∀ i, MeasurableSpace (E i)]
  (μ : (i : I) → Measure (E i)) [∀ i, IsProbabilityMeasure (μ i)]

open Classical in
/-- Keep the coordinates in `T` from `ω` and take all other coordinates from `η`. -/
def resample (T : Set I) (ω η : (i : I) → E i) : (i : I) → E i :=
  fun i => if i ∈ T then ω i else η i

/-- The resampled configuration depends measurably on the pair of samples. -/
theorem measurable_resample (T : Set I) :
    Measurable (fun z : ((i : I) → E i) × ((i : I) → E i) => resample T z.1 z.2) := by
  classical
  refine measurable_pi_iff.mpr fun i => ?_
  by_cases hi : i ∈ T
  · simp only [resample, if_pos hi]
    exact (measurable_pi_apply i).comp measurable_fst
  · simp only [resample, if_neg hi]
    exact (measurable_pi_apply i).comp measurable_snd

/-- Keeping a block of one sample and taking the rest from an independent copy preserves the law. -/
theorem measurePreserving_resample (T : Set I) :
    MeasurePreserving (fun z : ((i : I) → E i) × ((i : I) → E i) => resample T z.1 z.2)
      ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) (Measure.infinitePi μ) := by
  classical
  have h := (SubdiffusiveProcess.measurePreserving_copy_infinitePi_block μ T).comp
    (Measure.measurePreserving_swap (μ := Measure.infinitePi μ) (ν := Measure.infinitePi μ))
  exact h



theorem measurePreserving_swap_first {A B : Type*} [MeasurableSpace A] [MeasurableSpace B]
    (μ : Measure A) (ν : Measure B) [IsProbabilityMeasure μ] [IsProbabilityMeasure ν] :
    MeasurePreserving (fun x : (A × B) × (A × B) => ((x.2.1, x.1.2), (x.1.1, x.2.2)))
      ((μ.prod ν).prod (μ.prod ν)) ((μ.prod ν).prod (μ.prod ν)) := by
  have f1 := measurePreserving_prodAssoc μ ν (μ.prod ν)
  have f2 : MeasurePreserving (Prod.map id Prod.swap)
      (μ.prod (ν.prod (μ.prod ν))) (μ.prod ((μ.prod ν).prod ν)) :=
    (MeasurePreserving.id μ).prod Measure.measurePreserving_swap
  have f3 : MeasurePreserving (Prod.map id MeasurableEquiv.prodAssoc)
      (μ.prod ((μ.prod ν).prod ν)) (μ.prod (μ.prod (ν.prod ν))) :=
    (MeasurePreserving.id μ).prod (measurePreserving_prodAssoc μ ν ν)
  have f4 := (measurePreserving_prodAssoc μ μ (ν.prod ν)).symm
  have f5 : MeasurePreserving (Prod.map Prod.swap Prod.swap)
      ((μ.prod μ).prod (ν.prod ν)) ((μ.prod μ).prod (ν.prod ν)) :=
    Measure.measurePreserving_swap.prod Measure.measurePreserving_swap
  have g1 := measurePreserving_prodAssoc μ μ (ν.prod ν)
  have g2 : MeasurePreserving (Prod.map id MeasurableEquiv.prodAssoc.symm)
      (μ.prod (μ.prod (ν.prod ν))) (μ.prod ((μ.prod ν).prod ν)) :=
    (MeasurePreserving.id μ).prod (measurePreserving_prodAssoc μ ν ν).symm
  have g3 : MeasurePreserving (Prod.map id (Prod.map Prod.swap id))
      (μ.prod ((μ.prod ν).prod ν)) (μ.prod ((ν.prod μ).prod ν)) :=
    (MeasurePreserving.id μ).prod
      (Measure.measurePreserving_swap.prod (MeasurePreserving.id ν))
  have g4 : MeasurePreserving (Prod.map id MeasurableEquiv.prodAssoc)
      (μ.prod ((ν.prod μ).prod ν)) (μ.prod (ν.prod (μ.prod ν))) :=
    (MeasurePreserving.id μ).prod (measurePreserving_prodAssoc ν μ ν)
  have g5 := (measurePreserving_prodAssoc μ ν (μ.prod ν)).symm
  have h := g5.comp (g4.comp (g3.comp (g2.comp (g1.comp
    (f5.comp (f4.comp (f3.comp (f2.comp f1))))))))
  convert h using 1
  funext x
  rfl



theorem measurePreserving_swap_outside (T : Set I) :
    MeasurePreserving (fun z : ((i : I) → E i) × ((i : I) → E i) =>
        (resample T z.1 z.2, resample T z.2 z.1))
      ((Measure.infinitePi μ).prod (Measure.infinitePi μ))
      ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) := by
  classical
  let e := MeasurableEquiv.piEquivPiSubtypeProd E (fun i => i ∈ T)
  let νS := Measure.infinitePi (fun i : T => μ i)
  let νC := Measure.infinitePi (fun i : {i // i ∉ T} => μ i)
  have hsplit : MeasurePreserving e (Measure.infinitePi μ) (νS.prod νC) :=
    measurePreserving_infinitePi_split μ (fun i => i ∈ T)
  have h := (Measure.measurePreserving_swap).comp
    (((MeasurePreserving.symm e hsplit).prod (MeasurePreserving.symm e hsplit)).comp
    ((measurePreserving_swap_first νS νC).comp (hsplit.prod hsplit)))
  convert h using 1
  funext z
  apply Prod.ext
  · funext i
    change (if i ∈ T then z.1 i else z.2 i) =
      (if _h : i ∈ T then z.1 i else z.2 i)
    split_ifs <;> rfl
  · funext i
    change (if i ∈ T then z.2 i else z.1 i) =
      (if _h : i ∈ T then z.2 i else z.1 i)
    split_ifs <;> rfl

/-- Conditioning on the coordinates in `T` integrates out the others. -/
theorem condExp_coordinateSigma_ae_eq (T : Set I) {X : ((i : I) → E i) → ℝ}
    (hXm : Measurable X) (hX : Integrable X (Measure.infinitePi μ)) :
    (Measure.infinitePi μ)[X | coordinateSigma E T] =ᵐ[Measure.infinitePi μ]
      fun ω => ∫ η, X (resample T ω η) ∂Measure.infinitePi μ := by
  classical
  let e := MeasurableEquiv.piEquivPiSubtypeProd E (fun i => i ∈ T)
  have hsplit := measurePreserving_infinitePi_split μ (fun i => i ∈ T)
  have h1 := condExp_equiv_fst_integral e hsplit hX
  refine h1.trans (Filter.Eventually.of_forall fun ω => ?_)
  have h2 : MeasurePreserving (fun η => (e η).2) (Measure.infinitePi μ) _ :=
    measurePreserving_snd.comp hsplit
  have hm : Measurable (fun b => X (e.symm ((e ω).1, b))) :=
    hXm.comp (e.symm.measurable.comp (measurable_const.prodMk measurable_id))
  dsimp only
  rw [← h2.map_eq, integral_map h2.measurable.aemeasurable hm.aestronglyMeasurable]
  refine integral_congr_ae (Filter.Eventually.of_forall fun η => ?_)
  rfl

end Resample

section OneStep

variable {I : Type*} [DecidableEq I] {E : I → Type*} [∀ i, MeasurableSpace (E i)]
  (μ : (i : I) → Measure (E i)) [∀ i, IsProbabilityMeasure (μ i)]

/-- The change of `X` when the coordinate `j` is replaced by that of an independent copy. -/
def resampleDiff (X : ((i : I) → E i) → ℝ) (j : I) :
    ((i : I) → E i) × ((i : I) → E i) → ℝ :=
  fun q => X q.1 - X (Function.update q.1 j (q.2 j))

omit [∀ i, MeasurableSpace (E i)] in
/-- Updating one coordinate is resampling outside the singleton complement. -/
theorem update_eq_resample (j : I) (ω η : (i : I) → E i) :
    Function.update ω j (η j) = resample {j}ᶜ ω η := by
  classical
  funext i
  by_cases hij : i = j
  · subst hij
    simp [resample]
  · simp [resample, hij]

/-- Replacing one coordinate by that of an independent copy preserves the product law. -/
theorem measurePreserving_update_pair (j : I) :
    MeasurePreserving (fun q : ((i : I) → E i) × ((i : I) → E i) =>
        Function.update q.1 j (q.2 j))
      ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) (Measure.infinitePi μ) := by
  have h := measurePreserving_resample μ ({j}ᶜ : Set I)
  convert h using 2 with q
  exact update_eq_resample j q.1 q.2

/-- The resampling difference is measurable for a measurable variable. -/
theorem measurable_resampleDiff {X : ((i : I) → E i) → ℝ} (hXm : Measurable X) (j : I) :
    Measurable (resampleDiff X j) := by
  have h : Measurable (fun q : ((i : I) → E i) × ((i : I) → E i) =>
      Function.update q.1 j (q.2 j)) := by
    simp only [update_eq_resample]
    exact measurable_resample ({j}ᶜ : Set I)
  exact (hXm.comp measurable_fst).sub (hXm.comp h)

omit [∀ i, MeasurableSpace (E i)] in
/-- Resampling outside `S` is a one-coordinate update of resampling outside `insert j S`. -/
theorem resample_insert {S : Set I} {j : I} (hj : j ∉ S) (ω η : (i : I) → E i) :
    resample S ω η =
      Function.update (resample (insert j S) ω η) j (resample (insert j S) η ω j) := by
  classical
  funext i
  by_cases hij : i = j
  · subst hij
    simp [resample, hj]
  · rw [Function.update_of_ne hij]
    simp [resample, hij]

/-- One-step bound: adding the coordinate `j` to the conditioning changes the conditional
expectation by at most the `j`-resampling difference in `L^p`. -/
theorem eLpNorm_condExp_insert_sub_le {p : ℝ≥0∞} (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    {X : ((i : I) → E i) → ℝ} (hXm : Measurable X) (hX : Integrable X (Measure.infinitePi μ))
    {S : Set I} {j : I} (hj : j ∉ S) :
    eLpNorm ((Measure.infinitePi μ)[X | coordinateSigma E (insert j S)] -
        (Measure.infinitePi μ)[X | coordinateSigma E S]) p (Measure.infinitePi μ) ≤
      eLpNorm (resampleDiff X j) p ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) := by
  classical
  let P := Measure.infinitePi μ
  let U : Set I := insert j S
  let F : ((i : I) → E i) × ((i : I) → E i) → ℝ :=
    fun z => X (resample U z.1 z.2) - X (resample S z.1 z.2)
  have hIU : Integrable (fun z : ((i : I) → E i) × ((i : I) → E i) => X (resample U z.1 z.2))
      (P.prod P) := (measurePreserving_resample μ U).integrable_comp_of_integrable hX
  have hIS : Integrable (fun z : ((i : I) → E i) × ((i : I) → E i) => X (resample S z.1 z.2))
      (P.prod P) := (measurePreserving_resample μ S).integrable_comp_of_integrable hX
  have hFint : Integrable F (P.prod P) := hIU.sub hIS
  have hAU := condExp_coordinateSigma_ae_eq μ U hXm hX
  have hAS := condExp_coordinateSigma_ae_eq μ S hXm hX
  have hD : (P[X | coordinateSigma E U] - P[X | coordinateSigma E S]) =ᵐ[P]
      fun ω => ∫ η, F (ω, η) ∂P := by
    filter_upwards [hAU, hAS, hIU.prod_right_ae, hIS.prod_right_ae] with ω h1 h2 h3 h4
    rw [Pi.sub_apply, h1, h2]
    exact (integral_sub h3 h4).symm
  rw [eLpNorm_congr_ae hD]
  have hfst : MeasurePreserving (Prod.fst : _ × ((i : I) → E i) → _) (P.prod P) P :=
    measurePreserving_fst
  rw [← eLpNorm_comp_measurePreserving hFint.integral_prod_left.aestronglyMeasurable hfst]
  refine (eLpNorm_prod_integral_le hp hp_top hFint.aestronglyMeasurable).trans (le_of_eq ?_)
  have hΨ := measurePreserving_swap_outside μ U
  have hFeq : F = resampleDiff X j ∘ (fun z : ((i : I) → E i) × ((i : I) → E i) =>
      (resample U z.1 z.2, resample U z.2 z.1)) := by
    funext z
    simp only [F, resampleDiff, Function.comp_apply]
    rw [resample_insert hj z.1 z.2]
  rw [hFeq, eLpNorm_comp_measurePreserving (measurable_resampleDiff hXm j).aestronglyMeasurable hΨ]

end OneStep

section Telescope

variable {I : Type*} [DecidableEq I] {E : I → Type*} [∀ i, MeasurableSpace (E i)]
  (μ : (i : I) → Measure (E i)) [∀ i, IsProbabilityMeasure (μ i)]

omit [DecidableEq I] [∀ i, IsProbabilityMeasure (μ i)] in
/-- Conditional expectations onto coordinate σ-fields are a.e. strongly measurable. -/
theorem aestronglyMeasurable_condExp_coordinateSigma {X : ((i : I) → E i) → ℝ} (S : Set I) :
    AEStronglyMeasurable ((Measure.infinitePi μ)[X | coordinateSigma E S]) (Measure.infinitePi μ) :=
  (stronglyMeasurable_condExp.mono (coordinateSigma_le E S)).aestronglyMeasurable

/-- Finite telescoping: adding finitely many coordinates outside `J` to the conditioning
changes the conditional expectation by at most the sum of the resampling differences. -/
theorem eLpNorm_condExp_union_sub_le {p : ℝ≥0∞} (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    {X : ((i : I) → E i) → ℝ} (hXm : Measurable X) (hX : Integrable X (Measure.infinitePi μ))
    (J : Set I) (K : Finset I) (hK : ∀ k ∈ K, k ∉ J) :
    eLpNorm ((Measure.infinitePi μ)[X | coordinateSigma E (J ∪ (K : Set I))] -
        (Measure.infinitePi μ)[X | coordinateSigma E J]) p (Measure.infinitePi μ) ≤
      ∑ k ∈ K, eLpNorm (resampleDiff X k) p
        ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) := by
  induction K using Finset.induction_on with
  | empty => simp
  | insert a K ha ih =>
    have haJ : a ∉ J := hK a (Finset.mem_insert_self a K)
    have ih' := ih fun k hk => hK k (Finset.mem_insert_of_mem hk)
    have haS : a ∉ J ∪ (K : Set I) := by
      simp only [Set.mem_union, Finset.mem_coe, not_or]
      exact ⟨haJ, ha⟩
    have hstep := eLpNorm_condExp_insert_sub_le μ hp hp_top hXm hX haS
    have hset : J ∪ ((insert a K : Finset I) : Set I) = insert a (J ∪ (K : Set I)) := by
      rw [Finset.coe_insert, Set.union_insert]
    rw [hset, Finset.sum_insert ha]
    have hsplit : (Measure.infinitePi μ)[X | coordinateSigma E (insert a (J ∪ (K : Set I)))] -
        (Measure.infinitePi μ)[X | coordinateSigma E J] =
        ((Measure.infinitePi μ)[X | coordinateSigma E (insert a (J ∪ (K : Set I)))] -
          (Measure.infinitePi μ)[X | coordinateSigma E (J ∪ (K : Set I))]) +
        ((Measure.infinitePi μ)[X | coordinateSigma E (J ∪ (K : Set I))] -
          (Measure.infinitePi μ)[X | coordinateSigma E J]) := by
      abel
    rw [hsplit]
    exact (eLpNorm_add_le hp).trans (add_le_add hstep ih')

end Telescope

section Limit

variable {I : Type*} {E : I → Type*} [∀ i, MeasurableSpace (E i)]

/-- The filtration generated by an increasing sequence of coordinate sets. -/
def coordFiltration (S : ℕ → Set I) (hS : Monotone S) :
    Filtration ℕ (MeasurableSpace.pi : MeasurableSpace ((i : I) → E i)) where
  seq n := coordinateSigma E (S n)
  mono' _ _ hmn := coordinateSigma_mono E (hS hmn)
  le' n := coordinateSigma_le E (S n)

/-- An exhausting sequence of coordinate sets generates the product σ-field. -/
theorem iSup_coordinateSigma_eq_pi (S : ℕ → Set I) (hS : ∀ i, ∃ n, i ∈ S n) :
    ⨆ n, coordinateSigma E (S n) = (MeasurableSpace.pi : MeasurableSpace ((i : I) → E i)) := by
  refine le_antisymm (iSup_le fun n => coordinateSigma_le E (S n)) ?_
  refine iSup_le fun i => ?_
  obtain ⟨n, hn⟩ := hS i
  refine le_trans ?_ (le_iSup (fun n => coordinateSigma E (S n)) n)
  rw [coordinateSigma_eq_iSup]
  exact le_iSup₂ (f := fun i (_ : i ∈ S n) =>
    (inferInstance : MeasurableSpace (E i)).comap (fun x : (i : I) → E i => x i)) i hn

end Limit

section Main

variable {I : Type*} [Countable I] [DecidableEq I] {E : I → Type*} [∀ i, MeasurableSpace (E i)]
  (μ : (i : I) → Measure (E i)) [∀ i, IsProbabilityMeasure (μ i)]

omit [Countable I] [DecidableEq I] in
/-- A finite sum over coordinates outside `J` is bounded by the full sum over `Jᶜ`. -/
theorem sum_finset_le_tsum_compl (J : Set I) (K : Finset I) (hK : ∀ k ∈ K, k ∉ J)
    (c : I → ℝ≥0∞) : ∑ k ∈ K, c k ≤ ∑' j : ↥Jᶜ, c j := by
  classical
  calc ∑ k ∈ K, c k = ∑ j ∈ K.subtype (· ∈ Jᶜ), c j :=
        (Finset.sum_subtype_of_mem c (fun k hk => hK k hk)).symm
    _ ≤ ∑' j : ↥Jᶜ, c j := ENNReal.sum_le_tsum _

/-- The resampling bound for a measurable integrable variable. -/
theorem eLpNorm_sub_condExp_le_tsum_of_measurable {p : ℝ≥0∞} (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    {X : ((i : I) → E i) → ℝ} (hXm : Measurable X) (hX : Integrable X (Measure.infinitePi μ))
    (J : Set I) :
    eLpNorm (X - (Measure.infinitePi μ)[X | coordinateSigma E J]) p (Measure.infinitePi μ) ≤
      ∑' j : ↥Jᶜ, eLpNorm (resampleDiff X j) p
        ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) := by
  classical
  obtain ⟨ι, hι⟩ := Countable.exists_injective_nat I
  have hfin : ∀ n : ℕ, {i : I | i ∉ J ∧ ι i < n}.Finite := fun n =>
    ((Set.finite_lt_nat n).preimage hι.injOn).subset fun i hi => hi.2
  let K : ℕ → Finset I := fun n => (hfin n).toFinset
  have hK_mem : ∀ n i, i ∈ K n ↔ i ∉ J ∧ ι i < n := fun n i => Set.Finite.mem_toFinset (hfin n)
  have hKJ : ∀ n, ∀ k ∈ K n, k ∉ J := fun n k hk => ((hK_mem n k).1 hk).1
  let S : ℕ → Set I := fun n => J ∪ (K n : Set I)
  have hSmono : Monotone S := by
    intro m n hmn i hi
    rcases hi with hi | hi
    · exact Or.inl hi
    · have h := (hK_mem m i).1 (Finset.mem_coe.1 hi)
      exact Or.inr (Finset.mem_coe.2 ((hK_mem n i).2 ⟨h.1, lt_of_lt_of_le h.2 hmn⟩))
  have hSall : ∀ i, ∃ n, i ∈ S n := by
    intro i
    by_cases hi : i ∈ J
    · exact ⟨0, Or.inl hi⟩
    · exact ⟨ι i + 1, Or.inr (Finset.mem_coe.2 ((hK_mem _ i).2 ⟨hi, Nat.lt_succ_self _⟩))⟩
  let ℱ := coordFiltration (E := E) S hSmono
  have hlim : ∀ᵐ ω ∂(Measure.infinitePi μ), Tendsto
      (fun n => (Measure.infinitePi μ)[X | coordinateSigma E (S n)] ω) atTop (𝓝 (X ω)) := by
    have h1 := tendsto_ae_condExp (μ := Measure.infinitePi μ) (ℱ := ℱ) X
    have h2 : (Measure.infinitePi μ)[X | ⨆ n, ℱ n] = X := by
      have hsup : (⨆ n, ℱ n) = (MeasurableSpace.pi : MeasurableSpace ((i : I) → E i)) :=
        iSup_coordinateSigma_eq_pi S hSall
      rw [hsup]
      exact condExp_of_stronglyMeasurable le_rfl hXm.stronglyMeasurable hX
    filter_upwards [h1] with ω hω
    rwa [h2] at hω
  have hFatou : eLpNorm (X - (Measure.infinitePi μ)[X | coordinateSigma E J]) p
      (Measure.infinitePi μ) ≤ liminf (fun n => eLpNorm
        ((Measure.infinitePi μ)[X | coordinateSigma E (S n)] -
          (Measure.infinitePi μ)[X | coordinateSigma E J]) p (Measure.infinitePi μ)) atTop := by
    refine Lp.eLpNorm_lim_le_liminf_eLpNorm
      (f := fun n => (Measure.infinitePi μ)[X | coordinateSigma E (S n)] -
        (Measure.infinitePi μ)[X | coordinateSigma E J]) (fun n => ?_) _
        (hXm.aestronglyMeasurable.sub
          (aestronglyMeasurable_condExp_coordinateSigma μ J)) ?_
    · exact (aestronglyMeasurable_condExp_coordinateSigma μ _).sub
        (aestronglyMeasurable_condExp_coordinateSigma μ _)
    · filter_upwards [hlim] with ω hω
      exact hω.sub_const _
  refine hFatou.trans ?_
  refine (liminf_le_liminf (Eventually.of_forall fun n => ?_)).trans (le_of_eq (liminf_const _))
  exact (eLpNorm_condExp_union_sub_le μ hp hp_top hXm hX J (K n) (hKJ n)).trans
    (sum_finset_le_tsum_compl J (K n) (hKJ n) _)

/-- **Summing resampling bounds.** For an independent family (the coordinates of an infinite
product probability space) and `X ∈ L^p`, the `L^p` distance of `X` from its conditional
expectation on the coordinates in `J` is at most the sum, over the coordinates outside `J`, of
the `L^p` norms of the change of `X` when that coordinate is replaced by an independent copy. -/
theorem eLpNorm_sub_condExp_le_tsum_resample {I : Type*} [Countable I] [DecidableEq I]
    {E : I → Type*} [∀ i, MeasurableSpace (E i)]
    (μ : (i : I) → Measure (E i)) [∀ i, IsProbabilityMeasure (μ i)]
    {p : ℝ≥0∞} (hp : 1 ≤ p) (hp_top : p ≠ ∞)
    (X : ((i : I) → E i) → ℝ) (hX : MemLp X p (Measure.infinitePi μ)) (J : Set I) :
    eLpNorm (X - (Measure.infinitePi μ)[X |
        MeasurableSpace.comap (fun (ω : (i : I) → E i) (j : J) => ω j) MeasurableSpace.pi])
        p (Measure.infinitePi μ) ≤
      ∑' j : ↥Jᶜ, eLpNorm (fun q : ((i : I) → E i) × ((i : I) → E i) =>
          X q.1 - X (Function.update q.1 (j : I) (q.2 j))) p
        ((Measure.infinitePi μ).prod (Measure.infinitePi μ)) := by
  have hXX' : X =ᵐ[Measure.infinitePi μ] hX.aestronglyMeasurable.mk X :=
    hX.aestronglyMeasurable.ae_eq_mk
  have hX'm : Measurable (hX.aestronglyMeasurable.mk X) :=
    hX.aestronglyMeasurable.stronglyMeasurable_mk.measurable
  have hX'i : Integrable (hX.aestronglyMeasurable.mk X) (Measure.infinitePi μ) :=
    (hX.integrable hp).congr hXX'
  have key := eLpNorm_sub_condExp_le_tsum_of_measurable μ hp hp_top hX'm hX'i J
  have hL : X - (Measure.infinitePi μ)[X | coordinateSigma E J] =ᵐ[Measure.infinitePi μ]
      hX.aestronglyMeasurable.mk X - (Measure.infinitePi μ)[hX.aestronglyMeasurable.mk X |
        coordinateSigma E J] := hXX'.sub (condExp_congr_ae hXX')
  have hfst : (fun q : ((i : I) → E i) × ((i : I) → E i) => X q.1) =ᵐ[
      (Measure.infinitePi μ).prod (Measure.infinitePi μ)]
      fun q => hX.aestronglyMeasurable.mk X q.1 :=
    (measurePreserving_fst (μ := Measure.infinitePi μ)
      (ν := Measure.infinitePi μ)).quasiMeasurePreserving.ae_eq hXX'
  refine le_of_le_of_eq (le_of_eq_of_le (eLpNorm_congr_ae hL) key) (tsum_congr fun j => ?_)
  refine eLpNorm_congr_ae ?_
  filter_upwards [hfst, (measurePreserving_update_pair μ (j : I)).quasiMeasurePreserving.ae_eq
    hXX'] with q h1 h2
  change hX.aestronglyMeasurable.mk X q.1 -
      hX.aestronglyMeasurable.mk X (Function.update q.1 (j : I) (q.2 j)) =
    X q.1 - X (Function.update q.1 (j : I) (q.2 j))
  have h2' : X (Function.update q.1 (j : I) (q.2 j)) =
      hX.aestronglyMeasurable.mk X (Function.update q.1 (j : I) (q.2 j)) := h2
  rw [← h1, ← h2']

end Main

end
end SubdiffusiveProcess.Probability
