module

public import SubdiffusiveProcess.CoarseGrainingVocab.Concentration
public import SubdiffusiveProcess.Model.GMCModel

@[expose] public section

/-!
# Single-shell columns for the Section 6 density arrays

The score arrays in the proof of `p.density.of.good.scales` are indexed by
`ℤ`, while the GMC shell stream is indexed by `ℕ`.  The manuscript extends the
arrays by zero at negative column indices.  This file records the exact
measure-theoretic adapter: independent nonnegative shell columns remain
independent after adjoining arbitrary deterministic columns.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section6Density

open MeasureTheory ProbabilityTheory

noncomputable section

private abbrev Sample (d : ℕ) := _root_.SubdiffusiveProcess.Model.PotentialSample d

/-- The sigma-field generated by the `i`th GMC shell coordinate. -/
@[instance_reducible]
def shellSigma (d i : ℕ) : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) :=
  MeasurableSpace.comap (fun omega : _root_.SubdiffusiveProcess.Model.PotentialSample d => omega i) inferInstance

theorem shellSigma_le {d : ℕ} (i : ℕ) :
    shellSigma d i ≤ (inferInstance : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d)) :=
  (_root_.SubdiffusiveProcess.Model.measurable_potentialCoordinate i).comap_le

/-- A family remains mutually independent after deterministic coordinates are
adjoined.  This is the abstract step needed for the manuscript's extension of
the score arrays by zero on negative integer columns. -/
theorem iIndepFun_of_iIndepFun_subtype_of_constant
    {Omega ι β : Type*} [MeasurableSpace Omega] [MeasurableSpace β]
    {mu : Measure Omega} [IsProbabilityMeasure mu]
    (A : Set ι) (f : ι → Omega → β)
    (hA : iIndepFun (fun i : A => f i.1) mu)
    (hconst : ∀ i, i ∉ A → ∃ c : β, ∀ omega, f i omega = c) :
    iIndepFun f mu := by
  rw [iIndepFun_iff]
  intro s g hg
  classical
  by_cases hempty : ∃ i ∈ s, i ∉ A ∧ g i = ∅
  · obtain ⟨i, his, _hiA, hgi⟩ := hempty
    have hinter : (⋂ j ∈ s, g j) = ∅ := by
      apply Set.eq_empty_iff_forall_notMem.2
      intro omega homega
      have hi := Set.mem_iInter.mp (Set.mem_iInter.mp homega i) his
      simp [hgi] at hi
    rw [hinter, measure_empty]
    exact (Finset.prod_eq_zero his (by simp [hgi])).symm
  · have hout : ∀ i ∈ s, i ∉ A → g i = Set.univ := by
      intro i his hiA
      rcases hconst i hiA with ⟨c, hc⟩
      rcases MeasurableSpace.measurableSet_comap.1 (hg i his) with
        ⟨t, _ht, hgt⟩
      by_cases hct : c ∈ t
      · ext omega
        simp only [Set.mem_univ, iff_true]
        rw [← hgt]
        simpa only [Set.mem_preimage, hc omega] using hct
      · have hzero : g i = ∅ := by
          ext omega
          rw [← hgt]
          simp only [Set.mem_preimage, Set.notMem_empty, iff_false]
          intro hmem
          exact hct (hc omega ▸ hmem)
        exact False.elim (hempty ⟨i, his, hiA, hzero⟩)
    let sA : Finset A := (s.filter fun i => i ∈ A).attach.map
      ⟨fun i => (⟨i.1, (Finset.mem_filter.mp i.2).2⟩ : A), by
        intro i j hij
        have hv : i.1 = j.1 := congrArg (fun x : A => x.1) hij
        exact Subtype.ext hv⟩
    have hsA_mem : ∀ i : A, i ∈ sA ↔ i.1 ∈ s := by
      intro i
      constructor
      · intro hi
        simp only [sA, Finset.mem_map, Finset.mem_attach] at hi
        obtain ⟨j, _hj, hji⟩ := hi
        have hv : j.1 = i.1 := congrArg (fun x : A => x.1) hji
        have hjs : j.1 ∈ s := (Finset.mem_filter.mp j.2).1
        simpa only [hv] using hjs
      · intro hi
        simp only [sA, Finset.mem_map, Finset.mem_attach]
        refine ⟨⟨i.1, Finset.mem_filter.mpr ⟨hi, i.2⟩⟩, trivial, ?_⟩
        exact Subtype.ext rfl
    have hmeasA : ∀ i : A, i ∈ sA →
        MeasurableSet[(inferInstance : MeasurableSpace β).comap (f i.1)] (g i.1) := by
      intro i hi
      exact hg i.1 ((hsA_mem i).1 hi)
    have hmain := hA.meas_biInter hmeasA
    have hinter : (⋂ i ∈ s, g i) = ⋂ i ∈ sA, g i.1 := by
      ext omega
      simp only [Set.mem_iInter]
      constructor
      · intro h i hi
        exact h i.1 ((hsA_mem i).1 hi)
      · intro h i hi
        by_cases hiA : i ∈ A
        · exact h ⟨i, hiA⟩ ((hsA_mem ⟨i, hiA⟩).2 hi)
        · rw [hout i hi hiA]
          trivial
    have hfilter : (∏ i ∈ s.filter fun i => i ∈ A, mu (g i)) =
        ∏ i ∈ s, mu (g i) := by
      apply Finset.prod_subset (Finset.filter_subset _ _)
      intro i hi hisub
      have hiA : i ∉ A := by
        intro hia
        exact hisub (Finset.mem_filter.mpr ⟨hi, hia⟩)
      simp [hout i hi hiA]
    have hmap : (∏ i ∈ sA, mu (g i.1)) =
        ∏ i ∈ s.filter fun i => i ∈ A, mu (g i) := by
      change (∏ i ∈ (s.filter fun i => i ∈ A).attach.map
          ⟨fun i => (⟨i.1, (Finset.mem_filter.mp i.2).2⟩ : A), by
            intro i j hij
            have hv : i.1 = j.1 := congrArg (fun x : A => x.1) hij
            exact Subtype.ext hv⟩, mu (g i.1)) = _
      rw [Finset.prod_map]
      exact Finset.prod_attach (s.filter fun i => i ∈ A) (fun i => mu (g i))
    have hprod : (∏ i ∈ s, mu (g i)) = ∏ i ∈ sA, mu (g i.1) :=
      hfilter.symm.trans hmap.symm
    rw [hinter, hprod]
    exact hmain

private theorem injective_residue {r : ℕ} (hr : 1 ≤ r) (b : ℤ) :
    Function.Injective fun j : ℤ => j * (r : ℤ) + b := by
  intro i j hij
  have hr0 : (r : ℤ) ≠ 0 := by exact_mod_cast Nat.one_le_iff_ne_zero.mp hr
  apply mul_right_cancel₀ hr0
  linarith

private theorem iIndepFun_of_iIndep_sigma_pi
    {Omega ι : Type*} [MeasurableSpace Omega]
    {mu : Measure Omega} {m : ι → MeasurableSpace Omega} (h : iIndep m mu)
    {beta : ι → Type*} [∀ i, MeasurableSpace (beta i)]
    {f : ∀ i, Omega → beta i} (hf : ∀ i, Measurable[m i] (f i)) :
    iIndepFun f mu := by
  rw [iIndepFun_iff_iIndep, iIndep_iff]
  intro s g hg
  exact (iIndep_iff m mu).1 h s
    (fun i hi => (hf i).comap_le (g i) (hg i hi))

/-- A two-index array whose nonnegative `j`th column reads only shell `j`, and
whose negative columns are deterministic, satisfies Appendix B's exact
`ColumnsIndep` condition at every positive residue range. -/
theorem columnsIndep_of_nonnegative_shellColumn_of_constant
    {d : ℕ}
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d)
    (X : ℤ → ℤ → _root_.SubdiffusiveProcess.Model.PotentialSample d → ℝ) {r : ℕ} (hr : 1 ≤ r)
    (hcol : ∀ k j : ℤ, 0 ≤ j →
      Measurable[shellSigma d j.toNat] (X k j))
    (hconst : ∀ k j : ℤ, j < 0 → ∃ c : ℝ, ∀ omega, X k j omega = c) :
    SubdiffusiveProcess.Concentration.ColumnsIndep M.P.toMeasure X r := by
  intro b
  let A : Set ℤ := {j | 0 ≤ j * (r : ℤ) + b}
  let F : ℤ → _root_.SubdiffusiveProcess.Model.PotentialSample d → (ℤ → ℝ) :=
    fun j omega k => X k (j * (r : ℤ) + b) omega
  apply iIndepFun_of_iIndepFun_subtype_of_constant A F
  · let e : A → ℕ := fun j => (j.1 * (r : ℤ) + b).toNat
    have he : Function.Injective e := by
      intro i j hij
      apply Subtype.ext
      apply injective_residue hr b
      have hi : 0 ≤ i.1 * (r : ℤ) + b := i.2
      have hj : 0 ≤ j.1 * (r : ℤ) + b := j.2
      have hijZ : ((e i : ℕ) : ℤ) = ((e j : ℕ) : ℤ) := by exact_mod_cast hij
      simpa only [e, Int.toNat_of_nonneg hi, Int.toNat_of_nonneg hj] using hijZ
    have hshell : iIndep (fun j : A => shellSigma d (e j)) M.P.toMeasure := by
      have h := M.shellPrefix.independent.precomp he
      rw [iIndepFun_iff_iIndep] at h
      exact h
    refine iIndepFun_of_iIndep_sigma_pi hshell ?_
    intro j
    let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) := shellSigma d (e j)
    exact measurable_pi_iff.mpr fun k => hcol k (j.1 * (r : ℤ) + b) j.2
  · intro j hj
    have hneg : j * (r : ℤ) + b < 0 := by
      simpa [A] using hj
    refine ⟨fun k => Classical.choose (hconst k _ hneg), ?_⟩
    intro omega
    funext k
    exact (Classical.choose_spec (hconst k _ hneg)) omega

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section6Density
