module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.Section9ConservationProbabilityMoments
public import SubdiffusiveProcess.CoarseGrainingVocab.Section7Clock.TimeChangeMarkovProperty
public import SubdiffusiveProcess.CoarseGrainingVocab.Section7Clock.TimeChangeStoppedFiltration

@[expose] public section

/-!
# Finite-dimensional marginals of the time-changed process

`TimeChangeMarkovProperty` proves that the time-changed process `Y = X ∘ θ`
restarts after every deterministic time, in the event-restricted form, and
`TimeChangeStoppedFiltration` proves that the state of `Y` at a time `s ≤ t` is
an event of the stopped sigma-algebra of `θ_t`.  Together these are exactly the
Markov property of `Y` conditioned on its own present state.

This file performs the structural induction those two results were prepared
for: from the restart property and the **one-dimensional** marginals of `Y`,
every finite-dimensional marginal of `Y` is the corresponding finite-time law
of the target semigroup.  The induction is on the recursion by which
`MarkovProcess.SubMarkovKernelSemigroup.finiteTimeKernel` is defined — sample
the first time, then the relative tail — and it contains no analysis.

Combined with `TimeChangeFiniteDimensionalReduction`, the frozen time-change anchor
is thereby reduced to exactly two
scalar-analytic inputs: almost-sure divergence of the clock, and the
one-dimensional marginals.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section7Clock

open MeasureTheory ProbabilityTheory MarkovProcess Set
open SubdiffusiveProcess.Frozen.Section7
open scoped ENNReal NNReal

noncomputable section

/-! ### From a restricted restart identity to the joint law -/

/-- **The joint law from the restricted restart identity.**  This is the
converse of `MarkovProcess.restrict_map_eq_comap_comp_of_map_prodMk_eq_compProd`:
if the law of `Y` after restriction to every event of the sigma-algebra
generated by `X` is the mixture of `kappa` over that restricted law, then the
joint law of `(X, Y)` is the composition-product of the law of `X` with
`kappa`. -/
theorem map_prodMk_eq_compProd_of_restrict_map
    {Omega beta gamma : Type*} [MeasurableSpace Omega] [MeasurableSpace beta]
    [MeasurableSpace gamma]
    (mu : Measure Omega) [IsFiniteMeasure mu]
    {X : Omega → beta} (hX : Measurable X)
    {Y : Omega → gamma} (hY : Measurable Y)
    (kappa : Kernel beta gamma) [IsMarkovKernel kappa]
    (h : ∀ B : Set beta, MeasurableSet B →
      (mu.restrict (X ⁻¹' B)).map Y =
        (Kernel.comap kappa X hX) ∘ₘ (mu.restrict (X ⁻¹' B))) :
    mu.map (fun omega ↦ (X omega, Y omega)) = (mu.map X) ⊗ₘ kappa := by
  have key : ∀ B : Set beta, MeasurableSet B → ∀ C : Set gamma, MeasurableSet C →
      mu.map (fun omega ↦ (X omega, Y omega)) (B ×ˢ C) =
        ((mu.map X) ⊗ₘ kappa) (B ×ˢ C) := by
    intro B hB C hC
    have hrestrict : (mu.restrict (X ⁻¹' B)).map Y C =
        ((Kernel.comap kappa X hX) ∘ₘ (mu.restrict (X ⁻¹' B))) C := by
      rw [h B hB]
    rw [Measure.map_apply (hX.prodMk hY) (hB.prod hC), Set.mk_preimage_prod]
    rw [Measure.map_apply hY hC, Measure.restrict_apply (hY hC),
      Set.inter_comm] at hrestrict
    rw [hrestrict, Measure.bind_apply hC (Kernel.aemeasurable _)]
    simp only [Kernel.comap_apply]
    rw [Measure.compProd_apply_prod hB hC]
    rw [setLIntegral_map hB (kappa.measurable_coe hC) hX]
  refine ext_of_generate_finite _ generateFrom_prod.symm isPiSystem_prod ?_ ?_
  · rintro s ⟨B, hB, C, hC, rfl⟩
    exact key B hB C hC
  · have huniv : (Set.univ : Set (beta × gamma)) = Set.univ ×ˢ Set.univ := by
      simp
    rw [huniv]
    exact key _ MeasurableSet.univ _ MeasurableSet.univ


/-- Mapping the second factor of a composition-product is the composition-product
with the mapped kernel. -/
theorem compProd_map_right {beta gamma delta : Type*} [MeasurableSpace beta]
    [MeasurableSpace gamma] [MeasurableSpace delta]
    (mu : Measure beta) [SFinite mu] (kappa : Kernel beta gamma)
    [IsSFiniteKernel kappa] {F : gamma → delta} (hF : Measurable F) :
    (mu ⊗ₘ kappa).map (fun p : beta × gamma ↦ (p.1, F p.2)) =
      mu ⊗ₘ (kappa.map F) := by
  have hmap : Measurable (fun p : beta × gamma ↦ (p.1, F p.2)) :=
    measurable_fst.prodMk (hF.comp measurable_snd)
  ext s hs
  rw [Measure.map_apply hmap hs, Measure.compProd_apply (hs.preimage hmap),
    Measure.compProd_apply hs]
  refine lintegral_congr fun b ↦ ?_
  rw [Kernel.map_apply _ hF, Measure.map_apply hF (measurable_prodMk_left hs)]
  rfl

/-- Evaluating a kernel composition-product whose second factor ignores the
starting state is the measure composition-product. -/
theorem kernel_compProd_prodMkLeft_apply {alpha beta gamma : Type*}
    [MeasurableSpace alpha] [MeasurableSpace beta] [MeasurableSpace gamma]
    (kappa : Kernel alpha beta) [IsSFiniteKernel kappa]
    (eta : Kernel beta gamma) [IsSFiniteKernel eta] (x : alpha) :
    (kappa ⊗ₖ Kernel.prodMkLeft alpha eta) x = (kappa x) ⊗ₘ eta := by exact SubdiffusiveProcess.CoarseGrainingVocab.Section9Support.compProd_prodMkLeft_apply (A := alpha) (B := beta) (C := gamma) (kappa := kappa) (eta := eta) (x := x)


/-! ### The time-changed process as a kernel -/

variable {Theta : Type*} {d : ℕ} {a : Theta → State d → ℝ} {theta : Theta}

/-- The law of the time-changed process, as a kernel in the starting state of
the input process. -/
def timeChangedProcess (P : SubMarkovKernelSemigroup (State d)) (hP : P.IsConservative)
    (a : Theta → State d → ℝ) (theta : Theta) (ha : Continuous (a theta))
    (hapos : ∀ x, 0 < a theta x) (default : ContinuousPath (State d)) :
    Kernel (State d) (ContinuousPath (State d)) :=
  (SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP).map
    (measurableTimeChangedContinuousPath a theta ha hapos default)

theorem timeChangedProcess_apply (P : SubMarkovKernelSemigroup (State d))
    (hP : P.IsConservative) (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d)) (x : State d) :
    timeChangedProcess P hP a theta ha hapos default x =
      (SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP x).map
        (measurableTimeChangedContinuousPath a theta ha hapos default) :=
  Kernel.map_apply _ (measurable_measurableTimeChangedContinuousPath ha hapos default) x

instance isMarkovKernel_timeChangedProcess (P : SubMarkovKernelSemigroup (State d))
    (hP : P.IsConservative) (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d)) :
    IsMarkovKernel (timeChangedProcess P hP a theta ha hapos default) :=
  Kernel.IsMarkovKernel.map _ (measurable_measurableTimeChangedContinuousPath ha hapos default)

/-! ### The restart identity in terms of the time-changed process itself -/

/-- **The time-changed process restarts after conditioning on its own present
state.**  This is `timeChanged_restrict_map_shift` with the conditioning event
rewritten as an event of the time-changed process at time `t`, which is
legitimate because the state of the time-changed process at `t` is measurable
for the stopped sigma-algebra of the inverse clock at `t`. -/
theorem timeChangedProcess_restrict_map_shift
    (P : SubMarkovKernelSemigroup (State d)) (hP : P.IsConservative)
    (hFeller : P.IsFellerKernelSemigroup) (hK : P.KolmogorovRegular hP)
    (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d)) (x : State d) (t : NNReal)
    (hunb : ∀ᵐ omega ∂(SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP x),
      omega ∈ timeChangeUnboundedEvent a theta)
    {B : Set (State d)} (hB : MeasurableSet B) :
    (((timeChangedProcess P hP a theta ha hapos default x).restrict
          ((fun eta : ContinuousPath (State d) ↦ eta t) ⁻¹' B)).map
        (ContinuousPath.shift t)) =
      (Kernel.comap (timeChangedProcess P hP a theta ha hapos default)
          (fun eta : ContinuousPath (State d) ↦ eta t)
          (ContinuousPath.measurable_coordinateProcess t)) ∘ₘ
        ((timeChangedProcess P hP a theta ha hapos default x).restrict
          ((fun eta : ContinuousPath (State d) ↦ eta t) ⁻¹' B)) := by
  set Q := SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP with hQ
  set Psi := measurableTimeChangedContinuousPath a theta ha hapos default with hPsi
  have hPsiMeas : Measurable Psi :=
    measurable_measurableTimeChangedContinuousPath ha hapos default
  have hevalMeas : Measurable (fun eta : ContinuousPath (State d) ↦ eta t) :=
    ContinuousPath.measurable_coordinateProcess t
  have hAmeas := measurableSet_preimage_timeChangedValue (a := a) (theta := theta)
    ha hapos default t t le_rfl hB
  have hkey : (Q x).restrict (timeChangedValue a theta t ⁻¹' B) =
      (Q x).restrict (Psi ⁻¹' ((fun eta : ContinuousPath (State d) ↦ eta t) ⁻¹' B)) := by
    refine Measure.restrict_congr_set ?_
    filter_upwards [hunb] with omega homega
    show (timeChangedValue a theta t omega ∈ B) =
      (measurableTimeChangedContinuousPath a theta ha hapos default omega t ∈ B)
    rw [measurableTimeChangedContinuousPath_apply_eq_timeChangedValue ha hapos default t homega]
  have hrestrict : ((Q x).restrict (timeChangedValue a theta t ⁻¹' B)).map Psi =
      (timeChangedProcess P hP a theta ha hapos default x).restrict
        ((fun eta : ContinuousPath (State d) ↦ eta t) ⁻¹' B) := by
    rw [hkey, timeChangedProcess_apply P hP ha hapos default x,
      Measure.restrict_map hPsiMeas (hevalMeas hB)]
  have h := timeChanged_restrict_map_shift P hP hFeller hK ha hapos default x t hunb
    (timeChangedValue a theta t ⁻¹' B) hAmeas
  rw [hrestrict] at h
  exact h

/-! ### The joint law of the present state and the shifted future -/



theorem timeChangedProcess_map_prodMk_eq_compProd
    (P : SubMarkovKernelSemigroup (State d)) (hP : P.IsConservative)
    (hFeller : P.IsFellerKernelSemigroup) (hK : P.KolmogorovRegular hP)
    (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d)) (x : State d) (t : NNReal)
    (hunb : ∀ᵐ omega ∂(SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP x),
      omega ∈ timeChangeUnboundedEvent a theta) :
    (timeChangedProcess P hP a theta ha hapos default x).map
        (fun eta : ContinuousPath (State d) ↦ (eta t, ContinuousPath.shift t eta)) =
      ((timeChangedProcess P hP a theta ha hapos default x).map
          (fun eta : ContinuousPath (State d) ↦ eta t)) ⊗ₘ
        (timeChangedProcess P hP a theta ha hapos default) := by
  refine map_prodMk_eq_compProd_of_restrict_map _
    (ContinuousPath.measurable_coordinateProcess t)
    (ContinuousPath.measurable_shift_fixed t) _ ?_
  intro B hB
  exact timeChangedProcess_restrict_map_shift P hP hFeller hK ha hapos default x t hunb hB


/-! ### The finite-dimensional marginals -/

/-- **The finite-dimensional marginals of the time-changed process from its
one-dimensional marginals.**  Given almost-sure divergence of the clock (so that
the time-changed process is well defined and restarts) and the identification of
the one-dimensional marginals of the time-changed process with the transition
kernels of `PY`, every finite-time marginal of the time-changed process is the
finite-time law of `PY`.

The induction is exactly the recursion defining
`MarkovProcess.SubMarkovKernelSemigroup.finiteTimeKernel`: the joint law of the
state at the first time and the shifted future factorizes, and the shifted
future is again the time-changed process started at that state. -/
theorem timeChangedProcess_map_finiteEvaluation
    (P : SubMarkovKernelSemigroup (State d)) (hP : P.IsConservative)
    (hFeller : P.IsFellerKernelSemigroup) (hK : P.KolmogorovRegular hP)
    (PY : SubMarkovKernelSemigroup (State d)) (hPY : PY.IsConservative)
    (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d))
    (hunb : ∀ y : State d,
      ∀ᵐ omega ∂(SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP y),
      omega ∈ timeChangeUnboundedEvent a theta)
    (h1d : ∀ (y : State d) (t : NNReal),
      (timeChangedProcess P hP a theta ha hapos default y).map
        (fun eta : ContinuousPath (State d) ↦ eta t) = PY t y)
    {n : ℕ} (times : FiniteOrderedTimes n) (x : State d) :
    (timeChangedProcess P hP a theta ha hapos default x).map
        (ContinuousPath.finiteEvaluation (fun i : Fin n ↦ times i)) =
      SubMarkovKernelSemigroup.finiteTimeKernel PY times x := by
  revert x
  revert times
  induction n with
  | zero =>
      intro times x
      have hconst : ContinuousPath.finiteEvaluation (α := State d) (fun i : Fin 0 ↦ times i) =
          fun _ : ContinuousPath (State d) ↦ FiniteOrderedTimes.emptyPath (State d) := by
        funext eta
        exact FiniteOrderedTimes.eq_emptyPath _
      rw [hconst, SubMarkovKernelSemigroup.finiteTimeKernel_zero, Kernel.const_apply,
        Measure.map_const]
      have : IsProbabilityMeasure (timeChangedProcess P hP a theta ha hapos default x) :=
        IsMarkovKernel.isProbabilityMeasure x
      rw [measure_univ, one_smul]
  | succ n ih =>
      intro times x
      set nu := timeChangedProcess P hP a theta ha hapos default with hnu
      have : IsMarkovKernel (SubMarkovKernelSemigroup.finiteTimeKernel PY times.relativeTail) :=
        hPY.isMarkovKernel_finiteTimeKernel PY times.relativeTail
      have : IsMarkovKernel (PY (times 0)) := hPY.isMarkovKernel (times 0)
      have : IsProbabilityMeasure (PY (times 0) x) := IsMarkovKernel.isProbabilityMeasure x
      have hF : Measurable (ContinuousPath.finiteEvaluation (α := State d)
          (fun j : Fin n ↦ times.relativeTail j)) :=
        ContinuousPath.measurable_finiteEvaluation _
      have hg1 : Measurable (fun eta : ContinuousPath (State d) ↦
          (eta (times 0), ContinuousPath.shift (times 0) eta)) :=
        (ContinuousPath.measurable_coordinateProcess (times 0)).prodMk
          (ContinuousPath.measurable_shift_fixed (times 0))
      have hg2 : Measurable (fun p : State d × ContinuousPath (State d) ↦
          (p.1, ContinuousPath.finiteEvaluation (α := State d)
            (fun j : Fin n ↦ times.relativeTail j) p.2)) :=
        measurable_fst.prodMk (hF.comp measurable_snd)
      have hfun : ContinuousPath.finiteEvaluation (α := State d) (fun i : Fin (n + 1) ↦ times i) =
          (fun z : State d × (Fin n → State d) ↦
              @Fin.cons n (fun _ : Fin (n + 1) ↦ State d) z.1 z.2) ∘
            ((fun p : State d × ContinuousPath (State d) ↦
                (p.1, ContinuousPath.finiteEvaluation (α := State d)
                  (fun j : Fin n ↦ times.relativeTail j) p.2)) ∘
              (fun eta : ContinuousPath (State d) ↦
                (eta (times 0), ContinuousPath.shift (times 0) eta))) := by
        funext eta
        funext i
        refine Fin.cases ?_ (fun j ↦ ?_) i
        · rfl
        · show eta (times j.succ) = _
          rw [Function.comp_apply, Function.comp_apply, Fin.cons_succ]
          show eta (times j.succ) = eta ((times 0) + times.relativeTail j)
          rw [FiniteOrderedTimes.add_relativeTail]
      have hkernel : nu.map (ContinuousPath.finiteEvaluation (α := State d)
          (fun j : Fin n ↦ times.relativeTail j)) =
          SubMarkovKernelSemigroup.finiteTimeKernel PY times.relativeTail := by
        refine Kernel.ext fun y ↦ ?_
        rw [Kernel.map_apply _ hF]
        exact ih times.relativeTail y
      have hj := timeChangedProcess_map_prodMk_eq_compProd P hP hFeller hK ha hapos default
        x (times 0) (hunb x)
      rw [h1d x (times 0)] at hj
      calc
        (nu x).map (ContinuousPath.finiteEvaluation (α := State d) (fun i : Fin (n + 1) ↦ times i))
            = (((nu x).map (fun eta : ContinuousPath (State d) ↦
                  (eta (times 0), ContinuousPath.shift (times 0) eta))).map
                (fun p : State d × ContinuousPath (State d) ↦
                  (p.1, ContinuousPath.finiteEvaluation (α := State d)
                    (fun j : Fin n ↦ times.relativeTail j) p.2))).map
                (fun z : State d × (Fin n → State d) ↦
                  @Fin.cons n (fun _ : Fin (n + 1) ↦ State d) z.1 z.2) := by
          rw [Measure.map_map hg2 hg1, Measure.map_map measurable_finCons (hg2.comp hg1), hfun]
        _ = (((PY (times 0) x) ⊗ₘ nu).map
              (fun p : State d × ContinuousPath (State d) ↦
                (p.1, ContinuousPath.finiteEvaluation (α := State d)
                  (fun j : Fin n ↦ times.relativeTail j) p.2))).map
              (fun z : State d × (Fin n → State d) ↦
                @Fin.cons n (fun _ : Fin (n + 1) ↦ State d) z.1 z.2) := by rw [hj]
        _ = ((PY (times 0) x) ⊗ₘ
              (SubMarkovKernelSemigroup.finiteTimeKernel PY times.relativeTail)).map
              (fun z : State d × (Fin n → State d) ↦
                @Fin.cons n (fun _ : Fin (n + 1) ↦ State d) z.1 z.2) := by
          rw [compProd_map_right _ _ hF, hkernel]
        _ = SubMarkovKernelSemigroup.finiteTimeKernel PY times x := by
          rw [SubMarkovKernelSemigroup.finiteTimeKernel_succ, Kernel.mapOfMeasurable_eq_map,
            Kernel.map_apply _ measurable_finCons, kernel_compProd_prodMkLeft_apply]


/-- The fallback path of the total transform is immaterial for any law under
which the clock diverges almost surely. -/
theorem map_measurableTimeChangedContinuousPath_congr_default
    (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default default' : ContinuousPath (State d))
    (mu : Measure (ContinuousPath (State d)))
    (hmu : ∀ᵐ omega ∂mu, omega ∈ timeChangeUnboundedEvent a theta) :
    mu.map (measurableTimeChangedContinuousPath a theta ha hapos default) =
      mu.map (measurableTimeChangedContinuousPath a theta ha hapos default') := by
  refine Measure.map_congr ?_
  filter_upwards [hmu] with omega homega
  rw [measurableTimeChangedContinuousPath_eq_timeChangedPath ha hapos default homega,
    measurableTimeChangedContinuousPath_eq_timeChangedPath ha hapos default' homega]

/-- **The finite-set marginals of the time-changed process from its
one-dimensional marginals.**  The reindexing of
`timeChangedProcess_map_finiteEvaluation` by a finite set of times. -/
theorem timeChangedProcess_map_finsetEvaluation
    (P : SubMarkovKernelSemigroup (State d)) (hP : P.IsConservative)
    (hFeller : P.IsFellerKernelSemigroup) (hK : P.KolmogorovRegular hP)
    (PY : SubMarkovKernelSemigroup (State d)) (hPY : PY.IsConservative)
    (ha : Continuous (a theta)) (hapos : ∀ x, 0 < a theta x)
    (default : ContinuousPath (State d))
    (hunb : ∀ y : State d,
      ∀ᵐ omega ∂(SubMarkovKernelSemigroup.IsConservative.continuousProcess P hP y),
      omega ∈ timeChangeUnboundedEvent a theta)
    (h1d : ∀ (y : State d) (t : NNReal),
      (timeChangedProcess P hP a theta ha hapos default y).map
        (fun eta : ContinuousPath (State d) ↦ eta t) = PY t y)
    (I : Finset NNReal) (x : State d) :
    (timeChangedProcess P hP a theta ha hapos default x).map
        (ContinuousPath.finsetEvaluation I) =
      SubMarkovKernelSemigroup.finiteSetKernel PY I x := by
  have hbase := timeChangedProcess_map_finiteEvaluation P hP hFeller hK PY hPY ha hapos default
    hunb h1d (SubMarkovKernelSemigroup.finiteSetTimes I) x
  have hF : Measurable (ContinuousPath.finiteEvaluation (α := State d)
      (fun i : Fin I.card ↦ SubMarkovKernelSemigroup.finiteSetTimes I i)) :=
    ContinuousPath.measurable_finiteEvaluation _
  have hO : Measurable (SubMarkovKernelSemigroup.orderedPathToFiniteSet (α := State d) I) :=
    SubMarkovKernelSemigroup.measurable_orderedPathToFiniteSet I
  have hcomp : SubMarkovKernelSemigroup.orderedPathToFiniteSet (α := State d) I ∘
      ContinuousPath.finiteEvaluation (α := State d)
        (fun i : Fin I.card ↦ SubMarkovKernelSemigroup.finiteSetTimes I i) =
      ContinuousPath.finsetEvaluation (alpha := State d) I := by
    funext eta
    funext t
    show eta (SubMarkovKernelSemigroup.finiteSetTimes I ((I.orderIsoOfFin rfl).symm t)) =
      eta ((t : NNReal))
    congr 1
    show (I.orderEmbOfFin rfl) ((I.orderIsoOfFin rfl).symm t) = ((t : NNReal))
    rw [← Finset.coe_orderIsoOfFin_apply, OrderIso.apply_symm_apply]
  rw [SubMarkovKernelSemigroup.finiteSetKernel_eq_map, Kernel.map_apply _ hO, ← hbase,
    Measure.map_map hO hF, hcomp]


/-! ### The sharpened residual for the frozen anchor -/

/-- **The exact residual producer for the frozen v3 anchor, in one-dimensional
form.**  Given almost-sure divergence of the reciprocal clock under the
canonical `(a, a)` process and the identification of the **one-dimensional**
marginals of the time-changed process with the transition kernels of the
`(a, 1)` semigroup, the frozen intrinsic-time-change conclusion holds for every
pair of `CemeteryDiffusion` records.

This sharpens `isIntrinsicTimeChange_of_finiteDimensional_marginals`: the
finite-dimensional hypothesis there has been discharged by the Markov property
of the time-changed process, leaving only a statement about single times. -/
theorem isIntrinsicTimeChange_of_oneDimensional_marginals [MeasurableSpace Theta]
    (a : Theta → State d → ℝ)
    (ha_pos : ∀ theta x, 0 < a theta x)
    (ha_cont : ∀ theta, Continuous (a theta))
    {DXDatum DYDatum : Theta →
      SubdiffusiveProcess.CoarseGrainingVocab.Section8Resolvent.C0ResolventDatum (State d)}
    (DX : GeneratedDiffusionFamily Theta d a a DXDatum)
    (DY : GeneratedDiffusionFamily Theta d a (fun _ _ ↦ 1) DYDatum)
    (PX : CemeteryDiffusion d DX) (PY : CemeteryDiffusion d DY)
    (default : Theta → ContinuousPath (State d))
    (hunbounded : ∀ theta y, ∀ᵐ omega ∂
      ParameterizedSubMarkovKernelSemigroup.IsConservative.continuousProcess
        DX.semigroup DX.conservative (theta, y),
      omega ∈ timeChangeUnboundedEvent a theta)
    (h1d : ∀ theta (y : State d) (t : NNReal),
      (timeChangedProcess (DX.semigroup.toSubMarkovKernelSemigroup theta)
          (DX.conservative theta) a theta (ha_cont theta) (ha_pos theta)
          (default theta) y).map
        (fun eta : ContinuousPath (State d) ↦ eta t) =
      (DY.semigroup.toSubMarkovKernelSemigroup theta) t y) :
    IsIntrinsicTimeChange a
      (Kernel.toLifetimePathKernel PX.law)
      (Kernel.toLifetimePathKernel PY.law) := by
  refine isIntrinsicTimeChange_of_finiteDimensional_marginals a ha_pos ha_cont DX DY PX PY
    (fun theta _ ↦ default theta) hunbounded ?_
  intro theta x I
  have hFellerX : (DX.semigroup.toSubMarkovKernelSemigroup theta).IsFellerKernelSemigroup := by
    rw [DX.semigroup_eq theta]
    exact (DXDatum theta).isFellerKernelSemigroup_fellerKernelSemigroup (DX.denseRange theta)
  obtain ⟨p, q, M, hmom⟩ := DX.displacementMoments
  have hKX := ParameterizedSubMarkovKernelSemigroup.KolmogorovRegular.of_hasKolmogorovMoments
    DX.semigroup DX.conservative hmom theta
  have hunb : ∀ y : State d, ∀ᵐ omega ∂(SubMarkovKernelSemigroup.IsConservative.continuousProcess
      (DX.semigroup.toSubMarkovKernelSemigroup theta) (DX.conservative theta) y),
      omega ∈ timeChangeUnboundedEvent a theta := by
    intro y
    have h := hunbounded theta y
    rwa [ParameterizedSubMarkovKernelSemigroup.IsConservative.continuousProcess_apply] at h
  have hmain := timeChangedProcess_map_finsetEvaluation
    (DX.semigroup.toSubMarkovKernelSemigroup theta) (DX.conservative theta) hFellerX hKX
    (DY.semigroup.toSubMarkovKernelSemigroup theta) (DY.conservative theta)
    (ha_cont theta) (ha_pos theta) (default theta) hunb (h1d theta) I x
  rw [timeChangedProcess_apply,
    ← ParameterizedSubMarkovKernelSemigroup.IsConservative.continuousProcess_apply] at hmain
  exact hmain

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section7Clock
