module
public import Mathlib

/-!
# Large-scale Hölder regularity and a Liouville theorem (Theorem C, paper label `t.C`)

Mathlib-only statement of Theorem C. Fix `d ≥ 2`. There are `δ₀, C₀, C > 0`, depending only on
`d`, such that for every model `M : GMCModel d` of disorder `δ = M.delta ≤ δ₀` (independent
layers `g_k` with the exact triadic scaling and the assumptions (g1)–(g4) of the paper) the
following hold, with `γ_reg = 1 − C₀ δ √|log δ|`.

1. *Large-scale Hölder estimate.* For every `γ ∈ [1/2, γ_reg]`, every cutoff `L ∈ ℕ ∪ {∞}` and
   every `m ≥ 1` there is a random `ℕ`-valued minimal scale `𝓛_L(γ, m)` with
   `P[𝓛_L(γ, m) > k] ≤ C exp(−(1−γ)² (k − C)₊ / (C δ² |log δ|))` for every `k ≥ 1`. Almost surely,
   for all `L` and `m`, every `a_L`-harmonic `u ∈ H¹(𝒞ₘ)`, every `n ≤ m − 𝓛_L(γ, m)` and every
   `z ∈ 3ⁿℤᵈ` with `z + 𝒞ₙ ⊆ 𝒞ₘ₋₁`:
   `‖u − (u)_{z+𝒞ₙ}‖_{L²(z+𝒞ₙ)} ≤ C 3^{−γ(m−n)} ‖u − (u)_{𝒞ₘ}‖_{L²(𝒞ₘ)}` and
   `‖√a_L ∇u‖_{L²(z+𝒞ₙ)} ≤ C 3^{(1−γ)(m−n)} ‖√a_L ∇u‖_{L²(𝒞ₘ)}`.
2. *Liouville theorem.* Almost surely, for every `L`, every `u ∈ H¹_loc(ℝᵈ)` that is
   `a_L`-harmonic and satisfies `liminf_{R→∞} R^{−γ_reg} inf_c ‖u − c‖_{L²(B_R)} = 0` is constant.

Here `a_L = exp(Σ_{k ≤ L} (g_k − τ²))` for finite `L` and `a_∞ = exp(Σ_{k ≥ 0} (g_k − g_k(0)))`.
Cubes and balls use the maximum norm, `L²` norms are volume-normalized, and `(u)_U` is the average
of `u` on `U`.

## How this differs from the wording of the paper

Every difference either adds a conclusion or restates a hypothesis in an equivalent or weaker
form.

1. *Sample space.* A model is a law `P` on sequences of regular potentials (`ℕ → PotentialField
   d`, each layer `C¹` with locally Lipschitz derivative), so "almost surely `C^{1,1}_loc`" in
   (g2) is built into the sample space. The size in (g2) is `‖g‖_∞ + ‖∇g‖_∞ + Lip(∇g)` on `(−1/2,
   1/2)ᵈ`, with the maximum norm on space and its dual norm on gradients, as in the paper.
2. *Range of dependence (g1).* Independence is imposed on the σ-algebras generated by integrals of
   the field against bounded measurable test functions with compact support that vanish outside
   `U` (resp. `V`), for measurable `U`, `V` at Euclidean distance at least `√d`. These are
   contained in the σ-algebras generated by the values of the field on `U` and `V`, so the
   hypothesis is not stronger than the paper's.
3. *Uncut coefficient.* For `L = ∞` the carrier `AnchoredC11Sample d` consists of the samples for
   which `Σ_k (g_k − g_k(0))` converges in `C^{1,1}_loc`; "almost surely" refers to the pullback
   of `P` to this carrier, which has probability one, so it is not the zero measure.
4. *Extra conclusions.* `γ_reg ∈ (1/2, 1)`; each `𝓛_L(γ, m)` is measurable; and the Liouville
   conclusion is a constant continuous representative equal almost everywhere to `u`, which says
   exactly that `u` is almost everywhere constant. Nothing is claimed about pointwise Hölder
   regularity at the microscopic scale.
5. *Quantifier placement.* The Liouville clause is stated inside the quantifier over `γ` but does
   not depend on `γ`; since `[1/2, γ_reg]` is nonempty this is the paper's statement.
6. *Weak solutions.* `a`-harmonic means weakly harmonic against `H¹₀` test functions (the closure
   of `C_c^∞` in `H¹`); for locally bounded coefficients this is the same as testing against
   `C_c^∞`.

Only Mathlib is imported. The sole intentional `sorry` is the proof of the final theorem; the
separate Solution proves the same statement from the library.
-/

@[expose] public section
set_option autoImplicit false
noncomputable section
namespace SubdiffusiveProcessAudit.AnomalousHolderRegularity
open scoped BigOperators
namespace Homogenization
/-- The coordinate space ℝᵈ, with its sup-norm topology. -/
abbrev Vec (d : ℕ) :=
  Fin d → ℝ
/-- Real d-by-d matrices acting on the coordinate space. -/
abbrev Mat (d : ℕ) :=
  Matrix (Fin d) (Fin d) ℝ
/-- The Euclidean scalar product, expressed as a sum over coordinates. -/
def vecDot {d : ℕ} (x y : Homogenization.Vec d) : ℝ :=
  ∑ i, x i * y i
/-- The squared Euclidean norm. -/
def vecNormSq {d : ℕ} (x : Homogenization.Vec d) : ℝ :=
  vecDot x x
/-- Matrix multiplication of a coordinate vector. -/
def matVecMul {d : ℕ} (A : Mat d) (x : Homogenization.Vec d) : Homogenization.Vec d := fun i =>
  ∑ j, A i j * x j
/-- The Euclidean norm, as the square root of the scalar product. -/
noncomputable def euclideanNorm {d : ℕ} (x : Homogenization.Vec d) : ℝ :=
  Real.sqrt (vecNormSq x)
end Homogenization
open _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.Homogenization Topology
/-- A scalar field with a continuous derivative and locally Lipschitz derivative. -/
def SubdiffusiveProcess.Model.PotentialField (d : ℕ) :=
  { p : C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) //
    (∀ x, HasFDerivAt p.1 (p.2 x) x) ∧
      ∀ K : Set (Homogenization.Vec d), IsCompact K → ∃ C : NNReal, LipschitzOnWith C p.2 K }
namespace Homogenization
/-- The scalar multiple of the identity matrix. -/
abbrev scalarMatrix {d : ℕ} (sigma : ℝ) : Mat d :=
  sigma • (1 : Mat d)
open MeasureTheory
/-- A matrix field whose entries are measurable and locally integrable. -/
structure RegCoeffField (d : ℕ) where
  toFun : Homogenization.Vec d → Mat d
  entry_measurable : ∀ i j, Measurable (fun x : Homogenization.Vec d => toFun x i j)
  entry_locInt : ∀ i j, LocallyIntegrable (fun x : Homogenization.Vec d => toFun x i j) volume
namespace RegCoeffField
variable {d : ℕ}
instance : CoeFun (RegCoeffField d) (fun _ => Homogenization.Vec d → Mat d) :=
  ⟨toFun⟩
end RegCoeffField
open MeasureTheory
variable {d : ℕ}
/-- A bounded measurable test function with compact support. -/
structure IsProbeR (φ : Homogenization.Vec d → ℝ) : Prop where
  measurable : Measurable φ
  bounded : ∃ C : ℝ, ∀ x, |φ x| ≤ C
  hasCompactSupport : HasCompactSupport φ
/-- The integral of one matrix entry against a scalar test function. -/
def entryTestR (i j : Fin d) (φ : Homogenization.Vec d → ℝ) (a : RegCoeffField d) : ℝ :=
  ∫ x, a x i j * φ x ∂volume
/-- The local coefficient σ-algebra generated by entry integrals against supported
probes. -/
def LocalSigmaR (U : Set (Homogenization.Vec d)) : MeasurableSpace (RegCoeffField d) :=
  MeasurableSpace.generateFrom
    {s |
      ∃ (i j : Fin d) (φ : Homogenization.Vec d → ℝ),
        IsProbeR φ ∧
          Function.support φ ⊆ U ∧ ∃ t : Set ℝ, MeasurableSet t ∧ s = entryTestR i j φ ⁻¹' t}
end Homogenization
namespace SubdiffusiveProcess.Model
open _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.Homogenization MeasureTheory Topology
noncomputable instance potentialFieldTopologicalSpace (d : ℕ) :
    TopologicalSpace (PotentialField d) :=
  TopologicalSpace.induced Subtype.val inferInstance
noncomputable instance potentialFieldMeasurableSpace (d : ℕ) : MeasurableSpace (PotentialField d) :=
  borel (PotentialField d)
instance potentialFieldBorelSpace (d : ℕ) : BorelSpace (PotentialField d) :=
  ⟨rfl⟩
namespace PotentialField
variable {d : ℕ}
instance : CoeFun (PotentialField d) (fun _ ↦ Homogenization.Vec d → ℝ) :=
  ⟨fun g ↦ g.1.1⟩
/-- The continuous derivative stored with a potential field. -/
def deriv (g : PotentialField d) : C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  g.1.2
theorem hasFDerivAt (g : PotentialField d) (x : Homogenization.Vec d) :
    HasFDerivAt g (deriv g x) x :=
  g.2.1 x
/-- The regular matrix field g(x)·Id obtained by forgetting the derivative data of
a scalar potential. -/
def forgetPotential (g : PotentialField d) : RegCoeffField d
    where
  toFun x := scalarMatrix (d := d) (g x)
  entry_measurable := fun i k ↦
    by
    have hmat : Continuous (fun x : Homogenization.Vec d ↦ scalarMatrix (d := d) (g x)) :=
      g.1.1.continuous.smul continuous_const
    exact ((continuous_apply k).comp ((continuous_apply i).comp hmat)).measurable
  entry_locInt := fun i k ↦
    by
    have hmat : Continuous (fun x : Homogenization.Vec d ↦ scalarMatrix (d := d) (g x)) :=
      g.1.1.continuous.smul continuous_const
    exact ((continuous_apply k).comp ((continuous_apply i).comp hmat)).locallyIntegrable
end PotentialField
end SubdiffusiveProcess.Model
namespace Homogenization
/-- An orthogonal coordinate permutation with independently chosen coordinate
signs. -/
def IsSignedPermutationMatrix {d : ℕ} (R : Mat d) : Prop :=
  ∃ σ : Equiv.Perm (Fin d),
    ∃ s : Fin d → ℝ, (∀ i, s i = 1 ∨ s i = -1) ∧ ∀ i j, R i j = if i = σ j then s j else 0
end Homogenization
namespace SubdiffusiveProcess.Model.PotentialField
variable {d : ℕ}
/-- Multiplication by a scalar, as a continuous map on potential values. -/
def valueScaleMap (c : ℝ) : C(ℝ, ℝ) :=
  ⟨fun y ↦ c * y, continuous_const.mul continuous_id⟩
/-- Multiplication by a scalar on the space of derivative linear maps. -/
def derivScaleCLM (c : ℝ) : (Homogenization.Vec d →L[ℝ] ℝ) →L[ℝ] (Homogenization.Vec d →L[ℝ] ℝ) :=
  c • ContinuousLinearMap.id ℝ (Homogenization.Vec d →L[ℝ] ℝ)
/-- The continuous-map form of scalar multiplication on derivatives. -/
def derivScaleMap (c : ℝ) : C(Homogenization.Vec d →L[ℝ] ℝ, Homogenization.Vec d →L[ℝ] ℝ) :=
  ⟨derivScaleCLM c, (derivScaleCLM c).continuous⟩
/-- Scalar multiplication of a field and its derivative before restricting to
regular fields. -/
def scaleAmbient (c : ℝ) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ ((valueScaleMap c).comp p.1, (derivScaleMap c).comp p.2)
/-- Scalar multiplication of a regular potential field. -/
def scale (c : ℝ) (g : PotentialField d) : PotentialField d :=
  ⟨scaleAmbient c g.1, by
    constructor
    · intro x
      simpa only [scaleAmbient, valueScaleMap, derivScaleMap, derivScaleCLM,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply] using!
        (g.hasFDerivAt x).const_smul c
    · intro K hK
      obtain ⟨C, hC⟩ := g.2.2 K hK
      refine ⟨‖derivScaleCLM (d := d) c‖₊ * C, ?_⟩
      simpa only [scaleAmbient, derivScaleMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def] using!
        (derivScaleCLM (d := d) c).lipschitzWith.comp_lipschitzOnWith hC⟩
/-- The continuous spatial translation used to pull back a field. -/
def translateMap (z : Homogenization.Vec d) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨fun x ↦ x + z, continuous_id.add continuous_const⟩
/-- Translation of a field together with its derivative. -/
def translateAmbient (z : Homogenization.Vec d) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ (p.1.comp (translateMap z), p.2.comp (translateMap z))
/-- Translation of a regular potential field. -/
def translate (z : Homogenization.Vec d) (g : PotentialField d) : PotentialField d :=
  ⟨translateAmbient z g.1, by
    constructor
    · intro x
      simpa only [translateAmbient, translateMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def] using!
        (g.hasFDerivAt (x + z)).comp x ((hasFDerivAt_id x).add_const z)
    · intro K hK
      let T : Homogenization.Vec d → Homogenization.Vec d := fun x ↦ x + z
      obtain ⟨C, hC⟩ := g.2.2 (T '' K) (hK.image (isometry_add_right z).continuous)
      refine ⟨C, ?_⟩
      simpa only [translateAmbient, translateMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def, T, mul_one] using!
        hC.comp (isometry_add_right z).lipschitzWith.lipschitzOnWith (Set.mapsTo_image T K)⟩
/-- The continuous linear spatial dilation x ↦ r x. -/
def spatialCLM (r : ℝ) : Homogenization.Vec d →L[ℝ] Homogenization.Vec d :=
  r • ContinuousLinearMap.id ℝ (Homogenization.Vec d)
/-- Spatial dilation regarded as a continuous map. -/
def spatialMap (r : ℝ) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨spatialCLM r, (spatialCLM r).continuous⟩
/-- Pullback by spatial dilation, including the derivative chain-rule factor. -/
def spatialScaleAmbient (r : ℝ) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ (p.1.comp (spatialMap r), (derivScaleMap r).comp (p.2.comp (spatialMap r)))
/-- Spatial dilation of a regular potential field. -/
def spatialScale (r : ℝ) (g : PotentialField d) : PotentialField d :=
  ⟨spatialScaleAmbient r g.1, by
    constructor
    · intro x
      simpa only [spatialScaleAmbient, spatialMap, spatialCLM, derivScaleMap, derivScaleCLM,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        ContinuousMap.coe_mk, ContinuousMap.coe_comp, ContinuousLinearMap.comp_smul,
        ContinuousLinearMap.comp_id, Function.comp_def] using!
        (g.hasFDerivAt (r • x)).comp x ((hasFDerivAt_id x).const_smul r)
    · intro K hK
      let S : Homogenization.Vec d → Homogenization.Vec d := spatialCLM (d := d) r
      obtain ⟨C, hC⟩ := g.2.2 (S '' K) (hK.image (spatialCLM (d := d) r).continuous)
      have hinner :=
        hC.comp (spatialCLM (d := d) r).lipschitzWith.lipschitzOnWith (Set.mapsTo_image S K)
      refine ⟨‖derivScaleCLM (d := d) r‖₊ * (C * ‖spatialCLM (d := d) r‖₊), ?_⟩
      simpa only [spatialScaleAmbient, spatialMap, derivScaleMap, ContinuousMap.comp_apply,
        ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq,
        smul_apply, ContinuousLinearMap.id_apply, Function.comp_def, S] using!
        (derivScaleCLM (d := d) r).lipschitzWith.comp_lipschitzOnWith hinner⟩
/-- Pullback by the inverse triadic dilation x ↦ 3⁻ᵏ x. -/
def triadicScale (k : ℕ) (g : PotentialField d) : PotentialField d :=
  spatialScale (((3 : ℝ) ^ k)⁻¹) g
/-- Negation of a regular potential field. -/
def negate (g : PotentialField d) : PotentialField d :=
  scale (-1) g
/-- Matrix action on vectors as a continuous linear map. -/
def matVecContinuousLinearMap (R : Mat d) : Homogenization.Vec d →L[ℝ] Homogenization.Vec d :=
  ⟨Matrix.toLin' R, (Matrix.toLin' R).continuous_of_finiteDimensional⟩
/-- The derivative transformation under a signed coordinate permutation. -/
def rotateDerivativeMap (R : Mat d) :
    (Homogenization.Vec d →L[ℝ] ℝ) →L[ℝ] (Homogenization.Vec d →L[ℝ] ℝ) :=
  (ContinuousLinearMap.compL ℝ (Homogenization.Vec d) (Homogenization.Vec d) ℝ).flip
    (matVecContinuousLinearMap R)
/-- The spatial signed-coordinate permutation as a continuous map. -/
def rotateDomainMap (R : Mat d) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨matVecContinuousLinearMap R, (matVecContinuousLinearMap R).continuous⟩
/-- The continuous-map form of the derivative transformation under rotation. -/
def rotateDerivativeContinuousMap (R : Mat d) :
    C(Homogenization.Vec d →L[ℝ] ℝ, Homogenization.Vec d →L[ℝ] ℝ) :=
  ⟨rotateDerivativeMap R, (rotateDerivativeMap R).continuous⟩
/-- Pullback of a field and its derivative under a signed coordinate permutation. -/
def rotateAmbient (R : Mat d) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦
  (p.1.comp (rotateDomainMap R),
    (rotateDerivativeContinuousMap R).comp (p.2.comp (rotateDomainMap R)))
/-- The regular potential field obtained by a signed coordinate permutation. -/
def rotate (R : Mat d) (_hR : IsSignedPermutationMatrix R) (g : PotentialField d) :
    PotentialField d :=
  ⟨rotateAmbient R g.1, by
    constructor
    · intro x
      simpa only [rotateAmbient, rotateDomainMap, rotateDerivativeContinuousMap,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        rotateDerivativeMap] using!
        (g.hasFDerivAt (matVecMul R x)).comp x (matVecContinuousLinearMap R).hasFDerivAt
    · intro K hK
      let S : Homogenization.Vec d → Homogenization.Vec d := matVecContinuousLinearMap R
      obtain ⟨C, hC⟩ := g.2.2 (S '' K) (hK.image (matVecContinuousLinearMap R).continuous)
      have hinner :=
        hC.comp (matVecContinuousLinearMap R).lipschitzWith.lipschitzOnWith (Set.mapsTo_image S K)
      refine ⟨‖rotateDerivativeMap R‖₊ * (C * ‖matVecContinuousLinearMap R‖₊), ?_⟩
      simpa only [rotateAmbient, rotateDomainMap, rotateDerivativeContinuousMap,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        Function.comp_def, S] using!
        (rotateDerivativeMap R).lipschitzWith.comp_lipschitzOnWith hinner⟩
end SubdiffusiveProcess.Model.PotentialField
/-- A sequence of regular potential layers indexed by nonnegative integers. -/
abbrev SubdiffusiveProcess.Model.PotentialSample (d : ℕ) :=
  ℕ → SubdiffusiveProcess.Model.PotentialField d
namespace SubdiffusiveProcess.Model
open Filter _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.Homogenization Topology
namespace PotentialField
variable {d : ℕ}
/-- Addition of two regular potential fields. -/
def add (g h : PotentialField d) : PotentialField d :=
  ⟨(g.1.1 + h.1.1, deriv g + deriv h), by
    constructor
    · intro x
      exact (g.hasFDerivAt x).add (h.hasFDerivAt x)
    · intro K hK
      obtain ⟨Cg, hg⟩ := g.2.2 K hK
      obtain ⟨Ch, hh⟩ := h.2.2 K hK
      exact ⟨Cg + Ch, hg.add hh⟩⟩
/-- Subtracting the value at the origin from a regular potential field. -/
def anchor (g : PotentialField d) : PotentialField d :=
  ⟨(⟨fun x ↦ g x - g 0, g.1.1.continuous.sub continuous_const⟩, deriv g),
    by
    constructor
    · intro x
      exact (g.hasFDerivAt x).sub_const (g 0)
    · exact g.2.2⟩
end PotentialField
variable {d : ℕ}
/-- The finite potential-layer sum with each layer anchored at the origin. -/
def anchoredPartialSum (omega : PotentialSample d) (L : ℕ) (x : Homogenization.Vec d) : ℝ :=
  ∑ k ∈ Finset.range (L + 1), (omega k x - omega k 0)
/-- The anchored finite layer sum packaged as a regular potential field. -/
def anchoredPartialSumField (omega : PotentialSample d) : ℕ → PotentialField d
  | 0 => PotentialField.anchor (omega 0)
  | L + 1 =>
    PotentialField.add (anchoredPartialSumField omega L) (PotentialField.anchor (omega (L + 1)))
/-- The Cauchy condition in the derivative Lipschitz seminorm on a spatial set. -/
def LipschitzSeminormCauchyOn (F : ℕ → Homogenization.Vec d → (Homogenization.Vec d →L[ℝ] ℝ))
    (K : Set (Homogenization.Vec d)) : Prop :=
  ∀ epsilon : ℝ,
    0 < epsilon →
      ∃ N : ℕ,
        ∀ m n : ℕ, N ≤ m → N ≤ n → LipschitzOnWith (Real.toNNReal epsilon) (fun x ↦ F m x - F n x) K
end SubdiffusiveProcess.Model
open MeasureTheory ProbabilityTheory
/-- The marginal probability law of one potential layer. -/
noncomputable def SubdiffusiveProcess.Model.potentialMarginalLaw {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) (k : ℕ) :
    ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialField d) :=
  P.map (fun omega => omega k)
/-- The probability law of the layer at scale zero. -/
noncomputable def SubdiffusiveProcess.Model.zeroPotentialLaw {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) :
    ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialField d) :=
  SubdiffusiveProcess.Model.potentialMarginalLaw P 0
/-- Dimension and disorder bounds, layer independence and exact triadic marginal
scaling. -/
structure SubdiffusiveProcess.Model.ShellLawPrefix (d : ℕ) (delta : ℝ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  dimension : 2 ≤ d
  delta_pos : 0 < delta
  delta_le_half : delta ≤ (1 : ℝ) / 2
  independent :
    iIndepFun (fun k : ℕ ↦ fun ω : SubdiffusiveProcess.Model.PotentialSample d ↦ ω k)
      P.toMeasure
  marginal_scaling :
    ∀ k : ℕ,
      SubdiffusiveProcess.Model.potentialMarginalLaw P k =
        (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
          (SubdiffusiveProcess.Model.PotentialField.triadicScale k)
/-- The local σ-algebra generated by supported integral probes of the scalar field
represented as g(x)·Id. -/
def SubdiffusiveProcess.Model.PotentialField.localSigma {d : ℕ}
    (U : Set (Homogenization.Vec d)) :
    MeasurableSpace (SubdiffusiveProcess.Model.PotentialField d) :=
  MeasurableSpace.comap SubdiffusiveProcess.Model.PotentialField.forgetPotential
    (LocalSigmaR U)
/-- Assumption (g1): integrability, mean zero, stationarity and finite-range
independence. -/
structure SubdiffusiveProcess.Model.ShellLawG1 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  integrable :
    ∀ x : Homogenization.Vec d,
      Integrable (fun ω : SubdiffusiveProcess.Model.PotentialSample d ↦ ω 0 x)
        P.toMeasure
  mean_zero :
    ∀ x : Homogenization.Vec d,
      ∫ ω : SubdiffusiveProcess.Model.PotentialSample d, ω 0 x ∂P.toMeasure = 0
  stationary :
    ∀ z : Homogenization.Vec d,
      Measure.map (SubdiffusiveProcess.Model.PotentialField.translate z)
          (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure =
        (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
  range_dependence :
    ∀ (U V : Set (Homogenization.Vec d)),
      MeasurableSet U →
        MeasurableSet V →
          (∀ ⦃x y : Homogenization.Vec d⦄,
              x ∈ U → y ∈ V → Real.sqrt (d : ℝ) ≤ euclideanNorm (x - y)) →
            Indep (SubdiffusiveProcess.Model.PotentialField.localSigma U)
              (SubdiffusiveProcess.Model.PotentialField.localSigma V)
              (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
namespace Homogenization
/-- A triadic cube specified by its integer scale and lattice center. -/
structure TriadicCube (d : ℕ) where
  scale : ℤ
  index : Fin d → ℤ
/-- The side-length factor 3 to the cube's integer scale. -/
noncomputable def cubeScaleFactor {d : ℕ} (Q : TriadicCube d) : ℝ :=
  (3 : ℝ) ^ Q.scale
/-- The open cube with the specified triadic center and side length. -/
def openCubeSet {d : ℕ} (Q : TriadicCube d) : Set (Homogenization.Vec d) :=
  {x |
    ∀ i,
      (((Q.index i : ℝ) - (1 / 2 : ℝ)) * cubeScaleFactor Q < x i) ∧
        (x i < (((Q.index i : ℝ) + (1 / 2 : ℝ)) * cubeScaleFactor Q))}
/-- The triadic cube centered at the origin at the specified scale. -/
def originCube (d : ℕ) (m : ℤ) : TriadicCube d :=
  { scale := m
    index := 0 }
end Homogenization
/-- The supremum of the absolute potential on the open unit cube, with zero
included in the supremum set. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.unitCubeValueNorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range fun o : Option { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ↦
      match o with
      | none => 0
      | some x => |g x.1|)
/-- The supremum of the derivative operator norm on the open unit cube, with zero
included. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.unitCubeDerivNorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range fun o : Option { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ↦
      match o with
      | none => 0
      | some x => ‖SubdiffusiveProcess.Model.PotentialField.deriv g x.1‖)
/-- The Lipschitz seminorm of the derivative on the open unit cube. -/
noncomputable def
  SubdiffusiveProcess.Model.PotentialField.unitCubeDerivLipschitzSeminorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range
      fun o :
        Option
          { p :
            ({ x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ×
              { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) }) //
            p.1 ≠ p.2 } ↦
      match o with
      | none => 0
      | some p =>
        dist (SubdiffusiveProcess.Model.PotentialField.deriv g p.1.1.1)
            (SubdiffusiveProcess.Model.PotentialField.deriv g p.1.2.1) /
          dist p.1.1.1 p.1.2.1)
/-- The sum of the unit-cube value, derivative and derivative-Lipschitz sizes. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.g2Observable {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  SubdiffusiveProcess.Model.PotentialField.unitCubeValueNorm g +
      SubdiffusiveProcess.Model.PotentialField.unitCubeDerivNorm g +
    SubdiffusiveProcess.Model.PotentialField.unitCubeDerivLipschitzSeminorm g
/-- The moment condition `E exp((max(X,0)/A)^σ) ≤ 2`, with the integrand integrable
(`σ = 2` is the sub-Gaussian case). -/
def SubdiffusiveProcess.OGammaLE {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (σ A : ℝ)
    (X : Ω → ℝ) : Prop :=
  Integrable (fun ω ↦ Real.exp ((A⁻¹ * max (X ω) 0) ^ σ)) μ ∧
    ∫ ω, Real.exp ((A⁻¹ * max (X ω) 0) ^ σ) ∂μ ≤ 2
/-- Assumption (g2): the disorder-scaled exponential moment of the unit-cube C¹,¹
size. -/
structure SubdiffusiveProcess.Model.ShellLawG2 (d : ℕ) (delta : ℝ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  regularity_expectation :
    SubdiffusiveProcess.OGammaLE
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure 2 delta
      SubdiffusiveProcess.Model.PotentialField.g2Observable
/-- Assumption (g3): invariance under signed coordinate permutations and field
negation. -/
structure SubdiffusiveProcess.Model.ShellLawG3 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  signed_coordinate_permutations :
    ∀ (R : Mat d) (hR : IsSignedPermutationMatrix R),
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
          (SubdiffusiveProcess.Model.PotentialField.rotate R hR) =
        SubdiffusiveProcess.Model.zeroPotentialLaw P
  negation :
    (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
        SubdiffusiveProcess.Model.PotentialField.negate =
      SubdiffusiveProcess.Model.zeroPotentialLaw P
/-- The logarithm of the zero-layer exponential moment at the origin, denoted τ²
in the paper. -/
noncomputable def SubdiffusiveProcess.Model.tauSq {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : ℝ :=
  Real.log
    (∫ g : SubdiffusiveProcess.Model.PotentialField d,
      Real.exp (g 0) ∂(SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure)
/-- Assumption (g4): integrability of the exponential at the origin and positivity
of τ². -/
structure SubdiffusiveProcess.Model.ShellLawG4 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  exponential_integrable :
    Integrable (fun g : SubdiffusiveProcess.Model.PotentialField d ↦ Real.exp (g 0))
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
  tauSq_pos : 0 < SubdiffusiveProcess.Model.tauSq P
/-- A supplied layer probability law and positive disorder satisfying the standing
assumptions (g1)–(g4). -/
structure SubdiffusiveProcess.Model.GMCModel (d : ℕ) where
  delta : ℝ
  P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)
  shellPrefix : SubdiffusiveProcess.Model.ShellLawPrefix d delta P
  G1 : SubdiffusiveProcess.Model.ShellLawG1 d P
  G2 : SubdiffusiveProcess.Model.ShellLawG2 d delta P
  G3 : SubdiffusiveProcess.Model.ShellLawG3 d P
  G4 : SubdiffusiveProcess.Model.ShellLawG4 d P
/-- The exponential of the layer sum through cutoff L, centered by (L+1)τ². -/
noncomputable def SubdiffusiveProcess.Model.aCutoff {d : ℕ}
    (M : SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
    (ω : SubdiffusiveProcess.Model.PotentialSample d) (x : Homogenization.Vec d) : ℝ :=
  Real.exp (∑ k ∈ Finset.range (L + 1), (ω k x - SubdiffusiveProcess.Model.tauSq M.P))
namespace Homogenization
/-- The coordinate basis vector with value one in the specified coordinate. -/
def basisVec {d : ℕ} (i : Fin d) : Homogenization.Vec d :=
  Pi.single i (1 : ℝ)
/-- The distributional integration-by-parts identity for one partial derivative. -/
def HasWeakPartialDerivOn {d : ℕ} (U : Set (Homogenization.Vec d)) (i : Fin d)
    (u gi : Homogenization.Vec d → ℝ) : Prop :=
  ∀ φ : Homogenization.Vec d → ℝ,
    ContDiff ℝ (⊤ : ℕ∞) φ →
      HasCompactSupport φ →
        tsupport φ ⊆ U →
          ∫ x in U, u x * (fderiv ℝ φ x) (basisVec i) ∂MeasureTheory.volume =
            -∫ x in U, gi x * φ x ∂MeasureTheory.volume
/-- The distributional integration-by-parts identities for all gradient
components. -/
def HasWeakGradientOn {d : ℕ} (U : Set (Homogenization.Vec d)) (u : Homogenization.Vec d → ℝ)
    (Du : Homogenization.Vec d → Homogenization.Vec d) : Prop :=
  ∀ i : Fin d, HasWeakPartialDerivOn U i u (fun x => Du x i)
/-- Square integrability on the specified domain with restricted Lebesgue measure. -/
abbrev MemL2On {d : ℕ} (U : Set (Homogenization.Vec d)) (u : Homogenization.Vec d → ℝ) : Prop :=
  MeasureTheory.MemLp u 2 (MeasureTheory.volume.restrict U)
/-- Square integrability of each weak gradient component on the domain. -/
def GradMemL2On {d : ℕ} (U : Set (Homogenization.Vec d))
    (Du : Homogenization.Vec d → Homogenization.Vec d) : Prop :=
  ∀ i : Fin d, MemL2On U (fun x => Du x i)
/-- A function and weak gradient with the L² certificates defining H¹ on a domain. -/
structure H1Function {d : ℕ} (U : Set (Homogenization.Vec d)) where
  toFun : Homogenization.Vec d → ℝ
  grad : Homogenization.Vec d → Homogenization.Vec d
  memL2 : MemL2On U toFun
  gradMemL2 : GradMemL2On U grad
  hasWeakGradient : HasWeakGradientOn U toFun grad
instance {d : ℕ} {U : Set (Homogenization.Vec d)} :
    CoeFun (H1Function U) (fun _ => Homogenization.Vec d → ℝ) where coe u := u.toFun
/-- An H¹ function approximable by compactly supported smooth functions in H¹,
encoding zero trace. -/
structure H10Function {d : ℕ} (U : Set (Homogenization.Vec d)) extends H1Function U where
  approx : ℕ → Homogenization.Vec d → ℝ
  approx_smooth : ∀ n, ContDiff ℝ (⊤ : ℕ∞) (approx n)
  approx_hasCompactSupport : ∀ n, HasCompactSupport (approx n)
  approx_support_subset : ∀ n, tsupport (approx n) ⊆ U
  tendsto_approx :
    Filter.Tendsto
      (fun n =>
        MeasureTheory.eLpNorm (fun x => approx n x - toH1Function.toFun x) 2
          (MeasureTheory.volume.restrict U))
      Filter.atTop (nhds 0)
  tendsto_approx_grad :
    ∀ i : Fin d,
      Filter.Tendsto
        (fun n =>
          MeasureTheory.eLpNorm
            (fun x => (fderiv ℝ (approx n) x) (basisVec i) - toH1Function.grad x i) 2
            (MeasureTheory.volume.restrict U))
        Filter.atTop (nhds 0)
instance {d : ℕ} {U : Set (Homogenization.Vec d)} :
    CoeFun (H10Function U) (fun _ => Homogenization.Vec d → ℝ) where coe u := u.toH1Function.toFun
/-- The Lebesgue-volume-normalized average on a spatial set. -/
noncomputable def volumeAverage {d : ℕ} (U : Set (Homogenization.Vec d))
    (f : Homogenization.Vec d → ℝ) : ℝ :=
  (MeasureTheory.volume U).toReal⁻¹ * ∫ x in U, f x ∂MeasureTheory.volume
end Homogenization
namespace SubdiffusiveProcess.CoarseGrainingVocab
open Filter MeasureTheory
/-- The coordinate space ℝᵈ, with its sup-norm topology. -/
abbrev Vec (d : ℕ) :=
  Homogenization.Vec d
open Filter MeasureTheory _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.Homogenization
open scoped BigOperators ENNReal Topology
attribute [local instance] Classical.propDecidable
/-- The origin-centered triadic cube at the specified integer scale. -/
def cube (d : ℕ) (m : ℤ) : Set (Homogenization.Vec d) :=
  openCubeSet (originCube d m)
/-- A triadic cube translated by the specified center. -/
def translatedCube (d : ℕ) (m : ℤ) (z : Homogenization.Vec d) : Set (Homogenization.Vec d) :=
  (fun x ↦ z + x) '' cube d m
/-- The weak divergence-form harmonic equation with scalar coefficient on the
domain. -/
def IsWeaklyHarmonicOn {d : ℕ} (a : Homogenization.Vec d → ℝ) (W : Set (Homogenization.Vec d))
    (u : H1Function W) : Prop :=
  ∀ φ : H10Function W, ∫ x in W, vecDot (a x • u.grad x) (φ.toH1Function.grad x) ∂volume = 0
/-- The L² size normalized by the volume of a spatial set. -/
def normalizedL2On {d : ℕ} (W : Set (Homogenization.Vec d)) (f : Homogenization.Vec d → ℝ) : ℝ :=
  Real.sqrt (volumeAverage W (fun x ↦ f x ^ 2))
/-- The volume-normalized L² size of the Euclidean norm of a vector field. -/
def vectorNormalizedL2On {d : ℕ} (W : Set (Homogenization.Vec d))
    (f : Homogenization.Vec d → Homogenization.Vec d) : ℝ :=
  normalizedL2On W (fun x ↦ Homogenization.euclideanNorm (f x))
/-- The Lebesgue-volume-normalized average on the spatial set. -/
def averageOn {d : ℕ} (W : Set (Homogenization.Vec d)) (f : Homogenization.Vec d → ℝ) : ℝ :=
  volumeAverage W f
/-- The center belongs to the lattice 3ⁿℤᵈ. -/
def OnTriadicGrid {d : ℕ} (n : ℕ) (z : Homogenization.Vec d) : Prop :=
  ∀ i : Fin d, ∃ k : ℤ, z i = (3 : ℝ) ^ n * k
end SubdiffusiveProcess.CoarseGrainingVocab
open Filter _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.Homogenization Topology
/-- Compact-uniform convergence of the anchored layer sums and derivatives,
derivative Lipschitz-Cauchy control, and value zero at the origin. -/
structure SubdiffusiveProcess.Model.IsAnchoredC11Limit {d : ℕ}
    (omega : SubdiffusiveProcess.Model.PotentialSample d)
    (g : SubdiffusiveProcess.Model.PotentialField d) : Prop where
  value_tendsto :
    ∀ K : Set (Homogenization.Vec d),
      IsCompact K →
        TendstoUniformlyOn
          (fun L x ↦ SubdiffusiveProcess.Model.anchoredPartialSum omega L x) g atTop K
  deriv_tendsto :
    ∀ K : Set (Homogenization.Vec d),
      IsCompact K →
        TendstoUniformlyOn
          (fun L x ↦
            SubdiffusiveProcess.Model.PotentialField.deriv
              (SubdiffusiveProcess.Model.anchoredPartialSumField omega L) x)
          (SubdiffusiveProcess.Model.PotentialField.deriv g) atTop K
  deriv_lipschitz_cauchy :
    ∀ K : Set (Homogenization.Vec d),
      IsCompact K →
        SubdiffusiveProcess.Model.LipschitzSeminormCauchyOn
          (fun L x ↦
            SubdiffusiveProcess.Model.PotentialField.deriv
              (SubdiffusiveProcess.Model.anchoredPartialSumField omega L) x)
          K
  anchored : g 0 = 0
/-- The event on which the anchored sums have a unique regular limit. The library
proves measurability by measurableSet_anchoredC11GoodSet and full mass by
measure_anchoredC11GoodSet_eq_one; hence the subtype pullback in theoremC is a
probability measure. -/
def SubdiffusiveProcess.Model.anchoredC11GoodSet (d : ℕ) :
    Set (SubdiffusiveProcess.Model.PotentialSample d) :=
  {omega |
    ∃! g : SubdiffusiveProcess.Model.PotentialField d,
      SubdiffusiveProcess.Model.IsAnchoredC11Limit omega g}
/-- The subtype of potential samples on the anchored C¹,¹ convergence event. -/
abbrev SubdiffusiveProcess.Model.AnchoredC11Sample (d : ℕ) :=
  { omega : SubdiffusiveProcess.Model.PotentialSample d //
    omega ∈ SubdiffusiveProcess.Model.anchoredC11GoodSet d }
/-- The unique regular anchored logarithmic potential selected on its convergence
carrier. -/
noncomputable def SubdiffusiveProcess.Model.anchoredLog {d : ℕ}
    (omega : SubdiffusiveProcess.Model.AnchoredC11Sample d) :
    SubdiffusiveProcess.Model.PotentialField d :=
  Classical.choose omega.property.exists
/-- The exponential coefficient of the anchored logarithmic potential. -/
noncomputable def SubdiffusiveProcess.Model.aAnchored {d : ℕ}
    (_M : SubdiffusiveProcess.Model.GMCModel d)
    (omega : SubdiffusiveProcess.Model.AnchoredC11Sample d)
    (x : Homogenization.Vec d) : ℝ :=
  Real.exp (SubdiffusiveProcess.Model.anchoredLog omega x)
/-- The finite-cutoff coefficient at finite L, and the anchored coefficient at L =
∞. -/
noncomputable def SubdiffusiveProcess.CoarseGrainingVocab.coefficientAt {d : ℕ}
    (M : SubdiffusiveProcess.Model.GMCModel d) (L : WithTop ℕ)
    (ω : SubdiffusiveProcess.Model.AnchoredC11Sample d) :
    SubdiffusiveProcess.CoarseGrainingVocab.Vec d → ℝ :=
  match L with
  | ⊤ => SubdiffusiveProcess.Model.aAnchored M ω
  | (n : ℕ) => SubdiffusiveProcess.Model.aCutoff M n ω.1
/-- The upper large-scale regularity exponent 1 − C₀ δ √|log δ|. -/
noncomputable def SubdiffusiveProcess.CoarseGrainingVocab.gammaReg (C0 delta : ℝ) : ℝ :=
  1 - C0 * delta * |Real.log delta| ^ (1 / 2 : ℝ)
open Filter _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.SubdiffusiveProcess
  _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.SubdiffusiveProcess.Model
  MeasureTheory ProbabilityTheory
open Set
open
  _root_.SubdiffusiveProcessAudit.AnomalousHolderRegularity.SubdiffusiveProcess.CoarseGrainingVocab
open scoped ENNReal NNReal Topology
namespace SubdiffusiveProcess.CoarseGrainingVocab
variable {d : ℕ}
/-- The oscillation estimate on `z + 𝒞ₙ ⊆ 𝒞ₘ`: the `L²` distance of `u` from its mean on `z + 𝒞ₙ`
is at most `C 3^{-γ(m-n)}` times that on `𝒞ₘ`. -/
def OscillationDecay (γ C : ℝ) (m : ℕ) (n : ℕ) (z : Homogenization.Vec d)
    (u : H1Function (openCubeSet (originCube d m))) : Prop :=
  normalizedL2On (translatedCube d n z)
      (fun x => u.toFun x - averageOn (translatedCube d n z) u.toFun) ≤
    C * (3 : ℝ) ^ (-γ * ((m : ℝ) - (n : ℝ))) *
      normalizedL2On (cube d m) (fun x => u.toFun x - averageOn (cube d m) u.toFun)
/-- The energy estimate on `z + 𝒞ₙ ⊆ 𝒞ₘ`: the weighted gradient `√a ∇u` has `L²` size at most
`C 3^{(1-γ)(m-n)}` times that on `𝒞ₘ`. -/
def EnergyGrowth (a : Homogenization.Vec d → ℝ) (γ C : ℝ) (m : ℕ) (n : ℕ) (z : Homogenization.Vec d)
    (u : H1Function (openCubeSet (originCube d m))) : Prop :=
  vectorNormalizedL2On (translatedCube d n z) (fun x => Real.sqrt (a x) • u.grad x) ≤
    C * (3 : ℝ) ^ ((1 - γ) * ((m : ℝ) - (n : ℝ))) *
      vectorNormalizedL2On (cube d m) (fun x => Real.sqrt (a x) • u.grad x)
/-- `u` is locally `H¹` and `a`-harmonic on all of `ℝᵈ`: on every origin cube it has an `H¹`
version (equal to `u` everywhere) that is weakly `a`-harmonic. -/
def IsEntireHarmonic (a : Homogenization.Vec d → ℝ) (u : Homogenization.Vec d → ℝ) : Prop :=
  ∀ m : ℤ,
    ∃ um : H1Function (openCubeSet (originCube d m)),
      (∀ x, um.toFun x = u x) ∧ IsWeaklyHarmonicOn a (cube d m) um
/-- The subcritical growth hypothesis of the Liouville theorem:
`liminf_{R → ∞} R^{-γ} inf_c ‖u - c‖_{L²(B_R)} = 0`. -/
def HasSubcriticalGrowth (γ : ℝ) (u : Homogenization.Vec d → ℝ) : Prop :=
  ∀ eps > 0,
    ∃ᶠ R : ℝ in Filter.atTop,
      R ^ (-γ) *
          sInf
            {r : ℝ |
              ∃ c : ℝ,
                r = normalizedL2On (Metric.ball (0 : Homogenization.Vec d) R) (fun x => u x - c)} <
        eps
end SubdiffusiveProcess.CoarseGrainingVocab
/-- **Theorem C** (`t.C`). The constants `δ₀, C₀, C` depend only on `d` and are chosen before the
model; `γ_reg = 1 − C₀ δ √|log δ|`. For each `γ ∈ [1/2, γ_reg]` the random minimal scales `𝓛_L(γ,
m)` (`Lscale L m`) are chosen first; the almost-sure event then holds simultaneously for all
cutoffs `L` (including `L = ∞`), all `m`, all weakly harmonic `u`, all `n` and `z`, and all
Liouville candidates. The sample law is the pullback of `M.P` to the anchored `C^{1,1}` carrier.
-/
theorem theoremC (d : ℕ) (hd : 2 ≤ d) :
    ∃ delta0 C0 C : ℝ,
      0 < delta0 ∧
        0 < C0 ∧
          0 < C ∧
            ∀ M : GMCModel d,
              M.delta ≤ delta0 →
                let mu :=
                  Measure.comap (Subtype.val : AnchoredC11Sample d → PotentialSample d)
                    M.P.toMeasure
                gammaReg C0 M.delta ∈ Set.Ioo (1 / 2 : ℝ) 1 ∧
                  ∀ gamma ∈ Set.Icc (1 / 2 : ℝ) (gammaReg C0 M.delta),
                    ∃ Lscale : WithTop ℕ → ℕ → AnchoredC11Sample d → ℕ,
                      (∀ (L : WithTop ℕ) (m : ℕ), Measurable (Lscale L m)) ∧
                        (∀ (L : WithTop ℕ) (m k : ℕ),
                            0 < k →
                              mu {omega | k < Lscale L m omega} ≤
                                ENNReal.ofReal
                                  (C *
                                    Real.exp
                                      (-((1 - gamma) ^ 2 * max ((k : ℝ) - C) 0) /
                                        (C * M.delta ^ 2 * |Real.log M.delta|)))) ∧
                          ∀ᵐ omega ∂mu,
                            (∀ (L : WithTop ℕ) (m : ℕ),
                                0 < m →
                                  ∀ u : H1Function (openCubeSet (originCube d m)),
                                    IsWeaklyHarmonicOn (coefficientAt M L omega) (cube d m) u →
                                      ∀ n : ℕ,
                                        (n : ℤ) ≤ (m : ℤ) - (Lscale L m omega : ℤ) →
                                          ∀ z : Homogenization.Vec d,
                                            OnTriadicGrid n z →
                                              translatedCube d n z ⊆ cube d (m - 1) →
                                                OscillationDecay gamma C m n z u ∧
                                                  EnergyGrowth (coefficientAt M L omega) gamma C m n
                                                    z u) ∧
                              (∀ (L : WithTop ℕ) (u : Homogenization.Vec d → ℝ),
                                IsEntireHarmonic (coefficientAt M L omega) u →
                                  HasSubcriticalGrowth (gammaReg C0 M.delta) u →
                                    ∃ uRep : Homogenization.Vec d → ℝ,
                                      Continuous uRep ∧
                                        uRep =ᵐ[volume] u ∧
                                          (∀ m : ℤ,
                                              ∀ um : H1Function (openCubeSet (originCube d m)),
                                                (∀ x, um.toFun x = u x) →
                                                  IsWeaklyHarmonicOn (coefficientAt M L omega)
                                                      (cube d m) um →
                                                    uRep =ᵐ[volume.restrict
                                                        (openCubeSet (originCube d m))]
                                                      um.toFun) ∧
                                            ∃ c : ℝ, ∀ x, uRep x = c) :=
  by sorry
end SubdiffusiveProcessAudit.AnomalousHolderRegularity
