import SubdiffusiveProcess.CoarseGrainingVocab.Section8Resolvent.C0ResolventPackage




namespace SubdiffusiveProcess.CoarseGrainingVocab.Section8Resolvent

open Filter MeasureTheory Set Topology
open MarkovProcess MarkovProcess.Semigroup
open scoped NNReal ZeroAtInfty

noncomputable section

variable {E : Type*} [TopologicalSpace E] [T2Space E] [LocallyCompactSpace E]
  [SecondCountableTopology E] [MeasurableSpace E] [BorelSpace E]

namespace C0ResolventDatum

variable (D : C0ResolventDatum E) (hdense : ∀ μ, DenseRange (D.operator μ))

/-- **The sub-Markov kernel semigroup generated by the resolvent.**  Concretely
this is the Hille--Yosida semigroup of `L` on `C₀`, represented by transition
kernels through the Riesz representation of its positive `C₀` operators. -/
def fellerKernelSemigroup : SubMarkovKernelSemigroup E :=
  (D.toPositiveC0ContractiveResolvent hdense).kernelSemigroup

/-- The generated kernel semigroup is Feller: it maps `C₀` into itself and its
`C₀` orbits are norm-continuous in time. -/
theorem isFellerKernelSemigroup_fellerKernelSemigroup :
    (D.fellerKernelSemigroup hdense).IsFellerKernelSemigroup :=
  (D.toPositiveC0ContractiveResolvent hdense).isFellerKernelSemigroup_kernelSemigroup

/-- The transition kernels act on `C₀` by the generated semigroup operators. -/
theorem integral_fellerKernelSemigroup (t : ℝ≥0) (f : C₀(E, ℝ)) (x : E) :
    ∫ y, f y ∂(D.fellerKernelSemigroup hdense) t x =
      (D.toContractiveResolvent hdense).generatedSemigroup t f x :=
  (D.toPositiveC0ContractiveResolvent hdense).integral_kernelSemigroup t f x



theorem solution_eq_laplace (μ : PositiveShift) (f : C₀(E, ℝ)) (x : E) :
    D.solution μ f x =
      ∫ t in Ioi (0 : ℝ), Real.exp (-(μ : ℝ) * t) *
        kernelIntegral ((D.fellerKernelSemigroup hdense) (Real.toNNReal t)) f x := by
  have hres := ((D.toPositiveC0ContractiveResolvent hdense)).resolvent_c0Semigroup_kernelSemigroup μ
  have hlap := (D.isFellerKernelSemigroup_fellerKernelSemigroup hdense).resolvent_apply_apply
    μ f x
  rw [← hlap]
  rw [show (D.isFellerKernelSemigroup_fellerKernelSemigroup hdense) =
    (D.toPositiveC0ContractiveResolvent hdense).isFellerKernelSemigroup_kernelSemigroup from rfl]
  rw [hres]
  rfl

end C0ResolventDatum



theorem exists_fellerKernelSemigroup_of_c0ResolventDatum
    (D : C0ResolventDatum E) (hdense : ∀ μ, DenseRange (D.operator μ)) :
    ∃ P : SubMarkovKernelSemigroup E, P.IsFellerKernelSemigroup ∧
      ∀ (μ : PositiveShift) (f : C₀(E, ℝ)) (x : E),
        D.solution μ f x =
          ∫ t in Ioi (0 : ℝ), Real.exp (-(μ : ℝ) * t) *
            kernelIntegral (P (Real.toNNReal t)) f x :=
  ⟨D.fellerKernelSemigroup hdense,
    D.isFellerKernelSemigroup_fellerKernelSemigroup hdense,
    D.solution_eq_laplace hdense⟩



theorem exists_conservative_fellerKernelSemigroup_of_c0ResolventDatum
    (D : C0ResolventDatum E) (hdense : ∀ μ, DenseRange (D.operator μ))
    (hcons : (D.fellerKernelSemigroup hdense).IsConservative) :
    ∃ P : SubMarkovKernelSemigroup E, P.IsConservative ∧ P.IsFellerKernelSemigroup ∧
      ∀ (μ : PositiveShift) (f : C₀(E, ℝ)) (x : E),
        D.solution μ f x =
          ∫ t in Ioi (0 : ℝ), Real.exp (-(μ : ℝ) * t) *
            kernelIntegral (P (Real.toNNReal t)) f x :=
  ⟨D.fellerKernelSemigroup hdense, hcons,
    D.isFellerKernelSemigroup_fellerKernelSemigroup hdense,
    D.solution_eq_laplace hdense⟩

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section8Resolvent
