import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Instances
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Isometric
import SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKScalar
import SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKComplexLp




open MeasureTheory Complex Set
open scoped RealInnerProductSpace ENNReal

noncomputable section

namespace SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKOperatorHalf

open SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.HeatKernelRegularity
open SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKScalar
open SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKComplexLp

variable {X : Type*} [MeasurableSpace X] {mu : Measure X}

section Pow

variable {R : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu}

theorem isSymmetricOp_pow (hR : IsSymmetricOp R) (n : ℕ) : IsSymmetricOp (R ^ n) := by
  induction n with
  | zero => intro f g; simp
  | succ n ih =>
      intro f g
      have h1 : (R ^ (n + 1)) f = (R ^ n) (R f) := by
        rw [pow_succ]; rfl
      have h2 : (R ^ (n + 1)) g = R ((R ^ n) g) := by
        rw [pow_succ']; rfl
      rw [h1, h2, ih, hR]

theorem injective_pow (hR : Function.Injective R) (n : ℕ) : Function.Injective (R ^ n) := by
  induction n with
  | zero => intro f g h; simpa using h
  | succ n ih =>
      intro f g h
      have h1 : ∀ x : Lp ℝ 2 mu, (R ^ (n + 1)) x = (R ^ n) (R x) := fun x => by
        rw [pow_succ]; rfl
      rw [h1, h1] at h
      exact hR (ih h)

end Pow

variable (s : ℝ) (N : ℕ) (R : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu)

/-- `e^{-uH} = φ_u((I+sH)⁻¹)`, the semigroup generated by the resolvent `R`. -/
def rrkSemigroup (u : ℝ) : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu :=
  realOp (cfc (rrkFn (u / s) 0) (cxOp R))

/-- `B_t = (I+sH)^N e^{-tH/2} = ψ_t((I+sH)⁻¹)`, the manuscript's smoothing operator. -/
def rrkSmoothing (t : ℝ) : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu :=
  realOp (cfc (rrkFn (t / (2 * s)) N) (cxOp R))

variable {s N R}

theorem isSymmetricOp_rrkSmoothing (t : ℝ) :
    IsSymmetricOp (rrkSmoothing s N R t) :=
  isSymmetricOp_realOp (T := cfc (rrkFn (t / (2 * s)) N) (cxOp R)) IsSelfAdjoint.cfc

theorem isSymmetricOp_rrkSemigroup (u : ℝ) :
    IsSymmetricOp (rrkSemigroup s R u) :=
  isSymmetricOp_realOp (T := cfc (rrkFn (u / s) 0) (cxOp R)) IsSelfAdjoint.cfc



theorem resolvent_comp_rrkSmoothing (hs : 0 < s) (hR : IsSymmetricOp R) {t : ℝ} (ht : 0 < t) :
    (R ^ N).comp (rrkSmoothing s N R t) = rrkSemigroup s R (t / 2) := by
  have hsa : IsSelfAdjoint (cxOp R) := isSelfAdjoint_cxOp hR
  have hapos : 0 < t / (2 * s) := by positivity
  set a : ℝ := t / (2 * s) with ha
  have hcpsi : ContinuousOn (rrkFn a N) (spectrum ℝ (cxOp R)) :=
    (continuous_rrkFn hapos N).continuousOn
  have hcpow : ContinuousOn (fun x : ℝ => x ^ N) (spectrum ℝ (cxOp R)) :=
    (continuous_pow N).continuousOn
  have key : cfc (rrkFn a 0) (cxOp R) = (cxOp R) ^ N * cfc (rrkFn a N) (cxOp R) := by
    have hfun : rrkFn a 0 = fun x : ℝ => x ^ N * rrkFn a N x := (funext (pow_mul_rrkFn a N)).symm
    rw [hfun, cfc_mul _ _ _ hcpow hcpsi, cfc_pow_id (R := ℝ) (cxOp R) N]
  have hhalf : t / 2 / s = a := by rw [ha, div_div]
  rw [rrkSemigroup, hhalf, key, ← cxOp_pow, realOp_cxOp_mul]
  rfl

/-- Norm-continuity of `t ↦ ψ_t(R)` on `(0,∞)`, from the uniform scalar Lipschitz
estimate and the isometry of the continuous functional calculus. -/
theorem continuousOn_cfc_rrkFn (N : ℕ) (R : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu) :
    ContinuousOn (fun a : ℝ => cfc (rrkFn a N) (cxOp R)) (Ioi 0) := by
  intro a0 ha0
  have ha0' : (0:ℝ) < a0 := ha0
  refine ContinuousAt.continuousWithinAt ?_
  rw [Metric.continuousAt_iff]
  intro ε hε
  set L : ℝ := Real.exp (2 * a0) * (((N : ℝ) + 1) / (a0 / 2)) ^ (N + 1) + Real.exp (2 * a0) with hL
  have hLpos : 0 < L := by
    have h1 : (0:ℝ) < Real.exp (2 * a0) := Real.exp_pos _
    have h2 : (0:ℝ) < (((N : ℝ) + 1) / (a0 / 2)) ^ (N + 1) := by positivity
    positivity
  refine ⟨min (a0 / 2) (ε / (2 * L)), by positivity, fun {a} hd => ?_⟩
  have hd1 : |a - a0| < a0 / 2 := by
    rw [Real.dist_eq] at hd; exact lt_of_lt_of_le hd (min_le_left _ _)
  have hd2 : |a - a0| < ε / (2 * L) := by
    rw [Real.dist_eq] at hd; exact lt_of_lt_of_le hd (min_le_right _ _)
  have habs := abs_lt.mp hd1
  have hlow : a0 / 2 ≤ a := by linarith [habs.1]
  have hhigh : a ≤ 2 * a0 := by linarith [habs.2]
  have hapos : (0:ℝ) < a := lt_of_lt_of_le (by linarith) hlow
  have hcont_a : ContinuousOn (rrkFn a N) (spectrum ℝ (cxOp R)) :=
    (continuous_rrkFn hapos N).continuousOn
  have hcont_a0 : ContinuousOn (rrkFn a0 N) (spectrum ℝ (cxOp R)) :=
    (continuous_rrkFn ha0' N).continuousOn
  have hbound : ‖cfc (rrkFn a N) (cxOp R) - cfc (rrkFn a0 N) (cxOp R)‖ ≤ |a - a0| * L := by
    rw [← cfc_sub _ _ _ hcont_a hcont_a0]
    refine norm_cfc_le (by positivity) fun x _ => ?_
    have := rrkFn_sub_abs_le (a := a) (b := a0) (m := a0 / 2) (M := 2 * a0)
      (by linarith) hlow (by linarith) hhigh (by linarith) N x
    simpa [hL, Real.norm_eq_abs] using this
  rw [dist_eq_norm]
  calc ‖cfc (rrkFn a N) (cxOp R) - cfc (rrkFn a0 N) (cxOp R)‖ ≤ |a - a0| * L := hbound
    _ < (ε / (2 * L)) * L := by
        exact mul_lt_mul_of_pos_right hd2 hLpos
    _ = ε / 2 := by field_simp
    _ < ε := by linarith

/-- **`t ↦ B_t` is norm-continuous on `(0,∞)`.** -/
theorem continuousOn_rrkSmoothing (hs : 0 < s) :
    ContinuousOn (rrkSmoothing s N R) (Ioi 0) := by
  have hdiv : ContinuousOn (fun t : ℝ => t / (2 * s)) (Ioi 0) :=
    (continuous_id.div_const (2 * s)).continuousOn
  have hmaps : MapsTo (fun t : ℝ => t / (2 * s)) (Ioi 0) (Ioi 0) := by
    intro t ht
    have : (0:ℝ) < t := ht
    exact div_pos this (by linarith)
  exact continuous_realOp.comp_continuousOn
    ((continuousOn_cfc_rrkFn N R).comp hdiv hmaps)


/-! ### The semigroup law

`realOp` is not multiplicative in general, but it is on operators fixed by the real
structure of `RRKComplexLp`, and the functional calculus of `cxOp R` is fixed by it —
this is `StarAlgHomClass.map_cfc` for the `ℝ`-linear `⋆`-automorphism
`RRKComplexLp.conjOpHom`.  That gives the semigroup law for `rrkSemigroup`. -/

/-- **The functional calculus of a complexified real operator is real.** -/
theorem conjOp_cfc (hR : IsSymmetricOp R) (f : ℝ → ℝ)
    (hf : ContinuousOn f (spectrum ℝ (cxOp R))) :
    conjOp (cfc f (cxOp R)) = cfc f (cxOp R) := by
  have hsa : IsSelfAdjoint (cxOp R) := isSelfAdjoint_cxOp hR
  have hfix : IsSelfAdjoint (conjOpHom mu (cxOp R)) := by
    rw [conjOpHom_apply, conjOp_cxOp]; exact hsa
  have h := StarAlgHomClass.map_cfc (R := ℝ) (S := ℝ) (conjOpHom mu) f (cxOp R) hf
    continuous_conjOpHom hsa hfix
  rw [conjOpHom_apply, conjOpHom_apply, conjOp_cxOp] at h
  exact h

/-- **The semigroup law `e^{-tH} e^{-uH} = e^{-(t+u)H}`.** -/
theorem rrkSemigroup_comp (hs : 0 < s) (hR : IsSymmetricOp R) {t u : ℝ} (ht : 0 < t)
    (hu : 0 < u) :
    (rrkSemigroup s R t).comp (rrkSemigroup s R u) = rrkSemigroup s R (t + u) := by
  have hat : 0 < t / s := div_pos ht hs
  have hau : 0 < u / s := div_pos hu hs
  have hct : ContinuousOn (rrkFn (t / s) 0) (spectrum ℝ (cxOp R)) :=
    (continuous_rrkFn hat 0).continuousOn
  have hcu : ContinuousOn (rrkFn (u / s) 0) (spectrum ℝ (cxOp R)) :=
    (continuous_rrkFn hau 0).continuousOn
  have hreal := conjOp_cfc hR (rrkFn (t / s) 0) hct
  have hfun : (fun x : ℝ => rrkFn (t / s) 0 x * rrkFn (u / s) 0 x) = rrkFn ((t + u) / s) 0 := by
    funext x
    rw [rrkFn_zero_mul]
    congr 1
    ring
  have key : cfc (rrkFn (t / s) 0) (cxOp R) * cfc (rrkFn (u / s) 0) (cxOp R)
      = cfc (rrkFn ((t + u) / s) 0) (cxOp R) := by
    rw [← cfc_mul _ _ _ hct hcu, hfun]
  rw [rrkSemigroup, rrkSemigroup, rrkSemigroup, ← realOp_mul_of_conjOp hreal, key]

/-! ### Packaging -/



def IsResolventSemigroup (s : ℝ) (R : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu)
    (P : ℝ → (Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu)) : Prop :=
  ∀ u, 0 < u → P u = rrkSemigroup s R u

theorem isResolventSemigroup_rrkSemigroup (s : ℝ) (R : Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu) :
    IsResolventSemigroup s R (rrkSemigroup s R) := fun _ _ => rfl



theorem rrk_operator_half (hs : 0 < s) (hR : IsSymmetricOp R) (hinj : Function.Injective R)
    {P : ℝ → (Lp ℝ 2 mu →L[ℝ] Lp ℝ 2 mu)} (hP : IsResolventSemigroup s R P) :
    IsSymmetricOp (R ^ N) ∧
      Function.Injective (R ^ N) ∧
      (∀ t, 0 < t → IsSymmetricOp (rrkSmoothing s N R t)) ∧
      (∀ t, 0 < t → (R ^ N).comp (rrkSmoothing s N R t) = P (t / 2)) ∧
      ContinuousOn (rrkSmoothing s N R) (Ioi 0) ∧
      (∀ t, 0 < t → IsSymmetricOp (P t)) ∧
      (∀ t u, 0 < t → 0 < u → (P t).comp (P u) = P (t + u)) := by
  refine ⟨isSymmetricOp_pow hR N, injective_pow hinj N,
    fun t _ => isSymmetricOp_rrkSmoothing t, fun t ht => ?_, continuousOn_rrkSmoothing hs,
    fun t ht => ?_, fun t u ht hu => ?_⟩
  · rw [hP (t / 2) (by linarith), resolvent_comp_rrkSmoothing hs hR ht]
  · rw [hP t ht]; exact isSymmetricOp_rrkSemigroup t
  · rw [hP t ht, hP u hu, hP (t + u) (by linarith), rrkSemigroup_comp hs hR ht hu]

end SubdiffusiveProcess.CoarseGrainingVocab.Section8Support.RRKOperatorHalf
