module

public import Homogenization.Ambient.Basic
public import MarkovProcess.Kernel.PositiveC0Resolvent

@[expose] public section




namespace SubdiffusiveProcess.CoarseGrainingVocab.Section7Process

open Homogenization MarkovProcess
open scoped ZeroAtInfty

noncomputable section

variable {d : ℕ}

/-! ### The ambient carrier -/

/-- The ambient carrier is a complete metric space. -/
theorem completeSpace_vec (d : ℕ) : CompleteSpace (Vec d) := inferInstance

/-- The ambient carrier carries the Borel `σ`-algebra of its metric topology. -/
theorem borelSpace_vec (d : ℕ) : BorelSpace (Vec d) := inferInstance

/-- The ambient carrier is second countable. -/
theorem secondCountableTopology_vec (d : ℕ) : SecondCountableTopology (Vec d) :=
  inferInstance

/-- The ambient carrier is nonempty. -/
theorem nonempty_vec (d : ℕ) : Nonempty (Vec d) := inferInstance

/-- The ambient carrier is locally compact. -/
theorem locallyCompactSpace_vec (d : ℕ) : LocallyCompactSpace (Vec d) := inferInstance

/-- The ambient carrier is Hausdorff. -/
theorem t2Space_vec (d : ℕ) : T2Space (Vec d) := inferInstance

/-! ### The provider interface -/

/-- Package the five analytic facts about a resolvent family indexed by a positive
real shift as the `MarkovProcess` provider interface.

This is the exact obligation of the resolvent provider: a family `Rop` of bounded
operators on `C₀(Vec d, ℝ)`, defined for every positive shift, satisfying the
resolvent identity in the `(a + A)⁻¹` sign convention, the Hille--Yosida
contraction bound `‖Rop a‖ ≤ a⁻¹`, dense range, and preservation of nonnegative
functions. -/
def resolventOfPositiveData
    (Rop : ℝ → C₀(Vec d, ℝ) →L[ℝ] C₀(Vec d, ℝ))
    (hid : ∀ a b : ℝ, 0 < a → 0 < b →
      Rop a - Rop b = (b - a) • ((Rop a).comp (Rop b)))
    (hbd : ∀ a : ℝ, 0 < a → ‖Rop a‖ ≤ a⁻¹)
    (hdense : ∀ a : ℝ, 0 < a → DenseRange (Rop a))
    (hpos : ∀ a : ℝ, 0 < a → ∀ f : C₀(Vec d, ℝ), (∀ x, 0 ≤ f x) → ∀ x, 0 ≤ Rop a f x) :
    PositiveC0ContractiveResolvent (Vec d) where
  operator a := Rop (a : ℝ)
  resolvent_identity a b := hid (a : ℝ) (b : ℝ) a.2 b.2
  opNorm_le_inv a := hbd (a : ℝ) a.2
  denseRange a := hdense (a : ℝ) a.2
  isPositive a := hpos (a : ℝ) a.2

@[simp]
theorem resolventOfPositiveData_operator
    (Rop : ℝ → C₀(Vec d, ℝ) →L[ℝ] C₀(Vec d, ℝ))
    (hid : ∀ a b : ℝ, 0 < a → 0 < b →
      Rop a - Rop b = (b - a) • ((Rop a).comp (Rop b)))
    (hbd : ∀ a : ℝ, 0 < a → ‖Rop a‖ ≤ a⁻¹)
    (hdense : ∀ a : ℝ, 0 < a → DenseRange (Rop a))
    (hpos : ∀ a : ℝ, 0 < a → ∀ f : C₀(Vec d, ℝ), (∀ x, 0 ≤ f x) → ∀ x, 0 ≤ Rop a f x)
    (a : MarkovProcess.Semigroup.PositiveShift) :
    (resolventOfPositiveData Rop hid hbd hdense hpos).toContractiveResolvent.operator a =
      Rop (a : ℝ) :=
  rfl

/-! ### The transition semigroup of a resolvent -/

variable (R : PositiveC0ContractiveResolvent (Vec d))

/-- The transition semigroup of the Section 7 diffusion, as produced by
`MarkovProcess` from a positive `C₀`-contractive resolvent. -/
def semigroupOfResolvent : SubMarkovKernelSemigroup (Vec d) :=
  R.kernelSemigroup

/-- The transition semigroup of a resolvent is Feller: it preserves `C₀` and its
`C₀` orbits are norm continuous in time. -/
theorem isFellerKernelSemigroup_semigroupOfResolvent :
    (semigroupOfResolvent R).IsFellerKernelSemigroup :=
  R.isFellerKernelSemigroup_kernelSemigroup

/-- The transition kernels act on `C₀` exactly by the semigroup generated by the
resolvent.  This is the identity that lets a `C₀`-level statement about the
resolvent be read as a statement about transition probabilities. -/
theorem integral_semigroupOfResolvent (t : NNReal) (f : C₀(Vec d, ℝ)) (x : Vec d) :
    ∫ y, f y ∂(semigroupOfResolvent R) t x =
      R.toContractiveResolvent.generatedSemigroup t f x :=
  R.integral_kernelSemigroup t f x

/-- Repackaging the transition semigroup as a strongly continuous contraction
semigroup on `C₀` recovers the semigroup generated by the resolvent. -/
theorem c0Semigroup_semigroupOfResolvent :
    (isFellerKernelSemigroup_semigroupOfResolvent R).c0Semigroup =
      R.toContractiveResolvent.generatedSemigroup :=
  R.c0Semigroup_kernelSemigroup

/-- Every transition measure of the semigroup of a resolvent is a sub-probability
measure. -/
theorem measure_univ_semigroupOfResolvent_le_one (t : NNReal) (x : Vec d) :
    (semigroupOfResolvent R) t x Set.univ ≤ 1 :=
  (semigroupOfResolvent R).measure_univ_le_one t x

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section7Process
