module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section6SupportBase
public import SubdiffusiveProcess.Dirichlet.RestrictedCombinedEstimate

@[expose] public section

set_option autoImplicit false
set_option relaxedAutoImplicit false

open MeasureTheory SubdiffusiveProcess.CoarseGrainingVocab
open Homogenization hiding Vec
open Homogenization.Book
open scoped ENNReal

noncomputable section

namespace SubdiffusiveProcess.Paper

/-- **Theorem `t.cutoff.Dirichlet.homogenization`**.

The random factors `Z_{L,M}` are `σ(A_{L,M})`-measurable, where
`A_{L,M}(x) = a_hom,L⁻¹ a_L(3^M x)` is defined for `x ∈ 𝒞_0`: the σ-field is
`restrictedCoefficientSigma (rescaledCutoffCoefficient M L N) (cube d 0)`, generated by the
evaluations on `𝒞_0`.  The proof is the frozen combined estimate
(`SubdiffusiveProcess.CoarseGrainingVocab.Section6Dirichlet.exists_cutoffDirichletCombinedEstimate`) with the
measurability conjunct replaced by the window-restricted version
(`SubdiffusiveProcess.RestrictedResponse.measurable_cutoffDirichletRandomFactor_restricted`). -/
theorem t_cutoff_Dirichlet_homogenization
    (d : ℕ) [NeZero d] :
    ∀ vartheta q : ℝ, vartheta ∈ Set.Ioo (0 : ℝ) 1 → 1 ≤ q →
      ∃ delta0 C : ℝ, 0 < delta0 ∧ ∀ M : _root_.SubdiffusiveProcess.Model.GMCModel d,
        (M.delta ≤ delta0 →
        ∃ Z : ℕ → ℕ → _root_.SubdiffusiveProcess.Model.PotentialSample d → ℝ,
          (∀ L N, L ≤ N →
            @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ
              (restrictedCoefficientSigma
                (fun omega ↦ rescaledCutoffCoefficient M L N omega) (cube d 0))
              (borel ℝ) (Z L N)) ∧
          (∀ L N omega, L ≤ N → 1 ≤ Z L N omega) ∧
          (∀ L N, L ≤ N →
            eLpNorm (Z L N) (ENNReal.ofReal q) M.P.toMeasure ≤ ENNReal.ofReal C) ∧
          ∀ᵐ omega ∂M.P.toMeasure, ∀ L N : ℕ, L ≤ N →
            ∀ (f : Vec d → ℝ),
              MemLp f 2 (volume.restrict (openCubeSet (originCube d 0))) →
            ∀ h : H2Datum (originCube d 0),
              (∃ uLM : H1Function (openCubeSet (originCube d 0)),
                IsScalarDirichletSolutionOn
                  (scalarCoeffField (rescaledCutoffCoefficient M L N omega))
                  (originCube d 0) uLM h.toH1 f) ∧
              (∀ uLM uLM' : H1Function (openCubeSet (originCube d 0)),
                IsScalarDirichletSolutionOn
                    (scalarCoeffField (rescaledCutoffCoefficient M L N omega))
                    (originCube d 0) uLM h.toH1 f →
                IsScalarDirichletSolutionOn
                    (scalarCoeffField (rescaledCutoffCoefficient M L N omega))
                    (originCube d 0) uLM' h.toH1 f →
                uLM.toFun =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uLM'.toFun ∧
                  uLM.grad =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uLM'.grad) ∧
              (∃ uHom : H1Function (openCubeSet (originCube d 0)),
                IsScalarDirichletSolutionOn (fun _ ↦ 1)
                  (originCube d 0) uHom h.toH1 f) ∧
              (∀ uHom uHom' : H1Function (openCubeSet (originCube d 0)),
                IsScalarDirichletSolutionOn (fun _ ↦ 1)
                    (originCube d 0) uHom h.toH1 f →
                IsScalarDirichletSolutionOn (fun _ ↦ 1)
                    (originCube d 0) uHom' h.toH1 f →
                uHom.toFun =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uHom'.toFun ∧
                  uHom.grad =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uHom'.grad) ∧
              ∀ (uLM uHom : H1Function (openCubeSet (originCube d 0))),
                IsScalarDirichletSolutionOn
                    (scalarCoeffField (rescaledCutoffCoefficient M L N omega))
                    (originCube d 0) uLM h.toH1 f →
                IsScalarDirichletSolutionOn (fun _ ↦ 1)
                    (originCube d 0) uHom h.toH1 f →
                ∃ gradDifference fluxDifference : L2VectorField (originCube d 0),
                  (∀ x, gradDifference.toFun x = uLM.grad x - uHom.grad x) ∧
                  (∀ x, fluxDifference.toFun x =
                    rescaledCutoffCoefficient M L N omega x • uLM.grad x - uHom.grad x) ∧
                  l2Size (originCube d 0) (fun x ↦ uLM.toFun x - uHom.toFun x) +
                        ordinaryVectorHMinusOne (originCube d 0) gradDifference +
                      ordinaryVectorHMinusOne (originCube d 0) fluxDifference ≤
                    ENNReal.ofReal (Z L N omega * M.delta ^ vartheta) *
                      (l2Size (originCube d 0) f + h.norm) ∧
                    (f = 0 →
                    l2Size (originCube d 0) (fun x ↦ uLM.toFun x - uHom.toFun x) +
                          ordinaryVectorHMinusOne (originCube d 0) gradDifference +
                        ordinaryVectorHMinusOne (originCube d 0) fluxDifference ≤
                      ENNReal.ofReal (Z L N omega * C * M.delta) * h.norm)) :=
  fun vartheta q hvartheta hq =>
    SubdiffusiveProcess.RestrictedResponse.exists_cutoffDirichletCombinedEstimate_restricted
      d vartheta q hvartheta hq

end SubdiffusiveProcess.Paper
