module

public import SubdiffusiveProcess.Paper.mfd_lem_rare_tests

@[expose] public section

open SubdiffusiveProcess SubdiffusiveProcess.Paper MeasureTheory ProbabilityTheory Filter Set Topology
open scoped ENNReal NNReal BigOperators

noncomputable section
namespace SubdiffusiveProcess.AuditExports

/-- The sigma algebra generated by the bilateral field on a closed integer interval. -/
abbrev rare_test_band_sigma (d : ℕ)
    [MeasurableSpace C(SpatialCoordinates d, ℝ)] (lo hi : ℤ) :
    MeasurableSpace (BilateralField d) :=
  MeasurableSpace.comap ((Set.Icc lo hi).domRestrict)
    (inferInstance : MeasurableSpace ((i : Set.Icc lo hi) → C(SpatialCoordinates d, ℝ)))

/-- Uniform convergence in probability of bounded tests gives one expectation cutoff. -/
private lemma uniform_test_mean (d : ℕ)
    [MeasurableSpace C(SpatialCoordinates d, ℝ)]
    (P : Measure (BilateralField d)) [IsProbabilityMeasure P]
    (I : ℕ → Type) (X : ∀ m, I m → BilateralField d → ℝ)
    (hX01 : ∀ m i ω, X m i ω ∈ Set.Icc (0 : ℝ) 1)
    (hmeas : ∀ m i, Measurable (X m i))
    (hprob : ∀ eps : ℝ, 0 < eps →
      Tendsto (fun m => ⨆ i : I m, P {ω | eps < X m i ω}) atTop (𝓝 0))
    (B : ℝ) (H0 : ℕ) :
    ∃ m0 : ℕ, ∀ m, m0 ≤ m → ∀ i : I m,
      ∫⁻ ω, ENNReal.ofReal (X m i ω) ∂P ≤
        ENNReal.ofReal (Real.exp (-(B * (H0 : ℝ))) / 8) := by
  set δ : ℝ := Real.exp (-(B * (H0 : ℝ))) / 8 with hδ
  have hδ2pos : 0 < δ / 2 := by rw [hδ]; positivity
  have hδ4pos : 0 < δ / 4 := by rw [hδ]; positivity
  have hev := (hprob (δ / 4) hδ4pos).eventually
    (Iio_mem_nhds (ENNReal.ofReal_pos.mpr hδ2pos))
  obtain ⟨m0, hm0⟩ := Filter.eventually_atTop.mp hev
  refine ⟨m0, fun m hm i => ?_⟩
  have hAmeas : MeasurableSet {ω : BilateralField d | δ / 2 ≤ X m i ω} :=
    measurableSet_le measurable_const (hmeas m i)
  have hPA : P {ω : BilateralField d | δ / 2 ≤ X m i ω} ≤ ENNReal.ofReal (δ / 2) := by
    have hsub : {ω : BilateralField d | δ / 2 ≤ X m i ω} ⊆
        {ω | δ / 4 < X m i ω} := by
      intro ω hω
      simp only [mem_ofPred_eq] at hω ⊢
      linarith
    exact (measure_mono hsub).trans ((le_iSup
      (fun j : I m => P {ω | δ / 4 < X m j ω}) i).trans (hm0 m hm).le)
  have hsplit := MeasureTheory.lintegral_add_compl (μ := P)
    (fun ω => ENNReal.ofReal (X m i ω)) hAmeas
  rw [← hsplit]
  calc ∫⁻ ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}, ENNReal.ofReal (X m i ω) ∂P
        + ∫⁻ ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}ᶜ, ENNReal.ofReal (X m i ω) ∂P
      ≤ ENNReal.ofReal (δ / 2) + ENNReal.ofReal (δ / 2) := by
        apply add_le_add
        · calc ∫⁻ ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}, ENNReal.ofReal (X m i ω) ∂P
              ≤ ∫⁻ _ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}, (1 : ℝ≥0∞) ∂P := by
                refine MeasureTheory.setLIntegral_mono (g := fun _ => (1 : ℝ≥0∞)) measurable_const ?_
                intro ω _
                exact ENNReal.ofReal_le_one.mpr (hX01 m i ω).2
            _ = P {ω : BilateralField d | δ / 2 ≤ X m i ω} := by
                rw [MeasureTheory.setLIntegral_const, one_mul]
            _ ≤ ENNReal.ofReal (δ / 2) := hPA
        · calc ∫⁻ ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}ᶜ, ENNReal.ofReal (X m i ω) ∂P
              ≤ ∫⁻ _ω in {ω : BilateralField d | δ / 2 ≤ X m i ω}ᶜ, ENNReal.ofReal (δ / 2) ∂P := by
                refine MeasureTheory.setLIntegral_mono
                  (g := fun _ => ENNReal.ofReal (δ / 2)) measurable_const ?_
                intro ω hω
                simp only [Set.mem_compl_iff, mem_ofPred_eq, not_le] at hω
                exact ENNReal.ofReal_le_ofReal hω.le
            _ = ENNReal.ofReal (δ / 2) * P {ω : BilateralField d | δ / 2 ≤ X m i ω}ᶜ := by
                rw [MeasureTheory.setLIntegral_const]
            _ ≤ ENNReal.ofReal (δ / 2) * 1 := mul_le_mul_right prob_le_one _
            _ = ENNReal.ofReal (δ / 2) := mul_one _
    _ = ENNReal.ofReal δ := by
        rw [← ENNReal.ofReal_add hδ2pos.le hδ2pos.le]
        congr 1
        ring


/-- The existing dyadic cover argument with its initial expectation estimate exposed. -/
private lemma cover_of_test_mean (d : ℕ)
    [MeasurableSpace C(SpatialCoordinates d, ℝ)]
    [BorelSpace C(SpatialCoordinates d, ℝ)]
    (P : Measure (BilateralField d)) [IsProbabilityMeasure P]
    (center : ℤ) (X : ℕ → BilateralField d → ℝ)
    (hX01 : ∀ m ω, X m ω ∈ Set.Icc (0 : ℝ) 1)
    (hmeas : ∀ m, Measurable (X m))
    (H0 : ℕ) (hH00 : 0 < H0) (B : ℝ) (m : ℕ)
    (hmean : ∫⁻ ω, ENNReal.ofReal (X m ω) ∂P ≤
      ENNReal.ofReal (Real.exp (-(B * (H0 : ℝ))) / 8))
    (hD : ∀ᵐ ω ∂P, Tendsto
      (fun ell : ℕ => (P[X m | rare_test_band_sigma d
        (center - (2 ^ ell * H0 : ℕ)) (center + (2 ^ ell * H0 : ℕ))]) ω)
      atTop (𝓝 (X m ω)))
    (hHinc : ∀ ell : ℕ, 1 ≤ ell →
      P {ω | 2 ^ (-(ell : ℤ) - 3 : ℤ) ≤
        (P[X m | rare_test_band_sigma d
          (center - (2 ^ ell * H0 : ℕ)) (center + (2 ^ ell * H0 : ℕ))]) ω -
        (P[X m | rare_test_band_sigma d
          (center - (2 ^ (ell - 1) * H0 : ℕ))
          (center + (2 ^ (ell - 1) * H0 : ℕ))]) ω} ≤
        ENNReal.ofReal (Real.exp (-(B * ((2 ^ ell * H0 : ℕ) : ℝ))))) :
    ∃ W : ℕ+ → Set (BilateralField d),
      (∀ h : ℕ+, MeasurableSet[rare_test_band_sigma d
        (center - 2 * (h : ℤ)) (center + (h : ℤ))] (W h)) ∧
      (∀ h : ℕ+, P (W h) ≤ ENNReal.ofReal (Real.exp (-(B * (h : ℝ))))) ∧
      (∀ h : ℕ+, (h : ℕ) < H0 → W h = ∅) ∧
      (∀ᵐ ω ∂P, 1 / 2 < X m ω → ω ∈ ⋃ h : ℕ+, W h) := by
  let Bsym0 : ℕ → MeasurableSpace (BilateralField d) := fun H =>
    MeasurableSpace.comap ((Set.Icc (center - (H : ℤ)) (center + (H : ℤ))).domRestrict)
      (inferInstance : MeasurableSpace ((i : Set.Icc (center - (H : ℤ)) (center + (H : ℤ))) → C(SpatialCoordinates d, ℝ)))
  have hBsym0 : ∀ H : ℕ, Bsym0 H = MeasurableSpace.comap ((Set.Icc (center - (H : ℤ)) (center + (H : ℤ))).domRestrict)
      (inferInstance : MeasurableSpace ((i : Set.Icc (center - (H : ℤ)) (center + (H : ℤ))) → C(SpatialCoordinates d, ℝ))) := fun H => rfl
  have hlevel := aux_rare_h0_level_prob d P center X hmeas hX01 Bsym0 H0 m B hmean
  let W : ℕ+ → Set (BilateralField d) := fun h => (if (h : ℕ) = H0 then {ω : BilateralField d | (3 / 8 : ℝ) ≤ (P[X m | Bsym0 H0]) ω} else ∅) ∪ ⋃ (l : { l : ℕ // 1 ≤ l ∧ 2 ^ l * H0 = (h : ℕ) }), {ω : BilateralField d | (2 : ℝ) ^ (-(((l : ℕ) : ℤ)) - 3) ≤ (P[X m | Bsym0 (2 ^ (l : ℕ) * H0)]) ω - (P[X m | Bsym0 (2 ^ ((l : ℕ) - 1) * H0)]) ω}
  refine ⟨W, ?_, ?_, ?_, ?_⟩
  · exact aux_rare_clause_meas3 d P center X Bsym0 hBsym0 H0 m W rfl
  · intro h
    by_cases hh : (h : ℕ) = H0
    · have hWeq : W h = {ω : BilateralField d | (3 / 8 : ℝ) ≤ (P[X m | Bsym0 H0]) ω} := by
        dsimp only [W]
        rw [ite_eq_left hh]
        have : IsEmpty { l : ℕ // 1 ≤ l ∧ 2 ^ l * H0 = (h : ℕ) } :=
          ⟨fun l => by
            have h2l : 2 ≤ 2 ^ (l : ℕ) := by
              calc 2 = 2 ^ (1 : ℕ) := by norm_num
                _ ≤ 2 ^ (l : ℕ) := Nat.pow_le_pow_right (by norm_num) l.2.1
            have hmul : 2 * H0 ≤ 2 ^ (l : ℕ) * H0 := Nat.mul_le_mul_right H0 h2l
            rw [l.2.2, hh] at hmul
            omega⟩
        rw [iUnion_of_empty, Set.union_empty]
      rw [hWeq]
      refine le_trans hlevel (le_of_eq ?_)
      rw [show (h : ℝ) = (H0 : ℝ) from by rw [hh]]
    · by_cases hex : ∃ l : ℕ, 1 ≤ l ∧ 2 ^ l * H0 = (h : ℕ)
      · obtain ⟨l, hl1, hl2⟩ := hex
        have hsub : W h ⊆ {ω : BilateralField d | (2 : ℝ) ^ (-(((l : ℕ) : ℤ)) - 3) ≤ (P[X m | Bsym0 (2 ^ (l : ℕ) * H0)]) ω - (P[X m | Bsym0 (2 ^ ((l : ℕ) - 1) * H0)]) ω} := by
          intro ω hω
          dsimp only [W] at hω
          rw [ite_eq_right hh, Set.empty_union] at hω
          simp only [Set.mem_iUnion, mem_ofPred_eq] at hω
          obtain ⟨l', hl'mem⟩ := hω
          have hl'eq : (l' : ℕ) = l := by
            have h2 : 2 ^ l = 2 ^ (l' : ℕ) := Nat.eq_of_mul_eq_mul_right hH00 (hl2.trans l'.2.2.symm)
            exact (Nat.pow_right_injective (by norm_num) h2).symm
          rw [hl'eq] at hl'mem
          exact hl'mem
        refine le_trans (measure_mono hsub) ?_
        have hcast : ((2 ^ l * H0 : ℕ) : ℝ) = ((h : ℕ) : ℝ) := by exact_mod_cast hl2
        have hmono := hHinc l hl1
        rw [hcast] at hmono
        exact hmono
      · have hWeq : W h = ∅ := by
          dsimp only [W]
          rw [ite_eq_right hh, Set.empty_union]
          have : IsEmpty { l : ℕ // 1 ≤ l ∧ 2 ^ l * H0 = (h : ℕ) } := ⟨fun l => hex ⟨l, l.2.1, l.2.2⟩⟩
          rw [iUnion_of_empty]
        rw [hWeq, measure_empty]
        exact zero_le
  · exact aux_rare_clause_empty3 d P center X Bsym0 hBsym0 H0 m hH00 W rfl
  · filter_upwards [hD] with ω hlim
    intro hlt
    by_cases h0 : (P[X m | Bsym0 H0]) ω < 3 / 8
    · have hfail : ¬ (∀ l : ℕ, 1 ≤ l → (P[X m | Bsym0 (2 ^ l * H0)]) ω - (P[X m | Bsym0 (2 ^ (l - 1) * H0)]) ω < (2 : ℝ) ^ (-(l : ℤ) - 3)) := by
        intro hΔ
        exact absurd (aux_rare_cover_telescope d P center X Bsym0 H0 hH00 m ω hlim h0 hΔ) (not_le.mpr hlt)
      push Not at hfail
      obtain ⟨l, hl1, hl2⟩ := hfail
      refine Set.mem_iUnion.mpr ⟨⟨2 ^ l * H0, Nat.mul_pos (Nat.pow_pos (by norm_num)) hH00⟩, ?_⟩
      dsimp only [W]
      exact Or.inr (Set.mem_iUnion.mpr ⟨⟨l, hl1, rfl⟩, hl2⟩)
    · push Not at h0
      refine Set.mem_iUnion.mpr ⟨⟨H0, hH00⟩, ?_⟩
      dsimp only [W]
      split_ifs with hc
      · exact Or.inl h0
      · exfalso; exact absurd rfl hc

/-- Paper `mfd:lem-rare-tests`, for a countable family at each scale and varying deterministic
band centers. The dyadic start is chosen before the law and the tests; the eventual cutoff is
common to every member. For each scale the exceptional null set is common to all members. -/
theorem rare_tests_family :
    ∃ Cgeom : ℝ, 4 ≤ Cgeom ∧
      ∀ (Cstar a p : ℝ), 0 < Cstar → 0 < a → 1 ≤ p →
      ∀ B : ℝ, Cgeom * B < a * p * Real.log 3 →
      ∃ H0 : ℕ, 0 < H0 ∧
      ∀ (d : ℕ), 1 ≤ d →
      ∀ [MeasurableSpace C(SpatialCoordinates d, ℝ)]
        [BorelSpace C(SpatialCoordinates d, ℝ)]
        (P : Measure (BilateralField d)) [IsProbabilityMeasure P]
        (I : ℕ → Type) [∀ m, Countable (I m)]
        (center : ∀ m, I m → ℤ) (X : ∀ m, I m → BilateralField d → ℝ),
        (∀ m i ω, X m i ω ∈ Set.Icc (0 : ℝ) 1) →
        (∀ m i, Measurable (X m i)) →
        (∀ eps : ℝ, 0 < eps →
          Tendsto (fun m => ⨆ i : I m, P {ω | eps < X m i ω}) atTop (𝓝 0)) →
        (∀ m i (H : ℕ),
          eLpNorm (fun ω => X m i ω - (P[X m i | rare_test_band_sigma d
            (center m i - (H : ℤ)) (center m i + (H : ℤ))]) ω)
            (ENNReal.ofReal p) P ≤
          ENNReal.ofReal (Cstar * (3 : ℝ) ^ (-(a * (H : ℝ))))) →
        ∃ m0 : ℕ, ∀ m, m0 ≤ m →
        ∃ W : I m → ℕ+ → Set (BilateralField d),
          (∀ i (h : ℕ+), MeasurableSet[rare_test_band_sigma d
            (center m i - 2 * (h : ℤ)) (center m i + (h : ℤ))] (W i h)) ∧
          (∀ i (h : ℕ+), P (W i h) ≤ ENNReal.ofReal (Real.exp (-(B * (h : ℝ))))) ∧
          (∀ i (h : ℕ+), (h : ℕ) < H0 → W i h = ∅) ∧
          (∀ᵐ ω ∂P, ∀ i, 1 / 2 < X m i ω → ω ∈ ⋃ h : ℕ+, W i h) := by
  classical
  refine ⟨4, by norm_num, ?_⟩
  intro Cstar a p hCstar ha hp B hmargin
  by_cases hB : 0 < B
  · obtain ⟨H0, hH00, hAbs⟩ :=
      aux_lem_rare_tests_band_increment_bound_absorption Cstar a p 4 B
        hCstar ha hp (by norm_num) hB hmargin
    refine ⟨H0, hH00, ?_⟩
    intro d hd _ _ P _ I _ center X hX01 hmeas hprob hCE
    obtain ⟨m0, hm0⟩ := uniform_test_mean d P I X hX01 hmeas hprob B H0
    refine ⟨m0, fun m hm => ?_⟩
    have hex : ∀ i : I m, ∃ W : ℕ+ → Set (BilateralField d),
        (∀ h : ℕ+, MeasurableSet[rare_test_band_sigma d
          (center m i - 2 * (h : ℤ)) (center m i + (h : ℤ))] (W h)) ∧
        (∀ h : ℕ+, P (W h) ≤ ENNReal.ofReal (Real.exp (-(B * (h : ℝ))))) ∧
        (∀ h : ℕ+, (h : ℕ) < H0 → W h = ∅) ∧
        (∀ᵐ ω ∂P, 1 / 2 < X m i ω → ω ∈ ⋃ h : ℕ+, W h) := by
      intro i
      let Y : ℕ → BilateralField d → ℝ := fun _ => X m i
      have hCEY : ∀ (n H : ℕ),
          eLpNorm (fun ω => Y n ω - (P[Y n | rare_test_band_sigma d
            (center m i - (H : ℤ)) (center m i + (H : ℤ))]) ω)
            (ENNReal.ofReal p) P ≤
          ENNReal.ofReal (Cstar * (3 : ℝ) ^ (-(a * (H : ℝ)))) :=
        fun _ H => hCE m i H
      have hInc := aux_mfd_lem_rare_tests_fixed_increment d hd P (center m i) Y
        Cstar a p hCstar ha hp hCEY H0 B (hAbs H0 le_rfl)
      have hAE := aux_mfd_lem_rare_tests_ae_limit d hd P (center m i) Y
        (fun _ => hmeas m i) Cstar a p hCstar ha hp hCEY
      exact cover_of_test_mean d P (center m i) Y (fun _ => hX01 m i)
        (fun _ => hmeas m i) H0 hH00 B 0 (hm0 m hm i)
        (hAE 0 H0 hH00) (hInc 0)
    choose W hWm hWp hWe hWa using hex
    exact ⟨W, hWm, hWp, hWe, ae_all_iff.mpr hWa⟩
  · refine ⟨1, by omega, ?_⟩
    intro d _ _ _ P _ I _ center X _ _ _ _
    refine ⟨0, fun _ _ => ⟨fun _ _ => Set.univ, ?_, ?_, ?_, ?_⟩⟩
    · exact fun _ _ => MeasurableSet.univ
    · intro i h
      rw [measure_univ]
      apply ENNReal.one_le_ofReal.mpr
      apply Real.one_le_exp_iff.mpr
      have hh : 0 ≤ (h : ℝ) := (Nat.cast_nonneg _)
      have hB0 : B ≤ 0 := le_of_not_gt hB
      nlinarith
    · intro i h hh
      have := h.pos
      omega
    · filter_upwards with ω i _
      exact Set.mem_iUnion.mpr ⟨1, Set.mem_univ ω⟩

end SubdiffusiveProcess.AuditExports
