module

public import SubdiffusiveProcess.Probability.InfraredWholePrefixIndependence

@[expose] public section

open Filter MeasureTheory Set Topology
open SubdiffusiveProcess

noncomputable section
namespace SubdiffusiveProcess.AuditExports

/-- The coordinates retained after deleting the layer indexed by `-layer`. -/
abbrev RemainingLayers (d layer : ℕ) :=
  {j : ℤ // j ≠ -(Int.ofNat layer)} → C(SpatialCoordinates d, ℝ)

/-- The literal projection onto the remaining coordinates. -/
def remainingProjection {d : ℕ} (layer : ℕ) (omega : BilateralField d) :
    RemainingLayers d layer := fun j => omega j.val

/-- The sigma-field generated by all coordinates except the deleted layer. -/
abbrev remainingSigma {d : ℕ} [MeasurableSpace C(SpatialCoordinates d, ℝ)]
    (layer : ℕ) : MeasurableSpace (BilateralField d) :=
  MeasurableSpace.comap (remainingProjection layer)
    (inferInstance : MeasurableSpace (RemainingLayers d layer))

/-- Positive layers, which determine the anchored infrared field. -/
abbrev PositiveLayers (d : ℕ) := {j : ℤ // 0 < j} → C(SpatialCoordinates d, ℝ)

/-- Restrict a sample to its positive layers. -/
def positiveProjection {d : ℕ} (omega : BilateralField d) : PositiveLayers d :=
  fun j => omega j.val

/-- Embed the positive layers with zero at every nonpositive index. -/
def positiveEmbedding {d : ℕ} (y : PositiveLayers d) : BilateralField d := by
  classical
  exact fun j => if hj : 0 < j then y ⟨j, hj⟩ else 0

/-- The positive-layer sigma-field. -/
abbrev positiveSigma {d : ℕ} [MeasurableSpace C(SpatialCoordinates d, ℝ)] :
    MeasurableSpace (BilateralField d) :=
  MeasurableSpace.comap positiveProjection
    (inferInstance : MeasurableSpace (PositiveLayers d))

/-- The totalized limit used in the existing infrared independence proofs. -/
def infraredTotalLimit {d : ℕ} (omega : BilateralField d) :
    C(SpatialCoordinates d, ℝ) := by
  classical
  exact if h : ∃ y : C(SpatialCoordinates d, ℝ),
      Tendsto (infraredPartialSum omega) atTop (𝓝 y) then Classical.choose h else 0

/-- Totalize the infrared limit on positive layers alone. -/
def positiveInfraredVersion {d : ℕ} (omega : BilateralField d) :
    C(SpatialCoordinates d, ℝ) :=
  infraredTotalLimit (positiveEmbedding (positiveProjection omega))

variable {d : ℕ} [MeasurableSpace C(SpatialCoordinates d, ℝ)]
  [BorelSpace C(SpatialCoordinates d, ℝ)]

/-- Each positive-layer partial sum is measurable in the full product sigma-field. -/
theorem measurable_infraredPartialSum (L : ℕ) :
    Measurable (fun omega : BilateralField d => infraredPartialSum omega L) := by
  unfold infraredPartialSum
  apply Continuous.measurable
  apply continuous_finsetSum
  intro n _
  have hcoord : Continuous (fun omega : BilateralField d => omega (Int.ofNat (n + 1))) :=
    continuous_apply _
  have hc : Continuous (fun omega : BilateralField d =>
      ContinuousMap.const (SpatialCoordinates d) ((omega (Int.ofNat (n + 1))) 0)) := by
    exact ContinuousMap.continuous_const'.comp ((continuous_eval_const 0).comp hcoord)
  exact hcoord.sub hc

/-- The chosen limit is measurable, including its value on the nonconvergence set. -/
theorem measurable_infraredTotalLimit :
    Measurable (infraredTotalLimit (d := d)) := by
  classical
  let good : Set (BilateralField d) :=
    {omega | ∃ y : C(SpatialCoordinates d, ℝ),
      Tendsto (infraredPartialSum omega) atTop (𝓝 y)}
  have hgood : MeasurableSet good :=
    measurableSet_exists_tendsto measurable_infraredPartialSum
  let seq : ℕ → BilateralField d → C(SpatialCoordinates d, ℝ) := fun L omega =>
    if omega ∈ good then infraredPartialSum omega L else 0
  have hseq : ∀ L, Measurable (seq L) := fun L =>
    Measurable.ite hgood (measurable_infraredPartialSum L) measurable_const
  have hlim : Tendsto seq atTop (𝓝 (infraredTotalLimit (d := d))) := by
    rw [tendsto_pi_nhds]
    intro omega
    by_cases h : omega ∈ good
    · have hex : ∃ y : C(SpatialCoordinates d, ℝ),
          Tendsto (infraredPartialSum omega) atTop (𝓝 y) := h
      simpa only [seq, infraredTotalLimit, ite_eq_left h, dite_eq_left hex] using
        Classical.choose_spec hex
    · have hex : ¬ ∃ y : C(SpatialCoordinates d, ℝ),
          Tendsto (infraredPartialSum omega) atTop (𝓝 y) := h
      simp only [seq, infraredTotalLimit, ite_eq_right h, dite_eq_right hex]
      exact tendsto_const_nhds
  exact measurable_of_tendsto_metrizable hseq hlim

omit [BorelSpace C(SpatialCoordinates d, ℝ)] in
/-- Zero embedding of the positive coordinates is measurable. -/
theorem measurable_positiveEmbedding : Measurable (positiveEmbedding (d := d)) := by
  classical
  apply Measurable.of_eval
  intro j
  by_cases hj : 0 < j
  · simpa only [positiveEmbedding, dite_eq_left hj] using
      (measurable_pi_apply (⟨j, hj⟩ : {j : ℤ // 0 < j}))
  · simp only [positiveEmbedding, dite_eq_right hj]
    exact measurable_const

/-- The version is measurable using only positive layers. -/
theorem measurable_positiveInfraredVersion_positive :
    Measurable[positiveSigma (d := d)] (positiveInfraredVersion (d := d)) :=
  (measurable_infraredTotalLimit.comp measurable_positiveEmbedding).comp
    (comap_measurable positiveProjection)

omit [BorelSpace C(SpatialCoordinates d, ℝ)] in
/-- The version factors through the coordinates remaining after any nonpositive deletion. -/
theorem measurable_positiveProjection_remaining (layer : ℕ) :
    Measurable[remainingSigma (d := d) layer] (positiveProjection (d := d)) := by
  let : MeasurableSpace (BilateralField d) := remainingSigma layer
  apply measurable_pi_iff.mpr
  intro j
  have hj : j.val ≠ -(Int.ofNat layer) := by
    have := j.property
    have := Int.natCast_nonneg layer
    change j.val ≠ -(layer : ℤ)
    omega
  exact (measurable_pi_apply (⟨j.val, hj⟩ : {j : ℤ // j ≠ -(Int.ofNat layer)})).comp
    (comap_measurable (remainingProjection (d := d) layer))

/-- The infrared version is measurable in every remaining-field sigma-field. -/
theorem measurable_positiveInfraredVersion_remaining (layer : ℕ) :
    Measurable[remainingSigma (d := d) layer] (positiveInfraredVersion (d := d)) :=
  (measurable_infraredTotalLimit.comp measurable_positiveEmbedding).comp
    (measurable_positiveProjection_remaining layer)

/-- It is also measurable in the original product sigma-field. -/
theorem measurable_positiveInfraredVersion :
    Measurable (positiveInfraredVersion (d := d)) :=
  (measurable_infraredTotalLimit.comp measurable_positiveEmbedding).comp
    (by apply Measurable.of_eval; intro j; exact measurable_pi_apply j.val)

omit [MeasurableSpace C(SpatialCoordinates d, ℝ)] [BorelSpace C(SpatialCoordinates d, ℝ)] in
/-- Replacing nonpositive coordinates does not affect any anchored partial sum. -/
theorem infraredPartialSum_positiveEmbedding (omega : BilateralField d) (L : ℕ) :
    infraredPartialSum (positiveEmbedding (positiveProjection omega)) L =
      infraredPartialSum omega L := by
  classical
  unfold infraredPartialSum
  apply Finset.sum_congr rfl
  intro n _
  have hn : (0 : ℤ) < Int.ofNat (n + 1) := Int.natCast_pos.mpr (Nat.zero_lt_succ n)
  simp only [positiveEmbedding, dite_eq_left hn, positiveProjection]

/-- Every characterized infrared field agrees almost surely with the positive-layer version. -/
theorem positiveInfraredVersion_ae_eq
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d)
    (H : BilateralField d → C(SpatialCoordinates d, ℝ))
    (hH : InfraredCharacterization M H) :
    positiveInfraredVersion =ᵐ[(chaosSampleLaw M).toMeasure] H := by
  classical
  filter_upwards [hH.2] with omega homega
  have hlim : Tendsto (infraredPartialSum (positiveEmbedding (positiveProjection omega)))
      atTop (𝓝 (H omega)) := by
    have heq : infraredPartialSum (positiveEmbedding (positiveProjection omega)) =
        infraredPartialSum omega := funext (infraredPartialSum_positiveEmbedding omega)
    rw [heq]
    exact homega
  have hgood : ∃ y : C(SpatialCoordinates d, ℝ),
      Tendsto (infraredPartialSum (positiveEmbedding (positiveProjection omega)))
        atTop (𝓝 y) := ⟨H omega, hlim⟩
  dsimp only [positiveInfraredVersion, infraredTotalLimit]
  rw [dite_eq_left hgood]
  exact tendsto_nhds_unique (Classical.choose_spec hgood) hlim

/-- The produced version retains the exact infrared characterization. -/
theorem infraredCharacterization_positiveInfraredVersion
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d)
    (H : BilateralField d → C(SpatialCoordinates d, ℝ))
    (hH : InfraredCharacterization M H) :
    InfraredCharacterization M positiveInfraredVersion := by
  refine ⟨measurable_positiveInfraredVersion, ?_⟩
  filter_upwards [hH.2, positiveInfraredVersion_ae_eq M H hH] with omega hlim heq
  rw [heq]
  exact hlim

end SubdiffusiveProcess.AuditExports
