module

public import SubdiffusiveProcess.Probability.Diffusion.Packet452PairingChain
public import Mathlib.MeasureTheory.PiSystem

@[expose] public section

/-!
# P-452 seed (i): uniqueness on the canonical filtration from finite-dimensional cylinders

A reusable tool, independent of anything Brownian.  Two measures on continuous-path space that
agree on every **finite intersection of one-time cylinders at times `≤ T`**, and are σ-finite along
the exhaustion by `{ω | ω 0 ∈ closedBall 0 n}`, have the same integral against every
`𝓕_T`-measurable nonnegative function.

Why this is the right formulation, and why it is short:

* `ContinuousPath.canonicalFiltration T` is **by definition** `⨆ q : Iic T, comap (eval q)`, so
  `MeasurableSpace.generateFrom_piiUnionInter_measurableSet` identifies the generated σ-algebra of
  the cylinder π-system with it on the nose.  No statement about the Borel σ-algebra of path space
  is needed -- which is what made the `denseRestriction` route necessary for the (false)
  unrestricted reversal statement.
* The σ-finiteness is supplied by a **one-time** cylinder at the time `0`, which is in the π-system
  because `0 ≤ T`.
* Passing from measure equality to the `lintegral` identity is `MeasureTheory.lintegral_trim`, not
  an `ennreal_induction`: the two trimmed measures on `(ContinuousPath, 𝓕_T)` are equal, and
  `lintegral_trim` moves a `𝓕_T`-measurable integrand across the trim in both directions.
-/

set_option autoImplicit false

open Homogenization MeasureTheory MeasurableSpace MarkovProcess Set

open scoped ENNReal NNReal

noncomputable section

namespace SubdiffusiveProcess.Probability.Diffusion.Packet452Route

variable {d : ℕ}

/-- The σ-algebra generated by the single coordinate at time `q`. -/
def coordSigma (q : ℝ≥0) : MeasurableSpace (ContinuousPath (Vec d)) :=
  MeasurableSpace.comap (fun ω : ContinuousPath (Vec d) => ω q) inferInstance

/-- The π-system of finite intersections of one-time cylinders at times `≤ T`. -/
def cylinderPi (T : ℝ≥0) : Set (Set (ContinuousPath (Vec d))) :=
  piiUnionInter (fun q : ℝ≥0 => {A | MeasurableSet[coordSigma (d := d) q] A}) (Set.Iic T)

theorem isPiSystem_cylinderPi (T : ℝ≥0) : IsPiSystem (cylinderPi (d := d) T) :=
  isPiSystem_piiUnionInter _ (fun q => @isPiSystem_measurableSet _ (coordSigma (d := d) q)) _

theorem generateFrom_cylinderPi (T : ℝ≥0) :
    MeasurableSpace.generateFrom (cylinderPi (d := d) T)
      = ContinuousPath.canonicalFiltration (alpha := Vec d) T := by
  rw [cylinderPi, generateFrom_piiUnionInter_measurableSet (coordSigma (d := d)) (Set.Iic T)]
  refine le_antisymm (iSup₂_le fun q hq => ?_) (iSup_le fun s => ?_)
  · exact le_iSup (fun s : Set.Iic T =>
      MeasurableSpace.comap (ContinuousPath.coordinateProcess (alpha := Vec d) (s : ℝ≥0))
        (inferInstance : MeasurableSpace (Vec d))) ⟨q, hq⟩
  · exact le_iSup₂ (f := fun (q : ℝ≥0) (_ : q ∈ Set.Iic T) => coordSigma (d := d) q)
      (s : ℝ≥0) s.2

theorem measurableSet_of_mem_cylinderPi {T : ℝ≥0} {s : Set (ContinuousPath (Vec d))}
    (hs : s ∈ cylinderPi (d := d) T) :
    MeasurableSet[ContinuousPath.canonicalFiltration (alpha := Vec d) T] s := by
  rw [← generateFrom_cylinderPi T]
  exact MeasurableSpace.measurableSet_generateFrom hs

/-- The rectangle form of a member of the π-system. -/
theorem mem_cylinderPi_of_rectangle {T : ℝ≥0} (t : Finset ℝ≥0) (S : ℝ≥0 → Set (Vec d))
    (hle : ∀ q ∈ t, q ≤ T) (hS : ∀ q, MeasurableSet (S q)) :
    {ω : ContinuousPath (Vec d) | ∀ q ∈ t, ω q ∈ S q} ∈ cylinderPi (d := d) T := by
  refine ⟨t, fun q hq => hle q hq, fun q => {ω : ContinuousPath (Vec d) | ω q ∈ S q},
    fun q _ => ⟨S q, hS q, rfl⟩, ?_⟩
  ext ω
  simp only [Set.mem_setOf_eq, Set.mem_iInter]

/-- The exhausting one-time cylinder. -/
theorem ball_cylinder_mem (T : ℝ≥0) (n : ℕ) :
    {ω : ContinuousPath (Vec d) | ω 0 ∈ Metric.closedBall (0 : Vec d) n}
      ∈ cylinderPi (d := d) T := by
  classical
  have h := mem_cylinderPi_of_rectangle (d := d) (T := T) {0}
    (fun q => if q = 0 then Metric.closedBall (0 : Vec d) n else Set.univ)
    (fun q hq => by simp only [Finset.mem_singleton] at hq; simp [hq])
    (fun q => by by_cases h : q = 0 <;> simp [h, Metric.isClosed_closedBall.measurableSet])
  convert h using 1
  ext ω
  simp

/-- **Uniqueness on the canonical filtration from finite-dimensional cylinders.** -/
theorem lintegral_eq_of_cylinder_eq {T : ℝ≥0} {μ ν : Measure (ContinuousPath (Vec d))}
    (hfin : ∀ n : ℕ, μ {ω : ContinuousPath (Vec d) | ω 0 ∈ Metric.closedBall (0 : Vec d) n} ≠ ∞)
    (hcyl : ∀ (t : Finset ℝ≥0) (S : ℝ≥0 → Set (Vec d)), (∀ q ∈ t, q ≤ T) →
      (∀ q, MeasurableSet (S q)) →
      μ {ω : ContinuousPath (Vec d) | ∀ q ∈ t, ω q ∈ S q}
        = ν {ω : ContinuousPath (Vec d) | ∀ q ∈ t, ω q ∈ S q})
    {G : ContinuousPath (Vec d) → ℝ≥0∞}
    (hG : Measurable[ContinuousPath.canonicalFiltration (alpha := Vec d) T] G) :
    (∫⁻ ω, G ω ∂μ) = ∫⁻ ω, G ω ∂ν := by
  classical
  set m : MeasurableSpace (ContinuousPath (Vec d)) :=
    ContinuousPath.canonicalFiltration (alpha := Vec d) T with hm
  have hle := (ContinuousPath.canonicalFiltration (alpha := Vec d)).le T
  have hpi : ∀ s ∈ cylinderPi (d := d) T, μ s = ν s := by
    rintro s ⟨t, hts, f, hf, rfl⟩
    have hchoice : ∀ q ∈ t, ∃ S : Set (Vec d), MeasurableSet S ∧
        (fun ω : ContinuousPath (Vec d) => ω q) ⁻¹' S = f q := fun q hq => hf q hq
    choose! S hSmeas hSeq using hchoice
    have hrw : (⋂ q ∈ t, f q)
        = {ω : ContinuousPath (Vec d) | ∀ q ∈ t, ω q ∈ (if q ∈ t then S q else Set.univ)} := by
      ext ω
      simp only [Set.mem_iInter, Set.mem_setOf_eq]
      refine forall_congr' fun q => forall_congr' fun hq => ?_
      rw [if_pos hq, ← hSeq q hq]
      rfl
    rw [hrw]
    exact hcyl t (fun q => if q ∈ t then S q else Set.univ) (fun q hq => hts hq)
      (fun q => by by_cases h : q ∈ t <;> simp [h, hSmeas])
  have htrim : μ.trim hle = ν.trim hle := by
    refine @Measure.ext_of_generateFrom_of_iUnion _ m (μ.trim hle) (ν.trim hle)
      (cylinderPi (d := d) T)
      (fun n : ℕ => {ω : ContinuousPath (Vec d) | ω 0 ∈ Metric.closedBall (0 : Vec d) n})
      (generateFrom_cylinderPi T).symm (isPiSystem_cylinderPi T) ?_ ?_ ?_ ?_
    · ext ω
      simp only [Set.mem_iUnion, Set.mem_setOf_eq, Set.mem_univ, iff_true,
        Metric.mem_closedBall, dist_zero_right]
      obtain ⟨n, hn⟩ := exists_nat_ge ‖ω 0‖
      exact ⟨n, by exact_mod_cast hn⟩
    · exact fun n => ball_cylinder_mem T n
    · intro n
      rw [trim_measurableSet_eq hle (measurableSet_of_mem_cylinderPi (ball_cylinder_mem T n))]
      exact hfin n
    · intro s hs
      rw [trim_measurableSet_eq hle (measurableSet_of_mem_cylinderPi hs),
        trim_measurableSet_eq hle (measurableSet_of_mem_cylinderPi hs)]
      exact hpi s hs
  rw [← lintegral_trim hle hG, ← lintegral_trim hle hG, htrim]

end SubdiffusiveProcess.Probability.Diffusion.Packet452Route
