module

public import SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation.Lattice
public import Mathlib.Probability.Independence.Basic

@[expose] public section




namespace SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation

open MeasureTheory ProbabilityTheory

variable {d : ℕ} {Ω : Type*} [mΩ : MeasurableSpace Ω] {μ : Measure Ω}

noncomputable section
attribute [local instance] Classical.propDecidable

/-- The sigma-algebra generated by the events indexed by sites in `S`. -/
def eventFieldSigma (E : Lattice d → Set Ω) (S : Set (Lattice d)) :
    MeasurableSpace Ω :=
  MeasurableSpace.generateFrom {A | ∃ z ∈ S, A = E z}

omit mΩ in
theorem eventFieldSigma_mono (E : Lattice d → Set Ω) {S T : Set (Lattice d)}
    (hST : S ⊆ T) : eventFieldSigma E S ≤ eventFieldSigma E T := by
  refine MeasurableSpace.generateFrom_mono fun A hA => ?_
  obtain ⟨z, hz, rfl⟩ := hA
  exact ⟨z, hST hz, rfl⟩

omit mΩ in
theorem measurableSet_event_of_mem {E : Lattice d → Set Ω}
    {S : Set (Lattice d)} {z : Lattice d} (hz : z ∈ S) :
    MeasurableSet[eventFieldSigma E S] (E z) :=
  MeasurableSpace.measurableSet_generateFrom ⟨z, hz, rfl⟩

/-- Exact two-subfamily finite-range dependence at range `R`. -/
def FiniteRangeIndependentEvents (μ : Measure Ω) (R : ℕ)
    (E : Lattice d → Set Ω) : Prop :=
  ∀ S T : Set (Lattice d),
    (∀ u ∈ S, ∀ v ∈ T, R < latticeDist u v) →
      Indep (eventFieldSigma E S) (eventFieldSigma E T) μ

/-- Scale-dependent version of the exact spatial finite-range hypothesis. -/
def MultiscaleFiniteRangeIndependentEvents (μ : Measure Ω) (R : ℕ → ℕ)
    (E : ℕ → Lattice d → Set Ω) : Prop :=
  ∀ j, FiniteRangeIndependentEvents μ (R j) (E j)

/-- Independence of the full spatial event fields as the scale varies. -/
def IndependentEventScales (μ : Measure Ω)
    (E : ℕ → Lattice d → Set Ω) : Prop :=
  iIndep (fun j => eventFieldSigma (E j) Set.univ) μ

/-- The complete indicator configuration of a multiscale event field. -/
def eventFieldConfiguration (E : ℕ → Lattice d → Set Ω) (ω : Ω) :
    ℕ × Lattice d → ℝ :=
  fun p => (E p.1 p.2).indicator (fun _ω => (1 : ℝ)) ω

/-- Translation of the site coordinate in a multiscale event field. -/
def translateEventFieldConfiguration (E : ℕ → Lattice d → Set Ω)
    (a : Lattice d) (ω : Ω) : ℕ × Lattice d → ℝ :=
  fun p => (E p.1 (p.2 + a)).indicator (fun _ω => (1 : ℝ)) ω

/-- Translation invariance of the joint law of all event indicators.  The
measurability clause makes the two pushforward laws genuine `Measure.map`
laws rather than fallback values for nonmeasurable maps. -/
def TranslationInvariantEventLaw (μ : Measure Ω)
    (E : ℕ → Lattice d → Set Ω) : Prop :=
  (∀ j z, MeasurableSet (E j z)) ∧
    ∀ a : Lattice d,
      Measure.map (translateEventFieldConfiguration E a) μ =
        Measure.map (eventFieldConfiguration E) μ

theorem measurable_eventFieldConfiguration {E : ℕ → Lattice d → Set Ω}
    (hE : ∀ j z, MeasurableSet (E j z)) :
    Measurable (eventFieldConfiguration E) := by
  apply measurable_pi_lambda
  rintro ⟨j, z⟩
  exact measurable_const.indicator (hE j z)

theorem measurable_translateEventFieldConfiguration
    {E : ℕ → Lattice d → Set Ω} (hE : ∀ j z, MeasurableSet (E j z))
    (a : Lattice d) : Measurable (translateEventFieldConfiguration E a) := by
  apply measurable_pi_lambda
  rintro ⟨j, z⟩
  exact measurable_const.indicator (hE j (z + a))

private theorem measure_biInter_eq_prod_of_pairwise_separated
    [IsProbabilityMeasure μ] {E : Lattice d → Set Ω} {R : ℕ}
    {ι : Type*} {z : ι → Lattice d}
    (hindep : FiniteRangeIndependentEvents μ R E)
    (hsep : ∀ i j : ι, i ≠ j → R < latticeDist (z i) (z j)) :
    ∀ (s : Finset ι) (f : ι → Set Ω),
      (∀ i, i ∈ s → MeasurableSet[eventFieldSigma E ({z i} : Set (Lattice d))]
        (f i)) →
      μ (⋂ i ∈ s, f i) = ∏ i ∈ s, μ (f i) := by
  classical
  intro s
  induction s using Finset.induction_on with
  | empty => intro f _; simp
  | insert a s ha ih =>
      intro f hf
      have hA : MeasurableSet[eventFieldSigma E ({z a} : Set (Lattice d))] (f a) :=
        hf a (Finset.mem_insert_self a s)
      have hC : MeasurableSet[eventFieldSigma E
          (⋃ i ∈ (s : Set ι), ({z i} : Set (Lattice d)))] (⋂ i ∈ s, f i) := by
        refine Finset.measurableSet_biInter s fun i hi => ?_
        exact (eventFieldSigma_mono E (fun u hu =>
          Set.mem_biUnion (Finset.mem_coe.mpr hi) hu)) _
            (hf i (Finset.mem_insert_of_mem hi))
      have hseparated : ∀ u ∈ ({z a} : Set (Lattice d)),
          ∀ v ∈ (⋃ i ∈ (s : Set ι), ({z i} : Set (Lattice d))),
            R < latticeDist u v := by
        intro u hu v hv
        obtain ⟨i, hi, hv⟩ := Set.mem_iUnion₂.mp hv
        rw [Set.mem_singleton_iff] at hu hv
        subst u
        subst v
        exact hsep a i fun hai => ha (hai ▸ Finset.mem_coe.mp hi)
      have hprod := (Indep_iff _ _ μ).mp (hindep _ _ hseparated) _ _ hA hC
      rw [Finset.set_biInter_insert, hprod, Finset.prod_insert ha,
        ih f fun i hi => hf i (Finset.mem_insert_of_mem hi)]

/-- Pairwise spatial separation plus the manuscript's two-subfamily hypothesis
upgrades a finite family of events to the exact product formula. -/
theorem measure_biInter_event_eq_prod_of_finiteRange
    [IsProbabilityMeasure μ] {E : Lattice d → Set Ω} {R : ℕ}
    {ι : Type*} {z : ι → Lattice d}
    (hindep : FiniteRangeIndependentEvents μ R E)
    (hsep : ∀ i j : ι, i ≠ j → R < latticeDist (z i) (z j))
    (s : Finset ι) :
    μ (⋂ i ∈ s, E (z i)) = ∏ i ∈ s, μ (E (z i)) := by
  apply measure_biInter_eq_prod_of_pairwise_separated hindep hsep s
  intro i _hi
  exact measurableSet_event_of_mem (Set.mem_singleton (z i))

/-- Indicator columns at pairwise separated sites are mutually independent. -/
theorem iIndepFun_indicator_of_finiteRange [IsProbabilityMeasure μ]
    {E : Lattice d → Set Ω} {R : ℕ} {ι : Type*} {z : ι → Lattice d}
    (hindep : FiniteRangeIndependentEvents μ R E)
    (hsep : ∀ i j : ι, i ≠ j → R < latticeDist (z i) (z j)) :
    iIndepFun (fun i => (E (z i)).indicator fun _ω => (1 : ℝ)) μ := by
  rw [iIndepFun_iff_iIndep, iIndep_iff]
  intro s f hf
  apply measure_biInter_eq_prod_of_pairwise_separated hindep hsep s f
  intro i hi
  have hmeas : Measurable[eventFieldSigma E ({z i} : Set (Lattice d))]
      ((E (z i)).indicator fun _ω => (1 : ℝ)) :=
    measurable_const.indicator
      (measurableSet_event_of_mem (Set.mem_singleton (z i)))
  exact hmeas.comap_le _ (hf i hi)

end

end SubdiffusiveProcess.CoarseGrainingVocab.Section9Percolation
