module

public import SubdiffusiveProcess.Assumptions.PotentialField

@[expose] public section

/-!
# Local sigma-fields for scalar potentials
-/

open Homogenization

/-- The local sigma-field generated by the restriction of the scalar-matrix
coefficient field to `U`; see (g1). -/
@[instance_reducible]
def SubdiffusiveProcess.Model.PotentialField.localSigma {d : ℕ}
    (U : Set (Vec d)) :
    MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialField d) :=
  MeasurableSpace.comap
    _root_.SubdiffusiveProcess.Model.PotentialField.forgetPotential
    (LocalSigmaR U)
