import SubdiffusiveProcess.CoarseGrainingVocab.AhomCharacterization
import SubdiffusiveProcess.CoarseGrainingVocab.CutoffMoments
import SubdiffusiveProcess.CoarseGrainingVocab.SharpCompareJ
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Probability.Independence.Integration
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-!
# Probability support for `l.annealed.matrix.bounds`

This file develops the prefix/fresh-shell probability layer required by the
paper proof.  The finite-volume variational assembly and the separately
imported starred infinite-volume characterization remain downstream.
-/

namespace SubdiffusiveProcess.CoarseGrainingVocab

open MeasureTheory ProbabilityTheory Homogenization Homogenization.Book
open scoped BigOperators ENNReal MatrixOrder

noncomputable section

private abbrev Sample (d : ℕ) :=
  SubdiffusiveProcess.Frozen.Assumptions.PotentialSample d

private abbrev Field (d : ℕ) :=
  SubdiffusiveProcess.Frozen.Assumptions.PotentialField d

/- PROVENANCE: adapted from
`Algsuperdiff/Probability/IndexSigma.lean` and
`Algsuperdiff/Section3/Cutoff/ShellIndependence.lean`. -/

/-- The sigma-field generated by the potential layers whose indices lie in `I`. -/
def potentialIndexSigma {d : ℕ} (I : Set ℕ) :
    MeasurableSpace (Sample d) :=
  ⨆ k ∈ I, MeasurableSpace.comap (fun ω : Sample d => ω k) inferInstance

/-- The layer-generated sigma-field is below the ambient product sigma-field. -/
theorem potentialIndexSigma_le_borel {d : ℕ} (I : Set ℕ) :
    potentialIndexSigma (d := d) I ≤
      (inferInstance : MeasurableSpace (Sample d)) := by
  refine iSup_le fun k => iSup_le fun _ => ?_
  exact (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k).comap_le

private theorem measurable_potentialCoordinate_indexSigma {d : ℕ}
    {I : Set ℕ} {k : ℕ} (hk : k ∈ I) :
    @Measurable (Sample d) (Field d) (potentialIndexSigma I) inferInstance
      (fun ω => ω k) := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le k (le_iSup_of_le hk le_rfl)

private theorem indep_potentialIndexSigma_of_disjoint {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {I J : Set ℕ}
    (hIJ : Disjoint I J) :
    Indep (potentialIndexSigma (d := d) I) (potentialIndexSigma J)
      M.P.toMeasure := by
  exact indep_iSup_of_disjoint
    (fun k => (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k).comap_le)
    M.shellPrefix.independent.iIndep hIJ

/-- A cutoff through layer `L` is measurable for the prefix sigma-field. -/
private theorem measurable_aCutoff_prefix {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (x : Vec d) :
    @Measurable (Sample d) ℝ (potentialIndexSigma (Set.Iic L)) inferInstance
      (fun ω => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x) := by
  apply Measurable.exp
  apply Finset.measurable_sum
  intro k hk
  simp only [Finset.mem_range] at hk
  have hkL : k ≤ L := Nat.le_of_lt_succ hk
  exact ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
    (measurable_potentialCoordinate_indexSigma (I := Set.Iic L) hkL)).sub
      measurable_const

/-- The multiplicative increment from cutoff `n` to cutoff `m`. -/
private def freshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ)
    (x : Vec d) (ω : Sample d) : ℝ :=
  Real.exp (∑ k ∈ Finset.Ioc n m,
    (ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P))

private theorem aCutoff_eq_mul_freshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (x : Vec d) (ω : Sample d) :
    SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x =
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x * freshCutoffRatio M n m x ω := by
  rw [SubdiffusiveProcess.Frozen.Assumptions.aCutoff, SubdiffusiveProcess.Frozen.Assumptions.aCutoff,
    freshCutoffRatio, ← Real.exp_add]
  congr 1
  rw [← Finset.sum_union]
  · apply Finset.sum_congr
    · ext k
      simp only [Finset.mem_union, Finset.mem_range, Finset.mem_Ioc]
      omega
    · intro k _
      rfl
  · exact Finset.disjoint_left.mpr fun k hkRange hkIoc => by
      simp only [Finset.mem_range] at hkRange
      simp only [Finset.mem_Ioc] at hkIoc
      omega

/-- A fresh cutoff ratio reads only the shell block `(n,m]`. -/
private theorem measurable_freshCutoffRatio_block {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    @Measurable (Sample d) ℝ (potentialIndexSigma (Set.Ioc n m)) inferInstance
      (freshCutoffRatio M n m x) := by
  apply Measurable.exp
  apply Finset.measurable_sum
  intro k hk
  have hk' : k ∈ Set.Ioc n m := by simpa using hk
  exact ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
    (measurable_potentialCoordinate_indexSigma hk')).sub measurable_const

private theorem indep_prefix_fresh {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) :
    Indep (potentialIndexSigma (d := d) (Set.Iic n))
      (potentialIndexSigma (Set.Ioc n m)) M.P.toMeasure := by
  apply indep_potentialIndexSigma_of_disjoint M
  exact Set.disjoint_left.mpr fun k hkn hknm => by
    exact (not_lt_of_ge hkn) hknm.1

private theorem integrable_exp_potentialCoordinate_apply' {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (k : ℕ) (x : Vec d) :
    Integrable (fun ω : Sample d => Real.exp (ω k x)) M.P.toMeasure := by
  let evalK : Sample d → ℝ := fun ω => ω k x
  let eval0 : Field d → ℝ := fun g => g 0
  let phi : ℝ → ℝ := Real.exp
  have hevalK : Measurable evalK :=
    (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)
  have heval0 : Measurable eval0 :=
    SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0
  have hphi : Measurable phi := Real.measurable_exp
  have hmap := map_potentialCoordinate_apply_eq_zero M k x
  have h0map : Integrable phi
      (Measure.map eval0
        (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure) :=
    (integrable_map_measure hphi.aestronglyMeasurable heval0.aemeasurable).2
      M.G4.exponential_integrable
  have hkmap : Integrable phi (Measure.map evalK M.P.toMeasure) := by
    rw [hmap]
    exact h0map
  simpa [evalK, phi, Function.comp_def] using
    (integrable_map_measure hphi.aestronglyMeasurable hevalK.aemeasurable).1 hkmap

private theorem integral_exp_potentialCoordinate_apply' {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (k : ℕ) (x : Vec d) :
    ∫ ω : Sample d, Real.exp (ω k x) ∂M.P.toMeasure =
      ∫ g : Field d, Real.exp (g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
  let evalK : Sample d → ℝ := fun ω => ω k x
  let eval0 : Field d → ℝ := fun g => g 0
  let phi : ℝ → ℝ := Real.exp
  have hevalK : Measurable evalK :=
    (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)
  have heval0 : Measurable eval0 :=
    SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0
  have hphi : Measurable phi := Real.measurable_exp
  calc
    ∫ ω : Sample d, Real.exp (ω k x) ∂M.P.toMeasure =
        ∫ z, phi z ∂Measure.map evalK M.P.toMeasure := by
      simpa [evalK, phi, Function.comp_def] using
        (integral_map hevalK.aemeasurable hphi.aestronglyMeasurable).symm
    _ = ∫ z, phi z ∂Measure.map eval0
        (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
      rw [map_potentialCoordinate_apply_eq_zero M k x]
    _ = ∫ g : Field d, Real.exp (g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
      simpa [eval0, phi, Function.comp_def] using
        integral_map heval0.aemeasurable hphi.aestronglyMeasurable

private theorem freshCutoffRatio_integrable {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    Integrable (freshCutoffRatio M n m x) M.P.toMeasure := by
  let X : ℕ → Sample d → ℝ :=
    fun k ω => ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P
  have hIndep : iIndepFun X M.P.toMeasure := by
    simpa [X, Function.comp_def] using M.shellPrefix.independent.comp
      (fun _ g => g x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P)
      (fun _ => (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).sub
        measurable_const)
  have hMeas : ∀ k, Measurable (X k) := fun k =>
    ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)).sub measurable_const
  have hTerm : ∀ k ∈ Finset.Ioc n m,
      Integrable (fun ω => Real.exp (1 * X k ω)) M.P.toMeasure := by
    intro k _
    have h := (integrable_exp_potentialCoordinate_apply' M k x).const_mul
      (Real.exp (-SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P))
    convert h using 1
    funext ω
    simp only [X, one_mul]
    rw [Real.exp_sub, Real.exp_neg]
    ring
  have hSum := hIndep.integrable_exp_mul_sum (t := (1 : ℝ)) hMeas hTerm
  change Integrable (fun ω => Real.exp (∑ k ∈ Finset.Ioc n m, X k ω)) M.P.toMeasure
  simpa only [one_mul, Finset.sum_apply] using hSum

/-- The multiplicative fresh block has conditional and unconditional mean one. -/
private theorem integral_freshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    ∫ ω : Sample d, freshCutoffRatio M n m x ω ∂M.P.toMeasure = 1 := by
  let X : ℕ → Sample d → ℝ :=
    fun k ω => ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P
  have hIndep : iIndepFun X M.P.toMeasure := by
    simpa [X, Function.comp_def] using M.shellPrefix.independent.comp
      (fun _ g => g x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P)
      (fun _ => (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).sub
        measurable_const)
  have hMeas : ∀ k, Measurable (X k) := fun k =>
    ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)).sub measurable_const
  let Z : ℝ := ∫ g : Field d, Real.exp (g 0)
    ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure
  have hZ_nonneg : 0 ≤ Z := integral_nonneg fun _ => (Real.exp_pos _).le
  have hZ_pos : 0 < Z := by
    have hlog : 0 < Real.log Z := by
      simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using M.G4.tauSq_pos
    exact zero_lt_one.trans ((Real.log_pos_iff hZ_nonneg).mp hlog)
  have hexp_tau : Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) = Z := by
    simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using Real.exp_log hZ_pos
  have hFactor : ∀ k, ProbabilityTheory.mgf (X k) M.P.toMeasure 1 = 1 := by
    intro k
    rw [ProbabilityTheory.mgf]
    have hRaw := integral_exp_potentialCoordinate_apply' M k x
    calc
      ∫ ω, Real.exp (1 * X k ω) ∂M.P.toMeasure =
          Real.exp (-SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) *
            ∫ ω, Real.exp (ω k x) ∂M.P.toMeasure := by
        rw [← integral_const_mul]
        apply integral_congr_ae
        filter_upwards with ω
        simp only [X, one_mul]
        rw [Real.exp_sub, Real.exp_neg]
        ring
      _ = Real.exp (-SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) * Z := by rw [hRaw]
      _ = 1 := by rw [Real.exp_neg, hexp_tau]; field_simp
  calc
    ∫ ω : Sample d, freshCutoffRatio M n m x ω ∂M.P.toMeasure =
        ProbabilityTheory.mgf (∑ k ∈ Finset.Ioc n m, X k)
          M.P.toMeasure 1 := by
      simp [ProbabilityTheory.mgf, freshCutoffRatio, X, Finset.sum_apply]
    _ = ∏ k ∈ Finset.Ioc n m, ProbabilityTheory.mgf (X k) M.P.toMeasure 1 :=
      hIndep.mgf_sum hMeas _
    _ = 1 := by simp [hFactor]

/-- Conditioning the fresh multiplier on the lower prefix gives one. -/
private theorem condExp_freshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    M.P.toMeasure[freshCutoffRatio M n m x | potentialIndexSigma (Set.Iic n)]
      =ᵐ[M.P.toMeasure] fun _ => 1 := by
  have hFresh := measurable_freshCutoffRatio_block M n m x
  have hIndep := indep_prefix_fresh M n m
  have h := condExp_indep_eq
    (potentialIndexSigma_le_borel (d := d) (Set.Ioc n m))
    (potentialIndexSigma_le_borel (d := d) (Set.Iic n))
    hFresh.stronglyMeasurable hIndep.symm
  simpa [integral_freshCutoffRatio M n m x] using h

/-- The reciprocal fresh multiplier. -/
private def inverseFreshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ)
    (x : Vec d) (ω : Sample d) : ℝ :=
  Real.exp (-∑ k ∈ Finset.Ioc n m,
    (ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P))

private theorem inverseFreshCutoffRatio_eq_inv {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ)
    (x : Vec d) (ω : Sample d) :
    inverseFreshCutoffRatio M n m x ω = (freshCutoffRatio M n m x ω)⁻¹ := by
  unfold inverseFreshCutoffRatio freshCutoffRatio
  exact Real.exp_neg _

private theorem integral_exp_neg_zeroPotential_eq_exp {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) :
    ∫ g : Field d, Real.exp (-g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure =
      ∫ g : Field d, Real.exp (g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
  let μ0 := (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure
  let F : Field d → ℝ := fun g => Real.exp (g 0)
  have hF : Measurable F :=
    (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0).exp
  have hneg : Measure.map SubdiffusiveProcess.Frozen.Assumptions.PotentialField.negate μ0 = μ0 := by
    simpa [μ0] using congrArg ProbabilityMeasure.toMeasure M.G3.negation
  calc
    ∫ g : Field d, Real.exp (-g 0) ∂μ0 =
        ∫ g : Field d, F (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.negate g) ∂μ0 := by
      apply integral_congr_ae
      filter_upwards with g
      simp [F]
    _ = ∫ g : Field d, F g
        ∂Measure.map SubdiffusiveProcess.Frozen.Assumptions.PotentialField.negate μ0 := by
      exact (integral_map
        SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_negate.aemeasurable
        hF.aestronglyMeasurable).symm
    _ = ∫ g : Field d, Real.exp (g 0) ∂μ0 := by rw [hneg]

private theorem integrable_exp_neg_potentialCoordinate_apply {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (k : ℕ) (x : Vec d) :
    Integrable (fun ω : Sample d => Real.exp (-ω k x)) M.P.toMeasure := by
  let evalK : Sample d → ℝ := fun ω => ω k x
  let eval0 : Field d → ℝ := fun g => g 0
  let phi : ℝ → ℝ := fun z => Real.exp (-z)
  have hevalK : Measurable evalK :=
    (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)
  have heval0 : Measurable eval0 :=
    SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0
  have hphi : Measurable phi := Real.measurable_exp.comp measurable_neg
  have hneg0 : Integrable (fun g : Field d => Real.exp (-g 0))
      (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
    let μ0 := (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure
    let F : Field d → ℝ := fun g => Real.exp (g 0)
    have hF : Measurable F :=
      (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0).exp
    have hneg : Measure.map SubdiffusiveProcess.Frozen.Assumptions.PotentialField.negate μ0 = μ0 := by
      simpa [μ0] using congrArg ProbabilityMeasure.toMeasure M.G3.negation
    have hmapped : Integrable F
        (Measure.map SubdiffusiveProcess.Frozen.Assumptions.PotentialField.negate μ0) := by
      rw [hneg]
      exact M.G4.exponential_integrable
    have hcomp := (integrable_map_measure hF.aestronglyMeasurable
      SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_negate.aemeasurable).1 hmapped
    simpa [F, μ0, Function.comp_def] using hcomp
  have h0map : Integrable phi
      (Measure.map eval0
        (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure) :=
    (integrable_map_measure hphi.aestronglyMeasurable heval0.aemeasurable).2 hneg0
  have hkmap : Integrable phi (Measure.map evalK M.P.toMeasure) := by
    rw [map_potentialCoordinate_apply_eq_zero M k x]
    exact h0map
  simpa [evalK, phi, Function.comp_def] using
    (integrable_map_measure hphi.aestronglyMeasurable hevalK.aemeasurable).1 hkmap

private theorem integral_exp_neg_potentialCoordinate_apply {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (k : ℕ) (x : Vec d) :
    ∫ ω : Sample d, Real.exp (-ω k x) ∂M.P.toMeasure =
      ∫ g : Field d, Real.exp (g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
  let evalK : Sample d → ℝ := fun ω => ω k x
  let eval0 : Field d → ℝ := fun g => g 0
  let phi : ℝ → ℝ := fun z => Real.exp (-z)
  have hevalK : Measurable evalK :=
    (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)
  have heval0 : Measurable eval0 :=
    SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval 0
  have hphi : Measurable phi := Real.measurable_exp.comp measurable_neg
  calc
    ∫ ω : Sample d, Real.exp (-ω k x) ∂M.P.toMeasure =
        ∫ z, phi z ∂Measure.map evalK M.P.toMeasure := by
      simpa [evalK, phi, Function.comp_def] using
        (integral_map hevalK.aemeasurable hphi.aestronglyMeasurable).symm
    _ = ∫ z, phi z ∂Measure.map eval0
        (SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
      rw [map_potentialCoordinate_apply_eq_zero M k x]
    _ = ∫ g : Field d, Real.exp (-g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure := by
      simpa [eval0, phi, Function.comp_def] using
        integral_map heval0.aemeasurable hphi.aestronglyMeasurable
    _ = ∫ g : Field d, Real.exp (g 0)
        ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure :=
      integral_exp_neg_zeroPotential_eq_exp M

private theorem inverseFreshCutoffRatio_integrable {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    Integrable (inverseFreshCutoffRatio M n m x) M.P.toMeasure := by
  let X : ℕ → Sample d → ℝ :=
    fun k ω => ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P
  have hIndep : iIndepFun X M.P.toMeasure := by
    simpa [X, Function.comp_def] using M.shellPrefix.independent.comp
      (fun _ g => g x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P)
      (fun _ => (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).sub
        measurable_const)
  have hMeas : ∀ k, Measurable (X k) := fun k =>
    ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)).sub measurable_const
  have hTerm : ∀ k ∈ Finset.Ioc n m,
      Integrable (fun ω => Real.exp ((-1 : ℝ) * X k ω)) M.P.toMeasure := by
    intro k _
    have h := (integrable_exp_neg_potentialCoordinate_apply M k x).const_mul
      (Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P))
    convert h using 1
    funext ω
    simp only [X]
    rw [show (-1 : ℝ) * (ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) =
      -ω k x + SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P by ring, Real.exp_add]
    ring
  have hSum := hIndep.integrable_exp_mul_sum (t := (-1 : ℝ)) hMeas hTerm
  change Integrable (fun ω => Real.exp (-∑ k ∈ Finset.Ioc n m, X k ω)) M.P.toMeasure
  simpa only [Finset.sum_apply, neg_one_mul, Finset.sum_neg_distrib] using hSum

/-- The inverse fresh block has the exact G3 expectation printed in the paper. -/
private theorem integral_inverseFreshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    ∫ ω : Sample d, inverseFreshCutoffRatio M n m x ω ∂M.P.toMeasure =
      Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) := by
  let X : ℕ → Sample d → ℝ :=
    fun k ω => ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P
  have hIndep : iIndepFun X M.P.toMeasure := by
    simpa [X, Function.comp_def] using M.shellPrefix.independent.comp
      (fun _ g => g x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P)
      (fun _ => (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).sub
        measurable_const)
  have hMeas : ∀ k, Measurable (X k) := fun k =>
    ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)).sub measurable_const
  let Z : ℝ := ∫ g : Field d, Real.exp (g 0)
    ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure
  have hZ_nonneg : 0 ≤ Z := integral_nonneg fun _ => (Real.exp_pos _).le
  have hZ_pos : 0 < Z := by
    have hlog : 0 < Real.log Z := by
      simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using M.G4.tauSq_pos
    exact zero_lt_one.trans ((Real.log_pos_iff hZ_nonneg).mp hlog)
  have hexp_tau : Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) = Z := by
    simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using Real.exp_log hZ_pos
  have hFactor : ∀ k, ProbabilityTheory.mgf (X k) M.P.toMeasure (-1) =
      Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
    intro k
    rw [ProbabilityTheory.mgf]
    have hRaw := integral_exp_neg_potentialCoordinate_apply M k x
    calc
      ∫ ω, Real.exp ((-1 : ℝ) * X k ω) ∂M.P.toMeasure =
          Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) *
            ∫ ω, Real.exp (-ω k x) ∂M.P.toMeasure := by
        rw [← integral_const_mul]
        apply integral_congr_ae
        filter_upwards with ω
        simp only [X]
        rw [show (-1 : ℝ) * (ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) =
          SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P + -ω k x by ring, Real.exp_add]
      _ = Z * Z := by rw [hRaw, hexp_tau]
      _ = Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
        rw [← hexp_tau, ← Real.exp_add]
        congr 1
        ring
  calc
    ∫ ω : Sample d, inverseFreshCutoffRatio M n m x ω ∂M.P.toMeasure =
        ProbabilityTheory.mgf (∑ k ∈ Finset.Ioc n m, X k)
          M.P.toMeasure (-1) := by
      simp only [ProbabilityTheory.mgf, inverseFreshCutoffRatio, X,
        Finset.sum_apply, neg_one_mul]
    _ = ∏ k ∈ Finset.Ioc n m, ProbabilityTheory.mgf (X k) M.P.toMeasure (-1) :=
      hIndep.mgf_sum hMeas _
    _ = ∏ _k ∈ Finset.Ioc n m,
        Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
      apply Finset.prod_congr rfl
      intro k _
      exact hFactor k
    _ = Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) := by
      rw [Finset.prod_const]
      rw [Nat.card_Ioc]
      rw [← Real.exp_nat_mul]
      congr 1
      ring

private theorem measurable_inverseFreshCutoffRatio_block {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    @Measurable (Sample d) ℝ (potentialIndexSigma (Set.Ioc n m)) inferInstance
      (inverseFreshCutoffRatio M n m x) := by
  apply Measurable.exp
  apply Measurable.neg
  apply Finset.measurable_sum
  intro k hk
  have hk' : k ∈ Set.Ioc n m := by simpa using hk
  exact ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
    (measurable_potentialCoordinate_indexSigma hk')).sub measurable_const

/-- Conditional inverse-shell expectation, including the literal paper constant. -/
private theorem condExp_inverseFreshCutoffRatio {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (n m : ℕ) (x : Vec d) :
    M.P.toMeasure[inverseFreshCutoffRatio M n m x |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
      fun _ => Real.exp
        (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) := by
  have hFresh := measurable_inverseFreshCutoffRatio_block M n m x
  have hIndep := indep_prefix_fresh M n m
  have h := condExp_indep_eq
    (potentialIndexSigma_le_borel (d := d) (Set.Ioc n m))
    (potentialIndexSigma_le_borel (d := d) (Set.Iic n))
    hFresh.stronglyMeasurable hIndep.symm
  simpa [integral_inverseFreshCutoffRatio M n m x] using h

/-- Pointwise cutoff martingale identity at the prefix sigma-field. -/
private theorem condExp_aCutoff {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (x : Vec d) :
    M.P.toMeasure[(fun ω : Sample d =>
        SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x) |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
      fun ω => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x := by
  let lower : Sample d → ℝ := fun ω =>
    SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x
  let fresh : Sample d → ℝ := freshCutoffRatio M n m x
  have hlower : StronglyMeasurable[potentialIndexSigma (Set.Iic n)] lower :=
    (measurable_aCutoff_prefix M n x).stronglyMeasurable
  have hfresh : Integrable fresh M.P.toMeasure :=
    freshCutoffRatio_integrable M n m x
  have hprod : Integrable (lower * fresh) M.P.toMeasure := by
    have hm := integrable_aCutoff_apply M m x
    convert hm using 1
    funext ω
    exact (aCutoff_eq_mul_freshCutoffRatio M hnm x ω).symm
  calc
    M.P.toMeasure[(fun ω : Sample d =>
        SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x) |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
        M.P.toMeasure[lower * fresh | potentialIndexSigma (Set.Iic n)] := by
      apply condExp_congr_ae
      filter_upwards with ω
      exact aCutoff_eq_mul_freshCutoffRatio M hnm x ω
    _ =ᵐ[M.P.toMeasure] lower *
        M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] :=
      condExp_mul_of_stronglyMeasurable_left hlower hprod hfresh
    _ =ᵐ[M.P.toMeasure] lower := by
      filter_upwards [condExp_freshCutoffRatio M n m x] with ω hω
      change M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] ω = 1 at hω
      change lower ω * M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] ω = lower ω
      rw [hω, mul_one]

private theorem integrable_aCutoff_inv {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (x : Vec d) :
    Integrable (fun ω : Sample d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹) M.P.toMeasure := by
  let f : Sample d → ℝ := fun ω => inverseCutoffRatioMinusOne M L (-1) ω x
  have hfMeas : Measurable f := by
    have hfEq : f = fun ω : Sample d =>
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ - 1 := by
      funext ω
      simp [f, inverseCutoffRatioMinusOne, aCutoffAtInt]
    rw [hfEq]
    change Measurable (fun ω : Sample d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ - 1)
    exact (((measurable_cutoff_uncurry M L).comp
      (measurable_id.prodMk (measurable_const : Measurable fun _ : Sample d => x))).inv).sub
        measurable_const
  have hAbs : Integrable (fun ω => |f ω|) M.P.toMeasure := by
    have h := (integral_abs_inverseCutoffRatioMinusOne_rpow_root_le_raw
      M L (-1) x 1 (by norm_num) (by norm_num) (by omega)).1
    simpa only [Real.rpow_one] using h
  have hf : Integrable f M.P.toMeasure := by
    rw [← integrable_norm_iff hfMeas.aestronglyMeasurable]
    simpa only [Real.norm_eq_abs] using hAbs
  have hsum := hf.add (integrable_const (1 : ℝ))
  convert hsum using 1
  funext ω
  simp [f, inverseCutoffRatioMinusOne, aCutoffAtInt]

/-- Pointwise inverse-cutoff conditional expectation. -/
private theorem condExp_aCutoff_inv {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (x : Vec d) :
    M.P.toMeasure[(fun ω : Sample d =>
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹) |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
      fun ω => Real.exp
          (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) *
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ := by
  let lower : Sample d → ℝ := fun ω =>
    (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹
  let fresh : Sample d → ℝ := inverseFreshCutoffRatio M n m x
  have hlower : StronglyMeasurable[potentialIndexSigma (Set.Iic n)] lower :=
    (measurable_aCutoff_prefix M n x).inv.stronglyMeasurable
  have hfresh : Integrable fresh M.P.toMeasure :=
    inverseFreshCutoffRatio_integrable M n m x
  have hprod : Integrable (lower * fresh) M.P.toMeasure := by
    have hm := integrable_aCutoff_inv M m x
    convert hm using 1
    funext ω
    change lower ω * fresh ω = _
    dsimp only [fresh]
    rw [inverseFreshCutoffRatio_eq_inv]
    dsimp only [lower]
    rw [aCutoff_eq_mul_freshCutoffRatio M hnm x ω, mul_inv_rev]
    ring
  calc
    M.P.toMeasure[(fun ω : Sample d =>
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹) |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
        M.P.toMeasure[lower * fresh | potentialIndexSigma (Set.Iic n)] := by
      apply condExp_congr_ae
      filter_upwards with ω
      change _ = lower ω * fresh ω
      dsimp only [fresh]
      rw [inverseFreshCutoffRatio_eq_inv]
      dsimp only [lower]
      rw [aCutoff_eq_mul_freshCutoffRatio M hnm x ω, mul_inv_rev]
      ring
    _ =ᵐ[M.P.toMeasure] lower *
        M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] :=
      condExp_mul_of_stronglyMeasurable_left hlower hprod hfresh
    _ =ᵐ[M.P.toMeasure] fun ω => Real.exp
          (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) *
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ := by
      filter_upwards [condExp_inverseFreshCutoffRatio M n m x] with ω hω
      change M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] ω = _ at hω
      change lower ω * M.P.toMeasure[fresh | potentialIndexSigma (Set.Iic n)] ω = _
      rw [hω]
      dsimp [lower]
      ring

/-- Joint prefix measurability of the cutoff in sample and space. -/
private theorem measurable_aCutoff_prefix_uncurry {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) :
    @Measurable (Sample d × Vec d) ℝ
      (@Prod.instMeasurableSpace (Sample d) (Vec d)
        (potentialIndexSigma (Set.Iic L)) inferInstance)
      inferInstance
      (fun z => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2) := by
  letI : MeasurableSpace (Sample d) := potentialIndexSigma (Set.Iic L)
  have hEvalSwap : Measurable
      (Function.uncurry fun x : Vec d => fun g : Field d => g x) := by
    exact measurable_uncurry_of_continuous_of_measurable
      (ι := Vec d) (α := Field d) (β := ℝ)
      (fun g => g.1.1.continuous)
      (fun x => SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x)
  have hEval : Measurable (fun q : Field d × Vec d => q.1 q.2) :=
    hEvalSwap.comp measurable_swap
  apply Measurable.exp
  apply Finset.measurable_sum
  intro k hk
  simp only [Finset.mem_range] at hk
  have hkL : k ≤ L := Nat.le_of_lt_succ hk
  have hCoordinate : Measurable (fun z : Sample d × Vec d => (z.1 k, z.2)) :=
    ((measurable_potentialCoordinate_indexSigma (I := Set.Iic L) hkL).comp
      measurable_fst).prodMk measurable_snd
  exact (hEval.comp hCoordinate).sub measurable_const

private def weightedCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) (h : Vec d → ℝ) (ω : Sample d) : ℝ :=
  ∫ x, SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x * h x ∂ν

private theorem integrable_weightedCutoff_prod {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    Integrable (fun z : Sample d × Vec d =>
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2 * h z.2)
      (M.P.toMeasure.prod ν) := by
  have hJoint : AEStronglyMeasurable (fun z : Sample d × Vec d =>
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2 * h z.2)
      (M.P.toMeasure.prod ν) :=
    ((measurable_cutoff_uncurry M L).mul
      (hhMeas.comp measurable_snd)).aestronglyMeasurable
  apply (integrable_prod_iff' hJoint).mpr
  constructor
  · filter_upwards with x
    simpa [mul_comm] using (integrable_aCutoff_apply M L x).const_mul (h x)
  · have hNorm : (fun x => ∫ ω : Sample d,
        ‖SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x * h x‖ ∂M.P.toMeasure) = h := by
      funext x
      rw [show (fun ω : Sample d =>
          ‖SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x * h x‖) =
          fun ω => h x * SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x by
        funext ω
        rw [Real.norm_of_nonneg (mul_nonneg
          (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω x).le (hhNonneg x))]
        ring]
      rw [integral_const_mul, integral_aCutoff_apply M L x, mul_one]
    rw [hNorm]
    exact hhInt

private theorem integrable_weightedCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    Integrable (weightedCutoffIntegral M L ν h) M.P.toMeasure := by
  exact (integrable_weightedCutoff_prod M L ν hhMeas hhNonneg hhInt).integral_prod_left

private theorem stronglyMeasurable_weightedCutoffIntegral_prefix {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ} (hhMeas : Measurable h) :
    @MeasureTheory.StronglyMeasurable (Sample d) ℝ inferInstance
      (potentialIndexSigma (Set.Iic L))
      (weightedCutoffIntegral M L ν h) := by
  have hJoint : @Measurable (Sample d × Vec d) ℝ
      (@Prod.instMeasurableSpace (Sample d) (Vec d)
        (potentialIndexSigma (Set.Iic L)) inferInstance)
      inferInstance
      (fun z => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2 * h z.2) :=
    measurable_aCutoff_prefix_uncurry M L |>.mul (hhMeas.comp measurable_snd)
  letI : MeasurableSpace (Sample d) := potentialIndexSigma (Set.Iic L)
  exact hJoint.stronglyMeasurable.integral_prod_right'

/-- Conditional expectation commutes with every deterministic nonnegative
spatial weight in the primal energy. -/
private theorem condExp_weightedCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    M.P.toMeasure[weightedCutoffIntegral M m ν h |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
      weightedCutoffIntegral M n ν h := by
  let ambient : MeasurableSpace (Sample d) := inferInstance
  let μ := M.P.toMeasure
  let prefixSigma := potentialIndexSigma (d := d) (Set.Iic n)
  have hle : prefixSigma ≤ ambient :=
    potentialIndexSigma_le_borel (d := d) (Set.Iic n)
  have hmInt := integrable_weightedCutoffIntegral M m ν hhMeas hhNonneg hhInt
  have hnInt := integrable_weightedCutoffIntegral M n ν hhMeas hhNonneg hhInt
  have hnMeas := stronglyMeasurable_weightedCutoffIntegral_prefix M n ν hhMeas
  apply (ae_eq_condExp_of_forall_setIntegral_eq (m := prefixSigma) (m₀ := ambient)
    hle hmInt (fun s _ _ => hnInt.integrableOn) ?_
      hnMeas.aestronglyMeasurable).symm
  intro s hs _hsFinite
  letI : MeasurableSpace (Sample d) := ambient
  have hsAmbient : MeasurableSet s := hle s hs
  have hmProd := integrable_weightedCutoff_prod M m ν hhMeas hhNonneg hhInt
  have hnProd := integrable_weightedCutoff_prod M n ν hhMeas hhNonneg hhInt
  have hmRestrict : Integrable (fun z : Sample d × Vec d =>
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m z.1 z.2 * h z.2)
      ((μ.restrict s).prod ν) := by
    rw [← Measure.restrict_univ (μ := ν), Measure.prod_restrict]
    exact hmProd.restrict
  have hnRestrict : Integrable (fun z : Sample d × Vec d =>
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n z.1 z.2 * h z.2)
      ((μ.restrict s).prod ν) := by
    rw [← Measure.restrict_univ (μ := ν), Measure.prod_restrict]
    exact hnProd.restrict
  change ∫ ω in s, weightedCutoffIntegral M n ν h ω ∂μ =
    ∫ ω in s, weightedCutoffIntegral M m ν h ω ∂μ
  rw [show (∫ ω in s, weightedCutoffIntegral M n ν h ω ∂μ) =
      ∫ x, ∫ ω in s,
        SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x * h x ∂μ ∂ν by
    change (∫ ω, ∫ x,
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x * h x ∂ν ∂μ.restrict s) = _
    exact integral_integral_swap hnRestrict]
  rw [show (∫ ω in s, weightedCutoffIntegral M m ν h ω ∂μ) =
      ∫ x, ∫ ω in s,
        SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x * h x ∂μ ∂ν by
    change (∫ ω, ∫ x,
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x * h x ∂ν ∂μ.restrict s) = _
    exact integral_integral_swap hmRestrict]
  apply integral_congr_ae
  filter_upwards with x
  rw [integral_mul_const, integral_mul_const]
  congr 1
  calc
    ∫ ω in s, SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x ∂μ =
        ∫ ω in s,
          μ[(fun ω : Sample d => SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x) |
            prefixSigma] ω ∂μ := by
      apply setIntegral_congr_ae hsAmbient
      filter_upwards [condExp_aCutoff M hnm x] with ω hω _hωs
      exact hω.symm
    _ = ∫ ω in s, SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x ∂μ :=
      setIntegral_condExp (m := prefixSigma) (m₀ := ambient)
        hle (integrable_aCutoff_apply M m x) hs

private theorem integral_aCutoff_inv {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (x : Vec d) :
    ∫ ω : Sample d, (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ ∂M.P.toMeasure =
      Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((L + 1 : ℕ) : ℝ)) := by
  let X : ℕ → Sample d → ℝ :=
    fun k ω => ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P
  have hIndep : iIndepFun X M.P.toMeasure := by
    simpa [X, Function.comp_def] using M.shellPrefix.independent.comp
      (fun _ g => g x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P)
      (fun _ => (SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).sub
        measurable_const)
  have hMeas : ∀ k, Measurable (X k) := fun k =>
    ((SubdiffusiveProcess.Frozen.Assumptions.PotentialField.measurable_eval x).comp
      (SubdiffusiveProcess.Frozen.Assumptions.measurable_potentialCoordinate k)).sub measurable_const
  let Z : ℝ := ∫ g : Field d, Real.exp (g 0)
    ∂(SubdiffusiveProcess.Frozen.Assumptions.zeroPotentialLaw M.P).toMeasure
  have hZ_nonneg : 0 ≤ Z := integral_nonneg fun _ => (Real.exp_pos _).le
  have hZ_pos : 0 < Z := by
    have hlog : 0 < Real.log Z := by
      simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using M.G4.tauSq_pos
    exact zero_lt_one.trans ((Real.log_pos_iff hZ_nonneg).mp hlog)
  have hexp_tau : Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) = Z := by
    simpa [Z, SubdiffusiveProcess.Frozen.Assumptions.tauSq] using Real.exp_log hZ_pos
  have hFactor : ∀ k, ProbabilityTheory.mgf (X k) M.P.toMeasure (-1) =
      Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
    intro k
    rw [ProbabilityTheory.mgf]
    have hRaw := integral_exp_neg_potentialCoordinate_apply M k x
    calc
      ∫ ω, Real.exp ((-1 : ℝ) * X k ω) ∂M.P.toMeasure =
          Real.exp (SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) *
            ∫ ω, Real.exp (-ω k x) ∂M.P.toMeasure := by
        rw [← integral_const_mul]
        apply integral_congr_ae
        filter_upwards with ω
        simp only [X]
        rw [show (-1 : ℝ) * (ω k x - SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) =
          SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P + -ω k x by ring, Real.exp_add]
      _ = Z * Z := by rw [hRaw, hexp_tau]
      _ = Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
        rw [← hexp_tau, ← Real.exp_add]
        congr 1
        ring
  calc
    ∫ ω : Sample d, (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ ∂M.P.toMeasure =
        ProbabilityTheory.mgf (∑ k ∈ Finset.range (L + 1), X k)
          M.P.toMeasure (-1) := by
      simp only [ProbabilityTheory.mgf, SubdiffusiveProcess.Frozen.Assumptions.aCutoff, X,
        Finset.sum_apply, Real.exp_neg, neg_one_mul]
    _ = ∏ k ∈ Finset.range (L + 1),
        ProbabilityTheory.mgf (X k) M.P.toMeasure (-1) := hIndep.mgf_sum hMeas _
    _ = ∏ _k ∈ Finset.range (L + 1),
        Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P) := by
      apply Finset.prod_congr rfl
      intro k _
      exact hFactor k
    _ = Real.exp (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((L + 1 : ℕ) : ℝ)) := by
      rw [Finset.prod_const, Finset.card_range, ← Real.exp_nat_mul]
      congr 1
      ring

private def weightedInverseCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) (h : Vec d → ℝ) (ω : Sample d) : ℝ :=
  ∫ x, (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ * h x ∂ν

private theorem integrable_weightedInverseCutoff_prod {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    Integrable (fun z : Sample d × Vec d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2)⁻¹ * h z.2)
      (M.P.toMeasure.prod ν) := by
  have hJoint : AEStronglyMeasurable (fun z : Sample d × Vec d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2)⁻¹ * h z.2)
      (M.P.toMeasure.prod ν) :=
    ((measurable_cutoff_uncurry M L).inv.mul
      (hhMeas.comp measurable_snd)).aestronglyMeasurable
  apply (integrable_prod_iff' hJoint).mpr
  constructor
  · filter_upwards with x
    simpa [mul_comm] using (integrable_aCutoff_inv M L x).const_mul (h x)
  · let c := Real.exp
      (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((L + 1 : ℕ) : ℝ))
    have hNorm : (fun x => ∫ ω : Sample d,
        ‖(SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ * h x‖ ∂M.P.toMeasure) =
        fun x => c * h x := by
      funext x
      rw [show (fun ω : Sample d =>
          ‖(SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ * h x‖) =
          fun ω => h x * (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ by
        funext ω
        rw [Real.norm_of_nonneg (mul_nonneg (inv_nonneg.mpr
          (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω x).le) (hhNonneg x))]
        ring]
      rw [integral_const_mul, integral_aCutoff_inv M L x]
      dsimp [c]
      ring
    rw [hNorm]
    exact hhInt.const_mul c

private theorem integrable_weightedInverseCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    Integrable (weightedInverseCutoffIntegral M L ν h) M.P.toMeasure :=
  (integrable_weightedInverseCutoff_prod M L ν hhMeas hhNonneg hhInt).integral_prod_left

private theorem stronglyMeasurable_weightedInverseCutoffIntegral_prefix {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ} (hhMeas : Measurable h) :
    @MeasureTheory.StronglyMeasurable (Sample d) ℝ inferInstance
      (potentialIndexSigma (Set.Iic L))
      (weightedInverseCutoffIntegral M L ν h) := by
  have hJoint : @Measurable (Sample d × Vec d) ℝ
      (@Prod.instMeasurableSpace (Sample d) (Vec d)
        (potentialIndexSigma (Set.Iic L)) inferInstance)
      inferInstance
      (fun z => (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L z.1 z.2)⁻¹ * h z.2) :=
    (measurable_aCutoff_prefix_uncurry M L).inv.mul (hhMeas.comp measurable_snd)
  letI : MeasurableSpace (Sample d) := potentialIndexSigma (Set.Iic L)
  exact hJoint.stronglyMeasurable.integral_prod_right'

/-- Dual fixed-competitor conditional energy identity. -/
private theorem condExp_weightedInverseCutoffIntegral {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (ν : Measure (Vec d)) [SFinite ν] {h : Vec d → ℝ}
    (hhMeas : Measurable h) (hhNonneg : ∀ x, 0 ≤ h x)
    (hhInt : Integrable h ν) :
    M.P.toMeasure[weightedInverseCutoffIntegral M m ν h |
        potentialIndexSigma (Set.Iic n)] =ᵐ[M.P.toMeasure]
      fun ω => Real.exp
          (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) *
        weightedInverseCutoffIntegral M n ν h ω := by
  let ambient : MeasurableSpace (Sample d) := inferInstance
  let μ := M.P.toMeasure
  let prefixSigma := potentialIndexSigma (d := d) (Set.Iic n)
  let c := Real.exp
    (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ))
  have hle : prefixSigma ≤ ambient := potentialIndexSigma_le_borel _
  have hmInt := integrable_weightedInverseCutoffIntegral M m ν hhMeas hhNonneg hhInt
  have hnInt := integrable_weightedInverseCutoffIntegral M n ν hhMeas hhNonneg hhInt
  have hgInt := hnInt.const_mul c
  have hnMeas := stronglyMeasurable_weightedInverseCutoffIntegral_prefix M n ν hhMeas
  have hgMeas : @MeasureTheory.StronglyMeasurable (Sample d) ℝ inferInstance prefixSigma
      (fun ω => c * weightedInverseCutoffIntegral M n ν h ω) :=
    hnMeas.const_mul c
  apply (ae_eq_condExp_of_forall_setIntegral_eq (m := prefixSigma) (m₀ := ambient)
    hle hmInt (fun s _ _ => hgInt.integrableOn) ?_ hgMeas.aestronglyMeasurable).symm
  intro s hs _hsFinite
  letI : MeasurableSpace (Sample d) := ambient
  have hsAmbient : MeasurableSet s := hle s hs
  have hmProd := integrable_weightedInverseCutoff_prod M m ν hhMeas hhNonneg hhInt
  have hnProd := integrable_weightedInverseCutoff_prod M n ν hhMeas hhNonneg hhInt
  have hmRestrict : Integrable (fun z : Sample d × Vec d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m z.1 z.2)⁻¹ * h z.2)
      ((μ.restrict s).prod ν) := by
    rw [← Measure.restrict_univ (μ := ν), Measure.prod_restrict]
    exact hmProd.restrict
  have hnRestrict : Integrable (fun z : Sample d × Vec d =>
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n z.1 z.2)⁻¹ * h z.2)
      ((μ.restrict s).prod ν) := by
    rw [← Measure.restrict_univ (μ := ν), Measure.prod_restrict]
    exact hnProd.restrict
  change ∫ ω in s, c * weightedInverseCutoffIntegral M n ν h ω ∂μ =
    ∫ ω in s, weightedInverseCutoffIntegral M m ν h ω ∂μ
  rw [integral_const_mul]
  rw [show (∫ ω in s, weightedInverseCutoffIntegral M n ν h ω ∂μ) =
      ∫ x, ∫ ω in s,
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ * h x ∂μ ∂ν by
    change (∫ ω, ∫ x,
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ * h x ∂ν ∂μ.restrict s) = _
    exact integral_integral_swap hnRestrict]
  rw [show (∫ ω in s, weightedInverseCutoffIntegral M m ν h ω ∂μ) =
      ∫ x, ∫ ω in s,
        (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹ * h x ∂μ ∂ν by
    change (∫ ω, ∫ x,
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹ * h x ∂ν ∂μ.restrict s) = _
    exact integral_integral_swap hmRestrict]
  rw [← integral_const_mul]
  apply integral_congr_ae
  filter_upwards with x
  rw [integral_mul_const, integral_mul_const]
  rw [← mul_assoc]
  congr 1
  calc
    c * ∫ ω in s, (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ ∂μ =
        ∫ ω in s,
          μ[(fun ω : Sample d => (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹) |
            prefixSigma] ω ∂μ := by
      rw [← integral_const_mul]
      apply setIntegral_congr_ae hsAmbient
      filter_upwards [condExp_aCutoff_inv M hnm x] with ω hω _hωs
      change _ = c * (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω x)⁻¹ at hω
      exact hω.symm
    _ = ∫ ω in s, (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω x)⁻¹ ∂μ :=
      setIntegral_condExp (m := prefixSigma) (m₀ := ambient)
        hle (integrable_aCutoff_inv M m x) hs

private structure CutoffEllipticityData' {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ω : Sample d) (U : Ch02.Domain d) where
  lam : ℝ
  Lam : ℝ
  isElliptic : IsEllipticFieldOn lam Lam (U : Set (Vec d))
    (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω))

private theorem nonempty_cutoffEllipticityData' {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ω : Sample d) (U : Ch02.Domain d) :
    Nonempty (CutoffEllipticityData' M L ω U) := by
  let a := SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω
  have haCont : Continuous a := SubdiffusiveProcess.Frozen.Assumptions.continuous_aCutoff M L ω
  have hcompact : IsCompact (closure (U : Set (Vec d))) :=
    U.isBoundedDomain.isBounded.isCompact_closure
  have hnonempty : (closure (U : Set (Vec d))).Nonempty := U.nonempty.closure
  obtain ⟨xMin, hxMin, hMin⟩ :=
    hcompact.exists_isMinOn hnonempty haCont.continuousOn
  obtain ⟨xMax, hxMax, hMax⟩ :=
    hcompact.exists_isMaxOn hnonempty haCont.continuousOn
  refine ⟨{
    lam := a xMin
    Lam := a xMax
    isElliptic := ?_
  }⟩
  constructor
  · rw [measurable_pi_iff]
    intro i
    rw [measurable_pi_iff]
    intro j
    have hEntry : Measurable (fun x : Vec d => scalarCoeffField a x i j) := by
      have hMatrix : Continuous (fun x : Vec d => scalarCoeffField a x) :=
        haCont.smul continuous_const
      exact ((continuous_apply j).comp ((continuous_apply i).comp hMatrix)).measurable
    exact hEntry.piecewise U.measurableSet measurable_const
  · intro x hx
    exact (isEllipticMatrix_scalarMatrix (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω x)).mono
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω xMin)
      (hMin (subset_closure hx)) (hMax (subset_closure hx))

private noncomputable def cutoffEllipticityData' {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (ω : Sample d) (U : Ch02.Domain d) : CutoffEllipticityData' M L ω U :=
  Classical.choice (nonempty_cutoffEllipticityData' M L ω U)

private theorem blockEnergyDensity_scalarCoeffField' {d : ℕ}
    (a : Vec d → ℝ) (ha : ∀ x, 0 < a x) (X : BlockState d) (x : Vec d) :
    blockEnergyDensity (scalarCoeffField a) X x =
      (1 / 2 : ℝ) *
        (a x * vecDot (X.potential x) (X.potential x) +
          (a x)⁻¹ * vecDot (X.flux x) (X.flux x)) := by
  have hInv : ((Homogenization.scalarMatrix (d := d) (a x))⁻¹ : Mat d) =
      Homogenization.scalarMatrix (d := d) (a x)⁻¹ := by
    rw [Homogenization.scalarMatrix,
      Homogenization.nonsing_inv_smul (a x) (ha x).ne' (by simp)]
    simp [Homogenization.scalarMatrix]
  simp [blockEnergyDensity, blockCoeffField, blockMatrixOfCoeff,
    scalarCoeffField, Homogenization.Book.Ch02.symmPart_scalarMatrix,
    Homogenization.Book.Ch02.skewPart_scalarMatrix, hInv,
    BlockState.eval, blockMatVecMul, Homogenization.matVecMul_scalarMatrix,
    Homogenization.blockVecDot, Homogenization.matVecMul,
    Homogenization.vecDot, Homogenization.matTranspose, Finset.mul_sum,
    mul_left_comm]

/-- Scalar positive coefficients split the doubled block energy into its
potential and flux squares. -/
theorem blockEnergyDensity_scalarCoeffField_of_pos {d : ℕ}
    (a : Vec d → ℝ) (ha : ∀ x, 0 < a x) (X : BlockState d) (x : Vec d) :
    blockEnergyDensity (scalarCoeffField a) X x =
      (1 / 2 : ℝ) *
        (a x * vecDot (X.potential x) (X.potential x) +
          (a x)⁻¹ * vecDot (X.flux x) (X.flux x)) :=
  blockEnergyDensity_scalarCoeffField' a ha X x

/-- Admissible block energies against a fixed cutoff realization are
integrable over the domain. -/
theorem integrableOn_blockEnergyDensity_cutoff {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (omega : Sample d)
    (U : Ch02.Domain d) {P : BlockVec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) P X) :
    IntegrableOn
      (blockEnergyDensity
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) X)
      (U : Set (Vec d)) := by
  let E := cutoffEllipticityData' M L omega U
  exact (hX.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
    E.isElliptic).energyIntegrable

/-- Delete the flux component of a doubled competitor. -/
def zeroFluxProjection {d : ℕ} (X : BlockState d) : BlockState d where
  potential := X.potential
  flux := 0

@[simp] theorem zeroFluxProjection_idem {d : ℕ} (X : BlockState d) :
    zeroFluxProjection (zeroFluxProjection X) = zeroFluxProjection X := by
  rfl

/-- Delete the potential component of a doubled competitor. -/
def zeroPotentialProjection {d : ℕ} (X : BlockState d) : BlockState d where
  potential := 0
  flux := X.flux

@[simp] theorem zeroPotentialProjection_idem {d : ℕ} (X : BlockState d) :
    zeroPotentialProjection (zeroPotentialProjection X) = zeroPotentialProjection X := by
  rfl

/-- Deleting flux preserves admissibility for a pure-potential loading. -/
theorem zeroFluxProjection_admissible {d : ℕ}
    {U : Set (Vec d)} {p : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible U (-p, 0) X) :
    IsBlockMuAdmissible U (-p, 0) (zeroFluxProjection X) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · simpa [zeroFluxProjection] using hX.potentialCorrection_memL2
  · simpa [zeroFluxProjection] using hX.isPotentialZeroTrace
  · simp [zeroFluxProjection]
  · simpa [zeroFluxProjection] using (isSolenoidalZeroNormalTraceOn_zero (U := U))

/-- Deleting potential preserves admissibility for a pure-flux loading. -/
theorem zeroPotentialProjection_admissible {d : ℕ}
    {U : Set (Vec d)} {q : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible U (0, q) X) :
    IsBlockMuAdmissible U (0, q) (zeroPotentialProjection X) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · simp [zeroPotentialProjection]
  · simpa [zeroPotentialProjection] using (isPotentialZeroTraceOn_zero (U := U))
  · simpa [zeroPotentialProjection] using hX.fluxCorrection_memL2
  · simpa [zeroPotentialProjection] using hX.isSolenoidalZeroNormalTrace

/-- At a pure-potential loading, deleting flux cannot increase the energy. -/
theorem blockEnergyAverage_zeroFluxProjection_le {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (ω : Sample d)
    (U : Ch02.Domain d) {p : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (-p, 0) X) :
    blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω))
        (zeroFluxProjection X) ≤
      blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) X := by
  let E := cutoffEllipticityData' M L ω U
  have hXInt := (hX.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) E.isElliptic).energyIntegrable
  have hY := zeroFluxProjection_admissible hX
  have hYInt := (hY.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) E.isElliptic).energyIntegrable
  unfold blockEnergyAverage volumeAverage
  apply mul_le_mul_of_nonneg_left
  · apply integral_mono hYInt hXInt
    intro x
    have haPos : ∀ y, 0 < SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω y :=
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω
    rw [blockEnergyDensity_scalarCoeffField' _ haPos,
      blockEnergyDensity_scalarCoeffField' _ haPos]
    dsimp [zeroFluxProjection]
    have hflux : 0 ≤ vecDot (X.flux x) (X.flux x) := by
      unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
    have hainv : 0 ≤ (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ :=
      inv_nonneg.mpr (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω x).le
    have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
    rw [hzero]
    nlinarith
  · exact inv_nonneg.mpr ENNReal.toReal_nonneg

/-- At a pure-flux loading, deleting potential cannot increase the energy. -/
theorem blockEnergyAverage_zeroPotentialProjection_le {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (ω : Sample d)
    (U : Ch02.Domain d) {q : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (0, q) X) :
    blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω))
        (zeroPotentialProjection X) ≤
      blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) X := by
  let E := cutoffEllipticityData' M L ω U
  have hXInt := (hX.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) E.isElliptic).energyIntegrable
  have hY := zeroPotentialProjection_admissible hX
  have hYInt := (hY.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) E.isElliptic).energyIntegrable
  unfold blockEnergyAverage volumeAverage
  apply mul_le_mul_of_nonneg_left
  · apply integral_mono hYInt hXInt
    intro x
    have haPos : ∀ y, 0 < SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω y :=
      SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω
    rw [blockEnergyDensity_scalarCoeffField' _ haPos,
      blockEnergyDensity_scalarCoeffField' _ haPos]
    dsimp [zeroPotentialProjection]
    have hpot : 0 ≤ vecDot (X.potential x) (X.potential x) := by
      unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
    have ha : 0 ≤ SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x :=
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω x).le
    have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
    rw [hzero]
    nlinarith
  · exact inv_nonneg.mpr ENNReal.toReal_nonneg

theorem blockEnergyAverage_cutoff_nonneg {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (ω : Sample d)
    (U : Ch02.Domain d) {P : BlockVec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) P X) :
    0 ≤ blockEnergyAverage (U : Set (Vec d))
      (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) X := by
  let E := cutoffEllipticityData' M L ω U
  have hXInt := (hX.toBlockMuIntegrabilityDataOfIsEllipticFieldOn
    (a := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) E.isElliptic).energyIntegrable
  unfold blockEnergyAverage volumeAverage
  apply mul_nonneg (inv_nonneg.mpr ENNReal.toReal_nonneg)
  apply integral_nonneg_of_ae
  filter_upwards with x
  change 0 ≤ blockEnergyDensity
    (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) X x
  have haPos : ∀ y, 0 < SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω y :=
    SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω
  rw [blockEnergyDensity_scalarCoeffField' _ haPos]
  have hpot : 0 ≤ vecDot (X.potential x) (X.potential x) := by
    unfold vecDot
    exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
  have hflux : 0 ≤ vecDot (X.flux x) (X.flux x) := by
    unfold vecDot
    exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
  have ha : 0 ≤ SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x := (haPos x).le
  have hainv : 0 ≤ (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω x)⁻¹ :=
    inv_nonneg.mpr ha
  nlinarith [mul_nonneg ha hpot, mul_nonneg hainv hflux]

/-- Every cutoff variational value is nonnegative. -/
theorem cutoffMu_nonneg {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (omega : Sample d)
    (U : Ch02.Domain d) (P : BlockVec d) :
    0 ≤ Mu (U : Set (Vec d)) P
      (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega)) := by
  apply le_Mu_of_forall_isBlockMuAdmissible
  intro X hX
  exact blockEnergyAverage_cutoff_nonneg M L omega U hX

/-- Coefficient-independent zero-flux competitors compute the pure primal
cutoff variational value. -/
theorem cutoffMu_primal_countableReduction {d : ℕ} [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d)
    (p : Vec d) :
    ∃ Y : ℕ → BlockState d,
      (∀ k, IsBlockMuAdmissible (U : Set (Vec d)) (-p, 0) (Y k)) ∧
      (∀ k, zeroFluxProjection (Y k) = Y k) ∧
      ∀ ω : Sample d,
        Mu (U : Set (Vec d)) (-p, 0)
            (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) =
          ⨅ k : ℕ, blockEnergyAverage (U : Set (Vec d))
            (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) (Y k) := by
  obtain ⟨X, hX, hMu⟩ := cutoffMu_countableReduction M L U (-p, 0)
  let Y : ℕ → BlockState d := fun k => zeroFluxProjection (X k)
  refine ⟨Y, fun k => zeroFluxProjection_admissible (hX k), fun k => by rfl, ?_⟩
  intro ω
  let aω := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)
  have hRangeY : BddBelow (Set.range fun k =>
      blockEnergyAverage (U : Set (Vec d)) aω (Y k)) := by
    refine ⟨0, ?_⟩
    rintro value ⟨k, rfl⟩
    exact blockEnergyAverage_cutoff_nonneg M L ω U
      (zeroFluxProjection_admissible (hX k))
  have hValueBdd : BddBelow (muValueSet (U : Set (Vec d)) (-p, 0) aω) := by
    refine ⟨0, ?_⟩
    intro value hvalue
    rcases hvalue with ⟨Z, hZ, rfl⟩
    exact blockEnergyAverage_cutoff_nonneg M L ω U hZ
  apply le_antisymm
  · apply le_ciInf
    intro k
    exact csInf_le hValueBdd (muValueSet_mem (zeroFluxProjection_admissible (hX k)))
  · rw [hMu ω]
    apply ciInf_mono hRangeY
    intro k
    exact blockEnergyAverage_zeroFluxProjection_le M L ω U (hX k)

/-- Coefficient-independent zero-potential competitors compute the pure dual
cutoff variational value. -/
theorem cutoffMu_dual_countableReduction {d : ℕ} [NeZero d]
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ) (U : Ch02.Domain d)
    (q : Vec d) :
    ∃ Y : ℕ → BlockState d,
      (∀ k, IsBlockMuAdmissible (U : Set (Vec d)) (0, q) (Y k)) ∧
      (∀ k, zeroPotentialProjection (Y k) = Y k) ∧
      ∀ ω : Sample d,
        Mu (U : Set (Vec d)) (0, q)
            (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) =
          ⨅ k : ℕ, blockEnergyAverage (U : Set (Vec d))
            (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)) (Y k) := by
  obtain ⟨X, hX, hMu⟩ := cutoffMu_countableReduction M L U (0, q)
  let Y : ℕ → BlockState d := fun k => zeroPotentialProjection (X k)
  refine ⟨Y, fun k => zeroPotentialProjection_admissible (hX k), fun k => by rfl, ?_⟩
  intro ω
  let aω := scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω)
  have hRangeY : BddBelow (Set.range fun k =>
      blockEnergyAverage (U : Set (Vec d)) aω (Y k)) := by
    refine ⟨0, ?_⟩
    rintro value ⟨k, rfl⟩
    exact blockEnergyAverage_cutoff_nonneg M L ω U
      (zeroPotentialProjection_admissible (hX k))
  have hValueBdd : BddBelow (muValueSet (U : Set (Vec d)) (0, q) aω) := by
    refine ⟨0, ?_⟩
    intro value hvalue
    rcases hvalue with ⟨Z, hZ, rfl⟩
    exact blockEnergyAverage_cutoff_nonneg M L ω U hZ
  apply le_antisymm
  · apply le_ciInf
    intro k
    exact csInf_le hValueBdd (muValueSet_mem (zeroPotentialProjection_admissible (hX k)))
  · rw [hMu ω]
    apply ciInf_mono hRangeY
    intro k
    exact blockEnergyAverage_zeroPotentialProjection_le M L ω U (hX k)

private theorem measurable_vecDot_self {d : ℕ} {f : Vec d → Vec d}
    (hf : Measurable f) : Measurable (fun x => vecDot (f x) (f x)) := by
  unfold vecDot
  exact Finset.measurable_sum _ fun i _ =>
    ((measurable_pi_apply i).comp hf).mul ((measurable_pi_apply i).comp hf)

/-- A fixed zero-flux competitor has integrable random primal cutoff energy. -/
theorem integrable_zeroFlux_blockEnergyAverage {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (U : Ch02.Domain d) {p : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (-p, 0) X) :
    Integrable (fun omega : Sample d =>
      blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
        (zeroFluxProjection X)) M.P.toMeasure := by
  have hY := zeroFluxProjection_admissible hX
  have hPot : MemVectorL2 (U : Set (Vec d)) X.potential := by
    have hmem := hY.memBlockL2_eval
    simpa [BlockState.eval, zeroFluxProjection] using
      memVectorL2_fst_of_memBlockL2 (U := (U : Set (Vec d))) hmem
  let f : Vec d → Vec d := hPot.aestronglyMeasurable.mk X.potential
  have hfMeas : Measurable f := hPot.aestronglyMeasurable.measurable_mk
  let c : ℝ := (MeasureTheory.volume (U : Set (Vec d))).toReal⁻¹ * (1 / 2 : ℝ)
  let h : Vec d → ℝ := fun x => c * vecDot (f x) (f x)
  have hhMeas : Measurable h := measurable_const.mul (measurable_vecDot_self hfMeas)
  have hhNonneg : ∀ x, 0 ≤ h x := by
    intro x
    apply mul_nonneg
    · exact mul_nonneg (inv_nonneg.mpr ENNReal.toReal_nonneg) (by norm_num)
    · unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
  have hDotInt : Integrable (fun x => vecDot (f x) (f x))
      (volumeMeasureOn (U : Set (Vec d))) := by
    have hOrig := integrableOn_vecDot_of_memVectorL2 hPot hPot
    apply hOrig.congr
    filter_upwards [hPot.aestronglyMeasurable.ae_eq_mk] with x hx
    simp only [f]
    rw [← hx]
  have hhInt : Integrable h (volumeMeasureOn (U : Set (Vec d))) :=
    hDotInt.const_mul c
  have hWeighted := integrable_weightedCutoffIntegral M L
    (volumeMeasureOn (U : Set (Vec d))) hhMeas hhNonneg hhInt
  apply hWeighted.congr
  filter_upwards with omega
  unfold blockEnergyAverage volumeAverage weightedCutoffIntegral
  rw [← integral_const_mul]
  apply integral_congr_ae
  filter_upwards [hPot.aestronglyMeasurable.ae_eq_mk] with x hx
  rw [blockEnergyDensity_scalarCoeffField' _
    (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L omega)]
  dsimp [zeroFluxProjection, h, c, f]
  have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
  rw [hzero]
  simp only [mul_zero, add_zero]
  rw [hx]
  ring

theorem condExp_zeroFlux_blockEnergyAverage {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (U : Ch02.Domain d) {p : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (-p, 0) X) :
    M.P.toMeasure[(fun ω : Sample d =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω))
          (zeroFluxProjection X)) | potentialIndexSigma (Set.Iic n)]
      =ᵐ[M.P.toMeasure] fun ω =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω))
          (zeroFluxProjection X) := by
  have hY := zeroFluxProjection_admissible hX
  have hPot : MemVectorL2 (U : Set (Vec d)) X.potential := by
    have hmem := hY.memBlockL2_eval
    simpa [BlockState.eval, zeroFluxProjection] using
      memVectorL2_fst_of_memBlockL2 (U := (U : Set (Vec d))) hmem
  let f : Vec d → Vec d := hPot.aestronglyMeasurable.mk X.potential
  have hfMeas : Measurable f := hPot.aestronglyMeasurable.measurable_mk
  let c : ℝ := (MeasureTheory.volume (U : Set (Vec d))).toReal⁻¹ * (1 / 2 : ℝ)
  let h : Vec d → ℝ := fun x => c * vecDot (f x) (f x)
  have hhMeas : Measurable h := measurable_const.mul (measurable_vecDot_self hfMeas)
  have hhNonneg : ∀ x, 0 ≤ h x := by
    intro x
    have hf : 0 ≤ vecDot (f x) (f x) := by
      unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
    exact mul_nonneg (mul_nonneg (inv_nonneg.mpr ENNReal.toReal_nonneg) (by norm_num)) hf
  have hDotInt : Integrable (fun x => vecDot (f x) (f x))
      (volumeMeasureOn (U : Set (Vec d))) := by
    have hOrig := integrableOn_vecDot_of_memVectorL2 hPot hPot
    apply hOrig.congr
    filter_upwards [hPot.aestronglyMeasurable.ae_eq_mk] with x hx
    simp only [f]
    rw [← hx]
  have hhInt : Integrable h (volumeMeasureOn (U : Set (Vec d))) :=
    hDotInt.const_mul c
  have hEnergyEq : ∀ (L : ℕ) (ω : Sample d),
      blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω))
          (zeroFluxProjection X) =
        weightedCutoffIntegral M L (volumeMeasureOn (U : Set (Vec d))) h ω := by
    intro L ω
    unfold blockEnergyAverage volumeAverage weightedCutoffIntegral
    rw [← integral_const_mul]
    apply integral_congr_ae
    filter_upwards [hPot.aestronglyMeasurable.ae_eq_mk] with x hx
    rw [blockEnergyDensity_scalarCoeffField' _
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω)]
    dsimp [zeroFluxProjection, h, c, f]
    have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
    rw [hzero]
    simp only [mul_zero, add_zero]
    rw [hx]
    ring
  calc
    M.P.toMeasure[(fun ω : Sample d =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω))
          (zeroFluxProjection X)) | potentialIndexSigma (Set.Iic n)]
      =ᵐ[M.P.toMeasure]
        M.P.toMeasure[weightedCutoffIntegral M m
          (volumeMeasureOn (U : Set (Vec d))) h | potentialIndexSigma (Set.Iic n)] := by
      apply condExp_congr_ae
      filter_upwards with ω
      exact hEnergyEq m ω
    _ =ᵐ[M.P.toMeasure] weightedCutoffIntegral M n
        (volumeMeasureOn (U : Set (Vec d))) h :=
      condExp_weightedCutoffIntegral M hnm _ hhMeas hhNonneg hhInt
    _ =ᵐ[M.P.toMeasure] fun ω =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω))
          (zeroFluxProjection X) := by
      filter_upwards with ω
      exact (hEnergyEq n ω).symm

/-- A fixed zero-potential competitor has integrable random dual cutoff energy. -/
theorem integrable_zeroPotential_blockEnergyAverage {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) (L : ℕ)
    (U : Ch02.Domain d) {q : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (0, q) X) :
    Integrable (fun omega : Sample d =>
      blockEnergyAverage (U : Set (Vec d))
        (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L omega))
        (zeroPotentialProjection X)) M.P.toMeasure := by
  have hY := zeroPotentialProjection_admissible hX
  have hFlux : MemVectorL2 (U : Set (Vec d)) X.flux := by
    have hmem := hY.memBlockL2_eval
    simpa [BlockState.eval, zeroPotentialProjection] using
      memVectorL2_snd_of_memBlockL2 (U := (U : Set (Vec d))) hmem
  let f : Vec d → Vec d := hFlux.aestronglyMeasurable.mk X.flux
  have hfMeas : Measurable f := hFlux.aestronglyMeasurable.measurable_mk
  let c : ℝ := (MeasureTheory.volume (U : Set (Vec d))).toReal⁻¹ * (1 / 2 : ℝ)
  let h : Vec d → ℝ := fun x => c * vecDot (f x) (f x)
  have hhMeas : Measurable h := measurable_const.mul (measurable_vecDot_self hfMeas)
  have hhNonneg : ∀ x, 0 ≤ h x := by
    intro x
    apply mul_nonneg
    · exact mul_nonneg (inv_nonneg.mpr ENNReal.toReal_nonneg) (by norm_num)
    · unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
  have hDotInt : Integrable (fun x => vecDot (f x) (f x))
      (volumeMeasureOn (U : Set (Vec d))) := by
    have hOrig := integrableOn_vecDot_of_memVectorL2 hFlux hFlux
    apply hOrig.congr
    filter_upwards [hFlux.aestronglyMeasurable.ae_eq_mk] with x hx
    simp only [f]
    rw [← hx]
  have hhInt : Integrable h (volumeMeasureOn (U : Set (Vec d))) :=
    hDotInt.const_mul c
  have hWeighted := integrable_weightedInverseCutoffIntegral M L
    (volumeMeasureOn (U : Set (Vec d))) hhMeas hhNonneg hhInt
  apply hWeighted.congr
  filter_upwards with omega
  unfold blockEnergyAverage volumeAverage weightedInverseCutoffIntegral
  rw [← integral_const_mul]
  apply integral_congr_ae
  filter_upwards [hFlux.aestronglyMeasurable.ae_eq_mk] with x hx
  rw [blockEnergyDensity_scalarCoeffField' _
    (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L omega)]
  dsimp [zeroPotentialProjection, h, c, f]
  have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
  rw [hzero, mul_zero, zero_add, hx]
  ring

theorem condExp_zeroPotential_blockEnergyAverage {d : ℕ}
    (M : SubdiffusiveProcess.Frozen.Assumptions.GMCModel d) {n m : ℕ} (hnm : n < m)
    (U : Ch02.Domain d) {q : Vec d} {X : BlockState d}
    (hX : IsBlockMuAdmissible (U : Set (Vec d)) (0, q) X) :
    M.P.toMeasure[(fun ω : Sample d =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω))
          (zeroPotentialProjection X)) | potentialIndexSigma (Set.Iic n)]
      =ᵐ[M.P.toMeasure] fun ω => Real.exp
          (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ)) *
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω))
          (zeroPotentialProjection X) := by
  have hY := zeroPotentialProjection_admissible hX
  have hFlux : MemVectorL2 (U : Set (Vec d)) X.flux := by
    have hmem := hY.memBlockL2_eval
    simpa [BlockState.eval, zeroPotentialProjection] using
      memVectorL2_snd_of_memBlockL2 (U := (U : Set (Vec d))) hmem
  let f : Vec d → Vec d := hFlux.aestronglyMeasurable.mk X.flux
  have hfMeas : Measurable f := hFlux.aestronglyMeasurable.measurable_mk
  let c : ℝ := (MeasureTheory.volume (U : Set (Vec d))).toReal⁻¹ * (1 / 2 : ℝ)
  let h : Vec d → ℝ := fun x => c * vecDot (f x) (f x)
  have hhMeas : Measurable h := measurable_const.mul (measurable_vecDot_self hfMeas)
  have hhNonneg : ∀ x, 0 ≤ h x := by
    intro x
    have hf : 0 ≤ vecDot (f x) (f x) := by
      unfold vecDot
      exact Finset.sum_nonneg fun i _ => mul_self_nonneg _
    exact mul_nonneg (mul_nonneg (inv_nonneg.mpr ENNReal.toReal_nonneg) (by norm_num)) hf
  have hDotInt : Integrable (fun x => vecDot (f x) (f x))
      (volumeMeasureOn (U : Set (Vec d))) := by
    have hOrig := integrableOn_vecDot_of_memVectorL2 hFlux hFlux
    apply hOrig.congr
    filter_upwards [hFlux.aestronglyMeasurable.ae_eq_mk] with x hx
    simp only [f]
    rw [← hx]
  have hhInt : Integrable h (volumeMeasureOn (U : Set (Vec d))) :=
    hDotInt.const_mul c
  have hEnergyEq : ∀ (L : ℕ) (ω : Sample d),
      blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M L ω))
          (zeroPotentialProjection X) =
        weightedInverseCutoffIntegral M L (volumeMeasureOn (U : Set (Vec d))) h ω := by
    intro L ω
    unfold blockEnergyAverage volumeAverage weightedInverseCutoffIntegral
    rw [← integral_const_mul]
    apply integral_congr_ae
    filter_upwards [hFlux.aestronglyMeasurable.ae_eq_mk] with x hx
    rw [blockEnergyDensity_scalarCoeffField' _
      (SubdiffusiveProcess.Frozen.Assumptions.aCutoff_pos M L ω)]
    dsimp [zeroPotentialProjection, h, c, f]
    have hzero : vecDot (0 : Vec d) 0 = 0 := by simp [vecDot]
    rw [hzero, mul_zero, zero_add]
    rw [hx]
    ring
  let C := Real.exp
    (2 * SubdiffusiveProcess.Frozen.Assumptions.tauSq M.P * ((m - n : ℕ) : ℝ))
  calc
    M.P.toMeasure[(fun ω : Sample d =>
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M m ω))
          (zeroPotentialProjection X)) | potentialIndexSigma (Set.Iic n)]
      =ᵐ[M.P.toMeasure]
        M.P.toMeasure[weightedInverseCutoffIntegral M m
          (volumeMeasureOn (U : Set (Vec d))) h | potentialIndexSigma (Set.Iic n)] := by
      apply condExp_congr_ae
      filter_upwards with ω
      exact hEnergyEq m ω
    _ =ᵐ[M.P.toMeasure] fun ω => C * weightedInverseCutoffIntegral M n
        (volumeMeasureOn (U : Set (Vec d))) h ω := by
      simpa only [C] using
        condExp_weightedInverseCutoffIntegral M hnm _ hhMeas hhNonneg hhInt
    _ =ᵐ[M.P.toMeasure] fun ω => C *
        blockEnergyAverage (U : Set (Vec d))
          (scalarCoeffField (SubdiffusiveProcess.Frozen.Assumptions.aCutoff M n ω))
          (zeroPotentialProjection X) := by
      filter_upwards with ω
      rw [hEnergyEq n ω]

end

end SubdiffusiveProcess.CoarseGrainingVocab
