module

public import SubdiffusiveProcess.CoarseGrainingVocab.MeasurabilityProviders
public import SubdiffusiveProcess.CoarseGrainingVocab.NegativeBesovSupport
public import SubdiffusiveProcess.CoarseGrainingVocab.ShellSensitivity
public import Mathlib.Probability.Independence.Integration

@[expose] public section




namespace SubdiffusiveProcess.CoarseGrainingVocab

open MeasureTheory ProbabilityTheory Homogenization Homogenization.Book
open scoped ENNReal

noncomputable section

variable {d : ℕ}

private abbrev PSample (d : ℕ) :=
  _root_.SubdiffusiveProcess.Model.PotentialSample d

/-- A deterministic filler for coordinates discarded by a shell projection. -/
def zeroPotentialField (d : ℕ) :
    _root_.SubdiffusiveProcess.Model.PotentialField d := by
  refine ⟨(0, 0), ?_, ?_⟩
  · intro x
    simpa using! (hasFDerivAt_const (x := x) (c := (0 : ℝ)))
  · intro K _hK
    exact ⟨0, by simp [LipschitzOnWith]⟩

/-! ## Coordinate-block projections -/

/-- Keep exactly the shell coordinates in `I`, replacing all others by zero. -/
noncomputable def potentialShellProjection (I : Set ℕ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : _root_.SubdiffusiveProcess.Model.PotentialSample d := by
  classical
  exact fun k => if k ∈ I then omega k else zeroPotentialField d

/-- The coordinate-block projection is measurable from the sigma-field
generated by the retained coordinates to the ambient sample Borel space. -/
theorem measurable_potentialShellProjection (I : Set ℕ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) (_root_.SubdiffusiveProcess.Model.PotentialSample d) (potentialShellIndexSigma I) inferInstance
      (potentialShellProjection I) := by
  classical
  let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) := potentialShellIndexSigma I
  apply Measurable.of_eval
  intro k
  by_cases hk : k ∈ I
  · simpa [potentialShellProjection, hk] using
      (measurable_potentialCoordinate_shellIndexSigma (d := d) hk)
  · simp [potentialShellProjection, hk]

/-- A cutoff at level `n` is unchanged when shells strictly above `n` are
discarded. -/
theorem aCutoff_potentialShellProjection_Iic
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
    (x : Vec d) :
    _root_.SubdiffusiveProcess.Model.aCutoff M n
        (potentialShellProjection (Set.Iic n) omega) x =
      _root_.SubdiffusiveProcess.Model.aCutoff M n omega x := by
  classical
  unfold _root_.SubdiffusiveProcess.Model.aCutoff potentialShellProjection
  apply congrArg Real.exp
  apply Finset.sum_congr rfl
  intro k hk
  have hkn : k ≤ n := by
    simpa only [Finset.mem_range, Nat.lt_succ_iff] using hk
  simp only [ite_eq_left (show k ∈ Set.Iic n from hkn)]

/-! ## Prefix-measurable response probes -/

/-- Every fixed cutoff response probe reads only the first `n+1` shells.  The
variational observable itself is handled by `measurable_cutoff_responseJ`; the
present proof only supplies the prefix projection and certificate-irrelevance
rewrite. -/
theorem measurable_cutoff_responseJ_potentialShellIndexSigma_Iic [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (p q : Vec d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (fun omega => J U (aCutoffCoeffOnData M n omega U).toCoeffOn p q) := by
  have hcomp := (measurable_cutoff_responseJ M n U p q).comp
    (measurable_potentialShellProjection (d := d) (Set.Iic n))
  have heq :
      (fun omega : _root_.SubdiffusiveProcess.Model.PotentialSample d =>
        J U (aCutoffCoeffOnData M n
          (potentialShellProjection (Set.Iic n) omega) U).toCoeffOn p q) =
      fun omega => J U (aCutoffCoeffOnData M n omega U).toCoeffOn p q := by
    funext omega
    apply Ch02.responseJ_eq_ofAEEq
    filter_upwards with x
    change Homogenization.scalarMatrix
        (_root_.SubdiffusiveProcess.Model.aCutoff M n
          (potentialShellProjection (Set.Iic n) omega) x) =
      Homogenization.scalarMatrix
        (_root_.SubdiffusiveProcess.Model.aCutoff M n omega x)
    rw [aCutoff_potentialShellProjection_Iic]
  change @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma (Set.Iic n))
    inferInstance
    (fun omega => J U (aCutoffCoeffOnData M n
      (potentialShellProjection (Set.Iic n) omega) U).toCoeffOn p q) at hcomp
  rwa [heq] at hcomp

/-- The cutoff dual inverse coarse matrix, kept as a named finite-dimensional
carrier for normalized response probes. -/
noncomputable def randomSigmaStarInvMatrix
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : Mat d :=
  Ch02.sigmaStarInvCoarse U (aCutoffCoeffOnData M n omega U).toCoeffOn

/-- The dual inverse coarse matrix also reads only the prefix.  Its entries
are recovered from the pure-flux response probes by polarization. -/
theorem measurable_randomSigmaStarInvMatrix_potentialShellIndexSigma_Iic
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) (Mat d)
      (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (randomSigmaStarInvMatrix M n U) := by
  by_cases hd : d = 0
  · subst d
    let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample 0) :=
      potentialShellIndexSigma (d := 0) (Set.Iic n)
    apply Measurable.of_eval
    intro i
    exact Fin.elim0 i
  let : NeZero d := ⟨hd⟩
  let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) :=
    potentialShellIndexSigma (d := d) (Set.Iic n)
  apply Measurable.of_eval
  intro i
  apply Measurable.of_eval
  intro j
  by_cases hij : i = j
  · subst j
    have hprobe := measurable_cutoff_responseJ_potentialShellIndexSigma_Iic
      M n U 0 (Pi.single i 1)
    have hEq :
        (fun omega : _root_.SubdiffusiveProcess.Model.PotentialSample d => randomSigmaStarInvMatrix M n U omega i i) =
        fun omega => 2 * J U (aCutoffCoeffOnData M n omega U).toCoeffOn
          0 (Pi.single i 1) := by
      funext omega
      let B := randomSigmaStarInvMatrix M n U omega
      have hJ := Ch02.responseJ_zero_q_eq_sigmaStarInvCoarse U
        (aCutoffCoeffOnData M n omega U).toCoeffOn (Pi.single i 1)
      have hJ' : J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
          (Pi.single i 1) = (1 / 2 : ℝ) *
            vecDot (Pi.single i 1)
              (matVecMul B (Pi.single i 1)) := hJ
      change B i i = 2 * J U _ 0 (Pi.single i 1)
      rw [hJ']
      rw [vecDot_single_left, matVecMul_single]
      ring
    rw [hEq]
    exact measurable_const.mul hprobe
  · have hprobeSum :=
      measurable_cutoff_responseJ_potentialShellIndexSigma_Iic M n U 0
        (Pi.single i 1 + Pi.single j 1)
    have hprobeI :=
      measurable_cutoff_responseJ_potentialShellIndexSigma_Iic M n U 0
        (Pi.single i 1)
    have hprobeJ :=
      measurable_cutoff_responseJ_potentialShellIndexSigma_Iic M n U 0
        (Pi.single j 1)
    have hEq :
        (fun omega : _root_.SubdiffusiveProcess.Model.PotentialSample d => randomSigmaStarInvMatrix M n U omega i j) =
        fun omega =>
          J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
              (Pi.single i 1 + Pi.single j 1) -
            J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0 (Pi.single i 1) -
            J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
              (Pi.single j 1) := by
      funext omega
      let B := randomSigmaStarInvMatrix M n U omega
      have hsymm : B.IsSymm :=
        Ch02.sigmaStarInvCoarse_isSymm U
          (aCutoffCoeffOnData M n omega U).toCoeffOn
      have hsum := Ch02.responseJ_zero_q_eq_sigmaStarInvCoarse U
        (aCutoffCoeffOnData M n omega U).toCoeffOn
          (Pi.single i 1 + Pi.single j 1)
      have hi := Ch02.responseJ_zero_q_eq_sigmaStarInvCoarse U
        (aCutoffCoeffOnData M n omega U).toCoeffOn (Pi.single i 1)
      have hj := Ch02.responseJ_zero_q_eq_sigmaStarInvCoarse U
        (aCutoffCoeffOnData M n omega U).toCoeffOn (Pi.single j 1)
      have hsum' : J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
          (Pi.single i 1 + Pi.single j 1) = (1 / 2 : ℝ) *
            vecDot (Pi.single i 1 + Pi.single j 1)
              (matVecMul B (Pi.single i 1 + Pi.single j 1)) := hsum
      have hi' : J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
          (Pi.single i 1) = (1 / 2 : ℝ) *
            vecDot (Pi.single i 1) (matVecMul B (Pi.single i 1)) := hi
      have hj' : J U (aCutoffCoeffOnData M n omega U).toCoeffOn 0
          (Pi.single j 1) = (1 / 2 : ℝ) *
            vecDot (Pi.single j 1) (matVecMul B (Pi.single j 1)) := hj
      rw [hsum', hi', hj']
      change B i j =
        (1 / 2 : ℝ) * vecDot (Pi.single i 1 + Pi.single j 1)
            (matVecMul B (Pi.single i 1 + Pi.single j 1)) -
          (1 / 2 : ℝ) * vecDot (Pi.single i 1)
            (matVecMul B (Pi.single i 1)) -
          (1 / 2 : ℝ) * vecDot (Pi.single j 1)
            (matVecMul B (Pi.single j 1))
      rw [basis_sum_pairing, vecDot_single_left, matVecMul_single,
        vecDot_single_left, matVecMul_single]
      rw [Matrix.IsSymm.apply hsymm j i]
      ring
    rw [hEq]
    exact (hprobeSum.sub hprobeI).sub hprobeJ

/-- The primal cutoff coarse matrix reads only the prefix.  This is the
prefix-comap specialization of the ambient P-01 theorem. -/
theorem measurable_randomAMatrix_potentialShellIndexSigma_Iic
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) (Mat d)
      (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (randomAMatrix M n U) := by
  have hcomp := (measurable_randomAMatrix M n U).comp
    (measurable_potentialShellProjection (d := d) (Set.Iic n))
  have heq :
      (fun omega : _root_.SubdiffusiveProcess.Model.PotentialSample d =>
        randomAMatrix M n U (potentialShellProjection (Set.Iic n) omega)) =
      randomAMatrix M n U := by
    funext omega
    apply Ch02.aCoarse_eq_ofAEEq
    filter_upwards with x
    change Homogenization.scalarMatrix
        (_root_.SubdiffusiveProcess.Model.aCutoff M n
          (potentialShellProjection (Set.Iic n) omega) x) =
      Homogenization.scalarMatrix
        (_root_.SubdiffusiveProcess.Model.aCutoff M n omega x)
    rw [aCutoff_potentialShellProjection_Iic]
  change @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) (Mat d)
    (potentialShellIndexSigma (Set.Iic n)) inferInstance
    (fun omega => randomAMatrix M n U
      (potentialShellProjection (Set.Iic n) omega)) at hcomp
  rwa [heq] at hcomp

/-- Finite-dimensional matrix whose quadratic form is the normalized scalar
response probe appearing in `normalizedDefect`. -/
noncomputable def normalizedDefectMatrix
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : Mat d :=
  let c := Real.sqrt (ahom M n)
  ((1 / 2 : ℝ) * (c⁻¹) ^ 2) • randomAMatrix M n U omega +
    ((1 / 2 : ℝ) * c ^ 2) • randomSigmaStarInvMatrix M n U omega -
      (c⁻¹ * c) • (1 : Mat d)

/-- The normalized response matrix is prefix-measurable. -/
theorem measurable_normalizedDefectMatrix_potentialShellIndexSigma_Iic
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) (Mat d)
      (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (normalizedDefectMatrix M n U) := by
  let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) :=
    potentialShellIndexSigma (d := d) (Set.Iic n)
  apply Measurable.of_eval
  intro i
  apply Measurable.of_eval
  intro j
  simp only [normalizedDefectMatrix, Matrix.add_apply, Matrix.sub_apply]
  exact ((measurable_const.mul
      ((measurable_pi_apply j).comp ((measurable_pi_apply i).comp
        (measurable_randomAMatrix_potentialShellIndexSigma_Iic M n U)))).add
    (measurable_const.mul
      ((measurable_pi_apply j).comp ((measurable_pi_apply i).comp
        (measurable_randomSigmaStarInvMatrix_potentialShellIndexSigma_Iic
          M n U))))).sub measurable_const

/-- Identification of every normalized response probe with the quadratic form
of `normalizedDefectMatrix`. -/
theorem normalizedDefectMatrix_quadratic [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) (e : Vec d) :
    J U (aCutoffCoeffOnData M n omega U).toCoeffOn
        ((Real.sqrt (ahom M n))⁻¹ • e) (Real.sqrt (ahom M n) • e) =
      vecDot e (matVecMul (normalizedDefectMatrix M n U omega) e) := by
  let c := Real.sqrt (ahom M n)
  let hdata := aCutoffCoeffOnData M n omega U
  let a := hdata.toCoeffOn
  have hTheory := Ch02.responseSymmetricDirichletNeumannTheory U a hdata.isSymmetric
  have hsplit := hTheory.response_dirichlet_neumann_split (c⁻¹ • e) (c • e)
  rw [hTheory.dirichlet_value_by_sigma, hTheory.neumann_value_by_sigmaStarInv]
    at hsplit
  have hsplit' : J U a (c⁻¹ • e) (c • e) =
      (1 / 2 : ℝ) * vecDot (c⁻¹ • e)
          (matVecMul (Ch02.sigmaCoarse U a) (c⁻¹ • e)) +
        (1 / 2 : ℝ) * vecDot (c • e)
          (matVecMul (Ch02.sigmaStarInvCoarse U a) (c • e)) -
        vecDot (c⁻¹ • e) (c • e) := hsplit
  change J U a (c⁻¹ • e) (c • e) = _
  rw [hsplit']
  change _ = vecDot e
    (matVecMul
      (((1 / 2 : ℝ) * (c⁻¹) ^ 2) • Ch02.aCoarse U a +
        ((1 / 2 : ℝ) * c ^ 2) • Ch02.sigmaStarInvCoarse U a -
          (c⁻¹ * c) • (1 : Mat d)) e)
  rw [hTheory.derived_matrices.1]
  have vecDot_sub (x y z : Vec d) :
      vecDot x (y - z) = vecDot x y - vecDot x z := by
    simp [vecDot, Finset.sum_sub_distrib, mul_sub]
  simp only [add_matVecMul, sub_matVecMul, smul_matVecMul,
    vecDot_add_right, vecDot_sub, vecDot_smul_right,
    matVecMul_smul, vecDot_smul_left]
  have hone : matVecMul (1 : Mat d) e = e := Matrix.one_mulVec e
  rw [hone]
  ring

/-- The normalized response matrix is positive semidefinite. -/
theorem normalizedDefectMatrix_posSemidef [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) :
    (normalizedDefectMatrix M n U omega).PosSemidef := by
  apply Matrix.PosSemidef.of_dotProduct_mulVec_nonneg
  · have hA : (randomAMatrix M n U omega).IsSymm := by
      let hdata := aCutoffCoeffOnData M n omega U
      have hTheory := Ch02.responseSymmetricDirichletNeumannTheory U
        hdata.toCoeffOn hdata.isSymmetric
      change (Ch02.aCoarse U hdata.toCoeffOn).IsSymm
      rw [hTheory.derived_matrices.1]
      exact Ch02.sigmaCoarse_isSymm U hdata.toCoeffOn
    have hB : (randomSigmaStarInvMatrix M n U omega).IsSymm :=
      Ch02.sigmaStarInvCoarse_isSymm U
        (aCutoffCoeffOnData M n omega U).toCoeffOn
    let c := Real.sqrt (ahom M n)
    have hsymm := ((hA.smul ((1 / 2 : ℝ) * (c⁻¹) ^ 2)).add
      (hB.smul ((1 / 2 : ℝ) * c ^ 2))).sub
        (Matrix.isSymm_one.smul (c⁻¹ * c))
    simpa [Matrix.IsHermitian, Matrix.IsSymm, normalizedDefectMatrix, c] using hsymm
  · intro e
    simpa [dotProduct, Matrix.mulVec, vecDot, matVecMul] using
      (show 0 ≤ J U (aCutoffCoeffOnData M n omega U).toCoeffOn
          ((Real.sqrt (ahom M n))⁻¹ • e) (Real.sqrt (ahom M n) • e) from
        Ch02.responseJ_nonneg U _ _ _).trans_eq
          (normalizedDefectMatrix_quadratic M n U omega e)

/-- A positive-semidefinite quadratic response has literal unit-sphere
`ENNReal` supremum equal to its matrix operator norm.  This is the public
scalar-probe specialization of the compact/CFC maximum route used internally
by `SharpCompareJ`. -/
theorem paperScalarProbeMaxOn_eq_ofReal_matrixOperatorNorm [NeZero d]
    (U : Ch02.Domain d) (a : Ch02.CoeffOn U) (alpha : ℝ) (R : Mat d)
    (hR : R.PosSemidef)
    (hquad : ∀ e : Vec d,
      J U a ((Real.sqrt alpha)⁻¹ • e) (Real.sqrt alpha • e) =
        vecDot e (matVecMul R e)) :
    paperScalarProbeMaxOn U a alpha =
      ENNReal.ofReal (Ch02.matrixOperatorNorm R) := by
  let C := paperScalarProbeMaxOn U a alpha
  have hupper : C ≤ ENNReal.ofReal (Ch02.matrixOperatorNorm R) := by
    unfold C paperScalarProbeMaxOn
    refine iSup_le fun e => ?_
    rw [hquad e]
    exact ENNReal.ofReal_le_ofReal (by
      have h :=
        Ch02.vecDot_matVecMul_le_matrixOperatorNorm_mul_vecNormSq_of_posSemidef
          hR e
      simpa [e.2] using h)
  have hCtop : C ≠ ∞ :=
    ne_top_of_le_ne_top ENNReal.ofReal_ne_top hupper
  have hCnonneg : 0 ≤ C.toReal := ENNReal.toReal_nonneg
  have hB : (C.toReal • (1 : Mat d)).PosSemidef :=
    Matrix.PosSemidef.one.smul hCnonneg
  have hLoewner : MatLoewnerLE R (C.toReal • (1 : Mat d)) := by
    intro x
    by_cases hx : x = 0
    · subst x
      simp [vecDot, matVecMul]
    · have hxnorm : 0 < vecNormSq x := by
        exact lt_of_le_of_ne (vecNormSq_nonneg x)
          (by simpa [vecNormSq_eq_zero_iff, eq_comm] using hx)
      let t := Real.sqrt (vecNormSq x)
      let e : Vec d := t⁻¹ • x
      have ht : 0 < t := Real.sqrt_pos.2 hxnorm
      have htsq : t ^ 2 = vecNormSq x := Real.sq_sqrt hxnorm.le
      have he : vecNormSq e = 1 := by
        dsimp [e]
        rw [vecNormSq_smul]
        field_simp [ht.ne']
        nlinarith
      have hunitENN :
          ENNReal.ofReal (J U a ((Real.sqrt alpha)⁻¹ • e)
            (Real.sqrt alpha • e)) ≤ C := by
        unfold C paperScalarProbeMaxOn
        exact le_iSup (fun z : {z : Vec d // vecNormSq z = 1} =>
          ENNReal.ofReal (J U a ((Real.sqrt alpha)⁻¹ • z)
            (Real.sqrt alpha • z))) ⟨e, he⟩
      have hunit : vecDot e (matVecMul R e) ≤ C.toReal := by
        rw [← hquad e]
        exact (ENNReal.ofReal_le_iff_le_toReal hCtop).mp hunitENN
      have hte : t • e = x := by
        ext i
        simp [e, ht.ne']
      have hscale :
          vecDot x (matVecMul R x) =
            t ^ 2 * vecDot e (matVecMul R e) := by
        conv_lhs => rw [← hte]
        rw [matVecMul_smul, vecDot_smul_left, vecDot_smul_right]
        ring
      have hqx : vecDot x (matVecMul R x) ≤ C.toReal * vecNormSq x := by
        rw [hscale, ← htsq]
        calc
          t ^ 2 * vecDot e (matVecMul R e) ≤ t ^ 2 * C.toReal :=
            mul_le_mul_of_nonneg_left hunit (sq_nonneg t)
          _ = C.toReal * t ^ 2 := by ring
      rw [smul_matVecMul, vecDot_smul_right]
      have hone : matVecMul (1 : Mat d) x = x := Matrix.one_mulVec x
      rw [hone]
      exact mul_le_mul_of_nonneg_left hqx (by norm_num)
  have hop := Ch02.matrixOperatorNorm_le_of_matLoewnerLE_of_posSemidef
    hR hB hLoewner
  have hnorm : Ch02.matrixOperatorNorm R ≤ C.toReal := by
    simpa [Ch02.matrixOperatorNorm_smul_one_eq_of_nonneg hCnonneg] using hop
  have hlower : ENNReal.ofReal (Ch02.matrixOperatorNorm R) ≤ C := by
    calc
      ENNReal.ofReal (Ch02.matrixOperatorNorm R) ≤
          ENNReal.ofReal C.toReal := ENNReal.ofReal_le_ofReal hnorm
      _ = C := ENNReal.ofReal_toReal hCtop
  exact le_antisymm hupper hlower

/-- Unit directions used for the countable measurable version of the literal
probe supremum. -/


abbrev ScalarProbeUnitSphere (d : ℕ) :=
  {e : Vec d // vecNormSq e = 1}

instance [NeZero d] : Nonempty (ScalarProbeUnitSphere d) := by
  let e : Vec d := Pi.single default 1
  refine ⟨⟨e, ?_⟩⟩
  simp only [e, vecNormSq, vecDot]
  rw [Finset.sum_eq_single default]
  · simp
  · intro i _ hi
    have hi0 : i ≠ (0 : Fin d) := by simpa using hi
    simp [hi0]
  · simp

/-- Countable dense-probe representative of the normalized defect. -/
noncomputable def normalizedDefectCountableRepresentative [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : ℝ≥0∞ :=
  ⨆ i : ℕ, ENNReal.ofReal
    (J U (aCutoffCoeffOnData M n omega U).toCoeffOn
      ((Real.sqrt (ahom M n))⁻¹ •
        (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))
      (Real.sqrt (ahom M n) •
        (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d)))

theorem measurable_normalizedDefectCountableRepresentative [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ≥0∞
      (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (normalizedDefectCountableRepresentative M n U) := by
  unfold normalizedDefectCountableRepresentative
  exact Measurable.iSup fun i =>
    (measurable_cutoff_responseJ_potentialShellIndexSigma_Iic M n U
      ((Real.sqrt (ahom M n))⁻¹ •
        (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))
      (Real.sqrt (ahom M n) •
        (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))).ennreal_ofReal

/-- Density of the selected countable probes loses no directions. -/
theorem normalizedDefect_eq_countableRepresentative [NeZero d]
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) :
    normalizedDefect M n U omega =
      normalizedDefectCountableRepresentative M n U omega := by
  let a := (aCutoffCoeffOnData M n omega U).toCoeffOn
  let alpha := ahom M n
  let R := normalizedDefectMatrix M n U omega
  let T := normalizedDefectCountableRepresentative M n U omega
  have hR : R.PosSemidef := normalizedDefectMatrix_posSemidef M n U omega
  have hquad : ∀ e : Vec d,
      J U a ((Real.sqrt alpha)⁻¹ • e) (Real.sqrt alpha • e) =
        vecDot e (matVecMul R e) :=
    normalizedDefectMatrix_quadratic M n U omega
  have hTle : T ≤ paperScalarProbeMaxOn U a alpha := by
    unfold T normalizedDefectCountableRepresentative paperScalarProbeMaxOn
    refine iSup_le fun i => ?_
    exact le_iSup (fun e : ScalarProbeUnitSphere d =>
      ENNReal.ofReal (J U a ((Real.sqrt alpha)⁻¹ • e)
        (Real.sqrt alpha • e)))
      (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i)
  have hpaper := paperScalarProbeMaxOn_eq_ofReal_matrixOperatorNorm
    U a alpha R hR hquad
  have hTtop : T ≠ ∞ := by
    rw [hpaper] at hTle
    exact ne_top_of_le_ne_top ENNReal.ofReal_ne_top hTle
  have hf : Continuous (fun e : ScalarProbeUnitSphere d =>
      J U a ((Real.sqrt alpha)⁻¹ • (e : Vec d))
        (Real.sqrt alpha • (e : Vec d))) := by
    have heq : (fun e : ScalarProbeUnitSphere d =>
        J U a ((Real.sqrt alpha)⁻¹ • (e : Vec d))
          (Real.sqrt alpha • (e : Vec d))) =
      fun e : ScalarProbeUnitSphere d =>
        vecDot (e : Vec d) (matVecMul R (e : Vec d)) := by
      funext e
      exact hquad e
    rw [heq]
    unfold vecDot matVecMul
    apply continuous_finsetSum Finset.univ
    intro i _hi
    apply Continuous.mul
    · exact (continuous_apply i).comp continuous_subtype_val
    · apply continuous_finsetSum Finset.univ
      intro j _hj
      exact continuous_const.mul
        ((continuous_apply j).comp continuous_subtype_val)
  have hfull : paperScalarProbeMaxOn U a alpha ≤ T := by
    unfold paperScalarProbeMaxOn
    refine iSup_le fun e => ?_
    apply (ENNReal.ofReal_le_iff_le_toReal hTtop).2
    by_contra hnot
    push Not at hnot
    let eps :=
      J U a ((Real.sqrt alpha)⁻¹ • (e : Vec d))
        (Real.sqrt alpha • (e : Vec d)) - T.toReal
    have heps : 0 < eps := by dsimp [eps]; linarith
    obtain ⟨delta, hdelta, hball⟩ :=
      Metric.continuousAt_iff.1 hf.continuousAt eps heps
    obtain ⟨i, hi⟩ :=
      (TopologicalSpace.denseRange_denseSeq
        (ScalarProbeUnitSphere d)).exists_dist_lt e hdelta
    have hclose := hball (show dist
        (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i) e < delta by
      rwa [dist_comm])
    rw [Real.dist_eq] at hclose
    have hiENN : ENNReal.ofReal
        (J U a ((Real.sqrt alpha)⁻¹ •
          (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))
          (Real.sqrt alpha •
            (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) i : Vec d))) ≤ T := by
      unfold T normalizedDefectCountableRepresentative
      exact le_iSup (fun j : ℕ => ENNReal.ofReal
        (J U (aCutoffCoeffOnData M n omega U).toCoeffOn
          ((Real.sqrt (ahom M n))⁻¹ •
            (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) j : Vec d))
          (Real.sqrt (ahom M n) •
            (TopologicalSpace.denseSeq (ScalarProbeUnitSphere d) j : Vec d)))) i
    have hiReal := (ENNReal.ofReal_le_iff_le_toReal hTtop).mp hiENN
    dsimp [eps] at hclose
    have habs := (abs_lt.mp hclose).1
    linarith
  unfold normalizedDefect
  exact le_antisymm hfull hTle

/-- The literal normalized defect is measurable for the sigma-field generated
by the first `n+1` shells. -/
theorem measurable_normalizedDefect_potentialShellIndexSigma_Iic
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (U : Ch02.Domain d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ≥0∞
      (potentialShellIndexSigma (Set.Iic n)) inferInstance
      (normalizedDefect M n U) := by
  by_cases hd : d = 0
  · subst d
    have heq : normalizedDefect M n U = fun _ => 0 := by
      funext omega
      unfold normalizedDefect paperScalarProbeMaxOn
      apply le_antisymm
      · refine iSup_le fun e => ?_
        have hfalse : False := by
          have he := e.2
          simp [vecNormSq, vecDot] at he
        exact hfalse.elim
      · exact bot_le
    rw [heq]
    exact measurable_const
  let : NeZero d := ⟨hd⟩
  have hrep := measurable_normalizedDefectCountableRepresentative M n U
  have heq : normalizedDefect M n U =
      normalizedDefectCountableRepresentative M n U := by
    funext omega
    exact normalizedDefect_eq_countableRepresentative M n U omega
  rw [heq]
  exact hrep

/-! ## Suffix-measurable shell representatives -/

/-- A translated own-scale shell gauge is measurable for every shell-index
sigma-field containing its one coordinate. -/
theorem measurable_translatedShellG2_potentialShellIndexSigma
    {I : Set ℕ} {j : ℕ} (hj : j ∈ I) (z : Vec d) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma I) inferInstance
      (translatedShellG2 (d := d) j z) :=
  _root_.SubdiffusiveProcess.Model.PotentialField.g2Observable_measurable.comp
    ((_root_.SubdiffusiveProcess.Model.PotentialField.measurable_translate z).comp
      ((measurable_unscalePotential j).comp
        (measurable_potentialCoordinate_shellIndexSigma hj)))

/-- The finite spatial-cover maximum of one shell remains measurable for the
same one-coordinate sigma-field. -/
theorem measurable_largeCubeShellG2_potentialShellIndexSigma
    {I : Set ℕ} {j : ℕ} (hj : j ∈ I) (r : ℤ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma I) inferInstance
      (largeCubeShellG2 (d := d) j r) := by
  let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) := potentialShellIndexSigma I
  let Y : _root_.SubdiffusiveProcess.Model.PotentialSample d → ℝ :=
    (shellCoverShifts d r).sup' (shellCoverShifts_nonempty d r) fun p =>
      translatedShellG2 j (shellCoverCenter p)
  have hY : @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma I)
      inferInstance Y :=
    Finset.measurable_sup' (shellCoverShifts_nonempty d r)
      (fun p _ => measurable_translatedShellG2_potentialShellIndexSigma
        hj (shellCoverCenter p))
  have heq : Y = largeCubeShellG2 j r := by
    funext omega
    exact Finset.sup'_apply (shellCoverShifts_nonempty d r)
      (fun p => translatedShellG2 j (shellCoverCenter p)) omega
  rwa [← heq]

/-- Each field-sensitivity layer is measurable for the strict suffix above
the cutoff. -/
theorem measurable_sensitivityLayer_potentialShellIndexSigma_Ioi
    (n : ℕ) (k : ℤ) (i : ℕ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma (Set.Ioi n))
      inferInstance (sensitivityLayer (d := d) n k i) := by
  have hj : sensitivityShellIndex n i ∈ Set.Ioi n := by
    simp only [Set.mem_Ioi, sensitivityShellIndex]
    omega
  unfold sensitivityLayer shellOscillationEnvelope
  by_cases h : k ≤ (sensitivityShellIndex n i : ℤ)
  · simpa only [h, ite_true] using! measurable_const.mul
      (measurable_translatedShellG2_potentialShellIndexSigma
        (d := d) hj 0)
  · simpa only [h, ite_false] using! measurable_const.mul
      (measurable_largeCubeShellG2_potentialShellIndexSigma
        (d := d) hj (k - (sensitivityShellIndex n i : ℤ)))

/-- Everywhere-measurable nonnegative representative of the suffix field
oscillation stream.  Unlike the real `tsum`, this `ENNReal` sum has no
non-summable junk branch. -/
noncomputable def suffixSensitivityRepresentative (n : ℕ) (k : ℤ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : ℝ≥0∞ :=
  ∑' i, ENNReal.ofReal (sensitivityLayer n k i omega)

/-- The selected representative reads only shells strictly above `n`. -/
theorem measurable_suffixSensitivityRepresentative (n : ℕ) (k : ℤ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ≥0∞ (potentialShellIndexSigma (Set.Ioi n))
      inferInstance (suffixSensitivityRepresentative (d := d) n k) := by
  unfold suffixSensitivityRepresentative
  let : MeasurableSpace (_root_.SubdiffusiveProcess.Model.PotentialSample d) :=
    potentialShellIndexSigma (Set.Ioi n)
  exact Measurable.tsum fun i =>
    (measurable_sensitivityLayer_potentialShellIndexSigma_Ioi
      (d := d) n k i).ennreal_ofReal

/-- On the pointwise summability event, the suffix representative is exactly
the `ENNReal` coercion of the previously established real field representative. -/
theorem suffixSensitivityRepresentative_eq_ofReal_sensitivityFieldRepresentative
    (n : ℕ) (k : ℤ) (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d)
    (hs : Summable fun i => sensitivityLayer n k i omega) :
    suffixSensitivityRepresentative n k omega =
      ENNReal.ofReal (sensitivityFieldRepresentative n k omega) := by
  unfold suffixSensitivityRepresentative sensitivityFieldRepresentative
  rw [ENNReal.ofReal_tsum_of_nonneg]
  · exact fun i => shellOscillationEnvelope_nonneg _ _ _
  · exact hs

/-- Everywhere-measurable real version of the suffix representative. -/
noncomputable def suffixSensitivityRealRepresentative (n : ℕ) (k : ℤ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : ℝ :=
  (suffixSensitivityRepresentative n k omega).toReal

theorem measurable_suffixSensitivityRealRepresentative (n : ℕ) (k : ℤ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma (Set.Ioi n))
      inferInstance (suffixSensitivityRealRepresentative (d := d) n k) :=
  (measurable_suffixSensitivityRepresentative (d := d) n k).ennreal_toReal

/-- The everywhere-measurable real representative agrees almost surely with
the `sensitivityFieldRepresentative` carrying the established Gamma-two bound. -/
theorem ae_suffixSensitivityRealRepresentative_eq_sensitivityFieldRepresentative
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (k : ℤ) :
    suffixSensitivityRealRepresentative n k =ᵐ[M.P.toMeasure]
      sensitivityFieldRepresentative n k := by
  filter_upwards [ae_summable_sensitivityLayer M n k] with omega hs
  unfold suffixSensitivityRealRepresentative
  rw [suffixSensitivityRepresentative_eq_ofReal_sensitivityFieldRepresentative
    n k omega hs, ENNReal.toReal_ofReal]
  exact sensitivityFieldRepresentative_nonneg n k omega

/-- Measurable suffix-only cutoff-change majorant used as the selected
`X_(m,k)` representative in the response localization moment split. -/
noncomputable def cutoffChangeSuffixRepresentative (n : ℕ) (k : ℤ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) : ℝ :=
  Real.exp (suffixSensitivityRealRepresentative n k omega) - 1

theorem measurable_cutoffChangeSuffixRepresentative (n : ℕ) (k : ℤ) :
    @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ (potentialShellIndexSigma (Set.Ioi n))
      inferInstance (cutoffChangeSuffixRepresentative (d := d) n k) :=
  (measurable_suffixSensitivityRealRepresentative (d := d) n k).exp.sub
    measurable_const

theorem cutoffChangeSuffixRepresentative_nonneg (n : ℕ) (k : ℤ)
    (omega : _root_.SubdiffusiveProcess.Model.PotentialSample d) :
    0 ≤ cutoffChangeSuffixRepresentative n k omega := by
  unfold cutoffChangeSuffixRepresentative
  exact sub_nonneg.mpr (Real.one_le_exp
    (ENNReal.toReal_nonneg :
      0 ≤ (suffixSensitivityRepresentative n k omega).toReal))

/-- The selected suffix-only representative dominates every finite cutoff
ratio oscillation almost surely, hence is a valid `X_(m,k)` majorant for all
`m ≥ n` simultaneously. -/
theorem ae_cutoffRatioOscillationSup_le_cutoffChangeSuffixRepresentative
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) (k : ℤ) :
    ∀ᵐ omega ∂M.P.toMeasure,
      cutoffRatioOscillationSup n k omega ≤
        ENNReal.ofReal (cutoffChangeSuffixRepresentative n k omega) := by
  filter_upwards
    [ae_cutoffRatioOscillationSup_le_exp_representative M n k,
      ae_suffixSensitivityRealRepresentative_eq_sensitivityFieldRepresentative
        M n k] with omega hratio heq
  unfold cutoffChangeSuffixRepresentative
  rw [heq]
  exact hratio

/-! ## Prefix/suffix independence and factorization -/

/-- The first `n+1` coordinates and the strict suffix are independent. -/
theorem indep_potentialShellIndexSigma_Iic_Ioi
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ) :
    Indep (potentialShellIndexSigma (d := d) (Set.Iic n))
      (potentialShellIndexSigma (Set.Ioi n)) M.P.toMeasure :=
  indep_potentialShellIndexSigma_of_disjoint M (by
    exact Set.disjoint_left.mpr fun _ hx hy =>
      (not_lt_of_ge (Set.mem_Iic.mp hx)) (Set.mem_Ioi.mp hy))



theorem lintegral_mul_eq_lintegral_mul_lintegral_prefix_suffix
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ)
    {X Y : _root_.SubdiffusiveProcess.Model.PotentialSample d → ℝ≥0∞}
    (hX : @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ≥0∞
      (potentialShellIndexSigma (Set.Iic n)) inferInstance X)
    (hY : @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ≥0∞
      (potentialShellIndexSigma (Set.Ioi n)) inferInstance Y) :
    (∫⁻ omega, X omega * Y omega ∂M.P.toMeasure) =
      (∫⁻ omega, X omega ∂M.P.toMeasure) *
        ∫⁻ omega, Y omega ∂M.P.toMeasure := by
  exact lintegral_mul_eq_lintegral_mul_lintegral_of_independent_measurableSpace
    (potentialShellIndexSigma_le_borel (d := d) (Set.Iic n))
    (potentialShellIndexSigma_le_borel (d := d) (Set.Ioi n))
    (indep_potentialShellIndexSigma_Iic_Ioi M n) hX hY

/-- Real-valued expectation factorization.  Nonnegativity is retained in the
interface because this is the form consumed by the Section 4 moment chain. -/
theorem integral_mul_eq_integral_mul_integral_prefix_suffix
    (M : _root_.SubdiffusiveProcess.Model.GMCModel d) (n : ℕ)
    {X Y : _root_.SubdiffusiveProcess.Model.PotentialSample d → ℝ}
    (hX : @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ
      (potentialShellIndexSigma (Set.Iic n)) inferInstance X)
    (hY : @Measurable (_root_.SubdiffusiveProcess.Model.PotentialSample d) ℝ
      (potentialShellIndexSigma (Set.Ioi n)) inferInstance Y)
    (_hX_nonneg : ∀ omega, 0 ≤ X omega)
    (_hY_nonneg : ∀ omega, 0 ≤ Y omega) :
    ∫ omega, X omega * Y omega ∂M.P.toMeasure =
      (∫ omega, X omega ∂M.P.toMeasure) *
        ∫ omega, Y omega ∂M.P.toMeasure := by
  have hIndep := indepFun_of_measurable_potentialShellIndexSigma_of_disjoint M
    (by exact Set.disjoint_left.mpr fun _ hx hy =>
      (not_lt_of_ge (Set.mem_Iic.mp hx)) (Set.mem_Ioi.mp hy)) hX hY
  exact hIndep.integral_fun_mul_eq_mul_integral
    (hX.mono (potentialShellIndexSigma_le_borel (d := d) (Set.Iic n)) le_rfl).aestronglyMeasurable
    (hY.mono (potentialShellIndexSigma_le_borel (d := d) (Set.Ioi n)) le_rfl).aestronglyMeasurable

end

end SubdiffusiveProcess.CoarseGrainingVocab
