module
public import Mathlib

/-!
# Quantitative homogenization of the Dirichlet problem (Theorem B, paper label `t.B`)

Mathlib-only statement of Theorem B. Fix `d ≥ 2`. For cutoffs `L ≤ M` put
`A_{L,M}(x) = ahom_L⁻¹ a_L(3^M x)` and, for `f ∈ L²(𝒞₀)` and `h ∈ H²(𝒞₀)`, let `u_{L,M}` and
`u_hom ∈ H¹(𝒞₀)` solve `−∇·(A_{L,M}∇u) = f` and `−Δu = f` in the unit cube with boundary values
`h`. Put `𝒟_{L,M} = ‖u_{L,M} − u_hom‖_{L²} + ‖∇u_{L,M} − ∇u_hom‖_{H⁻¹} + ‖A_{L,M}∇u_{L,M} −
∇u_hom‖_{H⁻¹}`.

* **(i) Estimate uniform in the cutoff.** For every `ϑ ∈ (0, 1)` and `q ∈ [1, ∞)` there are
  `δ₀(ϑ, q, d) > 0` and `C(ϑ, q, d)` such that for every model `M : GMCModel d` of disorder
  `δ ≤ δ₀` there are random variables `Z_{L,M} ≥ 1` with `sup_{L ≤ M} ‖Z_{L,M}‖_{L^q} ≤ C` and,
  almost surely, for all `L ≤ M`, `f` and `h`: `𝒟_{L,M} ≤ Z_{L,M} δ^ϑ (‖f‖_{L²} + ‖h‖_{H²})`.
  If `f = 0`, the factor `δ^ϑ` may be replaced by `C δ`.
* **(ii) Algebraic rate at a fixed cutoff.** There is `α_hom(d) > 0` such that for every `L`,
  `q ∈ [1, ∞)` and disorder `δ` there is `C(L, q, d, δ)` such that for every model of disorder `δ`
  there is a random variable `Y_{L,q} ≥ 1` with `‖Y_{L,q}‖_{L^q} ≤ C` and, almost surely, for all
  `M ≥ L`, `f` and `h`: `𝒟_{L,M} ≤ Y_{L,q} 3^{−α_hom (M−L)} (‖f‖_{L²} + ‖h‖_{H²})`.

A model `M : GMCModel d` consists of independent layers `g_0, g_1, …` with `g_k` distributed as
`g_0(3^{−k}·)` and the assumptions (g1)–(g4) of the paper, in dimension `d ≥ 2` and with disorder
`δ ∈ (0, 1/2]`; `a_L = exp(Σ_{k ≤ L} (g_k − τ²))`, `τ² = log E exp(g_0(0))`.

Conventions. The negative norms are the volume-normalized, componentwise `H¹₀`-dual norms
`‖F‖_{H⁻¹} = Σ_i sup {⨍ F_i φ : φ ∈ C_c^∞(𝒞₀), ‖∇φ‖_{L²} ≤ 1}`. The `H²` norm is the sum of the
`L²` norms of `h`, of the components of `∇h` and of the components of `∇²h`; another choice of
norm changes it by a dimensional constant, which `Z`, `Y` and `C` absorb. `ahom_L` is the infimum
over cube scales `n` of `(1/d) Σᵢ E[eᵢ·a_L(𝒞ₙ)eᵢ]`, where `eᵢ·a_L(𝒞ₙ)eᵢ` is the energy
`min_{w ∈ H¹₀(𝒞ₙ)} ⨍ a_L |eᵢ + ∇w|²` of the cell problem, the paper's variational formula for the
coarse-grained matrix of a symmetric coefficient. These values are nonincreasing in `n`
(subadditivity), so the infimum is the paper's limit `lim_n ahom_L(𝒞ₙ)`.

## How this differs from the wording of the paper

Every difference adds a conclusion or restates a hypothesis in an equivalent or weaker form.

1. *Sample space and (g2).* A model is a law `P` on sequences of regular potentials
   (`ℕ → PotentialField d`, each layer `C¹` with locally Lipschitz derivative), so "almost surely
   `C^{1,1}_loc`" is built into the sample space. The size in (g2) is `‖g‖_∞ + ‖∇g‖_∞ + Lip(∇g)`
   on `(−1/2, 1/2)ᵈ`, with the maximum norm on space and its dual norm on gradients, as in the
   paper.
2. *Range of dependence (g1).* Independence is imposed on the σ-algebras generated by integrals of
   the field against bounded measurable test functions with compact support that vanish outside
   `U` (resp. `V`), for measurable `U`, `V` at Euclidean distance at least `√d`. These are
   contained in the σ-algebras generated by the values of the field on `U` and `V`, so the
   hypothesis is not stronger than the paper's.
3. Existence and uniqueness (up to almost-everywhere equality of the function and its gradient) of
   both Dirichlet solutions are asserted rather than assumed.
4. Each `Z_{L,M}` and `Y_{L,q}` is measurable for the σ-algebra generated by the coefficient it is
   built from.
5. `f = 0` means the zero function; changing `f` on a null set changes neither the solutions nor
   `𝒟`, so this is the same statement.

Only Mathlib is imported. The sole intentional `sorry` is the proof of the final theorem; the
separate Solution proves the same statement from the library.
-/

@[expose] public section
namespace SubdiffusiveProcessAudit.QuantitativeHomogenization
open scoped Distributions
set_option autoImplicit false
noncomputable section
open scoped BigOperators
namespace Homogenization
/-- The coordinate space ℝᵈ, with its sup-norm topology. -/
abbrev Vec (d : ℕ) :=
  Fin d → ℝ
/-- Real d-by-d matrices acting on the coordinate space. -/
abbrev Mat (d : ℕ) :=
  Matrix (Fin d) (Fin d) ℝ
/-- The Euclidean scalar product, expressed as a sum over coordinates. -/
def vecDot {d : ℕ} (x y : Homogenization.Vec d) : ℝ :=
  ∑ i, x i * y i
/-- The squared Euclidean norm. -/
def vecNormSq {d : ℕ} (x : Homogenization.Vec d) : ℝ :=
  vecDot x x
/-- Matrix multiplication of a coordinate vector. -/
def matVecMul {d : ℕ} (A : Mat d) (x : Homogenization.Vec d) : Homogenization.Vec d := fun i =>
  ∑ j, A i j * x j
/-- The Euclidean norm, as the square root of the scalar product. -/
noncomputable def euclideanNorm {d : ℕ} (x : Homogenization.Vec d) : ℝ :=
  Real.sqrt (vecNormSq x)
end Homogenization
open _root_.SubdiffusiveProcessAudit.QuantitativeHomogenization.Homogenization Topology
/-- A scalar field with a continuous derivative and locally Lipschitz derivative. -/
def SubdiffusiveProcess.Model.PotentialField (d : ℕ) :=
  { p : C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) //
    (∀ x, HasFDerivAt p.1 (p.2 x) x) ∧
      ∀ K : Set (Homogenization.Vec d), IsCompact K → ∃ C : NNReal, LipschitzOnWith C p.2 K }
namespace Homogenization
/-- Lebesgue measure restricted to the specified spatial set. -/
noncomputable abbrev volumeMeasureOn {d : ℕ} (U : Set (Homogenization.Vec d)) :=
  MeasureTheory.volume.restrict U
/-- L² membership of scalar forcing with respect to restricted domain volume. -/
noncomputable abbrev MemScalarL2 {d : ℕ} (U : Set (Homogenization.Vec d))
    (u : Homogenization.Vec d → ℝ) : Prop :=
  MeasureTheory.MemLp u 2 (volumeMeasureOn U)
/-- A spatially varying real matrix coefficient. -/
abbrev CoeffField (d : ℕ) :=
  Homogenization.Vec d → Mat d
/-- The scalar multiple of the identity matrix. -/
abbrev scalarMatrix {d : ℕ} (sigma : ℝ) : Mat d :=
  sigma • (1 : Mat d)
open MeasureTheory
/-- A matrix field whose entries are measurable and locally integrable. -/
structure RegCoeffField (d : ℕ) where
  toFun : Homogenization.Vec d → Mat d
  entry_measurable : ∀ i j, Measurable (fun x : Homogenization.Vec d => toFun x i j)
  entry_locInt : ∀ i j, LocallyIntegrable (fun x : Homogenization.Vec d => toFun x i j) volume
namespace RegCoeffField
variable {d : ℕ}
instance : CoeFun (RegCoeffField d) (fun _ => Homogenization.Vec d → Mat d) :=
  ⟨toFun⟩
end RegCoeffField
open MeasureTheory
variable {d : ℕ}
/-- A bounded measurable test function with compact support. -/
structure IsProbeR (φ : Homogenization.Vec d → ℝ) : Prop where
  measurable : Measurable φ
  bounded : ∃ C : ℝ, ∀ x, |φ x| ≤ C
  hasCompactSupport : HasCompactSupport φ
/-- The integral of one matrix entry against a scalar test function. -/
def entryTestR (i j : Fin d) (φ : Homogenization.Vec d → ℝ) (a : RegCoeffField d) : ℝ :=
  ∫ x, a x i j * φ x ∂volume
/-- The local coefficient σ-algebra generated by entry integrals against supported
probes. -/
def LocalSigmaR (U : Set (Homogenization.Vec d)) : MeasurableSpace (RegCoeffField d) :=
  MeasurableSpace.generateFrom
    {s |
      ∃ (i j : Fin d) (φ : Homogenization.Vec d → ℝ),
        IsProbeR φ ∧
          Function.support φ ⊆ U ∧ ∃ t : Set ℝ, MeasurableSet t ∧ s = entryTestR i j φ ⁻¹' t}
end Homogenization
namespace SubdiffusiveProcess.Model
open _root_.SubdiffusiveProcessAudit.QuantitativeHomogenization.Homogenization MeasureTheory
  Topology
noncomputable instance potentialFieldTopologicalSpace (d : ℕ) :
    TopologicalSpace (PotentialField d) :=
  TopologicalSpace.induced Subtype.val inferInstance
noncomputable instance potentialFieldMeasurableSpace (d : ℕ) : MeasurableSpace (PotentialField d) :=
  borel (PotentialField d)
namespace PotentialField
variable {d : ℕ}
instance : CoeFun (PotentialField d) (fun _ ↦ Homogenization.Vec d → ℝ) :=
  ⟨fun g ↦ g.1.1⟩
/-- The continuous derivative stored with a potential field. -/
def deriv (g : PotentialField d) : C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  g.1.2
theorem hasFDerivAt (g : PotentialField d) (x : Homogenization.Vec d) :
    HasFDerivAt g (deriv g x) x :=
  g.2.1 x
/-- The regular matrix field g(x)·Id obtained by forgetting the derivative data of
a scalar potential. -/
def forgetPotential (g : PotentialField d) : RegCoeffField d
    where
  toFun x := scalarMatrix (d := d) (g x)
  entry_measurable := fun i k ↦
    by
    have hmat : Continuous (fun x : Homogenization.Vec d ↦ scalarMatrix (d := d) (g x)) :=
      g.1.1.continuous.smul continuous_const
    exact ((continuous_apply k).comp ((continuous_apply i).comp hmat)).measurable
  entry_locInt := fun i k ↦
    by
    have hmat : Continuous (fun x : Homogenization.Vec d ↦ scalarMatrix (d := d) (g x)) :=
      g.1.1.continuous.smul continuous_const
    exact ((continuous_apply k).comp ((continuous_apply i).comp hmat)).locallyIntegrable
end PotentialField
end SubdiffusiveProcess.Model
namespace Homogenization
/-- An orthogonal coordinate permutation with independently chosen coordinate
signs. -/
def IsSignedPermutationMatrix {d : ℕ} (R : Mat d) : Prop :=
  ∃ σ : Equiv.Perm (Fin d),
    ∃ s : Fin d → ℝ, (∀ i, s i = 1 ∨ s i = -1) ∧ ∀ i j, R i j = if i = σ j then s j else 0
end Homogenization
namespace SubdiffusiveProcess.Model.PotentialField
variable {d : ℕ}
/-- Multiplication by a scalar, as a continuous map on potential values. -/
def valueScaleMap (c : ℝ) : C(ℝ, ℝ) :=
  ⟨fun y ↦ c * y, continuous_const.mul continuous_id⟩
/-- Multiplication by a scalar on the space of derivative linear maps. -/
def derivScaleCLM (c : ℝ) : (Homogenization.Vec d →L[ℝ] ℝ) →L[ℝ] (Homogenization.Vec d →L[ℝ] ℝ) :=
  c • ContinuousLinearMap.id ℝ (Homogenization.Vec d →L[ℝ] ℝ)
/-- The continuous-map form of scalar multiplication on derivatives. -/
def derivScaleMap (c : ℝ) : C(Homogenization.Vec d →L[ℝ] ℝ, Homogenization.Vec d →L[ℝ] ℝ) :=
  ⟨derivScaleCLM c, (derivScaleCLM c).continuous⟩
/-- Scalar multiplication of a field and its derivative before restricting to
regular fields. -/
def scaleAmbient (c : ℝ) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ ((valueScaleMap c).comp p.1, (derivScaleMap c).comp p.2)
/-- Scalar multiplication of a regular potential field. -/
def scale (c : ℝ) (g : PotentialField d) : PotentialField d :=
  ⟨scaleAmbient c g.1, by
    constructor
    · intro x
      simpa only [scaleAmbient, valueScaleMap, derivScaleMap, derivScaleCLM,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply] using!
        (g.hasFDerivAt x).const_smul c
    · intro K hK
      obtain ⟨C, hC⟩ := g.2.2 K hK
      refine ⟨‖derivScaleCLM (d := d) c‖₊ * C, ?_⟩
      simpa only [scaleAmbient, derivScaleMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def] using!
        (derivScaleCLM (d := d) c).lipschitzWith.comp_lipschitzOnWith hC⟩
/-- The continuous spatial translation used to pull back a field. -/
def translateMap (z : Homogenization.Vec d) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨fun x ↦ x + z, continuous_id.add continuous_const⟩
/-- Translation of a field together with its derivative. -/
def translateAmbient (z : Homogenization.Vec d) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ (p.1.comp (translateMap z), p.2.comp (translateMap z))
/-- Translation of a regular potential field. -/
def translate (z : Homogenization.Vec d) (g : PotentialField d) : PotentialField d :=
  ⟨translateAmbient z g.1, by
    constructor
    · intro x
      simpa only [translateAmbient, translateMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def] using!
        (g.hasFDerivAt (x + z)).comp x ((hasFDerivAt_id x).add_const z)
    · intro K hK
      let T : Homogenization.Vec d → Homogenization.Vec d := fun x ↦ x + z
      obtain ⟨C, hC⟩ := g.2.2 (T '' K) (hK.image (isometry_add_right z).continuous)
      refine ⟨C, ?_⟩
      simpa only [translateAmbient, translateMap, ContinuousMap.comp_apply, ContinuousMap.coe_comp,
        ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq, smul_apply,
        ContinuousLinearMap.id_apply, Function.comp_def, T, mul_one] using!
        hC.comp (isometry_add_right z).lipschitzWith.lipschitzOnWith (Set.mapsTo_image T K)⟩
/-- The continuous linear spatial dilation x ↦ r x. -/
def spatialCLM (r : ℝ) : Homogenization.Vec d →L[ℝ] Homogenization.Vec d :=
  r • ContinuousLinearMap.id ℝ (Homogenization.Vec d)
/-- Spatial dilation regarded as a continuous map. -/
def spatialMap (r : ℝ) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨spatialCLM r, (spatialCLM r).continuous⟩
/-- Pullback by spatial dilation, including the derivative chain-rule factor. -/
def spatialScaleAmbient (r : ℝ) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦ (p.1.comp (spatialMap r), (derivScaleMap r).comp (p.2.comp (spatialMap r)))
/-- Spatial dilation of a regular potential field. -/
def spatialScale (r : ℝ) (g : PotentialField d) : PotentialField d :=
  ⟨spatialScaleAmbient r g.1, by
    constructor
    · intro x
      simpa only [spatialScaleAmbient, spatialMap, spatialCLM, derivScaleMap, derivScaleCLM,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        ContinuousMap.coe_mk, ContinuousMap.coe_comp, ContinuousLinearMap.comp_smul,
        ContinuousLinearMap.comp_id, Function.comp_def] using!
        (g.hasFDerivAt (r • x)).comp x ((hasFDerivAt_id x).const_smul r)
    · intro K hK
      let S : Homogenization.Vec d → Homogenization.Vec d := spatialCLM (d := d) r
      obtain ⟨C, hC⟩ := g.2.2 (S '' K) (hK.image (spatialCLM (d := d) r).continuous)
      have hinner :=
        hC.comp (spatialCLM (d := d) r).lipschitzWith.lipschitzOnWith (Set.mapsTo_image S K)
      refine ⟨‖derivScaleCLM (d := d) r‖₊ * (C * ‖spatialCLM (d := d) r‖₊), ?_⟩
      simpa only [spatialScaleAmbient, spatialMap, derivScaleMap, ContinuousMap.comp_apply,
        ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv, ContinuousLinearMap.comp_id, id_eq,
        smul_apply, ContinuousLinearMap.id_apply, Function.comp_def, S] using!
        (derivScaleCLM (d := d) r).lipschitzWith.comp_lipschitzOnWith hinner⟩
/-- Pullback by the inverse triadic dilation x ↦ 3⁻ᵏ x. -/
def triadicScale (k : ℕ) (g : PotentialField d) : PotentialField d :=
  spatialScale (((3 : ℝ) ^ k)⁻¹) g
/-- Negation of a regular potential field. -/
def negate (g : PotentialField d) : PotentialField d :=
  scale (-1) g
/-- Matrix action on vectors as a continuous linear map. -/
def matVecContinuousLinearMap (R : Mat d) : Homogenization.Vec d →L[ℝ] Homogenization.Vec d :=
  ⟨Matrix.toLin' R, (Matrix.toLin' R).continuous_of_finiteDimensional⟩
/-- The derivative transformation under a signed coordinate permutation. -/
def rotateDerivativeMap (R : Mat d) :
    (Homogenization.Vec d →L[ℝ] ℝ) →L[ℝ] (Homogenization.Vec d →L[ℝ] ℝ) :=
  (ContinuousLinearMap.compL ℝ (Homogenization.Vec d) (Homogenization.Vec d) ℝ).flip
    (matVecContinuousLinearMap R)
/-- The spatial signed-coordinate permutation as a continuous map. -/
def rotateDomainMap (R : Mat d) : C(Homogenization.Vec d, Homogenization.Vec d) :=
  ⟨matVecContinuousLinearMap R, (matVecContinuousLinearMap R).continuous⟩
/-- The continuous-map form of the derivative transformation under rotation. -/
def rotateDerivativeContinuousMap (R : Mat d) :
    C(Homogenization.Vec d →L[ℝ] ℝ, Homogenization.Vec d →L[ℝ] ℝ) :=
  ⟨rotateDerivativeMap R, (rotateDerivativeMap R).continuous⟩
/-- Pullback of a field and its derivative under a signed coordinate permutation. -/
def rotateAmbient (R : Mat d) :
    (C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ)) →
      C(Homogenization.Vec d, ℝ) × C(Homogenization.Vec d, Homogenization.Vec d →L[ℝ] ℝ) :=
  fun p ↦
  (p.1.comp (rotateDomainMap R),
    (rotateDerivativeContinuousMap R).comp (p.2.comp (rotateDomainMap R)))
/-- The regular potential field obtained by a signed coordinate permutation. -/
def rotate (R : Mat d) (_hR : IsSignedPermutationMatrix R) (g : PotentialField d) :
    PotentialField d :=
  ⟨rotateAmbient R g.1, by
    constructor
    · intro x
      simpa only [rotateAmbient, rotateDomainMap, rotateDerivativeContinuousMap,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        rotateDerivativeMap] using!
        (g.hasFDerivAt (matVecMul R x)).comp x (matVecContinuousLinearMap R).hasFDerivAt
    · intro K hK
      let S : Homogenization.Vec d → Homogenization.Vec d := matVecContinuousLinearMap R
      obtain ⟨C, hC⟩ := g.2.2 (S '' K) (hK.image (matVecContinuousLinearMap R).continuous)
      have hinner :=
        hC.comp (matVecContinuousLinearMap R).lipschitzWith.lipschitzOnWith (Set.mapsTo_image S K)
      refine ⟨‖rotateDerivativeMap R‖₊ * (C * ‖matVecContinuousLinearMap R‖₊), ?_⟩
      simpa only [rotateAmbient, rotateDomainMap, rotateDerivativeContinuousMap,
        ContinuousMap.comp_apply, ContinuousMap.coe_comp, ContinuousMap.coe_mk, deriv,
        ContinuousLinearMap.comp_id, id_eq, smul_apply, ContinuousLinearMap.id_apply,
        Function.comp_def, S] using!
        (rotateDerivativeMap R).lipschitzWith.comp_lipschitzOnWith hinner⟩
end SubdiffusiveProcess.Model.PotentialField
/-- A sequence of regular potential layers indexed by nonnegative integers. -/
abbrev SubdiffusiveProcess.Model.PotentialSample (d : ℕ) :=
  ℕ → SubdiffusiveProcess.Model.PotentialField d
open MeasureTheory ProbabilityTheory
/-- The marginal probability law of one potential layer. -/
noncomputable def SubdiffusiveProcess.Model.potentialMarginalLaw {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) (k : ℕ) :
    ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialField d) :=
  P.map (fun omega => omega k)
/-- The probability law of the layer at scale zero. -/
noncomputable def SubdiffusiveProcess.Model.zeroPotentialLaw {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) :
    ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialField d) :=
  SubdiffusiveProcess.Model.potentialMarginalLaw P 0
/-- Dimension and disorder bounds, layer independence and exact triadic marginal
scaling. -/
structure SubdiffusiveProcess.Model.ShellLawPrefix (d : ℕ) (delta : ℝ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  dimension : 2 ≤ d
  delta_pos : 0 < delta
  delta_le_half : delta ≤ (1 : ℝ) / 2
  independent :
    iIndepFun (fun k : ℕ ↦ fun ω : SubdiffusiveProcess.Model.PotentialSample d ↦ ω k)
      P.toMeasure
  marginal_scaling :
    ∀ k : ℕ,
      SubdiffusiveProcess.Model.potentialMarginalLaw P k =
        (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
          (SubdiffusiveProcess.Model.PotentialField.triadicScale k)
/-- The local σ-algebra generated by supported integral probes of the scalar field
represented as g(x)·Id. -/
def SubdiffusiveProcess.Model.PotentialField.localSigma {d : ℕ}
    (U : Set (Homogenization.Vec d)) :
    MeasurableSpace (SubdiffusiveProcess.Model.PotentialField d) :=
  MeasurableSpace.comap SubdiffusiveProcess.Model.PotentialField.forgetPotential
    (LocalSigmaR U)
/-- Assumption (g1): integrability, mean zero, stationarity and finite-range
independence. -/
structure SubdiffusiveProcess.Model.ShellLawG1 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  integrable :
    ∀ x : Homogenization.Vec d,
      Integrable (fun ω : SubdiffusiveProcess.Model.PotentialSample d ↦ ω 0 x)
        P.toMeasure
  mean_zero :
    ∀ x : Homogenization.Vec d,
      ∫ ω : SubdiffusiveProcess.Model.PotentialSample d, ω 0 x ∂P.toMeasure = 0
  stationary :
    ∀ z : Homogenization.Vec d,
      Measure.map (SubdiffusiveProcess.Model.PotentialField.translate z)
          (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure =
        (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
  range_dependence :
    ∀ (U V : Set (Homogenization.Vec d)),
      MeasurableSet U →
        MeasurableSet V →
          (∀ ⦃x y : Homogenization.Vec d⦄,
              x ∈ U → y ∈ V → Real.sqrt (d : ℝ) ≤ euclideanNorm (x - y)) →
            Indep (SubdiffusiveProcess.Model.PotentialField.localSigma U)
              (SubdiffusiveProcess.Model.PotentialField.localSigma V)
              (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
namespace Homogenization
/-- A triadic cube specified by its integer scale and lattice center. -/
structure TriadicCube (d : ℕ) where
  scale : ℤ
  index : Fin d → ℤ
/-- The side-length factor 3 to the cube's integer scale. -/
noncomputable def cubeScaleFactor {d : ℕ} (Q : TriadicCube d) : ℝ :=
  (3 : ℝ) ^ Q.scale
/-- The open cube with the specified triadic center and side length. -/
def openCubeSet {d : ℕ} (Q : TriadicCube d) : Set (Homogenization.Vec d) :=
  {x |
    ∀ i,
      (((Q.index i : ℝ) - (1 / 2 : ℝ)) * cubeScaleFactor Q < x i) ∧
        (x i < (((Q.index i : ℝ) + (1 / 2 : ℝ)) * cubeScaleFactor Q))}
/-- The triadic cube centered at the origin at the specified scale. -/
def originCube (d : ℕ) (m : ℤ) : TriadicCube d :=
  { scale := m
    index := 0 }
theorem openCubeSet_eq_pi_Ioo {d : ℕ} (Q : TriadicCube d) :
    openCubeSet Q =
      Set.pi Set.univ
        (fun i : Fin d =>
          Set.Ioo ((((Q.index i : ℝ) - (1 / 2 : ℝ)) * cubeScaleFactor Q))
            ((((Q.index i : ℝ) + (1 / 2 : ℝ)) * cubeScaleFactor Q))) :=
  by
  ext x
  simp [openCubeSet]
end Homogenization
/-- The supremum of the absolute potential on the open unit cube, with zero
included in the supremum set. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.unitCubeValueNorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range fun o : Option { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ↦
      match o with
      | none => 0
      | some x => |g x.1|)
/-- The supremum of the derivative operator norm on the open unit cube, with zero
included. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.unitCubeDerivNorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range fun o : Option { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ↦
      match o with
      | none => 0
      | some x => ‖SubdiffusiveProcess.Model.PotentialField.deriv g x.1‖)
/-- The Lipschitz seminorm of the derivative on the open unit cube. -/
noncomputable def
  SubdiffusiveProcess.Model.PotentialField.unitCubeDerivLipschitzSeminorm {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  sSup
    (Set.range
      fun o :
        Option
          { p :
            ({ x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) } ×
              { x : Homogenization.Vec d // x ∈ openCubeSet (originCube d 0) }) //
            p.1 ≠ p.2 } ↦
      match o with
      | none => 0
      | some p =>
        dist (SubdiffusiveProcess.Model.PotentialField.deriv g p.1.1.1)
            (SubdiffusiveProcess.Model.PotentialField.deriv g p.1.2.1) /
          dist p.1.1.1 p.1.2.1)
/-- The sum of the unit-cube value, derivative and derivative-Lipschitz sizes. -/
noncomputable def SubdiffusiveProcess.Model.PotentialField.g2Observable {d : ℕ}
    (g : SubdiffusiveProcess.Model.PotentialField d) : ℝ :=
  SubdiffusiveProcess.Model.PotentialField.unitCubeValueNorm g +
      SubdiffusiveProcess.Model.PotentialField.unitCubeDerivNorm g +
    SubdiffusiveProcess.Model.PotentialField.unitCubeDerivLipschitzSeminorm g
/-- The moment condition `E exp((max(X,0)/A)^σ) ≤ 2`, with the integrand integrable
(`σ = 2` is the sub-Gaussian case). -/
def SubdiffusiveProcess.OGammaLE {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (σ A : ℝ)
    (X : Ω → ℝ) : Prop :=
  Integrable (fun ω ↦ Real.exp ((A⁻¹ * max (X ω) 0) ^ σ)) μ ∧
    ∫ ω, Real.exp ((A⁻¹ * max (X ω) 0) ^ σ) ∂μ ≤ 2
/-- Assumption (g2): the disorder-scaled exponential moment of the unit-cube C¹,¹
size. -/
structure SubdiffusiveProcess.Model.ShellLawG2 (d : ℕ) (delta : ℝ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  regularity_expectation :
    SubdiffusiveProcess.OGammaLE
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure 2 delta
      SubdiffusiveProcess.Model.PotentialField.g2Observable
/-- Assumption (g3): invariance under signed coordinate permutations and field
negation. -/
structure SubdiffusiveProcess.Model.ShellLawG3 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  signed_coordinate_permutations :
    ∀ (R : Mat d) (hR : IsSignedPermutationMatrix R),
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
          (SubdiffusiveProcess.Model.PotentialField.rotate R hR) =
        SubdiffusiveProcess.Model.zeroPotentialLaw P
  negation :
    (SubdiffusiveProcess.Model.zeroPotentialLaw P).map
        SubdiffusiveProcess.Model.PotentialField.negate =
      SubdiffusiveProcess.Model.zeroPotentialLaw P
/-- The logarithm of the zero-layer exponential moment at the origin, denoted τ²
in the paper. -/
noncomputable def SubdiffusiveProcess.Model.tauSq {d : ℕ}
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : ℝ :=
  Real.log
    (∫ g : SubdiffusiveProcess.Model.PotentialField d,
      Real.exp (g 0) ∂(SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure)
/-- Assumption (g4): integrability of the exponential at the origin and positivity
of τ². -/
structure SubdiffusiveProcess.Model.ShellLawG4 (d : ℕ)
    (P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)) : Prop where
  exponential_integrable :
    Integrable (fun g : SubdiffusiveProcess.Model.PotentialField d ↦ Real.exp (g 0))
      (SubdiffusiveProcess.Model.zeroPotentialLaw P).toMeasure
  tauSq_pos : 0 < SubdiffusiveProcess.Model.tauSq P
/-- A supplied layer probability law and positive disorder satisfying the standing
assumptions (g1)–(g4). -/
structure SubdiffusiveProcess.Model.GMCModel (d : ℕ) where
  delta : ℝ
  P : ProbabilityMeasure (SubdiffusiveProcess.Model.PotentialSample d)
  shellPrefix : SubdiffusiveProcess.Model.ShellLawPrefix d delta P
  G1 : SubdiffusiveProcess.Model.ShellLawG1 d P
  G2 : SubdiffusiveProcess.Model.ShellLawG2 d delta P
  G3 : SubdiffusiveProcess.Model.ShellLawG3 d P
  G4 : SubdiffusiveProcess.Model.ShellLawG4 d P
/-- The exponential of the layer sum through cutoff L, centered by (L+1)τ². -/
noncomputable def SubdiffusiveProcess.Model.aCutoff {d : ℕ}
    (M : SubdiffusiveProcess.Model.GMCModel d) (L : ℕ)
    (ω : SubdiffusiveProcess.Model.PotentialSample d) (x : Homogenization.Vec d) : ℝ :=
  Real.exp (∑ k ∈ Finset.range (L + 1), (ω k x - SubdiffusiveProcess.Model.tauSq M.P))
namespace Homogenization
theorem isOpen_openCubeSet {d : ℕ} (Q : TriadicCube d) : IsOpen (openCubeSet Q) :=
  by
  rw [openCubeSet_eq_pi_Ioo]
  exact isOpen_set_pi Set.finite_univ (fun _ _ => isOpen_Ioo)
/-- The coordinate basis vector with value one in the specified coordinate. -/
def basisVec {d : ℕ} (i : Fin d) : Homogenization.Vec d :=
  Pi.single i (1 : ℝ)
/-- The distributional integration-by-parts identity for one partial derivative. -/
def HasWeakPartialDerivOn {d : ℕ} (U : Set (Homogenization.Vec d)) (i : Fin d)
    (u gi : Homogenization.Vec d → ℝ) : Prop :=
  ∀ φ : Homogenization.Vec d → ℝ,
    ContDiff ℝ (⊤ : ℕ∞) φ →
      HasCompactSupport φ →
        tsupport φ ⊆ U →
          ∫ x in U, u x * (fderiv ℝ φ x) (basisVec i) ∂MeasureTheory.volume =
            -∫ x in U, gi x * φ x ∂MeasureTheory.volume
/-- The distributional integration-by-parts identities for all gradient
components. -/
def HasWeakGradientOn {d : ℕ} (U : Set (Homogenization.Vec d)) (u : Homogenization.Vec d → ℝ)
    (Du : Homogenization.Vec d → Homogenization.Vec d) : Prop :=
  ∀ i : Fin d, HasWeakPartialDerivOn U i u (fun x => Du x i)
/-- Square integrability on the specified domain with restricted Lebesgue measure. -/
abbrev MemL2On {d : ℕ} (U : Set (Homogenization.Vec d)) (u : Homogenization.Vec d → ℝ) : Prop :=
  MeasureTheory.MemLp u 2 (MeasureTheory.volume.restrict U)
/-- Square integrability of each weak gradient component on the domain. -/
def GradMemL2On {d : ℕ} (U : Set (Homogenization.Vec d))
    (Du : Homogenization.Vec d → Homogenization.Vec d) : Prop :=
  ∀ i : Fin d, MemL2On U (fun x => Du x i)
/-- A function and weak gradient with the L² certificates defining H¹ on a domain. -/
structure H1Function {d : ℕ} (U : Set (Homogenization.Vec d)) where
  toFun : Homogenization.Vec d → ℝ
  grad : Homogenization.Vec d → Homogenization.Vec d
  memL2 : MemL2On U toFun
  gradMemL2 : GradMemL2On U grad
  hasWeakGradient : HasWeakGradientOn U toFun grad
instance {d : ℕ} {U : Set (Homogenization.Vec d)} :
    CoeFun (H1Function U) (fun _ => Homogenization.Vec d → ℝ) where coe u := u.toFun
/-- An H¹ function approximable by compactly supported smooth functions in H¹,
encoding zero trace. -/
structure H10Function {d : ℕ} (U : Set (Homogenization.Vec d)) extends H1Function U where
  approx : ℕ → Homogenization.Vec d → ℝ
  approx_smooth : ∀ n, ContDiff ℝ (⊤ : ℕ∞) (approx n)
  approx_hasCompactSupport : ∀ n, HasCompactSupport (approx n)
  approx_support_subset : ∀ n, tsupport (approx n) ⊆ U
  tendsto_approx :
    Filter.Tendsto
      (fun n =>
        MeasureTheory.eLpNorm (fun x => approx n x - toH1Function.toFun x) 2
          (MeasureTheory.volume.restrict U))
      Filter.atTop (nhds 0)
  tendsto_approx_grad :
    ∀ i : Fin d,
      Filter.Tendsto
        (fun n =>
          MeasureTheory.eLpNorm
            (fun x => (fderiv ℝ (approx n) x) (basisVec i) - toH1Function.grad x i) 2
            (MeasureTheory.volume.restrict U))
        Filter.atTop (nhds 0)
instance {d : ℕ} {U : Set (Homogenization.Vec d)} :
    CoeFun (H10Function U) (fun _ => Homogenization.Vec d → ℝ) where coe u := u.toH1Function.toFun
end Homogenization
namespace SubdiffusiveProcess.CoarseGrainingVocab
/-- The coordinate space ℝᵈ, with its sup-norm topology. -/
abbrev Vec (d : ℕ) :=
  Homogenization.Vec d
/-- A positive scalar coefficient represented as its multiple of the identity matrix. -/
def scalarCoeffField {d : ℕ} (a : Homogenization.Vec d → ℝ) : Homogenization.CoeffField d :=
  fun x => Homogenization.scalarMatrix (a x)
/-- A triadic cube specified by its integer scale and lattice center. -/
abbrev TriadicCube (d : ℕ) :=
  Homogenization.TriadicCube d
/-- The Lebesgue-volume-normalized average on a spatial set. -/
noncomputable def volumeAverage {d : ℕ} (U : Set (Homogenization.Vec d))
    (f : Homogenization.Vec d → ℝ) : ℝ :=
  (volume U).toReal⁻¹ * ∫ x in U, f x ∂volume
/-- The cell-problem energy of direction `eᵢ` on the triadic cube `Q` for the scalar coefficient
`a`: `inf_{w ∈ H¹₀(Q)} ⨍_Q a |eᵢ + ∇w|²`. For a symmetric coefficient this is `eᵢ·a(Q)eᵢ`, where
`a(Q)` is the coarse-grained matrix of the paper. -/
noncomputable def cellEnergy {d : ℕ} (a : Homogenization.Vec d → ℝ) (Q : TriadicCube d)
    (i : Fin d) : ℝ :=
  sInf
    {E |
      ∃ w : Homogenization.H10Function (Homogenization.openCubeSet Q),
        E =
          volumeAverage (Homogenization.openCubeSet Q)
            (fun x => a x * Homogenization.vecNormSq (Homogenization.basisVec i + w.grad x))}
end SubdiffusiveProcess.CoarseGrainingVocab
/-- The effective diffusivity `ahom_m` of the cutoff coefficient `a_m`: the infimum over cube
scales `n` of `(1/d) Σᵢ E[eᵢ·a_m(𝒞ₙ)eᵢ]`. These values are nonincreasing in `n` (subadditivity),
so the infimum is the limit `lim_n ahom_m(𝒞ₙ)` of the paper. -/
noncomputable def SubdiffusiveProcess.CoarseGrainingVocab.ahom {d : ℕ}
    (M : SubdiffusiveProcess.Model.GMCModel d) (m : ℕ) : ℝ :=
  sInf
    (Set.range fun n : ℕ =>
      (∑ i : Fin d,
          ∫ ω,
            SubdiffusiveProcess.CoarseGrainingVocab.cellEnergy
              (SubdiffusiveProcess.Model.aCutoff M m ω) (Homogenization.originCube d n)
              i ∂M.P.toMeasure) /
        (d : ℝ))
namespace Homogenization
open scoped ENNReal Distributions
/-- The weak partial-derivative identities specifying every Hessian component. -/
structure HasWeakHessianOn {d : ℕ} (U : Set (Homogenization.Vec d)) (u : H1Function U) where
  hess : Fin d → Fin d → Homogenization.Vec d → ℝ
  hess_memL2 : ∀ i j, MemScalarL2 U (hess i j)
  weak_second : ∀ i j, HasWeakPartialDerivOn U j (fun x => u.grad x i) (hess i j)
end Homogenization
namespace SubdiffusiveProcess.CoarseGrainingVocab
open Filter MeasureTheory _root_.SubdiffusiveProcessAudit.QuantitativeHomogenization.Homogenization
open scoped BigOperators ENNReal Topology
attribute [local instance] Classical.propDecidable
/-- The weak divergence-form equation with scalar forcing on the domain. -/
def IsScalarRhsWeakSolutionOn {d : ℕ} (a : CoeffField d) (W : Set (Homogenization.Vec d))
    (u : H1Function W) (f : Homogenization.Vec d → ℝ) : Prop :=
  ∀ φ : H10Function W,
    ∫ x in W, vecDot (matVecMul (a x) (u.grad x)) (φ.toH1Function.grad x) ∂volume =
      ∫ x in W, f x * φ.toH1Function.toFun x ∂volume
/-- The boundary-data difference belongs to H¹₀, expressing the Dirichlet boundary
condition. -/
def HasZeroTraceDifferenceOn {d : ℕ} (W : Set (Homogenization.Vec d)) (u h : H1Function W) : Prop :=
  ∃ w : H10Function W,
    (∀ x, u.toFun x = h.toFun x + w.toH1Function.toFun x) ∧
      ∀ x, u.grad x = h.grad x + w.toH1Function.grad x
/-- A weak scalar-forcing solution with the specified Dirichlet boundary data. -/
def IsScalarDirichletSolutionOn {d : ℕ} (a : CoeffField d) (Q : TriadicCube d)
    (u h : H1Function (openCubeSet Q)) (f : Homogenization.Vec d → ℝ) : Prop :=
  HasZeroTraceDifferenceOn (openCubeSet Q) u h ∧ IsScalarRhsWeakSolutionOn a (openCubeSet Q) u f
/-- The `L²` norm of a scalar function on a triadic cube (Lebesgue measure restricted to the
cube); the cubes used have volume one, so it equals the volume-normalized norm. -/
def l2Size {d : ℕ} (Q : TriadicCube d) (f : Homogenization.Vec d → ℝ) : ℝ≥0∞ :=
  eLpNorm f 2 (volume.restrict (openCubeSet Q))
/-- A vector field with an L² certificate for every coordinate on the cube. -/
structure L2VectorField {d : ℕ} (Q : TriadicCube d) where
  toFun : Homogenization.Vec d → Homogenization.Vec d
  memLpCoord :
    ∀ i : Fin d,
      MemLp (fun x ↦ toFun x i) (ENNReal.conjExponent (2 : ENNReal))
        ((volume (openCubeSet Q))⁻¹ • volume.restrict (openCubeSet Q))
end SubdiffusiveProcess.CoarseGrainingVocab
/-- The σ-algebra generated by all point evaluations of the random coefficient. -/
def SubdiffusiveProcess.CoarseGrainingVocab.coefficientSigma {d : ℕ} {Ω : Type*}
    (A : Ω → SubdiffusiveProcess.CoarseGrainingVocab.Vec d → ℝ) : MeasurableSpace Ω :=
  ⨆ x : SubdiffusiveProcess.CoarseGrainingVocab.Vec d,
    MeasurableSpace.comap (fun ω ↦ A ω x) (borel ℝ)
/-- An H¹ datum together with a square-integrable weak Hessian, encoding H²
boundary data. -/
structure SubdiffusiveProcess.CoarseGrainingVocab.H2Datum {d : ℕ}
    (Q : SubdiffusiveProcess.CoarseGrainingVocab.TriadicCube d) where
  toH1 : Homogenization.H1Function (Homogenization.openCubeSet Q)
  weakHessian : Homogenization.HasWeakHessianOn (Homogenization.openCubeSet Q) toH1
open
  _root_.SubdiffusiveProcessAudit.QuantitativeHomogenization.SubdiffusiveProcess.CoarseGrainingVocab
  _root_.SubdiffusiveProcessAudit.QuantitativeHomogenization.Homogenization
open scoped BigOperators ENNReal
/-- The H² convention: the ℓ¹ sum of L² sizes of the function, gradient components
and Hessian components. -/
def SubdiffusiveProcess.CoarseGrainingVocab.H2Datum.norm {d : ℕ} {Q : TriadicCube d}
    (h : H2Datum Q) : ℝ≥0∞ :=
  l2Size Q h.toH1.toFun + (∑ i : Fin d, l2Size Q (fun x ↦ h.toH1.grad x i)) +
    ∑ i : Fin d, ∑ j : Fin d, l2Size Q (h.weakHessian.hess i j)
/-- The sum over components of the volume-normalized H¹₀-dual negative norms,
using compactly supported smooth tests with gradient L² size at most one. -/
noncomputable def SubdiffusiveProcess.CoarseGrainingVocab.ordinaryVectorHMinusOne {d : ℕ} [NeZero d]
    (Q : SubdiffusiveProcess.CoarseGrainingVocab.TriadicCube d)
    (F : SubdiffusiveProcess.CoarseGrainingVocab.L2VectorField Q) : ℝ≥0∞ :=
  ∑ i : Fin d,
    ⨆ phi :
      { phi : 𝓓^{⊤}(⟨Homogenization.openCubeSet Q, Homogenization.isOpen_openCubeSet Q⟩, ℝ) //
        (eLpNorm
              (fun x =>
                Homogenization.euclideanNorm
                  (fun j : Fin d =>
                    (fderiv ℝ (phi : Homogenization.Vec d → ℝ) x) (Homogenization.basisVec j)))
              2
              ((volume (Homogenization.openCubeSet Q))⁻¹ •
                volume.restrict (Homogenization.openCubeSet Q))).toReal ≤
          1 },
      ENNReal.ofReal
        (∫ x,
          F.toFun x i *
            phi.1
              x ∂((volume (Homogenization.openCubeSet Q))⁻¹ •
            volume.restrict (Homogenization.openCubeSet Q)))
/-- The normalized cutoff coefficient ahom_L⁻¹ a_L evaluated at the spatial scale
3ᴺ. -/
noncomputable def SubdiffusiveProcess.CoarseGrainingVocab.rescaledCutoffCoefficient {d : ℕ}
    (M : SubdiffusiveProcess.Model.GMCModel d) (L N : ℕ)
    (ω : SubdiffusiveProcess.Model.PotentialSample d)
    (x : SubdiffusiveProcess.CoarseGrainingVocab.Vec d) : ℝ :=
  (SubdiffusiveProcess.CoarseGrainingVocab.ahom M L)⁻¹ *
    SubdiffusiveProcess.Model.aCutoff M L ω ((3 : ℝ) ^ N • x)
namespace SubdiffusiveProcess.CoarseGrainingVocab
attribute [local instance] Classical.propDecidable
/-- Measurability with respect to the σ-algebra generated by the specified random
coefficient. -/
def CoefficientMeasurable {d : ℕ} {Ω : Type*} (A : Ω → Homogenization.Vec d → ℝ) (X : Ω → ℝ) :
    Prop :=
  @Measurable Ω ℝ (coefficientSigma A) (borel ℝ) X
end SubdiffusiveProcess.CoarseGrainingVocab
namespace SubdiffusiveProcess.CoarseGrainingVocab
variable {d : ℕ} [NeZero d]
/-- The weak Dirichlet problem `−∇·(A∇u) = f` in the unit cube `𝒞₀` with `u − h ∈ H¹₀`, and the
same problem for the Laplacian (`A = 1`), each have a solution, unique up to almost-everywhere
equality of the function and of its gradient. For every pair of solutions `(u, v)` the gradient
difference `∇u − ∇v` and the flux difference `A∇u − ∇v` are `L²` fields and the error
`𝒟 = ‖u − v‖_{L²} + ‖∇u − ∇v‖_{H⁻¹} + ‖A∇u − ∇v‖_{H⁻¹}` satisfies `good`. -/
def DirichletComparison (A : Homogenization.Vec d → ℝ) (f : Homogenization.Vec d → ℝ)
    (h : H2Datum (originCube d 0)) (good : ℝ≥0∞ → Prop) : Prop :=
  (∃ uLM : H1Function (openCubeSet (originCube d 0)),
      IsScalarDirichletSolutionOn (scalarCoeffField A) (originCube d 0) uLM h.toH1 f) ∧
    (∀ uLM uLM' : H1Function (openCubeSet (originCube d 0)),
        IsScalarDirichletSolutionOn (scalarCoeffField A) (originCube d 0) uLM h.toH1 f →
          IsScalarDirichletSolutionOn (scalarCoeffField A) (originCube d 0) uLM' h.toH1 f →
            uLM.toFun =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uLM'.toFun ∧
              uLM.grad =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uLM'.grad) ∧
      (∃ uHom : H1Function (openCubeSet (originCube d 0)),
          IsScalarDirichletSolutionOn (fun _ ↦ 1) (originCube d 0) uHom h.toH1 f) ∧
        (∀ uHom uHom' : H1Function (openCubeSet (originCube d 0)),
            IsScalarDirichletSolutionOn (fun _ ↦ 1) (originCube d 0) uHom h.toH1 f →
              IsScalarDirichletSolutionOn (fun _ ↦ 1) (originCube d 0) uHom' h.toH1 f →
                uHom.toFun =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uHom'.toFun ∧
                  uHom.grad =ᵐ[volume.restrict (openCubeSet (originCube d 0))] uHom'.grad) ∧
          ∀ uLM uHom : H1Function (openCubeSet (originCube d 0)),
            IsScalarDirichletSolutionOn (scalarCoeffField A) (originCube d 0) uLM h.toH1 f →
              IsScalarDirichletSolutionOn (fun _ ↦ 1) (originCube d 0) uHom h.toH1 f →
                ∃ gradDifference fluxDifference : L2VectorField (originCube d 0),
                  (∀ x, gradDifference.toFun x = uLM.grad x - uHom.grad x) ∧
                    (∀ x, fluxDifference.toFun x = A x • uLM.grad x - uHom.grad x) ∧
                      good
                        (l2Size (originCube d 0) (fun x ↦ uLM.toFun x - uHom.toFun x) +
                            ordinaryVectorHMinusOne (originCube d 0) gradDifference +
                          ordinaryVectorHMinusOne (originCube d 0) fluxDifference)
end SubdiffusiveProcess.CoarseGrainingVocab
/-- **Theorem B** (`t.B`). In (i) the constants `δ₀` and `C` depend only on `(ϑ, q, d)` and are
chosen before the model, while the random variables `Z L N` (`Z_{L,N}`) are chosen for the model
and all `L ≤ N`. In (ii) `α_hom` depends only on `d`, and `C` on `(L, q, d, δ)`; both are chosen
before the model, and `Y` (`Y_{L,q}`) after it. The three summands of `𝒟` are the `L²` distance
of the solutions and the `H⁻¹` distances of the gradients and of the fluxes. -/
theorem theoremB (d : ℕ) [NeZero d] (hd : 2 ≤ d) :
    (∀ vartheta q : ℝ,
        vartheta ∈ Set.Ioo (0 : ℝ) 1 →
          1 ≤ q →
            ∃ delta0 C : ℝ,
              0 < delta0 ∧
                ∀ M : SubdiffusiveProcess.Model.GMCModel d,
                  (M.delta ≤ delta0 →
                    ∃ Z : ℕ → ℕ → SubdiffusiveProcess.Model.PotentialSample d → ℝ,
                      (∀ L N,
                          L ≤ N →
                            CoefficientMeasurable
                              (fun omega ↦ rescaledCutoffCoefficient M L N omega) (Z L N)) ∧
                        (∀ L N omega, L ≤ N → 1 ≤ Z L N omega) ∧
                          (∀ L N,
                              L ≤ N →
                                eLpNorm (Z L N) (ENNReal.ofReal q) M.P.toMeasure ≤
                                  ENNReal.ofReal C) ∧
                            ∀ᵐ omega ∂M.P.toMeasure,
                              ∀ L N : ℕ,
                                L ≤ N →
                                  ∀ f : Homogenization.Vec d → ℝ,
                                    MemLp f 2 (volume.restrict (openCubeSet (originCube d 0))) →
                                      ∀ h : H2Datum (originCube d 0),
                                        DirichletComparison (rescaledCutoffCoefficient M L N omega)
                                          f h
                                          (fun error =>
                                            error ≤
                                                ENNReal.ofReal (Z L N omega * M.delta ^ vartheta) *
                                                  (l2Size (originCube d 0) f + h.norm) ∧
                                              (f = 0 →
                                                error ≤
                                                  ENNReal.ofReal (Z L N omega * C * M.delta) *
                                                    h.norm)))) ∧
      (∃ alphaHom : ℝ,
        0 < alphaHom ∧
          ∀ L : ℕ,
            ∀ q : ℝ,
              1 ≤ q →
                ∀ delta : ℝ,
                  ∃ C : ℝ,
                    0 < C ∧
                      ∀ M : SubdiffusiveProcess.Model.GMCModel d,
                        M.delta = delta →
                          ∃ Y : SubdiffusiveProcess.Model.PotentialSample d → ℝ,
                            CoefficientMeasurable
                                (SubdiffusiveProcess.Model.aCutoff M L) Y ∧
                              (∀ omega, 1 ≤ Y omega) ∧
                                eLpNorm Y (ENNReal.ofReal q) M.P.toMeasure ≤ ENNReal.ofReal C ∧
                                  ∀ᵐ omega ∂M.P.toMeasure,
                                    ∀ N : ℕ,
                                      L ≤ N →
                                        ∀ f : Homogenization.Vec d → ℝ,
                                          MemLp f 2
                                              (volume.restrict (openCubeSet (originCube d 0))) →
                                            ∀ h : H2Datum (originCube d 0),
                                              DirichletComparison
                                                (rescaledCutoffCoefficient M L N omega) f h
                                                (fun error =>
                                                  error ≤
                                                    ENNReal.ofReal
                                                        (Y omega *
                                                          (3 : ℝ) ^
                                                            (-alphaHom * ((N : ℝ) - (L : ℝ)))) *
                                                      (l2Size (originCube d 0) f + h.norm))) :=
  by sorry
end
end SubdiffusiveProcessAudit.QuantitativeHomogenization
